### ISSUE TITLE
%sh{ } with well-defined shell?

### ISSUE THREAD

**Issue by Droggelbecher** [mawww/kakoune#1000]
Hey everyone,
pretty new to kakoune, but I totally love the idea, thanks a lot for doing this :-)
I totally understand the rationale about not including a script language and rather allow usable ways of integrating external processes.

One thing worries me though with %sh { ... }: It uses whatever shell the user used to start kakoune.
For example, I nowadays usually use xonsh (a python-oriented shell which in some regards has very non-bash-like syntax). If I now try to use some extension written by somebody else that assumes bash, that won't work. Or even worse: Do something similar, but wrong eg. by messing up escaping/quoting of arguments to a delete command as that works differently across shells.

Also this paragraph worries me a lot:

> Note that in order to make only needed information available, Kakoune needs to find the environment variable reference in the shell script executed. Hence %sh{ ./script.sh } with script.sh referencing an environment variable will not work.

Does that mean, kakoune tries to be super-smart by assuming the shell script is written in bash and will only every use environment variables that kakoune can literally discover in the text?
Why? To what end? to not set some environment variables that are never used (and thus probably not a problem?)

So ideally, I'd like kakoune not to try to be a smart ass about this. If it has to for whatever technical reason, then please do not assume a certain kind of shell on the one hand and then use whatever is there. Maybe it would make sense to allow the writer to specify the shell such as "%sh bash { ls -lh }"
or "%sh python { print "Hello, World" }".

I suppose it should be possible to do something like %sh { bash my_bash_file.sh $kak_buffername ... } to work around this issue. That would only assume that this one very trivial line works the same in all encountered shells which it might if users don't get too exotic or there is a quoting/escaping/white space issue (d'oh!).

**Comment by mawww** [comment]
Hello,

So, %sh{ ... } uses `/bin/sh` which I assumed was guaranteed by posix to be a posix shell. It turns out `sh` is not guaranteed to be in `/bin`. That needs to be fixed, but the idea is to assume %sh{ ... } is run by a posix shell. We have been getting rid of most bashism, but there might be some lurking around.

Kakoune just looks for kak_.* words in the string passed to the shell, it does not check they are accessed by the shell, something else or not used, for example awk could use `ENVIRON["kak_opt_blah"]` and it should work, as long as we can see the kak_opt_blah word to make that environment var available.

The reason we do that is that building the enviroment variable block with all variables all the time could get quite expensive, that would contain all options, including hidden ones, the whole enviroment of the client (which might be a different process from the server) accessible as `kak_client_env_name`, the full contents of selections (so if we ran that with a 10MB buffer fully selected, we are passing that in the env block... It seemed safer to only include the vars on demand, with the idea that logic implemented in an invisible script should not rely on kakoune env vars anyway, but take them as parameters.

**Comment by Droggelbecher** [comment]
Hm I see, I suspected a performance issue there.

It seems you are right, but something else is messed up for me then:
> echo %sh{ echo $SHELL }

echoes

> /usr/bin/xonsh 

(which was why I was confused).
Turns out though the shell actually does not behave like xonsh but rather like sh or bash,
so it seems its just this environment variable that does not do what I expected. At this point I'm not sure whether $SHELL *should* be the innermost interactive shell or the innermost shell (my shell knowledge is not "deep" enough for this ;-)).

If you think this behavior is alright, please close this I'll say sorry for the bothering :-)

**Comment by mawww** [comment]
No worries, and this made me look into `/bin/sh` and see thats actually not portable.

**Comment by kballard** [comment]
@Droggelbecher I was going to say that I think that your shell is simply inheriting its `SHELL` environment variable from Kakoune, which inherits it from its own shell, but it turns out to be not quite correct. It looks like it can inherit it, but if it's not set, then the shell resets it to the user's login shell rather than to the executing shell. For example, my login shell is `/usr/local/bin/fish`, but if I tell Terminal to launch bash instead of login, bash still sets `SHELL` to `/usr/local/bin/fish`. And if I were to run `env -u SHELL bash`, the nested bash will again reset it to `/usr/local/bin/fish`.
