### ISSUE TITLE
Command descriptions in README.asciidoc are outdated

### ISSUE THREAD

**Issue by iology** [mawww/kakoune#1003]
The intro should be moved to the wiki to encourage frequent amendment without PRs.

**Comment by lenormf** [comment]
Which command descriptions are outdated?

Moving things to the wiki is taking a risk that users will miss important information, as it would put things one more click away from the project page.

**Comment by iology** [comment]
@lenormf Some commands about registers now take values from `%val{...}`: https://github.com/mawww/kakoune#defining-commands

The readme is a very long intro, full of duplicated contents. So it is quiet hard to keep everything up-to-date. We should put more effort into improving the builtin `doc` pages, or this could be gradually done after the wiki pages is well written.

**Comment by mawww** [comment]
It would be nice to progressively remove the content of the README thats duplicated by the doc pages. I think the first step would be to make the doc pages easily accessible on the website, then we can start cleaning up the README>

**Comment by Delapouite** [comment]
I agree, the content of the `doc` dir should be the single source of truth.

Currently the Makefile is in charge to generate proper man pages from the original asciidocs using `a2x`.
At first we could extend this task to convert these asciidocs to HTML pages that would be commited on the `gh-pages` branch to be accessible on the website.

The wiki can serve as a staging the zone for quick collaboration between multiple people in order to produce new `official` content for the `doc` directory.

**Comment by alexherbo2** [comment]
I agree the `README` is way too big.
