### ISSUE TITLE
Temporary directories are world writeable

### ISSUE THREAD

**Issue by kseistrup** [mawww/kakoune#1007]
The directories `/tmp/kakoune` resp. `/tmp/kakoune/${USER}` are created with permissions 0777, i.e., they're world writeable. Please make `/tmp/kakoune` sticky (1777) and use less exploitable permissions for the user directory (e.g., 0750).

Also, if the environment variable `$TMPDIR` is set under Linux, the user directory should be created in that directory, not in `/tmp`.

**Comment by mawww** [comment]
Should be better now, I went with 711 for the user dir, so that we can still manually give access to a session to another user, but without letting other users list our sessions.

`kak -c <user>/<session>` tries to connect to another user session, provided he gave your user the permission to access the socket. Thats pretty dangerous though, as you now have access to `%sh{...}` as `<user>`.
