### ISSUE TITLE
kakoune.org not available via https

### ISSUE THREAD

**Issue by thunderrabbit** [mawww/kakoune#1010]
Let's Encrypt makes it pretty easy to add SSL to sites, and it just seems a little more trustworthy to me if I see the URL as https://kakoune.org

**Comment by somasis** [comment]
Isn't this really an issue with GitHub Pages not allowing SSL for custom domains?

**Comment by lenormf** [comment]
As @somasis said, this is due to github not enabling (for technical reasons I reckon) https on github pages, which the site is hosted on. Nothing we can do there, unfortunately.

**Comment by thunderrabbit** [comment]
I found this https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/ but not sure if it will still work

**Comment by johnwchadwick** [comment]
Cloudflare is a workable solution here; it will provide HTTPS-to-HTTP with free certs. Not perfect, but better than no security at all. It may also be possible, with Cloudflare, to proxy HTTPS-to-HTTPS, accepting the Github certificate. I have not tested that.

I am running a Github pages atop Cloudflare here: https://restruct.io - and as you can see, from a UX and SEO perspective it works fine, though it may be somewhat deceptive in terms of security since it does eventually travel plaintext over the Internet.

A cheap-but-not-free alternative would be to use Amazon S3 + Cloudfront. Amazon does free SSL certificates for this, though the actual use of S3 and Cloudfront is not free.

The most inexpensive solution that does not trust a third-party with the SSL termination would be to run a Digital Ocean or Amazon Lightsail instance with the Caddy webserver, which will seamlessly handle leasing a Let's Encrypt certificate and is very fast and efficient. That would cost $5/mo at minimum.

If solutions that cost money or have moving parts are not on the table then I reckon it probably doesn't hurt to just use Cloudflare.

**Comment by doppioandante** [comment]
To the ignorants like me, what are the benefits of https when the website is just for content display?

**Comment by lenormf** [comment]
@doppioandante SSL prevents a third party from injecting arbitrary data into the content that your browser displays, very roughly put.

@johnwchadwick I don't like cloudflare, what they do is simply provide hardware and allow the government who controls them to monitor all the traffic. The alternative I had in mind was to just move the site to a dedicated server (mine, @mawww's, somebody's), but that would require maintainance (not much albeit, but still it would be nice to have a 99.99% uptime on the landing page of the project).

**Comment by johnwchadwick** [comment]
Fair enough. Then Let's Encrypt is probably ideal. In that case, my personal (unsolicited) recommendations are either:

- [Caddy](https://caddyserver.com/) web server, as I previously mentioned. It's pretty fast/lightweight, supports HTTP/2, automatically sets up SSL with nearly no configuration (doesn't even need a domain name.)

- OR, [Acmetool](https://github.com/hlandau/acme). It basically runs in the background and automatically deals with Let's Encrypt automatically, and it will work pretty simply with any webserver supporting TLS.

(Both tools are written in Go. That's not really an intentional choice, those just happen to be nice pieces of software and Go makes them extremely convenient to run anywhere.)

I do understand the concerns with Cloudflare. I just figure you are already trusting GitHub as-is, so it isn't a huge leap to also trust Cloudflare. If uptime and trust are more important than hosting being cheap, it is probably best to distribute both DNS and web serving across multiple providers.

**Comment by lenormf** [comment]
We're using github pages because it's a one-click deployment procedure, with no maintainance. So if we're going to move away from that, we might as well do things properly and not send all of the users' traffic through the NSA's most prolific tap.

As for the software, I like `lighttpd` and `nginx`, they play well with `certbot` but that's all hypothetical because we don't have any incentive to move away from github pages right now.

**Comment by johnwchadwick** [comment]
OK, agreed. There may be no reason to move now, [but I can imagine in the future the free lunch will end](https://www.bloomberg.com/news/articles/2016-12-15/github-is-building-a-coder-s-paradise-it-s-not-coming-cheap). So it may be worth considering for the future, if nothing else.

**Comment by somasis** [comment]
If it's really critical I wouldn't mind hosting kakoune.org on my server.
I'd be open to helping set up deployment via Travis to it, as I use that
for some of my own projects hosted on it.

**Comment by mattes** [comment]
S3 + Cloudfront. Cloudfront comes with included cert these days, too.

**Comment by lenormf** [comment]
I think this issue can be closed.

**Comment by mawww** [comment]
This might happen as a more general move of Kakoune's infrastructure to a dedicated server in the future (no plans for that yet, we stay with github for the forseable future), but I dont think its worth it to move the website alone now just to get https.

Could be good to see if github can enable https on custom domains, I dont know enough about it to see whats the technical limitation there.

**Comment by lenormf** [comment]
https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

**Comment by lenormf** [comment]
[It seems to be working now](https://kakoune.org/).
