### ISSUE TITLE
Package management

### ISSUE THREAD

**Issue by leemachin** [mawww/kakoune#1019]
A comment on #957 mentions [the idea](https://github.com/mawww/kakoune/issues/957#issuecomment-266852474) of a package manager.

I don't know how much of a need there is for this because I'm not 100% sure there is a community for script sharing yet. But I built (and am successfully using) an MVP one anyway in the hope that it boosts collaboration (with thanks to the suggestions on improving it on the IRC channel):

https://github.com/leemachin/armoury

I'd be happy to submit one of a couple of PRS:

1. Offer the script itself in a PR so it is part of the standard install (good: everyone can use it; bad: maybe it discourages other alternatives from being explored, even if you can just remove the file).

2. Update the readme or wiki to point out one of the options for using third party scripts (good: everyone has a choice).

What do you think?

**Comment by lenormf** [comment]
Hi,

Thanks for your contribution. That said I have never found "package managers" useful in any way, the ones I've tried (in `vim`) seem to merely be complicated and unecessary wrappers of HTTP or git clients. I would rather keep things UNIXy (which is one of a core concepts of the editor) and use tools who are good at keeping things up-to-date (a simple `git pull` is enough, but `vcsh` is good at updating big amounts of repositories) rather than trust my editor's third party script.

Now about the script:

* installing scripts in a custom directory is not convenient for reviewing (or debugging) what's been installed, I think you could make use of the `autoload` directory to simplify the loading process and keep things fairly transparent for the user;
* there are a few bits in the shell code that are not portable (e.g. `echo ${XDG_CONFIG_HOME:-$HOME/.config}/kak/armoury`, HERE strings, `grep -Fxqv`), if I had to guess I'd say that people who use BSD tools are going to have issues running the script
* `lenorf/kakoune-extras` should be `lenormf/kakoune-extra`; my repository is slightly (largely) out of date, so not all the scripts are going to be working out of the box; there's a few documentation files in the repository, maybe you should remove all files that are not kakoune scripts from the repositories cloned?

**Comment by alexherbo2** [comment]
Same as @lenormf.

Plus Kakoune already has [Pathogen][]-like functionality from Vim, so you can organize scripts like bundles and use your shell to manage them.

[Pathogen]: https://github.com/tpope/vim-pathogen

**Comment by leemachin** [comment]
Thanks for the feedback. I'm not so attached to the original proposal and the value here is diminished by the lack of any real collection of third party scripts. I'm happy to close this and let those who want it set the package up themselves.

**Comment by lenormf** [comment]
You can leave this up and wait for more people to share their feelings about it, also the script you developed is not totally useless and might be improved upon.

**Comment by doppioandante** [comment]
We could at least agree on a naming for github repositories that represent kakoune packages (like vim ones do with the .vim suffix I think).
Some packages can be made by splitting out the ones that currently are in the rc/extra folder, I remember @lenormf discussing this sometime ago but I didn't follow the resolution.
This would avoid the pollution of this issue tracker with stuff that's not really relevant to the core of the editor.

**Comment by leemachin** [comment]
I was wondering if depending on github was a good idea. It's convenient because it handles versioning,  but you can end up cloning a bunch of files you don't care about at all. You can say to work with releases instead, but then it's an even harder dependency on github because you need to query the API to know if an update exists. 

The alternative is to have a single package repo that you can build a system around (like with melpa, cocoapods, homebrew). But for me it keeps coming back to the same point: this stuff is super useful and I really enjoyed figuring out kakoune's config system so I could build it, but it actually needs the third party scripts to succeed. I'm hoping this encourages sharing so it can work, but no one will need it until managing their config becomes too much effort.

**Comment by mawww** [comment]
I think this discussion is pretty much finished, closing.
