### ISSUE TITLE
Integrating core code into IDE plugins?

### ISSUE THREAD

**Issue by Sushisource** [mawww/kakoune#1026]
Hi there,

Just tried out Kakoune for the first time recently and I think it's a brilliant improvement upon vim. Problem is (for me, and I suspect many others), I can't really justify learning it to use on a regular basis since the huge majority of my coding actually happens inside IntelliJ or Visual Studio, or whatever, with a vim plugin installed simply because the auto-completion and refactoring features are always going to be better than a vim/kak plugin, largely for reasons outside of the control of vim/kak developers.

I would love to use the kakoune editing model inside these IDEs though. IE: Have a kakoune plugin for these IDEs like there are already quite good vim plugins.

Would creating such a plugin, hopefully sharing most of the code with the existing kakoune codebase, be doable? Do the project devs consider it a goal at all? I am sure it would result in quite a bit more users.

**Comment by lenormf** [comment]
Such plugins would be really nice, but if you're thinking of a self contained library that would be loaded by an IDE, then there might be some work involved (you would need to build it statically as well). Otherwise, the easiest way to do it as of today would be to run a headless kakoune server on the system, and interacting with it using the json-rpc interface (that's how the couple implemented UIs do it).

**Comment by mawww** [comment]
Kakoune provides support for external UIs, currently through a json-rpc protocol, this could be the basis of integration in other tools/ide:

* use the json-rpc UI protocol to implement the display UI inside the IDE
* use the general command sending system `kak -p` for more advanced commands.

**Comment by jonpdw** [comment]
I would like this for intellij
