### ISSUE TITLE
Don't let cursor move past end of line in normal mode

### ISSUE THREAD

**Issue by akkartik** [mawww/kakoune#1061]
In Vim the cursor is only ever past end of line in insert mode. I'm curious if there is a reason Kakoune is different in this regard. (I tend to rely on that subtle signal to watch out for trailing whitespace.)

**Comment by lenormf** [comment]
We used to have it so that newline were never put in selections using movement keys, but that changed (to my dismay). Do you think you would benefit from being able to go over newlines only in insert mode?

Also by "move past new lines" I'm assuming you meant hovering newline characters, or did you mean wrap around lines when using movement keys, or something else?

**Comment by akkartik** [comment]
Sorry I wasn't clear. I wasn't thinking about wrapping or movement keys at all. Let me see if a screenshot helps.

![eol](https://cloud.githubusercontent.com/assets/3161/21415070/9484ce4e-c7ba-11e6-9406-f980131d3c03.png)

Notice the cursor towards the end of the second line. In Vim that cursor position tells me that one of these two facts must be true:

1. I'm in Insert mode, or
2. That line has trailing whitespace.

In Kakoune that's a valid position for the cursor in Normal mode even if there's no trailing whitespace.

**Comment by lenormf** [comment]
OK, in that case is that a problem in certain cases that this behaviour applies to all modes, aside from the fact that it prevents you from making out the insert mode from the command one? I don't think there was really a reason as to why this was implemented, aside from that it was different from what other editors do.

The discussion about this change is in #530.

**Comment by akkartik** [comment]
At least for me the issue isn't making out insert from command mode. I tend to have some "mental state" about which mode I'm in. My issue is that I'm often doing a double-take and getting distracted trying to delete trailing whitespace that isn't really there :)

It's not a huge issue, I just wanted to bring it up in case it's come up before. May be worth waiting and seeing if others have the same complaint.

**Comment by occivink** [comment]
Only tangentially related, but I like the whitespace highlighter with a dim face to see whitespace oddities:
```
face Whitespace rgb:505050,default
hook global WinCreate .* %{
  addhl show_whitespaces
}
```
Regarding the mode, you could also change the background of the status line depending on the current mode if you want a starker reminder:
```
hook global NormalBegin .* %{ 
  face StatusLine default,black
}
hook global InsertBegin .* %{ 
  face StatusLine default,green
}
```

**Comment by mawww** [comment]
Hello,

We used to prevent that, and got rid of it because it improved consistency; We cannot avoid being on an eol entirely as we have no choice on empty lines, and we sometimes do want to select the eol, which was cumbersome (`x;` was the recommended way).

What I have been thinking about was to highlight the cursor differently when it lies on an end of line, so that its easier to see if we are on an eol or a trailing whitespace, but this is already catered for by the show_whitespaces highlighters, and I am not keen on adding new faces just for highlighted eol.
