### ISSUE TITLE
Dummy selections description on `BufClose`

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1066]
Hi,

Looks like the `selections_desc` value always contains `1,1.1,1` as description when accessed from a `BufClose` hook.

```
hook global BufClose .+ %sh{echo $kak_selections_desc > /tmp/selections_desc}
```

HTH.

**Comment by mawww** [comment]
BufClose runs in a disposable context, the problem is that we cant really use the client context in the general case:  for `:delete-buffer name` the current context might not be using the `name` buffer, there might not be any context using it either.

We could add some complexity to run BufClose in the context of the current client only in the case where it is its current buffer, but I am not convinced it is worth it as it does not solve the general case.
