### ISSUE TITLE
`%sh{ls}` doesn't seem to work

### ISSUE THREAD

**Issue by akkartik** [mawww/kakoune#1076]
I'm probably doing something wrong here, but here's what I tried:

```
:echo %sh{pwd}
/home/akkartik
:echo %sh{ls}
Documents : no such command
:nop %sh{ls}
Documents : no such command
```

Any guidance most appreciated.

**Comment by mawww** [comment]
%sh{ls} will get expanded to multiple lines, but %sh{...} are retokenized *before* we split the command, so that they can expand to multiple commands. That means the first line will be treated as an argument to echo, but next lines as independent commands, and we try to execute the 'Document' (I assume thats a directory returned by ls) command which does not exist.

use `"%sh{ls}" to ensure its parsed as a single argument.
