### ISSUE TITLE
comment-selection does not do anything

### ISSUE THREAD

**Issue by Droggelbecher** [mawww/kakoune#1120]
Tested on my kakrc file on a single selection that spans multiple lines. comment-line on the other hand works fine (however only comments the first line as to be expected).

Can somebody reproduce?

My kak version is at 76c58aa0 .

**Comment by lenormf** [comment]
Not all filetypes have block comment characters set, because the language they wrap don't have either.

Example: kak scripts, in which you can only comment lines with the `#` character. To comment a block (I should have named the `comment-selection` command just that, `comment-block`), use `<a-s>:comment-line<ret>`.
