### ISSUE TITLE
Spell checker selects wrong regions for unicode text

### ISSUE THREAD

**Issue by rouanth** [mawww/kakoune#1126]
Steps to reproduce:

  1. Get [test.txt](https://github.com/mawww/kakoune/files/699083/test.txt);
  2. Acquire `aspell` dictionary for Russian;
  3. Run `aspell -l ru -c test.txt`; observe that `какунь` is shown to be the wrong word;
  4. Run `:spell ru` in `kak test.txt`; observe that wrong text is selected and some binary data is shown.

I presume that the highlighting is done on byte ranges instead of character ranges.

**Comment by mawww** [comment]
Yeah, seems aspell returns positions in characters, when Kakoune is expecting bytes there.

Using characters for that in Kakoune is going to be tricky, especially as we now update ranges based on buffer modfiications. Using characters means that in order to update positions, we need to know what bytes they referred to before modifications. It seems easier to try to fix spell.kak so that we use byte offsets.
