### ISSUE TITLE
expose $kak_command_history and $kak_search_history

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1130]
Hi

Use cases for these variables in rc scripts :
- save a history to a file
- pass a history to an external interactive filter like fzf to browse through the list of previous commands or searches

**Comment by lenormf** [comment]
Passing an entire history of commands through a single environment variable might yield undefined behaviour due to its size, depending on the shell that's run. Also it's going to take a massive hit on performance, as everything would have to be escaped to allow parsing using a delimiter.

The idea is good, but variables probably shouldn't be how it should be implemented.

**Comment by Delapouite** [comment]
You're right.

My issue could be more oriented about what I want to achieve than how this can be implemented.
Maybe these lists can be retrieved by asking the kak executable itself with a flag? Something like that:

```
kak -list-history ${kak_session_id}
```

**Comment by mawww** [comment]
I am not sure there is better than env vars for that:
* Not convinced we will hit any size limitations, history is not that big
* Escaping is going to be a problem no matter what way we send history, as long as it ultimately goes through text, we will have to separate entries somehow.

`kak -list-history` means we introduce "answers" in the remote protocol, which I still want to avoid.

So, in my opinion, the real problem here is to choose a nice delimiter. `\n` is not an option because we support multiline commands (write a multiline command in a buffer, select it and do `:<c-r>.` to see). `\0` Wont work if we use env vars (but thats not a strong enough argument to use something else).

Or we could use `\n` and escape the ones that are not history delimiters.

**Comment by lenormf** [comment]
>Not convinced we will hit any size limitations, history is not that big

I have a kak client running on a remote server I've been using for a couple months, if I had a way of counting I many commands I've issued in it I'm sure I would hit a 3 digits number. Now imagine concatenating all that together, adding delimiters, escaping, and you get a very big variable.

There's no POSIX limit to an environment variable's length that I know of, but I know there an implementation-defined limit to the length of the values that will be handled by shells. Even if there was an environment variable that held all of the commands history, chances are using it would be unpredictable because it depends on `/bin/sh` (which can be anything as we know).

>Escaping is going to be a problem no matter what way we send history, as long as it ultimately goes through text, we will have to separate entries somehow.

Taking into account the fact that the length of the commands history is not predictable (and can be fairly big as is my case), I'd rather not have my shell scopes randomly spawning with a delay caused by the editor escaping everything. This also becomes a concern if we assume that at some point we'll have a mechanism that restores command history across restarts.

**Comment by mawww** [comment]
> I have a kak client running on a remote server I've been using for a couple months, if I had a way of counting I many commands I've issued in it I'm sure I would hit a 3 digits number. Now imagine concatenating all that together, adding delimiters, escaping, and you get a very big variable.

Can you do a `debug memory` command on this client, and look at the size of the History domain ? That would be a nice data point.

We could just limit the history size as well, maybe we dont need more than a thousand history entries.

Its not the first case where we can have big env var, `$kak_selections` can be arbitrarily big as well.

> I'd rather not have my shell scopes randomly spawning with a delay caused by the editor escaping everything.

That would only happen on shell scopes that are using the history env var.

**Comment by lenormf** [comment]
>Can you do a debug memory command on this client, and look at the size of the History domain ? That would be a nice data point.

I actually closed the client when I realized it was running a months-old version :(

>We could just limit the history size as well, maybe we dont need more than a thousand history entries.

I don't think there's a point in providing only a part of the history, it would be assuming what scripts would need it for and go against the main use case envisioned for this feature, namely saving the (complete?) history to a file when the client exits.

>Its not the first case where we can have big env var, $kak_selections can be arbitrarily big as well.

Fair enough.

>That would only happen on shell scopes that are using the history env var.

My bad, I keep forgetting about the "smart" on-demand injection of variables in the environment.

**Comment by danr** [comment]
If we want to avoid making variables with large contents in %sh-splices, and want to avoid making `kak` reply with answers, I see an easy solution: make `kak` respond by  writing to a file.

We could have the commands `write-command-history` and `write-search-history` and `write-docstrings` (#1166). The take one argument: a filename to write to.

Here's some example code looking at the command history:

    %sh{
        notify=$(mktemp)
        histfile=$(mktemp)
        echo "write-command-history $histfile; %sh{ echo done > $notify }"
        (
            cat $notify > /dev/null
            rm $notify
            # do stuff with histfile, like fzf:
            cmd=$(cat $histfile | fzf)
            echo eval -client $kak_client "'$cmd'" | kak -p $kak_session
            rm $histfile
        ) >/dev/null 2>&1 </dev/null &
    }

**Comment by Screwtapello** [comment]
I think this can be closed. `$kak_command_history` is now `$kak_reg_colon` and `$kak_search_history` is now `$kak_reg_slash`.

**Comment by Delapouite** [comment]
You're right, now that registers are exposed as lists since https://github.com/mawww/kakoune/commit/271631 (2018), these variables should do the job.
