### ISSUE TITLE
Interfacing to a REPL

### ISSUE THREAD

**Issue by doppioandante** [mawww/kakoune#1154]
Hello, I'm trying to integrate intero for haskell in kakoune.
Intero is based on ghci, so I need to communicate with a repl instance to issue command (completion, build and so on).
Spawning an instance every time is out of question, so my idea was to use a FIFO as input to ghci and to read the output, redirected to a file, with cat.
```
mkfifo .kakinteroinfifo
tail -f .kakinteroinfifo | stack ghci --with-ghc intero >out 2>&1 &
```
In the terminal this works great, but I can't get it to work inside a %sh{} block because kakoune hangs.

What is the reason?
Is there any other way to do this?

**Comment by lenormf** [comment]
The shell that executes this command is waiting for the command to finish, adding an `&` after the command would only allow you to execute commands in the same scope right after this one has been spawned.

The only way you can get a command to run in the background is if the shell doesn't have any standard file descriptor to monitor, `{ command } 2>&1 >/dev/null </dev/null &`, which is a corner case that allows the shell to let go of the process.

**Comment by doppioandante** [comment]
> The only way you can get a command to run in the background is if the shell doesn't have any standard file descriptor to monitor, { command } 2>&1 >/dev/null </dev/null &, which is a corner case that allows the shell to let go of the process.

Thanks, this means that I either need the program to be executed outside from kakoune before, or that I have to write a small program that writes to the repl and answers back and closes immediately.

**Comment by mawww** [comment]
I dont get what you want to do, do you want the pipe to run in parallel with Kakoune ?
```
{ tail -f .kakinteroinfifo | stack ghci --with-ghc intero >out 2>&1 } 2>&1 >/dev/null </dev/null &
```

Should work for that, even in a `%sh{...}`.

**Comment by doppioandante** [comment]
> I dont get what you want to do, do you want the pipe to run in parallel with Kakoune ?
Yes
> { tail -f .kakinteroinfifo | stack ghci --with-ghc intero >out 2>&1 } 2>&1 >/dev/null </dev/null &

What is that syntax called? I can't make it work in sh, it waits for more input

**Comment by mawww** [comment]
I dont know if that syntax has a name, its just a general pattern we use in Kakoune `%sh{ ... }` blocks to run a set of shell commands that detach from their parent shell, so that the `%sh{ ... }` block finishes without waiting for them.

All the async tasks we rely on for completion, make, grep use that.

**Comment by RianFuro** [comment]
@doppioandante @mawww I believe the syntax is
`( expressions ) >/dev/null 2>&1 </dev/null &` or `{ expressions; } >/dev/null 2>&1 </dev/null &` (notice the semicolon at the end of expressions).
Also the order of the redirections is important, the error handler has to be redirected AFTER the stdout handler. Both versions should behave similar, bash is handling those cases slightly different though regarding their execution environment.

More information:
https://www.gnu.org/software/bash/manual/bashref.html#Redirections
https://www.gnu.org/software/bash/manual/bashref.html#Command-Grouping

Other than that, since this is pretty much just decoupling the stdin, stdout and stderr handlers from the terminal, I believe you can get similar results using nohup instead; haven't tried that  though.

**Comment by mawww** [comment]
@doppioandante is that issue still relevant ? Or can we close it ?

**Comment by doppioandante** [comment]
@RianFuro @mawww Thanks for the help, you can close. This is what I have now, for future reference:
```
def -allow-override intero-start %{
    %sh~
        PROJECT_ROOT=$(stack path | grep project-root | cut -d: -f 2 | sed "s/^\s*//")
        # TODO: check root

        if [ -n "$PROJECT_ROOT" ] && [ -s "$PROJECT_ROOT/.kakintero" ]; then
            echo "echo -color Error 'An intero session has already been started for this project'"
        else
            # start the interactive interpreter
            INFIFO="$PROJECT_ROOT/.kakinteroinfifo"
            rm -f $INFIFO
            mkfifo $INFIFO
            (tail -f .kakinteroinfifo | stack ghci >out 2>&1 --with-ghc intero ) >/dev/null 2>&1 </dev/null &
            PID=$!
            #write interpreter pid 
            echo "$PID" > "$PROJECT_ROOT/.kakintero"
        fi
    ~
}

def -allow-override intero-quit %{
    %sh{
        PROJECT_ROOT=$(stack path | grep project-root | cut -d: -f 2)
        if [ -n "$PROJECT_ROOT" ]; then
            if [ -s "$PROJECT_ROOT/.kakintero" ]; then
                echo ":q" > "$PROJECT_ROOT/.kakinteroinfifo" 
                kill "$(cat $PROJECT_ROOT/.kakintero)"
                echo "echo 'Intero has been terminated'"
            fi
            rm -f $PROJECT_ROOT/.kakintero
            rm -f $PROJECT_ROOT/.kakinteroinfifo
            rm -f $PROJECT_ROOT/out
        fi
    }
}
```
