### ISSUE TITLE
Can't add a `ranges` highlighter to windows using the `WinCreate` hook

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1197]
Hi,

When I came up with a solution for #1192, I noticed that the `WinCreate` hook supposed to add a `ranges` highlighter to the window doesn't do so. I verified that using the completion on the `rmhl` command, the highlighter isn't in the list of candidates returned.

To reproduce the issue, save the following script to a file and `source` it using the `-e` flag:

```
decl range-faces _

hook global WinCreate .+ %{
    set window _ "%val{timestamp}:1.1,1.1|Error"
    addhl ranges _
}
```

Note that this issue is only reproducible when the above script is loaded before any windows have been created, it otherwise works as expected.

HTH.

**Comment by mawww** [comment]
Cannot reproduce here, if I do `kak -e 'source test'` with the given commands in the test file, I do get an `hlranges__` highlighter in every new window I create, only the `*scratch*` window, that was created at startup, before running the init commands, does not have it.

**Comment by lenormf** [comment]
Yes, you have to open a file directly from the command line to reproduce the issue:
```
$ kak -e 'source test.kak` test.kak
rmhl<tab>
```

**Comment by mawww** [comment]
In that case, the issue is just that we run the init commands after opening the init files, but thats not clearly a wrong behaviour, I think its actually the best default, as it allows touching the client selection during init.

**Comment by lenormf** [comment]
So scripts loaded that way won't have access to the window context? It's not a big deal, but since this is unexpected, it would be nice if it could -easily- be fixed.

**Comment by mawww** [comment]
To be more explicit: `-e 'commands'` executes `commands` at some point during startup, `filename` opens the filename at some point during startup. Currently we do file opening first, then execute the initial commands. Doing things this way means that we have a real context ready, with a buffer opened, as set of selections, a window...

If we were to change that order, execute the initial commands first, then load the files, which would fix this issue's use case, we would be executing the init commands before getting a client context (we dont have any buffer and window created yet), which means the init commands could not do anything that requieres a context to be ready.

I am saying that I think the first option is better, because in most cases we want the init command to be able to interact with the client context.
