### ISSUE TITLE
Implement a portable `readlink` function

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1224]
Hi,

The `readlink` utility isn't available on mac by default, which means that the `ctags.kak` script (the only builtin script that uses `readlink`) won't work out of the box. It hasn't really been a problem until now because apparently most of our mac users either don't use ctags or have the GNU `coreutils` installed, which provide `readlink`, but it would be nice to get rid of this dependency.

Thanks.

**Comment by mawww** [comment]
is `realpath` available on mac by default ?

**Comment by lenormf** [comment]
According to @casimir no, you need to install a GNU package to have it along `readlink`.

**Comment by casimir** [comment]
By default there is only a BSD `readlink` that doesn't support the `-f` flag. By installing gnu-coreutils you also get the GNU readlink which binary is `greadlink` to avoid conflict and the GNU realpath which binary is `realpath` because no conflict.
AFAIK there no portable way to do it without installing some package or developing a shell function.

**Comment by 5paceToast** [comment]
Do note that there is at least [one](https://github.com/mkropat/sh-realpath) project that emulates `readlink` and/or `realpath` in sh.

**Comment by casimir** [comment]
For ref: 510be03910081f320fae600629f23591f4fc207c

**Comment by mawww** [comment]
ctags has been fixed with a custom impl, no other use cases, closing.
