### ISSUE TITLE
Specify a return code in quit command

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1230]
It'd be nice if you could specify a code which the current kakoune client would return at exit.  

Some potential use cases:

- abort an interactive git rebase or commit (or more broadly any that call `$EDITOR` and use its return value)
- use for non-interactive text processing with `kak -e` (in particular, wrap a command in try ... catch and return non-0 in case of an exception) to signify failure

**Comment by Delapouite** [comment]
Yes, it would be handy.

vim supports a `:cquit` command and it's appreciated by a lot of people: https://stackoverflow.com/questions/4323440/how-do-i-stop-a-git-commit-when-vi-is-on-the-screen-waiting-for-a-commit-message

But I reckon letting the user specify an optional error code after kakoune `q` command is a better design.

**Comment by Delapouite** [comment]
Currently, the `quit` command removes the current client from the client manager:

https://github.com/mawww/kakoune/blob/master/src/commands.cc#L425-L444
```c++
template<bool force>
void quit(Context& context)
{
    if (not force and ClientManager::instance().count() == 1)
        ensure_all_buffers_are_saved();

    ClientManager::instance().remove_client(context.client(), true);
}

const CommandDesc quit_cmd = {
    "quit",
    "q",
    "quit current client, and the kakoune session if the client is the last "
    "(if not running in daemon mode)",
    no_params,
    CommandFlags::None,
    CommandHelper{},
    CommandCompleter{},
    [](const ParametersParser&, Context& context, const ShellContext&){ quit<false>(context); }
};
```

which, as side effect, is exiting the main loop, since the client_manager is empty

https://github.com/mawww/kakoune/blob/master/src/main.cc#L634
```c++
while (not terminate and (not client_manager.empty() or (flags & ServerFlags::Daemon)))
```

and the execution flow is free to continue to the hardcoded return `0` value : 

https://github.com/mawww/kakoune/blob/master/src/main.cc#L668
```c++
return 0;
````

**Comment by mawww** [comment]
The main problem here is to define reasonable semantics for that: What process exactly should return the given exit code ?

* When we have multiple clients, only the current client will quit
* When we have one client and one server, they will both quit if the server is not in daemon mode
* The last client and server could as well be the same process

Also, if you run kak, and then for some reason it forks the server in the background (usually because it got suspended), the original process is now a client process.

It is tricky because the use case for that is if another process runs Kakoune as its child, and wants to get an exit status. The problem here is that for that exit status to be meaningful, it needs to be predictible. Currently we dont know which kind of Kakoune process the child will be on exit (will it be a server, a client, both server and client ?). We could bite the bullet and always use separate processes for client and server, but as the server needs to run in the background, it will likely be the process that gets forked off, meaning we would get the exit status of the client, the problem with that is that the server might, or not, still be running, which could be a problem (is it ?) for the motivating use case.

**Comment by occivink** [comment]
I may be glossing over technical difficulties, but I think having the client which sends the "quit" command exit with the return code would be consistent. The server would always exit with 0, but the use-case that make sense to me is for single-purpose clients to indicate whether they suceeded or failed.

- Server and client the same => The process exits with return code as if it were just a client. 
- Separate client and server => "quit" applies to the client process. If it's the last client, server exits with 0. Since the server got orphaned, we can't really use the return code anyway.
- Separate client and daemonized server => "quit" applies to the client. Since the only way to stop the server is by signaling it, the semantics of "quit" don't really apply.

1\) and 2) are consistent if you ever decide to always use separate processes.
