### ISSUE TITLE
Solarized colorscheme dark brown in tmux.

### ISSUE THREAD

**Issue by dpc** [mawww/kakoune#1259]
Outside of tmux, everything works fine. Inside tmux the colorscheme is dark/brownshish instead of dark solarized. I use `gnome-terminal` with `TERM=xterm-256color` and in `tmux` I have `TERM=screen-256color`.

**Comment by lenormf** [comment]
Do you have the appropriate terminfo databases installed on the system? Have you tried other terminals?

**Comment by dpc** [comment]
I tried it on both ArchLinux and Fedora 25.  I don't have solarized configured in other terminals. Vim works OK, I'm also using Spacemacs and it had some problems but eventually got it to work as well both outside and inside tmux.

**Comment by mawww** [comment]
Hello,

This is known, it is due to tmux not supporting color palette changes, so Kakoune has to project the colors to the closest in the hard coded 256color one. Solarized uses colors that have no close counterparts in that palette, so you end up with this brownish colors.

The solution would be for tmux to add support for palette changes, or for Kakoune to drop ncurses and write its own terminal backend to make uses of 24bit escape sequences.

**Comment by lenormf** [comment]
![](https://my.mixtape.moe/inajvd.png)

Damn.

**Comment by dpc** [comment]
So, at least for gnome-terminal, the 0 and 1 (standard fg and bg) are remapped to the right colors, I believe. How would I go about forcing (eg. hacking `solarized` colorscheme file) to make it output colors 0 and 1? Seems to me that other colors are just right.

**Comment by mawww** [comment]
You could do `face Default default,default` to use the default terminal colors for the base face, Just put that in your kakrc after calling `colorscheme solarized`
