### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by guillaumecherel** [mawww/kakoune#1272]
I wondered how to do a case insensitive search with `/`. I found out without much trouble that it could be done by using a regex like `(?i)something`. 

I haven't seen it in the [perl regex syntax link](http://www.boost.org/doc/libs/release/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html) provided in kakoune documentation (my poor of ability to read the doc?). I thought it might be worth documenting it more explicitly, given it's a relatively common need.

**Comment by lenormf** [comment]
Here is the relevant bit from the documentation:

>Modifiers
> (?imsx-imsx ... ) alters which of the perl modifiers are in effect within the pattern, changes take effect from the point that the block is first seen and extend to any enclosing ). Letters before a '-' turn that perl modifier on, letters afterward, turn it off.
>(?imsx-imsx:pattern) applies the specified modifiers to pattern only.

I have the following bindings in my configuration:

```
map -docstring 'case insensitive search' global user '/' /(?i)
map -docstring 'case insensitive backward search' global user '<a-/>' <a-/>(?i)
map -docstring 'case insensitive extend search' global user '?' ?(?i)
map -docstring 'case insensitive backward extend-search' global user '<a-?>' <a-?>(?i)
```

Maybe this could be written in the wiki or something.

**Comment by mawww** [comment]
Yep, case insensitive search is done by adding `(?i)` in the regex, and can be automated as shown by @lenormf.

**Comment by asmarcz** [comment]
For those struggling, `map global user '/' /(?i)` hasn't worked for me in v2021.11.08.
Try `map global normal '/' '/(?i)'` instead.

**Comment by Screwtapello** [comment]
`map global user '/' /(?i)` should work just fine, but it adds the mapping to the "user" mode. You can enter "user" mode from normal mode with the comma key, so "case insensitive search" would be `,/` instead of just `/`

`map global normal '/' /(?i)` lets you search case-insensitively just by typing `/`, but it prevents you from immediately hitting `<ret>` to repeat the previous search, or `<up>` and `<down>` to cycle through search history. You have to backspace over `(?i)` in order to get access to those features.

That's not to say either approach is wrong, but they each make some functionality easier to access at the expense of making other functionality more difficult. You can configure Kakoune to suit whichever functionality you use most often.
