### ISSUE TITLE
Bug? assert failed "it->type() == DisplayAtom::Range" at display_buffer.cc:120

### ISSUE THREAD

**Issue by nicholastmosher** [mawww/kakoune#1275]
Hi everyone.
I'm having a bug where kakoune crashes every time I type past 80 columns. I have a column highlighter (hlcol_80), and it seems that while I'm typing in insert mode as soon as I hit that line it crashes. I have the debug output below:

![capture](https://cloud.githubusercontent.com/assets/4210949/23776489/b065d480-04fc-11e7-99ea-6720d4cf14e0.png)

When kakoune crashes in this way all work that had not been saved is lost.

**Comment by mawww** [comment]
The work should not be lost, it should get saved into .<filename>.kak.XXXX files, and the autorestore.kak script is able to automatically restore these. If thats not the case, we have another bug.

I could not reproduce the bug though, do you have more precise reproduction steps ?

**Comment by lenormf** [comment]
I know what's going on, because I've hit this issue in the past.

What happens is that you have a highlighter set on the window already (`show_whitespaces`?), and it's going to replace the atom at the 80th column (making this particular atom a `ReplacedRange` atom). Then another highlighter is going to try to modify that same atom again, except when splitting the display line to insert a new atom, we're hitting the assert in the `DisplayLine::split()` function, which expects the atoms to be untouched.

How to reproduce the bug:

```
$ kak -n
:addhl show_whitespaces
i<space><esc>
:addhl column 1 red
A<backspace>
```
