### ISSUE TITLE
exec fails to bring up interactive prompt for commands

### ISSUE THREAD

**Issue by leeola** [mawww/kakoune#1303]
When implementing a custom user mode via https://github.com/mawww/kakoune/wiki/Implementing-user-mode, i noticed that i cannot get any interactive prompts from the `exec` command.

For example, in the above link it uses:

```
'<space>') echo exec ':buffer<space>' ;;
```

If i try to type/run `:exec ':buffer<space>'` manually, it does not bring up an interactive prompt. If i type `:buffer` manually, it *will* bring up an interactive prompt.

Oddly enough, if you type/run `:exec ':buffer<space><tab>'` you *do* see an interactive prompt, but it cannot be typed in. As soon as you type, it disappears. The following asciinema illustrates this: https://asciinema.org/a/978t3ygnge4jfft53cd3gh84n

**Comment by jockus** [comment]
I encountered the same issue, apparently completions are turned off for exec scopes by design.

**Comment by mawww** [comment]
So, this was put in place for two reasons, prevent screen flashing with redrawing due to completion, and avoid completion computations for non interactive use cases.

The first reason is moot now, the display logic has been reworked, and is much more lazy.

For the second reason, a nicer solution would be to make the prompt completion work in the same way as the insert completion: trigger only after some idle time without input.

I think this is a reasonable change, I'll take a stab at implementing that.

**Comment by leeola** [comment]
As an aside, this is perfectly fine default behavior, a flag to enable / configure how interactive `exec` behaves would be perfectly acceptable, imo.

Appreciate the comment, this is a greatly desired feature for those using custom user modes. Thanks!
