### ISSUE TITLE
Unintuitive "x" behavior when combined with numbers

### ISSUE THREAD

**Issue by bhajneet** [mawww/kakoune#1334]
![17-04-24_21 48 1493084889](https://cloud.githubusercontent.com/assets/14130567/25365595/c436246a-2937-11e7-87f4-805dd5f0a8f2.png)

In the above scenario if I'm trying to grab all lines from where the cursor is to the (relative) 5th line, I have to type 6X. Wouldn't it be more intuitive to type 5X? Right now I have to remember to add one to my x/X commands when using the left-hand line-numbers.

I don't think the scenario 1x/1X makes much sense either. You can always type x/X for that. But it would be confusing to switch models. Also this would be at odds with the w,e,b commands. However it would sort of integrate with 1j,1k comamnds. For instance, 3J and 3X currently highlight differing number of rows. First gets 4 lines, second gets 3 lines.

**Comment by lenormf** [comment]
The `X` key will expand the current selection with either the current line if the anchor is in the middle of the line, or with the next one if at the end. Repeating the `X` 5 times when the anchor is in the middle of the current line would get you 4 lines down, that's the expected behaviour.

The way you want to handle your case is too smart for its own good, you would have better results with a `5JGl`, even if it's longer (there's also `5J<a-L>` but that's too much gymnastics for my fingers).

**Comment by bhajneet** [comment]
I like the current `x` behavior, it's just when combined with numbers that it confuses me. It would be odd to have `x` be the only one that behaves differently out of `w`,`e`,`b`, but at the same time I can't see a reason for `1x`, `1w`, `1e`, `1b`. It's only when the numbers are higher than 1 that it makes sense, and then in the case of x it doesn't align with numbers on left. That's because it's counting its own line as one (as you said). 

It's a tricky situation. I don't think it can be fixed without a lot of thinking, and even then probably not worth the time. I think the solution for me would be this instead: `<a-x>#X`, or as you said `#J<a-x>`. Thanks for pointing out the alternate solution that works in my head!
