### ISSUE TITLE
Update README with proper instructions for installing on Debian based systems

### ISSUE THREAD

**Issue by aniketd** [mawww/kakoune#1351]
I learned that its deprecated from issue https://github.com/mawww/kakoune/pull/1300. So this needs to be updated in the README.

I'm on Kubuntu 16.04 LTS, how do I go about this? I have no experience make or maintaining packages for Debian, if I get help I would be glad to contribute a PR.

**Comment by lenormf** [comment]
There's an [ubuntu package](http://packages.ubuntu.com/zesty/kakoune) but it's out of date and probably unmaintained now.

I didn't fix the documentation because when I had `make_deb.bash` removed I wasn't aware this paragraph existed, the alternative is to use [kakoune-debian](https://github.com/lenormf/kakoune-debian), it should get you going.

I don't think my 3rd party repository should be documented officially, so I simply had the paragraph removed in #1352.

**Comment by aniketd** [comment]
@lenormf Thanks! I will try the other repo...
