### ISSUE TITLE
Allow completers to set MenuInfo

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1373]
The builtin word completer has an extra field with face MenuInfo which says which buffer the word appears in. This proposal wishes custom completers to be able to set this field too.

For LSP we could use this field to indicate the identifiers kind. Examples there are `method`, `field`, `class`, `function` etc (See `SymbolKind` in [protocol.md](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md)).

A backwards-compatible way to do this is to allow a optional fourth field of the `|`-separated string for each item with the contents of the menu item.

Example, if we complete this python snippet at the end 
```
class MyClass(object):
   def __init__(self):
       self.my_field = 'apa'

   def my_method(self):
      """My amazing method."""
      return self.my_field + ' bepa!'

cepa = MyClass()
cepa.
```

With this proposal we can use the menu info to show if completion alternatives are `method` or `field` by setting the completer option to:

```
10.5@4:my_method|My amazing method.|my_method|method:my_field||my_field|field'
```

Thanks!

**Comment by mawww** [comment]
So, using MenuInfo (or any other face) is already possible because the menu entry is parsed as a display line, so it supports `text{foo}text with face foo`. What is needed here is a way to align text.

The easiest way is just to let the script do that job, its just a matter of computing the longest candidate, and add `longest + 1 - len(candidate)` spaces before `{MenuInfo}$kind`.

**Comment by danr** [comment]
Amazing! I'm surprised that I hadn't tested that :upside_down_face:
