### ISSUE TITLE
Cursor shape doesn't change in insert mode

### ISSUE THREAD

**Issue by sassanh** [mawww/kakoune#1385]
Neovim has an option `guicursor` which handles cursor shapes without any pain. Is there anyway to set different cursor shapes in insert and normal mode for kakoune?

**Comment by ekie** [comment]
hello,
this is not possible and kakoune diverges from vim and other editors in that regard because kak always operates on selections.

https://github.com/mawww/kakoune#31-selections
> The main concept in Kakoune is the selection. A selection is an inclusive, directed range of character. A selection has two ends, the anchor and the cursor. 
There is always at least one selection, and a selection is always at least one character (in which case the anchor and cursor of the selections are on the same 
 character).

you can however use different faces differentiate the insert and  normal mode visually.

**Comment by sassanh** [comment]
Is a single character selected even in insert mode?

**Comment by ekie** [comment]
yes.

**Comment by sassanh** [comment]
OK, thanks for quick response.

**Comment by ekie** [comment]
since  https://github.com/mawww/kakoune/commit/91ed57c985a2edb879a1956c75282ff0f6b04485 the cursor is visible. #1393 would enable the ui to set the cursor shape.

**Comment by tmccombs** [comment]
> you can however use different faces to differentiate the insert and normal mode visually.

how would I do that?

**Comment by Screwtapello** [comment]
@tmccombs See https://discuss.kakoune.com/t/changing-the-cursor-colour-in-insert-mode/394 for an example.
