### ISSUE TITLE
Write runtime errors to the debug buffer

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1410]
Hi,

It can be difficult, if not impossible sometimes, to read the entire error in the statusbar, it'd be convenient to have runtime errors written to the debug buffer as well.

Thanks.

**Comment by mawww** [comment]
Hum, this would make sense, but I think we should separate "expected" errors like `nothing selected` from unexpected ones, like `unterminated strings`, and only write the unexpected ones in the `*debug*` buffer.

That way we would avoid flooding the debug buffer with expected errors.

**Comment by lenormf** [comment]
How do you determine what's expected from the others?

**Comment by mawww** [comment]
Well, selections errors, like hitting the end of a buffer with `w` or `s` not finding any matches are expected. But command parsing errors are not. I expect some cases will be more ambiguous, but it still seems pretty clearly defined.

**Comment by lenormf** [comment]
I'm not convinced a distinction should be made between errors, after all they are _errors_ and the debug buffer should contain as much unfiltered information as possible to be useful, but I guess this could be a start.

About the code, how do you think this should be done? Adding a field to the `runtime_error` that indicates by the catcher that the message should be logged in the debug buffer as well, or create a new type that inherits from it that will have its own catch, or something else?

**Comment by mawww** [comment]
It could be implemented by a subtype of runtime_error, either `expected_error` or `unexpected_error` (depending on which one we think is the default).

I think we dont really want every `s` or `w` or `<a-k>` that end up failing because they dont select anything to write in the debug buffer, they are "expected" in the sense that they should happen in regular use of Kakoune. Failing to parse a command however is not really expected, and should be logged.

All that said, I think we can just start by logging every errors and see if the flooding I fear is a real problem, or not.
