### ISSUE TITLE
Execute another shell program in the foreground

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1414]
Hi,

vim has the ability to launch another shell program in the foreground (e.g. `:silent !ranger`). It would be nice (especially for integration with file managers or `fzf`) to be able to do the same. 
I know that we can spawn new terminal emulators but I find that slightly awkward for this case.

**Comment by mawww** [comment]
There is a few problems that prevent such a feature: shell programs are run by the server, and what we would like is to run the shell program in the client's terminal. That means we would need to suspend the client, run a program in its terminal window, then resume the client from the *server*.

That would be pretty complex to do. Moreover, this would only work for terminal UIs, graphical UIs have no terminal emulator they run in.

**Comment by occivink** [comment]
I see, thanks for the explanation. If you think it would not be worth the complexity, just close the issue.

**Comment by lenormf** [comment]
Is there no way you can cheat to implement that? Like have an external X11 utility draw directly on the current window, and wrap the calls into a script? It would be ugly and I don't know if it's doable at all, but maybe there's a way for you to achieve the wanted result, no matter how ugly.

**Comment by mawww** [comment]
Well, it should be doable by suspending the client (that needs something to handle the suspending though, such as a shell that launched the client, not sure how to achieve that for clients launched dirrectly inside the terminal emulator), then running the shell command attached to that clients pty, which should be findable through the /proc filesystem.

Its going to be very hacky, but I think it might be doable.

**Comment by mawww** [comment]
Took a look, it is doable already, assuming you have a separate client running standalone in a terminal emulator:
```
kill -STOP $client_pid # Suspend client process
command </proc/$client_pid/fd/0 >/proc/$client_pid/fd/1 2>/proc/$client_pid/fd/2 # start other program using the clients tty's
kill -CONT $client_pid # Resume client process
```

This works with interactive programs, such as `mutt`, its necessary to STOP/CONT the kakoune client process so that it wont compete with the given command to read/write on the terminal (else you'd have a race between the two programs to get keys, and they would both be writing output to the terminal resulting in garbled screen).

The remaining problems are getting the client pid in a programatic way, along with supporting the same pattern when there is a shell underneath the client (currently the shell will try to take back control of the terminal when you suspend the client).

A last problem is easily solvable: if we are in mixed client/server mode, we need first to fork the server to background before suspending the remaining client process.

I am also wondering (again) if that single process mode is really worth it, we could just bite the bullet and always have separate client/server processes even in single client mode, which could simplify quite a bit of code.

**Comment by lenormf** [comment]
Another issue is that some programs still force attachment to the current terminal, such as `lf`.

**Comment by danr** [comment]
Got a bit interested to try this again, do we have any solution to get the client pid?

**Comment by mawww** [comment]
Not at the moment, but I could add it

**Comment by danr** [comment]
That would be most appreciated :)

**Comment by alesguzik** [comment]
Could this be implemented as simple `system("do something")` call inside the client? It suspends the caller and resumes it automatically after command is finished. This way you won't need to have any handling of it in the server, and if one need to pass data around, one may either pass file names as arguments, or even use shell redirections.

**Comment by mawww** [comment]
@alesguzik In order to do that, we would need to have a new user interface message sent from the server to the client that would tell it to run some shell command in place. It would be doable technically, but would be limited to terminal UIs (or require graphical UIs to support terminal emulation one way or another), and we would not be able to do anything special with the output (except if we started to have a way for that output to be sent back to the server, but that would mean implementing basic terminal emulation in clients...).

I think its going to be a hack in any case, so I'd rather leave it as an "external" one. Here is what I got so far, it works fine here for non primary clients (the ones created with `:new`):

```
define-command client-run -allow-override -params .. %{ %sh{
    kill -STOP $kak_client_pid
    (
        termcfg=$(stty -g)
        stty sane
        "$@"
        echo "Press <ret> to return"
        read line
        stty "$termcfg"
    ) </proc/$kak_client_pid/fd/0 >/proc/$kak_client_pid/fd/1 2>/proc/$kak_client_pid/fd/2
    kill -CONT $kak_client_pid
}}
```

I think we probably can get to something more robust this way, and we dont need to add that hack inside the core code.
