### ISSUE TITLE
Collapse successive white space when rendering status line

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1457]
Like web browsers render HTML.

That is strip surrounding white space and collapse successive white space into one when rendering `modelinefmt` option.

**Comment by mawww** [comment]
I dont think thats a good idea, in my view, either you have this problem because you are generating the status line through a complex process, and you'd better just filter the resulting line yourself. Or you are writting the status line manually, and it seems better to keep full control over it, instead of having Kakoune change the whitespacing.

I could be ok with stripping surrounding whitespaces, although the argument for it is not as strong as for the docstrings (that are usually multiline and hence sometimes end up with surrounding whitespaces just for formatting reason in their surrounding script), but collapsing successive whitespaces seems wrong to me, if you have them, its probably the user wanted them, or because the code that generated it did put them in, in which case that generating code should be fixed instead of having Kakoune post processing.

**Comment by alexherbo2** [comment]
I would like to split status line on multiple lines.

It’s the status line I use:

``` kak
set global modelinefmt '{{mode_info}} %opt<plug-in>… {magenta}%val(client){default} at {yellow}%val(session){default} on {green}%val(bufname){default} {{context_info}} {cyan}%val(cursor_line){default}:{cyan}%val(cursor_char_column){default}'
```

Usually to add an info, I rely on options and update them independently in a hook.

**Comment by mawww** [comment]
I dont think the use case is sufficiently strong to justify that change, I dont plan on doing that.
