### ISSUE TITLE
Preserve declaration order in user mapping infobox

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1479]
Currently the order of the user mappings in the infobox is seemingly arbitrary . It would be nice if it respected the order of declaration so that we could group similar mappings together.

**Comment by Delapouite** [comment]
> is seemingly arbitrary

Isnt it alphabetical ?

**Comment by occivink** [comment]
Oh you're right, the `<a-*>` mappings threw me off.

**Comment by lenormf** [comment]
>>is seemingly arbitrary

>Isnt it alphabetical ?

The entries are sorted by ASCII value (which means "alphabetically" in programming parlance) in `keymap_manager.cc:49`. Since this order doesn't really make sense to the average user (who will wonder why capitalized keys are placed after punctuation signs, apart from lower case keys), I suppose we could fix it in `normal.cc:134`, where this list is generated.

**Comment by mawww** [comment]
It would be possible to follow the order of definition, although it would not be perfect as we'll still have mappings grouped by scope (global mappings first, then buffer mappings, and finally window mapping).

If thats preferred, it should not be too hard to switch to that.

**Comment by occivink** [comment]
I don't use any scope-specific mappings so I can't say much, but even then the grouping would be more "logical" I think.
