### ISSUE TITLE
Add -toggle flag to set-option for boolean value

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1488]
Hi

`rc` scripts often need to do some bookkeeping to know things like if a command is currently enabled/disabled, or if a highlighter is on etc…
This state is stored in hidden boolean options.

Also it will ease mappings toggling on common options like `incsearch`, `aligntab`…

I suggest to introduce a `-toggle` flag that would turn a boolean option from `true` to `false` or inversely from `false` to `true`

```
declare-option bool foo_enabled false

set-option -toggle window foo_enabled
# foo_enabled is now true

set-option -toggle window foo_enabled
# foo_enabled is back to false
```

An alternative could be a proper `toggle-option <scope> <name>`, but the `-toggle` flag fits well alongside the already existing `-add` flag.

In vim, this behavior is triggered by appending a `!` after the option name which is less explicit.

**Comment by lenormf** [comment]
I like the idea, but where would this be needed? I personally only ever check whether an option is `true` or `false` because they tend to control the scripts' behavior, and never need to change them in the user's back.

**Comment by mawww** [comment]
Personally, I dont really like the few scripts that provide a `toggle` command, I dont think they should provide it themselves as it usually requires an additional option that is just used for that (knowing if they are enabled or not).

That said, we dont all have the same workflows. I am still dubious that this would really be useful, as I'd expect the scripts will need the value of the option when toggling in order to chose if they need to enable or disable the feature. Once you have that conditional anyway, the value of a toggle bool feature is pretty low. (And its likely the option handling is going to be done in the `enable-super-feature` and `disable-super-feature` commands anyway, so never in a context where we want to toggle).
