### ISSUE TITLE
Change `c` and `d` commands to never yank

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1497]
This discussion came up after adding #1175.

Suggested by @occivink

**Comment by mawww** [comment]
I like the idea from a design standpoint, I think it would make Kakoune editing language more orthogonal, however this is going to break lots of muscle memories (and possibly, many scripts), so it needs to be thoroughly discussed.

**Comment by lenormf** [comment]
Since we're talking about a side effect here, I don't think removing it would improve orthogonality.

In everyone's average editing session, how many times have you actually cared about not modifying the yank register, versus the amount of times that you've relied on `c`/`d` copying removed data to it in order to paste it again down the line? In my case, the ratio is probably 20%/80% respectively.

Also now that `<a-d>` has been assigned, we would have no chance to have a shoe-in legacy mapping (`yd` isn't that bad, but the original side effect seemed to be there precisely to avoid typing that combination that I personally need so often).

**Comment by alexherbo2** [comment]
How about

``` kak
map global normal ( <a-x>dk<a-P>
map global normal ) <a-x>d<a-p>
```

Suggested by @Delapouite from [vim-move][]

[vim-move]: https://github.com/matze/vim-move

**Comment by alexherbo2** [comment]
https://github.com/alexherbo2/move-line.kak

**Comment by doppioandante** [comment]
I usually do a lot of small deletion, particularly before copying some text in the place I want it to be, and I basically never want d to mess my clipboard.
Btw, don't other editors do the same? ctrl-c, ctrl-x and delete are separate operations. I though current `d` was some sort of legacy from vim.

**Comment by lenormf** [comment]
>I though current d was some sort of legacy from vim.

And I thought that `vim` eventually made `d` copy the deleted content to the yank register because it was a side effect users could use, as opposed to only making it remove the selection :p

**Comment by alexherbo2** [comment]
I’m not sure why either, but we can notice that the editing model would had not allowed such orthogonality.

In Kakoune, we can just chain the verbs on the objects, rather than in vi, it has to repeat the object for each verb.

**Comment by lenormf** [comment]
Doesn't 81b5de6fd86b4d1db25cf7e25f3e29bdb6ad9689 close this? The fact that alternative bindings to `c` and `d` that don't yank were added implies that the current behavior isn't going to be changed.

**Comment by mawww** [comment]
Not really, 81b5de6 more or less triggered that discussion about just not yanking on `d` and `c`. I am not sure about that change, I like it in principle, but after trying to use Kakoune for some time with the change locally, it felt wrong, maybe its because I am too used to the yanking behaviour.

I'd like to see more discussion on that before taking a decision.

**Comment by danr** [comment]
The non-yanking ones are more primitive: the yanking ones are easy to map using those as primitives:

```
map global normal c yc
map global normal d yd
```

I would probably make these mappings (and be totally OK with it) if you chose this more primitive behaviour.

**Comment by occivink** [comment]
It's also just as easy to go the other way currently:
```
map global normal c \"_c
map global normal d \"_d
```
Personally I'm in favor of this. I've been using these bindings since I started with kakoune as I think they align well with the "orthogonality" concept. Since I don't have any prior vim background it feels just as natural.

**Comment by occivink** [comment]
I think I would like to hear the thoughts from people who have joined since then (or didn't comment yet). Ping @Screwtapello, @Delapouite, @Franciman , @maximbaz, @ul, @shachaf, @robertmeta, @eraserhd, @andreyorst

**Comment by maximbaz** [comment]
I am in favor of making `c` and `d` to never yank, almost immediately after I discovered kakoune I swapped `c` and `d` with `<a-c>` and `<a-d>` and have been happy with this change ever since. I delete stuff more often than cut it, and when I cut something I don't want to accidentally overwrite it by deleting something else.

```
map global normal c       '<a-c>'
map global normal <a-c>   'c'
map global normal d       '<a-d>'
map global normal <a-d>   'd'
```

**Comment by ul** [comment]
I rely quite often on `c` and `d` yanking. Good example is when I want to extract block of code into a variable. I select that block, press `c`, write variable name, then go to a location where I want to declare it, press `.` to insert variable name and `p` to insert extracted code block. I don't want extra `y` press here.

The only thing which I tuned is duplicating yanked content into system clipboard: I remapped `y` that it does duplicate, while `c` and `d` still doesn't. So when I want explicitly yanked content I press `<leader>p` and get it from system clipboard, even if there were `c` and `d` in between. 

> What I do want is killring feature from emacs, where yank works as a stack.

Yes! That would be perfect.

**Comment by Franciman** [comment]
As long as there is a simple way to cut the selection, I'm fine with the change.

**Comment by TeddyDD** [comment]
I almost never had a situation when I needed to think about protecting clipboard content and I use yanking delete all the time. Some clipboard history / kill ring would be cool tho :O

**Comment by lenormf** [comment]
Since not everybody agrees, could we close this and let everybody redefine <kbd>c</kbd> and <kbd>d</kbd> locally?

**Comment by mawww** [comment]
Yeah, with no strong consensus, although I do like the idea from an orthogonality stand-point, keeping the status quo seems to be the best course of action.

**Comment by alexherbo2** [comment]
[![asciicast](https://asciinema.org/a/219306.svg)](https://asciinema.org/a/219306)

❯ [Yank Ring](https://github.com/alexherbo2/yank-ring.kak)
