### ISSUE TITLE
rc/core/doc.kak does not respect $(docdir) from make install

### ISSUE THREAD

**Issue by drwilly** [mawww/kakoune#1513]
Currently the script uses the hardcoded path `${kak_runtime}/../doc/kak/manpages/`.
Is the docdir var meant to be set manually for the install process?

**Comment by lenormf** [comment]
There's no pre-processing made of the runtime files during the compilation phase, and I think it's better that way. This has never really been a problem because most distributions put documentation into `/usr/share/doc` (I assume you're using gentoo?), but it must be a pain to come up with patches that fix the directory paths everywhere, so I guess this could be simplified.

Options I can think of right now:

* pre-process all the files that use directories set during the compilation phase
* declare a variable in all the scopes where a directory is used to allow doing a simple `sed` over an entire directory (e.g. `sed 's,path_docdir,/path/to/doc,g' *.kak`)
* declare hidden global options (in `kakrc`?) whose values would contain the paths

**Comment by drwilly** [comment]
Correct, I'm using gentoo.
The bug occurs because gentoo uses versioned doc dirs, so the correct path would be e.g. `/usr/share/doc/kakoune-0_pre20170523/manpages/`

**Comment by mawww** [comment]
should be fixed by 420c6aca233e79249ffc8513347f73978eb0ecdc

**Comment by drwilly** [comment]
neat
