### ISSUE TITLE
Cursor glitches (still)

### ISSUE THREAD

**Issue by esbullington** [mawww/kakoune#1524]
I'm still experiencing the issue described by multiple users in #1392 (glitchy cursors) with tmux 2.2 and kak commit 420c6ac (latest master).  It's only with tmux, not otherwise.  Occurred on two different machines, both running Ubuntu 16.04.

**Comment by mawww** [comment]
Thats strange, as we explicitely hide the cursor and never enable it again (we had glitches once we tried to have the hardware cursor visible), so I'd guess its tmux that shows it back for some reason.

Would you have some asciicast or video demonstrating what you experience ?

**Comment by mawww** [comment]
Cannot do much without more data, it seems to be an interaction with tmux that fails, and is pretty strange as we do not use the hardware cursor at all (well, we do place it at the main cursor position for terminals that use that as a hint, but it is supposed to be hidden).

Please reopen if/when you get a way to demonstrate it.

**Comment by marsell** [comment]
I installed 2018.09.04 on macOS 10.13.6. Moving the cursor, especially while scrolling, causes the cursor to flash on apparently random places on the screen. On small screens (e.g. 80x24), there is almost no noticeable flashing, but with larger screens it becomes increasingly apparent. It appears that number of columns has no effect on this; increasing number of rows is what makes it worse.

This affects kak started with -n as well. I tried it with macOS Terminal and iTerm2 3.2.0, and both are affected, although iTerm2 is much more noticeable.

I've attached a [recording](https://github.com/mawww/kakoune/files/2373482/ascii.cast.gz).

I'm surprised that nobody else has provided you with more info yet, because it's really annoying. If there's anything else that would help, please let me know.

**Comment by Screwtapello** [comment]
I don't think there's much Kakoune can do about this.

A terminal emulator receives a stream of drawing commands from the application running inside, but they're not grouped into frames or repaints, it's just a continual undifferentiated stream. Terminal emulators have to choose when they'll actually paint the result to the screen, and if the terminal chooses to paint while the application is halfway through sending a screen update, you'll see a half-updated screen with the cursor somewhere in the middle.

If you play back that asciinema recording, hit space-bar and then tap "." to advance frame-by-frame, you'll see that the cursor is not flashing in random places, but in a steady progression south-east. Evidently, Kakoune can draw three-and-a-bit lines of output in whatever time division asciinema defines as a "frame". That explains why the flickering is so much less on a smaller terminal: with less output to draw, repainting is much faster, and therefore less likely to occur while the application is still sending output.

One followup question is "why does repainting take so long?" One factor is macOS' graphical quality: they put a lot of effort into high-quality text-rendering, and macOS often runs on "retina" displays with four times as many pixels to push, so it's not surprising to me that repainting is slow, unless you're using a GPU-accellerated terminal like [alacritty](https://github.com/jwilm/alacritty) or [kitty](https://sw.kovidgoyal.net/kitty/). Another issue is that (according to that asciinema recording) Kakoune is redrawing the entire screen even when the cursor just moves from one line to the next. I'm not sure if that's something asciinema enforces so that it can properly record the screen output, or a genuine behaviour of Kakoune, but it would surprise me if it was Kakounes' fault: the ncurses library that Kakoune is built on is pretty good at minimising screen updates. After all, it was designed for use with real, physical terminals running over slow serial connections.

It may help to make sure that `$TERM` is set to the name of your terminal in the ncurses database. Most terminals these days set `$TERM` to "xterm" or "xterm-256color" for compatibility, even though they aren't 100% compatible. Apparently the best description of macOS Terminal is "nsterm-256color", and the best description of iTerm2 is "iterm2".

**Comment by marsell** [comment]
Thanks for the details. :)

If other editors (specifically: vim) had the same problem, I wouldn't have left a comment. vim is barely affected.

However, your comment about TERM led me to change it. My original TERM was xterm-color in both iTerm and Terminal. Changing it to xterm-256color or xterm fixed the problem for both of them. Hooray!

**Comment by mawww** [comment]
@marsell Thanks for giving feeback here, I suspect the root of the problem is that, for some reason, the escaping sequence responsible for hiding the cursor was not correct in `xterm-color` terminfo (assuming it existed), so the cursor was not hidden as it should (Kakoune takes over cursor drawing and makes the hard cursor invisible).
