### ISSUE TITLE
`echo` not behaving as expected

### ISSUE THREAD

**Issue by dgrisham** [mawww/kakoune#1528]
I noticed this awhile ago, but didn't report it as an issue then (I'd found a workaround, but have since forgotten what it was).

The issue is with `kak`'s `echo` command. If I run the example given in the README, which is `:echo %sh{ ls -l $kak_bufname }`, I get the error `1:1: 'echo' unknown option '-rw-r--r--'`. It seems to be trying to execute the output of the `ls -l` command. I can reproduce with other directories as well.

Is this an issue with the README not being updated, or a bug?

**Comment by ekie** [comment]
hello,

this is actually a bug in the README. What you experience in this particular case is that the shell expansion returns a string starting with `-` which gets interpreted by the echo command as a switch, hence the error message `'echo' unknown option -rw-r--r--'`. In order to prevent interpreting `-` in the output as a switch use `:echo -- %sh{ ls -l $kak_bufname }`. Moreover if your expansion returns multiple lines you would need to double quote strings, for example something like this `:echo "%sh{ls -l}"`. This is why another example in the section https://github.com/mawww/kakoune#432-shell-expansion `%sh{ ls }` can fail too.

The examples should be fixed, and `--` be documented as well. Maybe you can contribute and create a pull request to fix these issues.

As a reminder for myself: if echo takes multiline strings, status does not reset correctly.

**Comment by dgrisham** [comment]
Gotcha, that makes sense. I'd be happy to make a PR for this, might be a few days (or a bit more, we'll see) but if no one gets to it first I'm on it!

**Comment by lenormf** [comment]
If scopes are expanded into multiple lines, all individual lines after the first one will be executed as commands. The `:echo %sh{ls -1}` command will print the first entry, but then all remaining entries will be executed as commands, resulting into an error.

Additionally, if the expansion returns a string that starts with an hyphen, it will be interpreted as a command option.

I think the safest way to execute your particular command is the following: `:echo -- "%sh{…}"`.
