### ISSUE TITLE
Mouse support is bugged on xterm

### ISSUE THREAD

**Issue by denis-rochette** [mawww/kakoune#1532]
There is a strange bug with the version of Kakoune I use (Archlinux) on xterm: the mouse selection stop working if I try to select something on a big line. It often stop working after 129 letters.

It's easy to reproduce this bug: open a new kakoune, write a 200 letters line, try to select the 180th... for me, it select a random letter at the beginning of the line.

**Comment by Screwtapello** [comment]
I can confirm.

- I opened `xterm`
- I shrank the terminal font until I had at least 300 characters per line
- I ran `!seq 1 200` to generate a bunch of text, and `Gg<a-j>` to turn it into one long line.
- Clicking on column 128 does the right thing.
- Clicking on column 129 selects column 1
- Clicking on column 130 selects column 2, etc.
- Clicking on column 223 selects column 95
- Clicking on column 224 moves the cursor to the end of the line.

Exactly the same thing happens on `gnome-terminal`.

Now, the column 223 limit is because Kakoune uses straight ncurses, and ncurses only understands the classic X11 mouse protocol which can't represent coordinates larger than 223 (as opposed to [more modern extensions](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Extended-coordinates).

The column 128 limit is more puzzling. It smells a lot like the cursor position is being shoved into a signed char, or otherwise limited to 7 bits for some reason. However, `mouse(3NCURSES)` says that ncurses stores mouse-coordinates as `int`, and Kakoune's `NCursesUI::get_next_key()` takes the coordinates and sticks them in a `DisplayCoord` (which seems to also use `int`), and then calls `encode_coord()` to stick them into a `Key`... and `encode_coord()` seems to stick the X and Y into the upper and lower 16 bits of a 32-bit integer, which should be safe.

I'm not sure what's going on here. :/
