### ISSUE TITLE
Document each command's alias

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1556]
Hi,

It seems that users who read scripts get sometimes confused by the use of aliases, and don't necessarily know what they mean as they're not in the documentation. We should show each command's alias in the documentation, to avoid that.

**Comment by Delapouite** [comment]
Yes.

There are already a few *implicit* ones indicated on https://github.com/mawww/kakoune/blob/master/doc/manpages/commands.asciidoc

For example:
```
b[uffer]n[ext]
switch to the next buffer
```

which kind of indicates that `bn` is an alias.
But then it becomes awkward for lines like:

```
add-highlighter [<flags>] <highlighter_name> <highlighter_parameters> …​
```

which will be harder to read:

```
add[-]h[igh]l[ighter] [<flags>] <highlighter_name> <highlighter_parameters> …​
```

So it deserves a proper *alias* line in the doc.

Also some commands like `face` are not the correct ones, since `face` is already the alias of `set-face`.
