### ISSUE TITLE
Support named subexpressions on the `regex` highlighter

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1559]
Hi,

It'd be convenient if the following syntax was supported:

```
addhl regex '^(?<line>[^\n]+)$' line:red
```

Currently, only a group index is supported in the positional parameters.

Thanks.

**Comment by mawww** [comment]
Named subexpressions are not supported by std::regex, and I dont think they are better enough compared to numbered ones to warrant adding support for them. Additionally, they would be very hard to support for general captures (like for the `s` command), I realize thats not what you ask here, but if we were to use them, I'd want to make them generally available instead of specific to the regex highlighter.

**Comment by lenormf** [comment]
Named subexpressions have a way to self document what they match, which is convenient when writing a highlighter with complex regex.

Example, from `make.kak`:

```
add-highlighter -group /make regex "^\h*(~*(?:(\^)~*)?)$" 1:green 2:cyan+b
```

With names instead of integers, we would know what the regex highlights without having to understand it (I still don't know what this highlights btw).

**Comment by mawww** [comment]
That highlight is strange, I am not sure what its supposed to highlight either.

I agree it would make things more readable, but I'd like to avoid relying even more on boost specific features, especially when the alternative exists and is only slightly worse.
