### ISSUE TITLE
Plugin manager.

### ISSUE THREAD

**Issue by dpc** [mawww/kakoune#1603]
I'd really like to switch go `kak` but until it has something like `vim-plug` it just not going to happen.

My `.vimrc` is a bunch of lines enabling different plugins + some settings for them. I get a new workstation, I do `:PlugUpdate` and bam, my Vim config is ready and I feel like home.

**Comment by lenormf** [comment]
Maybe your issue is about deploying configuration files to an arbitrary system, check out [vcsh](https://github.com/RichiH/vcsh).

As for loading scripts automatically, you can version them in a repository, and load them all with a shell command at runtime:

```
%sh{ find my_repo -type f -name \*\\.kak -exec printf %s\\n 'source {}' \; }
```

**Comment by dpc** [comment]
That's just not the same. Plugin manager gives me automatic updates and I don't have to deal with maintaining my own list (even though I do have a dot-files repository, revisioned by git, and linked into my `$HOME`). It's just soo much easier to have one plugin, that maintains all other plugins.

I guess it's also a project future question. If the goal of Kakoune is to be a neat, but niche project, then people might be OK with maintaining a bunch of files with plugins. But if it is to be popular it has to have a big userbase. And people are looking for convenience...

Kakoune is written in C++, and I have plenty of C++ experience, so let me compare this to Rust. Ignoring Rust features, Rust comes bundled with `cargo` - a package manager. And it makes developers life so much better: it's official, blessed, standard, everyone are using it, sharing code is easy, discovering libraries is easy, dependency management is easier. The community gets created around tools supporting its existence. For this very reason, I feel like Rust have a bright feature, while the days of C++ are numbered (though there are still decades of them).

Similarly, while Kakoune seems awesome it will never build any momentum if using it requires scavenging down some plugins in obscure places. However, if it was more like many existing IDEs/text editors that come with plugin management, people would immediately start seeing a potential value, be trying existing plugins and build new ones.

**Comment by danr** [comment]
Getting VimPlug-like functionality turns out to be incredibly simple, see for example the comment here: https://www.reddit.com/r/kakoune/comments/714urk/ive_published_dedicated_repos_for_some_of_my/dn955mb/
Edit this as you see fit to update the repos.

**Comment by dpc** [comment]
@danr I'll give it a try. Thanks.

**Comment by lenormf** [comment]
>That's just not the same

This is a very simple problem that can be solved using dedicated tool for each feature you require:

* a way to automatically load the code at startup
* a versioning system to update the scripts (and possibly checkout an older version of the code)

The code I gave addresses the first one, all that's left to do is automatically `pull` code from the script directories… which is exactly what @danr's linked code does… it kind of proves that it's exactly the same, doesn't it?

Since it's always better to fix a problem by using an infrastructure tool rather than implement a dedicated tool for the task, this is as close as a "plugin manager" a similar kakoune script will ever get.

>But if it is to be popular it has to have a big userbase

Luckily the primary goal of the project is to create a good tool, not to be as popular as possible to take over all other code editors of the market.

**Comment by mawww** [comment]
I think @danr script shows that we have all the necessary building blocks (basically, a shell and the ability to source files from it) to have a <10 lines plugin manager.

I dont think we should bless any specific plugin managing behaviour in Kakoune core, so I am not in favor of adding this inside the distribution.

**Comment by andreyorst** [comment]
Sorry for bumping old thread, but

> I'd really like to switch go kak but until it has something like vim-plug it just not going to happen.

@dpc If you still interested, I'd like to shamelessly advertise [plug.kak](https://github.com/andreyorst/plug.kak) to you.

**Comment by lenormf** [comment]
You could also create a "Plugins Managers" page on the wiki, to allow users to discover plug.kak more easily.

**Comment by andreyorst** [comment]
Nice Idea. I know three plugin managers at the moment. I'll add them.

**Comment by TeddyDD** [comment]
@andreyorst I deprecated my plugin manager in favor of yours. I removed it from wiki page as well.

**Comment by andreyorst** [comment]
@TeddyDD IIRC my plugin manager still lacks a feature of loading single script, because I ~~**ACTUALLY BELIEVE**~~ think that this is plugin maintainer responsibility. I'd like to discuss this feature, but maybe not here. Did you found this feature useful? If so, can you please open issue, I may consider it as another parameter to `plug` function.

**Comment by alexherbo2** [comment]
@andreyorst `pathogen-infect` is a `source-recursive` command.

It doesn’t really manage plug-ins.

**Comment by dpc** [comment]
Awesome! I'll try these out eventually. Please keep instructions on wiki pages.

**Comment by andreyorst** [comment]
> @andreyorst pathogen-infect is a source-recursive command.
>
> It doesn’t really manage plug-ins.

[I know](https://github.com/mawww/kakoune/issues/2402#issuecomment-426759559). I just wanted to do the best and include all solutions that I know. That's why I called you here, so maybe you'll edit page.
