### ISSUE TITLE
Plugin API C library.

### ISSUE THREAD

**Issue by dpc** [mawww/kakoune#1604]
I have ambivalent feelings about `kak` plugin systems.

The bad part (IMO) is shell scripting. A shell is a terrible tool. It sucks. It is a convenient way to glue together a bunch of programs or do some basic automation. I look at some existing plugins and though I'm decent shell scripter, I just feel repulsion thinking about working with the shell and debugging it.

The good part (IMO) is being based on elegant input/output system, where plugins are basically sending keystrokes to `kak` process. However the problem with that is that it requires a good knowledge of kak "keystrokes".

Anyway, what I'd like to ask for is a simple C library that can be used as a base for building kak plugins without being an expert in driving kak behavior from the keyboard.

Something that I could call: `kak_display_message("Plugin is ready"); kak_flush();` and it would convert it to a corresponding writes to stdout, `kak` socket or an arbitrary file descriptor.

This way:

* I can write complex kakoune plugins, in a programming language of my choice; I personally would build Rust wrappers over that API, but anyone can use their own favorite language just fine; I realize that "shell is very portable", but I rather trade it  for complex plugins.
* By looking at the API, I have some discoverability of what I can do in kakoune, without being an expert already.
* I have some type-checking, so I can easily modify my plugin to work with any new versions of `kak`, by just making them compile again.

**Comment by lenormf** [comment]
>I have ambivalent feelings about kak plugin systems.

Scripts are called "plugins" for lack of a better word, but all we have is the bare minimum to allow the editor to get data from external tools: flow control (`try`), macros (called "commands" but they are never stateless unless declared within a draft scope), data inputs (through scopes).

>However the problem with that is that it requires a good knowledge of kak "keystrokes".

This is a feature inspired after `sed`, which allows writing concise expressions to modify a stream of data, it's harder to understand than commands at first, but allows easier interactive commands to be run from the prompt and shortens the scripts' length dramatically.

>Anyway, what I'd like to ask for is a simple C library that can be used as a base for building kak plugins without being an expert in driving kak behavior from the keyboard.
>I can write complex kakoune plugins, in a programming language of my choice

Exposing the internals of the editor in this form has been intentionally avoided for multiple reasons, and it would even be less convenient for users if it existed because they would have to modify their plugins every time the API changes (which happens a lot as it is, but would happen even more frequently at first, when everybody starts asking for some prototypes to be tweaked).

Also you can already [code plugins in whatever language you want](https://github.com/mawww/kakoune/blob/master/doc/manpages/faq.asciidoc#why-arent-there-other-scopes-similar-to-sh-eg-python-), as information is passed through the environment (the only hiccup being that you can expand an arbitrary option if its name is determined at runtime).

**Comment by mawww** [comment]
Something that we probably have not explained well enough about Kakoune is that it actually already supports an RPC protocol that allows to write extensions/plugins/whatever we name them in any language.

By using the `kak -p <sessions>` shell command, you can send arbitrary Kakoune prompt commands to a Kakoune session, using the same format you'd use if you were writing the command by hand. So any programming language that allows you to run a child process and send data to its stdin can be used to run a `kak -p <sessions>` process and write commands to it.

One limitation we have compared to a fully fledged RPC system is that we dont provided a built-in way to get data back (such as a return value), but thats still doable by making the command sent to Kakoune write the data somewhere (such as a file, or a pipe). for example, I could move the selection towards the next word, and get the selection description with `echo "exec w; nop %sh{ echo $kak_selections_desc > /tmp/kak-selections-desc }" | kak -p <sessions>`.

As said, this does not have to be done through the shell, you could just use whatever scripting languages you prefer. @danr has written http://github.com/danr/libkak in python to provide easy python access to kakoune RPC system.

I am not keen on a C library because that would make expose too much of Kakoune's internals, which I'd like to be able to change easily.

**Comment by mawww** [comment]
While I agree we need to improve the plugin api in general, I dont think it would be wise to expose it as a C library, but would prefer to improve our existing quasi-RPC api to something cleaner.
