### ISSUE TITLE
Path as session name

### ISSUE THREAD

**Issue by guillaumecherel** [mawww/kakoune#1635]
When I start kakoune with

    kak -s `pwd`

Kakoune starts without problem and I can see the current directory as expected as the session name on the right end of the status bar. However the session doesn't appear in the output of `kak -l`.

**Comment by lenormf** [comment]
I guess creating a UNIX socket with slash characters in the name isn't so good.

**Comment by mawww** [comment]
So, when Kakoune's session contains a `/`, Kakounes treat it as a path from `/tmp/kakoune` instead of as a session name inside `/tmp/kakoune/<user>/`. The logic behind that is to allow for cross user edition. On a system, `alice` could do `kak -s mysession`, then change the permissions of the socket at `/tmp/kakoune/alice/mysession` to let bob do `kak -c alice/mysession` and join her.

But if bob does `kak -l` it will list only his sessions, the ones in `/tmp/kakoune/bob`.

I think we could avoid that confusion by making two changes: not allowing `/` in session names when creating a session (so `kak -s` cannot use a path, its always a socket in `/tmp/kakoune/<user>`), and only allow a single `/` when joining a session.
