### ISSUE TITLE
Reverse search doesn't stop at closest match

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1638]
Hi,

Reproducer:

```
a⏎
⏎
[⏎]
```
reverse-searching for `a\n|$` selects the first line, but since the second line also matches I expect this one to be selected.

Can also be reproduced on the `regex-impl` branch

**Comment by lenormf** [comment]
`<a-/>a\n|\n` works as expected.

**Comment by mawww** [comment]
That is due to `$` matching an empty string, just *before* the second `⏎`. And `a\n` matching a string that finishes exactly at the same point. Even if we are searching backwards, we still favor the leftmost match, so between a 2 char match and an empty match that both finish at exactly the same place, we take the 2 char match.

It then happens, outside of the regex matching code, that when we have an empty match, we select the char following it (as selections cannot be empty), so `$` ends up selecting the second `⏎`.

I agree its surprising, but I dont think it is a bug.
