### ISSUE TITLE
reStructuredText highlighting

### ISSUE THREAD

**Issue by Lapin0t** [mawww/kakoune#1650]
It would be nice to have syntax highlighting for the [reStructuredText](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html) markup. I may contribute a configuration file in some time.

**Comment by Geemili** [comment]
I started working on adding support for reStructuredText. So far I have added highlighting support for headers.

ReStructuredText doesn't define a specific hierarchy for the headers, so I followed the [Python style guide's advice](https://docs.python.org/devguide/documenting.html#sections) for setting the `title` face.

I stuck the `restructured.kak` file into the `rc/base/` folder because the `markdown.kak` file is in there. Is that is the correct place for it?

My progress is [here](https://github.com/Geemili/kakoune/blob/feature-restructuredtext/rc/base/restructuredtext.kak), BTW.

**Comment by lenormf** [comment]
If you want to show the progress of your code and ask for reviews, create a pull request (mention in the title that it's a WIP), and refer to this issue in the description.

**Comment by mawww** [comment]
and `rc/base` would be correct as reStructuredText is a very common format.

**Comment by Delapouite** [comment]
The PR has been merged https://github.com/mawww/kakoune/blob/master/rc/base/restructuredtext.kak so we can close this issue.
