### ISSUE TITLE
Linking error on Arch

### ISSUE THREAD

**Issue by TeddyDD** [mawww/kakoune#1659]
OS: Linux Arch 64bit
Commit: 706202218700c989b760942170515c7f3757290b

I tired to build Kakoune using [AUR package](https://aur.archlinux.org/packages/kakoune-git) and manually. I'm getting linker error:
```
$ env DEBUG=no make  
[...]
/usr/bin/ld: .ncurses_ui.debug.o: undefined reference to symbol 'wtimeout'
/usr/lib/libtinfo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:70: kak.debug] error 1
```

I'v got `boost-libs` and `ncurses` installed. I'm not into cpp so I would appreciate help :)

Edit:
solution form IRC: I had to link libtinfo.so to makefile
Not closing yet since it might be Kakoune issue as well as Arch specific stuff.
Edit2:
I replicated it on base/devel docker container so at least I know it's not my box broken 🖥

**Comment by mawww** [comment]
I think we should probably switch the Makefile to use pkg-config in order to get the flags to pass the compiler.

I think we can pretty much assume pkg-config is going to be present on a modern linux distribution.

**Comment by lenormf** [comment]
I actually made a PoC for that yesterday, and it turns out that `boost` doesn't have a `.pc` file. Which means that the Makefile would end up having some calls to `pkg-config` for `ncurses`, but still have hardcoded flags for `boost`. Maybe this could be done once `regex-impl` has been merged upstream?
