### ISSUE TITLE
Cursor off screen after goto end with wrapped lines

### ISSUE THREAD

**Issue by aver-d** [mawww/kakoune#1710]
Hello, I've noticed an issue with the cursor going off screen using the wrap highlighter.

I have a buffer with many long, wrapped lines that extend well below the window height. Now, from the top of the buffer `ge` (goto end of buffer) goes to near the bottom, but does not show the last few lines and also causes the cursor to disappear.

Perhaps a recent change caused this. I compared with the previous version of kakoune from October I was using, and there's no issue there.

(Running with kak -n, and latest commit 079b006)

**Comment by lenormf** [comment]
I've noticed the same issue when searching. Seems to be a regression.

**Comment by lenormf** [comment]
Another glitch that could possibly be a symptom of this issue is that on some buffers whose length is greater than the size of the window, selecting everything (`%`) will make the last line of the window be a mangled mix of the lines that are out of view. Copying and pasting the content has the expected results, so it seems to be a display glitch only (I have the `wrap` and `number_lines` highlighters set).
