### ISSUE TITLE
Should WinClose hook run immediately after `:q` in a client?

### ISSUE THREAD

**Issue by nochiel** [mawww/kakoune#1716]
- WinClose is currently not intuitive (and not very useable when scripting) because, afaict, it doesn't run immediately after `:q`.
- Should there be a `KakClientEnd` hook?

# Steps:
- `kak -s test-session` 
- `hook -group test global WinClose .* %{ %sh{ echo "debug: WinClose: ${kak_bufname}" >> /tmp/kak.log }}`
- In a new terminal: `kak -c test-session -e "e -scratch *test*"`
- `:q`
- `less /tmp/kak.log`
- observed: log is empty.
- expected: log entry: `debug: WinClose: *test*`
- `:kill`
- observed: log is populated with WinClose entries for all buffers (and multiple entries for a given buffer if it was viewed using >1 windows).

**Comment by mawww** [comment]
`WinClose` does not run when the client quits because a window is only deleted once the buffer its relates to is deleted. When a client quits, the window is just put into the free window list.

That means `WinClose` is a pretty hard to predict hook, and I am wondering if it should be removed. What are you trying to achieve ?

**Comment by danr** [comment]
It does sound like a good candidate for removal if it is only run together with `BufClose`.

**Comment by nochiel** [comment]
> What are you trying to achieve ?

- GNU Screen integration: to run `screen -X remove` when a window is closed, basically to rearrange my terminal layout when I close a window.
- Logging: I have various logging/auditing things that run per window and wanted to close them for buffers I keep open all the time but open in multiple windows.

**Comment by danr** [comment]
@nociel, have you read this discussion about what the window scope is? 
https://github.com/mawww/kakoune/wiki/The-`window`-scope

**Comment by nochiel** [comment]
> @danr: have you read this discussion about what the window scope is?

Thanks. Yes, I had read it.  That's similar to the behaviour I'm accustomed to in Emacs.

**Comment by mawww** [comment]
So yeah, for what you want to achieve, its actually the client rather than the window that you want to watch, windows can move between clients, they are not the correct object.

We do not have ClientCreate/ClientClose hooks yet, they could be added provided a strong motivating use case. Its not currently available because I dont see a lot we can do with it, as we do not store client-specific data (clients are not a scope).

**Comment by nochiel** [comment]
> For the screen use case, would'nt it be possible to just tweak the command thats run in the screen window ? kak -c $kak_session; screen close this window

That works.  Thanks.

**Comment by topisani** [comment]
I'm also currently missing a ClientClose hook. I basically want to close my tools/docs clients automatically when all other clients are closed. Any other way to do this right now?
