### ISSUE TITLE
smarter N and <a-N>

### ISSUE THREAD

**Issue by valerdi** [mawww/kakoune#1729]
hi,
after a search with / and pressing N kak repeatedly selects the written regex for multiple cursors. Now, the problem i see is that with ? we can extend the actual selection and then N doesn't continue to extend, it actually adds the next regex instead of extending.

the only workaround i have found is to do ?enter repeatedly but it's uncomfortable.

**Comment by alexherbo2** [comment]
The <kbd>/</kbd> command moves _each selection_ to the next pattern, or _extends to_ with <kbd>?</kbd>.
The <kbd>n</kbd> command moves the _main selection_ to the next occurrence, or _adds next_ with <kbd>N</kbd>.

I like the <kbd>n</kbd> and <kbd>N</kbd> behaviours, especially since @lenormf’s proposal change (#1173).

But yeah, there is no direct way to achieve what you want, as one acts on each selection and the other on the main only.

I see the usefulness of the command when manipulating a single selection, and also, that it won’t interact well with multiple selections.

A simple mapping does the trick, but I don’t see it well in core.

``` kak
map global normal <c-/> ?<ret>
```

**Comment by valerdi** [comment]
the idea that i had is to makes N behaves depending on the last search command, if i did a search with ? it means that I want to extend so N should behave the same. If instead I used / then N should add instead of extending.

The reason behind it that the uses cases of extending with ? and then adding (instead of extending again) with N are so limited, i actually have never found myself trying to do this. 

So my propose is:

if / or <a-/> then N and <a-N> adds like it does now
if ? or <a-?> then N and <a-N> extend

**Comment by alexherbo2** [comment]
I’m not fond of <kbd>N</kbd> being context-dependent.

**Comment by mawww** [comment]
The problem here is that we have different functionalities we want, and not enough keys to bind them to. Sometimes we want to add the next match for the main selection, some other times we want to add the next match for all selections, sometimes we want to extend to next match (only for main selection ?) and all combinations of `n` are already taken.

Context-dependency is something I tried to avoid a lot in Kakoune's design, which is why `n` does not follow vim's model of going in the direction of the last search... `n` always goes forward, `<a-n>` always backward. Except for a few very explicit features (`<a-.>` and `.`) we avoid store this kind of non-explicit state (although you could argue that `n` access of the current search pattern is already using a non-explicit state, but the search pattern is in a register, which is exposed to the user, adding a extend flag would need to be exposed as well, or be changed as a side effect of modifying the search register...).

The current trade-off is to say `N` adds the next match, quite arbitrarily, the other functions can be accessed in two keystrokes instead of one, using `/<ret>` or `?<ret>`, I am not sure we can do much better, whatever we decide `N` to do is going to be arbitrary and not perfect.
