### ISSUE TITLE
[regex_search][regex_match] Segmentation Fault on weird modifiers

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1737]
>SEGV on unknown address 0x0000000db6ba (pc 0x00000051483b bp 0x7ffe5960b470 sp 0x7ffe5960b240 T0)
>The signal is caused by a READ memory access

Looks like it's triggered with a weird regex modifier, c.f. the reproducer.

Base64:

```
KD8h83YpZg==
KD8h8/cbKRs=
```

Commit: 839da764e7e86c712e8383e5c593e322e09ae2d4

Fuzzer code: [search_self.cc](https://github.com/lenormf/kakoune-fuzz/blob/master/regex/search_self.cc) [match_self.cc](https://github.com/lenormf/kakoune-fuzz/blob/master/regex/match_self.cc)

**Comment by mawww** [comment]
Haha, good find.

This is due to the way we encode lookarounds in regex, they are stored as a list of codepoints, with codepoints in the 'private use area' (0xF0000 - 0xFFFFD) being used to encode non literals (character classes, any char...). The problem is that we do not validate the regex against uses of those codepoints, which means that if a regex contains a lookahead that contains a private use area codepoint, the regex engine will try to interpret it as an index into the character classes of the regex, which might access invalid data.

It should be easy to fix, I dont think we need to support 'private use' codepoints in regular expressions.
