### ISSUE TITLE
Commenting code-blocks in markdown files

### ISSUE THREAD

**Issue by dgrisham** [mawww/kakoune#1745]
**Feature request**: It would be really cool/useful if you could use the `comment-line` and `comment-block` commands inside of a Markdown code block and have it comment the code in the block as it would for a code file written in that language.

For example, for the code block:

    ```c
    int main() { return 1; }
    ```

Running `:comment-line` while highlighting the `int main() ...` line would give:

    ```c
    //int main() { return 1; }
    ```

Is this possible with a clever set of commands, or something that could conceivably be added? How do you guys feel about a feature like this?

**Use case**: I'm starting to write Markdown files as both the documentation for my code as well as the code itself, then automatically separating the code into its own file. Because of this, I'm writing most of my code in `.md` code blocks. As a result, I completely lose the convenient commenting commands that I get in regular code files.

In fact, it would be cool to have a general way to treat code blocks inside of a Markdown file based on the language of the block -- would this be possible at the moment? Sounds difficult, or at least quite inefficient, but would have a lot of potential.

**Comment by TeddyDD** [comment]
First idea I had is to detect code fence from hook and switch filetype in the fly. It might cause trouble without some [narrowing](https://www.gnu.org/software/emacs/manual/html_node/emacs/Narrowing.html) mechanism.

**Comment by dgrisham** [comment]
@TeddyDD Right, I was thinking the same thing. If you changed changed the filetype of the entire buffer, at the very least you'd have alternating syntax highlighting for the entire file and at worst you're running commands that reformat the file or something every time you switch (depending on your `kakrc`, of course).

**Comment by TeddyDD** [comment]
Simple solution for comments would be to temporarily override options: `comment_line, comment_block_begin, comment_block_end`. Then you have to revert those outside of fence block. I guess this can be done similarly to indentation scripts. 

The problem is, you have to get information how to comment given language. I'm talking about general solution here, it's easy with hard-coded config for few languages.

I think we should discuss narrowing in separate issue

**Comment by mawww** [comment]
The "proper" way to solve such a use case would be to move region handling deeper into Kakoune (instead of having regions purely as an highlighting concept), combined with more flexible scope support (allowing filetype support to be specified as a shared, named, scope, instead of just having it as a set of hooks, highlighters, mappings, aliases... added to the current window).

This way we could basically specify that a certain region of the buffer needs to use this filetype specific scope, while the rest of the buffer needs to use another.

However, by thinking a bit more about that, it would mean options might have a different value for different selections, which would make the code handling multiple selections extremely complex as they would have to handle every scope-dependent value as potentially different for different selections. That would mean also hooks (used for indent) would be different for different selections, meaning hooks would need to run once per selection...

Ok, so after thinking while writing this answer, it looks like a big can of worm I am not willing to open right now.

**Comment by dgrisham** [comment]
@mawww Would it be worth opening a narrowing issue just to keep this in mind? Or is it not something you really want to support?

**Comment by danr** [comment]
This happens in other languages too (of course) such as HTML (or vue) embedding css and javascript.

**Comment by mawww** [comment]
I dont think we can sanely combine the current design of Kakoune with treating different part of the buffer as a different filetype. Its easy to do with highlighters, but for the other features (different option values, as the nested region might have another indentation setting, word definition, different hooks as we want to have different auto indentation logic...) it seems implementing them will be both complex and very inefficient.

I dont think its a trade-off Kakoune should make, the complexity cost is to high to support that. (Highlighting differently, on the other hand, is already supported, and stays out of the way of the rest of Kakoune).
