### ISSUE TITLE
File-name completion does not work with `:` characters

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1757]

**Comment by mawww** [comment]
Can you describe the issue more precisely ? Here if I create a file named 'test:test', I see it both in `:edit` completion candidates, and in filename insert completion.

**Comment by alexherbo2** [comment]
The break only happens after typing the `:` character.

**Comment by lenormf** [comment]
* `touch a:b`
* `kak`
* `i`
* `a:`
* `<c-x>f`

Typing only `a` or `b` before triggering the filename completion seems to work. I think that's what the issue is about?

Regardless, instructions to reproduce the issue should have been included in the original message.

**Comment by mawww** [comment]
Ok, I see what the problem is, but I dont think we should fix it:

When doing insert completion, we need to find a completion start point, what part of the already written text should be considered as part of what we want to complete. Its relatively easy for code, as this is usually an identifier/keyword, and those fall in the general category of "words", so we just have to find the start of the current word, and complete from there. For filenames, its trickier, as unix filenames can contain anything except `\0`, so if we used that we would almost always try to complete a filename matching everything written from buffer start... We have to choose what constitutes "common" filename characters, and currently Kakoune considers its alphanumeric characters, `/`, `-`, `_` and `.`. I dont think `:` should make it there, as its uncommon in filename, and often used to separate filenames from other data (as with the extremely common `<filename>:<line>` syntax).
