### ISSUE TITLE
Add <a-d> command to select discarded selections

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1768]
# Commands

- <kbd>Alt</kbd> <kbd>d</kbd> → Select discarded selections
- <kbd>Alt</kbd> <kbd>D</kbd> → Extend selections with the discarded ones

# Feature

Provide `if…else` functionality.

We already have this kind of functionality with `:try %{ … } catch %{ … }`, but it’s not interactive.

# Example

## Input

```
[foo]
[Foo]
[FOO]
```

With `[…]` being the initial selections.

## Output

```
bar
Bar
BAR
```

## Commands

``` kak
<a-k>foo<ret>cbar<esc>
<a-d>
<a-k>Foo<ret>cBar<esc>
<a-d>
cBAR<esc>
```

# Issue

The command is already taken to erase selected text, without yanking.

**Comment by mawww** [comment]
That seems far too specific as a feature, I understand that for this specific case you would prefer it to saving/restoring with `z` and `Z`, but I dont think the motivating use case is strong enough to add that. We have too many features already, I'd be more interested in ways to unify existing features into a single ones rather than adding yet another feature for a specific use case.
