### ISSUE TITLE
insert mode: `<a-;>i<esc>` does not escape from insert mode

### ISSUE THREAD

**Issue by nochiel** [mawww/kakoune#1776]
# steps
- <kbd>i</kbd>foo bar<kbd>\<a-;></kbd><kbd>i</kbd>lorem ipsum<kbd>\<esc></kbd>

# observed
- the cursor moves left one character.
- a second <kbd>\<esc></kbd> then causes a return to normal mode.

# expected
- kakoune should return to normal mode.

**Comment by Screwtapello** [comment]
Since `<a-;>` enters normal mode for one command, I'd expect it to return to insert mode once that command is done. If that command is "enter insert mode", then it makes sense to me that it would take two `<esc>` to return to "real" normal mode. In fact, by repeating `<a-;>i` an arbitrary number of times, you can require an arbitrary number of `<esc>` to get back.

I feel like this probably the more useful behaviour: it seems very unlikely that humans would encounter this behaviour by accident, while it's very useful for scripts because you can have an insert-mode binding that uses functionality in normal mode without worrying about whether any scripts happen to press `<esc>` along the way.

Why did you expect that a single `<esc>` should return to normal mode? Is it mentioned in the documentation somewhere? Is that how the analogous feature in Vim works?

**Comment by nochiel** [comment]
@Screwtapello 

Indeed, you raise a good point. I can see that it makes sense while scripting.  I'll eventually get used to it when working interactively.

[vim:insert.txt](http://vimdoc.sourceforge.net/htmldoc/insert.html) (the website is out of date) notes:
> The <kbd>CTRL-O</kbd> command takes you to Normal mode.  If you then use a command to enter
Insert mode again it normally doesn't nest.  Thus when typing <kbd>a</kbd><kbd>\<C-O></kbd><kbd>a</kbd> and then <kbd>\<Esc></kbd> takes you back to Normal mode, you do not need to type <kbd>\<Esc></kbd> twice.
> An exception is when not typing the command, e.g. when executing a mapping or
sourcing a script.  This makes mappings work that briefly switch to Insert
mode.

**Comment by mawww** [comment]
@nochiel Something to help your intuition about the current behaviour is that in Kakoune, modes are actually a stack.

You start in normal mode, then press `i`, you then get the following stack:
```
insert
normal
```
You press `<a-;>` which introduces a single command normal mode:
```
normal (single command)
insert
normal
```
Then `i` which enters a *new* insert mode
```
insert
normal (single command)
insert
normal
```

So once you press `<esc>`, the top insert mode quits, the single command normal mode quits (as it just executed its single command), and we get back to the initial insert mode.

I believe this is the correct behaviour, I suspect once users are aware of the mode stack, it will make much more sense to them and they'll find it intruitive.

**Comment by nochiel** [comment]
Thank you for that description, @mawww.

**Comment by nochiel** [comment]
@mawww The stack you described makes sense but during interactive useage (when I'm typing) it still feels obtrusive.  Too often I forget that I'm several layers up the mode stack and end up having to tap escape several times as I try to get to normal mode.  Am I correct in assuming that <kbd><a-;></kbd> is intended for use in scripts and not by the user?  

How difficult would it be to do something similar to what vim does i.e. as I quoted above: 

> [vim:insert.txt](https://github.com/vim/vim/blob/01164a6546b4c635daf96a1f17d1cb2d07f32a66/runtime/doc/insert.txt) notes:
>> The <kbd>CTRL-O</kbd> command takes you to Normal mode.  If you then use a command to enter
Insert mode again it normally doesn't nest.  Thus when typing <kbd>a</kbd><kbd>\<C-O></kbd><kbd>a</kbd> and then <kbd>\<Esc></kbd> takes you back to Normal mode, you do not need to type <kbd>\<Esc></kbd> twice.
> An exception is when not typing the command, e.g. when executing a mapping or
sourcing a script.  This makes mappings work that briefly switch to Insert
mode.

**Comment by Screwtapello** [comment]
How do you use `<a-;>i` in your normal interactive workflow?

**Comment by nochiel** [comment]
@Screwtapello My daily workflow consists of editing markdown in which source code and quotes are interspersed with bulletpoints.  So, for instance, just now, I was editing something of the form:

---

\- Point 1 <kbd>\<c-j></kbd>
\- Definition 1 <kbd>\<a-;>\o</kbd>
\> quote 1 <kbd>\<a-;>\o</kbd>
\``` lang <kbd>\<c-j></kbd>
example
\```

---

After both definition 1 and quote 1, to avoid a hook running that would automatically insert the next bullet point or angle quote respectively when I open a new line, I switch to single-command normal mode, disable hooks, then open a new line.  In this case, at the point at which I'm typing in the source code block, I have nested 2 single-command-normal modes. If I happen to press escape and attempt to select a region, I find myself typing text instead.  Depending on how quickly/hastily I've been working, I might end up with a rather deep nest of single-command normal modes.

**Comment by mawww** [comment]
@nochiel yeah, <kbd><a-;></kbd> is mostly expected to be used in scripts, the main motivation was that entering/leaving insert mode has side effects: We do not know if insert mode was entered with <kbd>i</kbd> or <kbd>a</kbd> which does not work exactly the same, so returning to insert mode after a set of normal mode commands cannot be transparent. Additionally, leaving insert mode avoids end of line (cursor on end of lines will move back one char if possible)...

In order to allow transparent use of normal mode, <kbd><a-;></kbd> was introduced, but this is mostly needed in scripts, as in interactive use the user can easily get back to the desired state (as the user knows the desired state).
