### ISSUE TITLE
Notify when config file changes

### ISSUE THREAD

**Issue by notramo** [mawww/kakoune#1784]
Kakoune should notify the user when the config file changes (similarly as it do when the edited file changes), and ask the user to reload.

**Comment by vimeitor** [comment]
Or should automatically reload unless there have been changes that would be overriden.

**Comment by mawww** [comment]
Kakoune's handling of config files is very simple at the moment, they are just a list of commands that are run in sequence at startup. Reloading a config file is not something we can do robustly, as it might change option values (which we might not want if the option was modified after the first loading), redeclare custom commands (which will fail because the command already exists), change the colorscheme... Trying to make that robust would be a big change in the config file (and command language) design, which I dont think would be worth it.

If you really want to watch the file for changes and trigger a reload, it should be pretty easy to do with tools such as `inotifywait`, then just send a `source` command to the kakoune session through `kak -p`.

**Comment by danr** [comment]
If you save the kakoune config file from within kakoune itself it is "easy" to reload it using a hook. Here's one way to do it:

https://github.com/danr/dotfiles/blob/master/config/kak/reload-kakrc.kak
