### ISSUE TITLE
How to diagnose slow startup performance

### ISSUE THREAD

**Issue by jacobdufault** [mawww/kakoune#1823]
I'm playing with kakoune on WSL (windows subsystem for linux) and it is extremely slow to load, is there a convenient way to profile why?

```bash
~/k/src> time kak -e quit
0.06user 0.59system 0:03.31elapsed 19%CPU (0avgtext+0avgdata 7220maxresident)k
0inputs+0outputs (0major+47908minor)pagefaults 0swaps

~/k/src> time kak -e quit -n
0.00user 0.01system 0:00.05elapsed 25%CPU (0avgtext+0avgdata 4148maxresident)k
0inputs+0outputs (0major+1124minor)pagefaults 0swaps
```

I believe I am using the optimized build.

```
~/k/src> readlink (which kak)
/home/jake/kakoune/src/kak

~/k/src> readlink (readlink (which kak))
kak.opt
```

**Comment by jacobdufault** [comment]
```bash
 kak -e "set global debug hooks|shell|profile|commands"
```

This sort of gets there. But it doesn't include enough information, ie, how long is it taking to actually parse/read each kak file?

**Comment by danr** [comment]
Did you compile with `debug=no`?

**Comment by jacobdufault** [comment]
> Did you compile with debug=no?

Yep, hence the symlink to `kak.opt`.

**Comment by mawww** [comment]
One way you can get better information would be to add

```
set global debug profile```

At the top of `/home/jake/kakoune/share/kak/kakrc` (this is *not* your user config file, it is the file kakoune sources on start that takes care of autoloading and then loading your user config).

With that you will get timings for what happens during startup (`kak -e` gets only applied much later during the startup process, `kak -E` would be slightly better, but it still takes place after loading scripts, although I am not sure if thats the best).

I also just pushed a small change so that `source` commands get profiled as well, get the latest code, do the suggested change, and you should get loading time for each scripts.

**Comment by jacobdufault** [comment]
Nothing obvious, outside of sourcing being generally slow.

https://gist.github.com/jacobdufault/64368ee6a84069d1cb408276a91b5920

**Comment by jacobdufault** [comment]
I did some digging, it looks like wsl is slow for random disk reads. https://github.com/Microsoft/WSL/issues/981.

Closing for the time being, since I don't think there is anything kakoune can reasonably do here outside of maybe automagically optimizing multiple *.kak files into a single-file cache.

**Comment by occivink** [comment]
You can try setting /bin/sh to symlink to dash, that should give some performance improvement

**Comment by jacobdufault** [comment]
> You can try setting /bin/sh to symlink to dash, that should give some performance improvement

Looks like this was already the case.

```bash
~> readlink /bin/sh
dash
```

**Comment by mawww** [comment]
Note that this slowdown of WSL seems specific to DrvFS, do you have a specific setup where your /home is not on a "native" WSL drive, but on a mounted windows drive ?

**Comment by jacobdufault** [comment]
> Note that this slowdown of WSL seems specific to DrvFS, do you have a specific setup where your /home is not on a "native" WSL drive, but on a mounted windows drive ?

Yep, that greatly increases performance. Good idea! Thanks
