### ISSUE TITLE
rename-buffer will read file contents and cause crash if renamed to directory in working dir

### ISSUE THREAD

**Issue by jacobdufault** [mawww/kakoune#1831]
### Steps 

Setup
```sh
$ mkdir repo && cd repo
$ touch file && mkdir dir
$ echo foo > file2
```

Crash on reading directory
```sh
$ kak file -e 'rename-buffer dir'
uncaught exception (N7Kakoune17file_access_errorE):
/repo/dir: is a directory
```

New file contents is read (ie, buffer is not empty).
```sh
$ kak file -e 'rename-buffer file2'
```

### Outcome 

Crash

### Expected 

No crash, file contents is not read.

**Comment by mawww** [comment]
The `file2` behaviour seems correct to me, it looks a bit strange in your case because you have `autoreload` set to `true`. When `autoreload` is set to the default `ask` value, you get a prompt telling you that the file on disk has changed (which is true, you have a buffer associated to a file, by renaming the buffer you changed the file to which it is associated, now Kakoune notifies you that the file content has changed, which would be also happening if after launching kakoune on a new file, you'd create this file externally like with `kak file -e '%sh{ echo blah > file }'`).

The directory behaviour is not correct though. It should not crash, and when `autoreload` is `ask`, we get a prompt telling to reload that never goes away.
