### ISSUE TITLE
What is the difference between add-on, plug-in and extension?

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1834]
What is the more appropriate wording for Kakoune?

**Comment by alexherbo2** [comment]
#1830

**Comment by alexherbo2** [comment]
#1833

**Comment by mawww** [comment]
Up to now, I think the term "script" has been the more common, but thats because most scripts were just that, simple scripts provided as part of kakoune. With the advent of http://github.com/danr/kakoune-languageclient, or https://github.com/occivink/kakoune-gdb/ I agree there is something that could be called plugin/extension/addon... Not sure what the best term would be, but seems plugin is getting some traction as thats the tag we use in the website.

So yeah, lets call complex scripts plugins, I guess everybody will understand what that means.
