### ISSUE TITLE
Cursor blink in dtach

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1851]
It happens after reattaching.

**Comment by mawww** [comment]
Thats due to dtach itself. dtach does not maintain the terminal state at all, so when you attach kakoune, it does not know Kakoune had hidden the terminal cursor, and does not restore that.

Kakoune could work around that by resetting its cursor state on window resize (as dtach, in some case, sends a resize message to try to force the underlying application to redraw), but dtach traded correctness to get simplicity, I dont think we should introduce complexity in client applications to fix that.
