### ISSUE TITLE
<s-w> for WORD object feels inconsistent

### ISSUE THREAD

**Issue by jockus** [mawww/kakoune#1861]
In general Kakoune uses shift for extending and alt for BIG nouns, e.g. <a-w> for WORD.

In the object selection menu WORD is mapped to <s - w>, which feels a bit inconsistent.

**Comment by mawww** [comment]
So, if I understand correctly you'd prefer WORD in text objects to be bound to `<a-w>` instead of `W` ?

Could be nice, definitely more consistent for WORD, I wonder if we have other mappings where we have inconsistency between shift/alt.

Any feedback on that from other users ? Happy with word moving to `<a-w>` in text objects ? seems easier to type as we typically already have `alt` down for text object introducer `<a-i>` or `<a-a>`

**Comment by jockus** [comment]
Yup, that's correct. It's the only inconsistent mapping I've ran in to so far.
