### ISSUE TITLE
[In tmux] Intermittent spurious `[1~` inserted when I press <esc> in insert mode

### ISSUE THREAD

**Issue by nochiel** [mawww/kakoune#1864]
NB. Because this bug is intermittent I don't yet know how to reproduce it reliably.  For a long running session, it occurs every half hour or so.  My next step, unless I can be given a hint as to where to look, is to run kakoune with gdb attached and get a backtrace when it eventually occurs.
### Steps 
- `kak -s test`
- `kak -c test`
- <kbd>i</kbd>
- <kbd>esc</kbd> (via <kbd>ctrl+[</kbd>)
### Outcome 
- `[1~` is inserted into the buffer.

### Expected 
- Switch to normal mode.

**Comment by Screwtapello** [comment]
Looking at xterm's `ctlseqs.pdf` document, the escape sequence `^[[1~`is sent by the Home key, at least for VT220 mode (as opposed to the usual PC keyboard mode). The usual culprit for this kind of thing is that a user hits Esc to leave Insert mode, then they immediately another key to do something in normal mode, and the terminal treats that as pressing that key with the Alt modifier, instead of two separate keystrokes.

If this is inside tmux, check [the FAQ](https://github.com/mawww/kakoune/blob/d6b5240bdfcb1a991e60fa3fd531e72cc8263ae9/doc/pages/faq.asciidoc#why-does-leaving-insert-mode-take-more-than-half-a-second-in-tmux-)

**Comment by nochiel** [comment]
I had `set -sg escape-time 0` in tmux.conf
I've set it to 25 as per the readme.  I'll report back if that resolves the problem.

**Comment by mawww** [comment]
Any change with that setting ? It seems reasonable to think setting the timeout to 0 could result in such edge cases.

**Comment by nochiel** [comment]
> @mawww: Any change with that setting ? It seems reasonable to think setting the timeout to 0 could result in such edge cases.

With `set -sg escape-time 25`, the spurious [1~ is occurring much less often, only twice since yesterday.

**Comment by mawww** [comment]
Are working through a ssh connection or something similar ?

**Comment by nochiel** [comment]
No, not on ssh or via any other type of tunnel; just regular desktop usage.

**Comment by mawww** [comment]
I have never experienced that with tmux, I wonder what in your setup triggers that behaviour.
