### ISSUE TITLE
buffer list

### ISSUE THREAD

**Issue by jgmtzmd** [mawww/kakoune#1881]
hi.
regular user of kakoune here. Just wanted to suggest to make the new opened buffers go to the end of buflist (excluding "\*bufer\*").
i guess i am not the only one who regularly works in 2 or 3 files but from time to time have to open and close others just to read or copy something, when i do, the recently opened buffer goes to the start of the list and that messes with "buffer-first" command (generaly the first buffer is the main file). i think having the new buffers appended to the end of buflist would allow us to tinker and get some neat and useful shortcuts to navigate through the buffers. In my case: i wanted to use Delapouite's kakoune-buffers and define some commands to quickly jump from buffer#1 to buffer#n lets say. But with the newest buffers messing the list this is not possible.
regards

**Comment by mawww** [comment]
Hello,

Sorry for the late answer,

I must confess I do not remember why we push buffers in front  of the list instead of at the back, but I suspect we had a long chat about that and ended up going with that decision. It would be pretty simple to change the way we create buffers so that new ones go at the end of the list, that would actually clean up the code slightly. We could try to do that, and see if anything breaks, I agree it would be intuitive for the buffer list to work this way.

**Comment by jgmtzmd** [comment]
hey, thanks.

Enviado con AquaMail para Android<https://play.google.com/store/apps/details?id=org.kman.AquaMail>
http://www.aqua-mail.com

En 4 de abril de 2018 6:37:36 p.m. Maxime Coste <notifications@github.com> escribió:

Hello,

Sorry for the late answer,

I must confess I do not remember why we push buffers in front of the list instead of at the back, but I suspect we had a long chat about that and ended up going with that decision. It would be pretty simple to change the way we create buffers so that new ones go at the end of the list, that would actually clean up the code slightly. We could try to do that, and see if anything breaks, I agree it would be intuitive for the buffer list to work this way.
