### ISSUE TITLE
Enter insert mode on hook

### ISSUE THREAD

**Issue by h-youhei** [mawww/kakoune#1894]
Hi.
I want to do someting like this
```
hook global WinSetOption filetype=git-commit %{
  execute-keys i
}
```
but nothing happen.
Changing to `execute-keys ia`, inserts a, and in normal mode.

Are there any to do this?

**Comment by danr** [comment]
Related: #1872

**Comment by mawww** [comment]
Unfortunately that will not work at the moment because `WinSetOption` hooks run in a window specific context totally separated from the client context, so `execute-keys i` will indeed enter insert mode, but not in the client context, where the user is interacting.

Finding a nice solution to that is hard, options can change from many sources, and windows are not always displayed in a client.

**Comment by danr** [comment]
Note: your original problem might be solved by setting the `GIT_EDITOR` environment variable like this: 

```bash
$ GIT_EDITOR='kak -e "execute-keys i"' git commit
```

**Comment by h-youhei** [comment]
Thank you.
WinDisplay works expected. As in mentioned #1872

**Comment by h-youhei** [comment]
WinDisplay doesn't work with daemon&client.

But GIT_EDITOR method works even with daemon&client.
