### ISSUE TITLE
Cancel object indent selection on lines with no indentation

### ISSUE THREAD

**Issue by aver-d** [mawww/kakoune#1904]
When on a line with no indentation, currently the entire buffer is selected with the commands `<a-a>i` and `<a-i>i`.

It's fairly easy to accidentally select the entire buffer, and I don't recall ever having the intention to use `<a-a>i`  or `<a-i>i` in this way. `%` or `%_` seem more obvious.

I wonder if an improved default behaviour would be to show the "no selections remaining" message in the event of the indentation level being zero.

There's maybe also a logical intuition that at the left-most area of the buffer there is no indentation to select, and the command can therefore be considered invalid.

**Comment by Delapouite** [comment]
I find this problem a bit related to the umbrella topic of "undoing selections": https://github.com/mawww/kakoune/issues/898 . In this kind of "oops" moment that is `<a-i>i` on col 0, it should be easy to go back to the previous selections list.

**Comment by mawww** [comment]
I agree with Delapouite on this one. I think `<a-i>i` on base identation is doing the right thing (it does select that identation level, and it so happens to be the whole buffer). The real problem is getting back to the previous selection when this was not intended.

I suspect that the bug you are experiencing is a different one though:

```
func():
    first line
    second line

    fourth line
```

When the cursor is on what could be called 'third line', selecting indentation selects the whole buffer, when it should select first to fourth line (leaving func() alone). This is a bug in the indent selector.

Is that the actual bug you are hitting ?

**Comment by aver-d** [comment]
Actually, no, not related to any bug – just a general thought about this text object's behaviour, and a thought more pragmatic than philosophical.

Object indent is a good friend of mine, but I don't find the zero indent useful for selecting the entire buffer. A more likely scenario would be the problem of regaining my previous position and focus after seeing the cursor suddenly jump to the end of the buffer.

I thought I might not be the only person who found this behaviour unhelpful (and possibly confusing to new users), so I raised the topic as a suggestion for an alternative default.

You both mention this is related to the wider issue of losing selections. Fortunately for me, in this particular case the selection is conceptually simple. So, the "problem" can be dealt with in a straightforward way ahead of time:

    def object-indent %{
      eval -no-hooks %{
        exec -draft gh <a-k> \h <ret>
        exec <a-i>i
      }
    }
    map global object i -docstring 'indent' '<esc>:object-indent<ret>'

An error occurs where a line does not begin with whitespace; the selection does not change.

Anyway, I'll now close this issue. Thanks both for your input.
