### ISSUE TITLE
Create missing parent directories on write

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1919]
Hi

Starting in an empty project:
`:edit foo/bar.c`
does not complain, so you write code.

Now you want to save it:
`:w`
error
`1:1: 'w' foo/bar.c: No such file or directory`

Should we assume a behavior ala `mkdir -p` where the missing dirs are automatically created if missing?

**Comment by alexherbo2** [comment]
Kakoune does not complain, because the buffer is not associated to the file-system.

A hook before writing the buffer can be used to create the sub-directories as needed.

``` kak
hook global BufWritePre .* %{ %sh{
  directory=$(dirname "$kak_buffile")
  test -d "$directory" ||
    mkdir --parents "$directory"
}}
```

Although I would like this behaviour being built-in.

**Comment by mawww** [comment]
I am not sure about that one, creating the directory should definitely not be silent, because thats pretty unexpected and it might be a user error, so making sure the user knows the directory was missing seems important.

As @alexherbo2 showed, its relatively easy to have the directory creation behaviour using a hook, so I am not convinced we need to have this behaviour built-in, but it could be nice.
