### ISSUE TITLE
Completion ordering not useful for prose text

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#1925]
### Steps 

1. `kak -n -e "set window static_words %sh{tr '\n' ':' < /usr/share/dict/words}"`
1. Enter insert mode, type `expressins` (note the missing "o")

### Outcome 

On my Debian Testing machine, the first completions offered are:

- "expressionism's"
- "expressionist's"
- "Expressionism's"
- "Expressionismus's"
- "Expressionist's"
- "Expressionistic's"
- "Expressionistically's"
- "expressionless's"
- "expressionlessness's"
- "expressiveness's"

Only then (after the first page of results) do I get the completion "expressions".

### Expected 

As "expressions" is only one letter different from "expressins", I'd have hoped it would be first, or at least higher in the list.

### Notes

Since all the useless words included an apostrophe, I wondered if perhaps 86fcc55e5 was relevant, but reverting it did not seem to change Kakoune's behaviour.

**Comment by mawww** [comment]
Hello,

Whats happening here is that those works are considered better matches because they have two word boundaries matching (e and s), when expressions, which is a single word, has only one.

I am not sure that sorting rule is that great, so I'd be willing to tweak matching. I do agree that `expresions` should be a better match here.
