### ISSUE TITLE
Feature Request: Optionally delimit expansion blocks with `{begin,sh} … end` (as in lua/ruby/ada).

### ISSUE THREAD

**Issue by nochiel** [mawww/kakoune#1935]
Currently,  predictably, yet alarmingly, something like `:eval echo %{ %sh{ echo "}" }}` will not parse.  
Importing scripts for use in kak scripts too often (for me) involves a hunt for a delimiter that will parse if the shell script already has offending characters.  Once I've found a delimiter, it's not a visually paired delimiter (e.g. `-` `@`) only to later have to modify the script and then have to change the delimiter.

It makes no sense that anyone should have to spend any time at all searching for a delimiter merely to get a kak script to parse especially when paired delimiters (brackets, braces, parentheses, chevrons) are in short supply.  Recently, I forgot about this problem and had to spend a rather long time debugging a large shell script once I tried to integrate it with kak.

~I'd like to request that we *get rid of this parsing problem once and for all* by making it possible for us to optionally delimit blocks as follows:~
```diff
- define-command foo
- begin
-   sh
- 
-   end
- end
```
~In particular, it should be possible to simply write a shell block as:~
```diff
- define-command bar %{
-    sh
-
-    end
-}
```

Alternatively, if no optional syntax is to be employed, then better/larger/more sophisticated lookahead and recovery should be implemented in the parser so that braces can be used and nested forever, even when mismatched (accidentally or intentionally) within the shell script itself, and still manage to send the correct shell block to sh(1). (I don't know, but that sounds more complicated even though new programming languages show up every day that use c-style braces for everything .)

**Comment by mawww** [comment]
Hello,

I am not sure how such a change would solve the problem we have. The quoting problem is due to the fact that Kakoune does not parse the content of `%sh{...}` blocks, so it has to treat it as a string. Parsing those blocks would mean implementing a posix shell compatible parser inside Kakoune... The current solution is to provide various delimiters so that hopefully for a given shell script, we can use a delimiter that is not unbalanced inside the shell script.

Not that unbalanced delimiters are relatively rare, they usually happen because they appear as literals in a string, and even there they often are balanced.

Introducing begin/end as delimiters would have the same problem, if "end" appears somewhere in the shell script, we will mistake it as the end of our block.

Any programming language I know of either parses fully a nestable companion language, or just uses strings to store the other language code, and requieres escaping of string delimiters.

I do agree it would be nice to solve the quoting problem, but I am not convinced the proposed solution would achieve that.

**Comment by occivink** [comment]
Wouldn't heredoc(or C++11's raw)-style strings be a more generic solution? You could make your delimiters as complex as needed.

Not that I think the current situation is that bad.

**Comment by nochiel** [comment]
Tentatively, I don't think a full posix parser is needed. (The notes from oil shell indicate that such a parser is *a lot* of work.) I suspect/hope that a partial parser with a bit of error recovery would do the right thing most of the time, mainly because, once a shell block has begun, the only possible valid syntax is a closing brace or statement. Recursive recovery from a parse error would mean going back to the last closing brace, ignoring it, and resuming parsing for a closing brace. I'll of course have to experiment/test my hypotheses before I can say anything more with certainty. 

(The syntax proposal, I admit, was more to do with ease of parsing visually on a late night of frustration, as I read a script, and less about its technical merit.)

**Comment by mawww** [comment]
At the minimum, we would need to be able to parse shell strings, including here-strings, not to confuse anything in there with the closing delimiter. This is non trivial, and I am not really keen on adding such a feature to Kakoune.

**Comment by mawww** [comment]
@occivink Yeah, C++ like raw strings would probably be my favourite solution for that. I am thinking of something like:
```
%sh`delim`my string containing ` and even `blah``delim`
```

Note that that would be a general syntax for `%` style strings. 
``
`%`delim`...`delim`
```
would work as well.

'`' seems like a good candidate for that.

**Comment by nochiel** [comment]
I'll try and write a small partial parser. If I make any progress I'll report back.  Thanks again for kakoune!

**Comment by mawww** [comment]
Now that the command parsing refactoring is in, I dont think this will get implemented.
