### ISSUE TITLE
Feature Request: add new hooks: BufSwitchPre and BufSwitchPost

### ISSUE THREAD

**Issue by tawsi-melek** [mawww/kakoune#1980]
Hi, I just switched from Neovim to Kakoune after playing with it for a few days.

I like how Kakoune delegates pane/window/tab management to external programs (tmux, in my case).

There is one thing I'm missing from Vim, though: in Vim, when you have more than one tab open at a time, you have a nice status line on top of the window with the current buffers names in it. Obviously, in Kakoune there is no need for such a status line because tmux status line works just as well.

Except for the buffer names. For example, if I open some tmux windows from inside Kakoune, all of them are named "kak". Obviously, I can rename them with `:%sh{ tmux renamew $kak_bufname }`, but of course I'd like to automate this. Specifically, it would be cool if Kakoune could automatically rename a tmux window each time that I switch buffer with the `:buffer` command.

So I looked at [the list of hooks](https://github.com/mawww/kakoune/blob/master/doc/pages/hooks.asciidoc), but there doesn't seem to be a hook for when the current buffer changes.

`BufCreate`, `BufNewFile` and `BufOpenFile` do not work with buffers that have already been loaded by kakoune. `BufClose` only works when `:delete-buffer` is called, but not when a buffer becomes "inactive".

As of now, I'm using the NormalKey hook with the Return key (since it's not used for anything), buf of course this means that every time that I switch buffers I have to press Enter to have tmux display the correct buffer name.

Thus, it would be nice of mawww if he could include a `BufSwitchPre` and a `BufSwitchPost` hooks, or just a `BufSwitchPost` hook, really, so that arbitrary commands can be executed automatically when the user switches buffer.

Thank you for the attention.

**Comment by mawww** [comment]
Hello,

Actually there is a hook you can use, it is `WinDisplay`. I understand it can be surprising, so here is a quick explanation:

In Kakoune, when you switch buffer, what actually happens is that the current client (thats the Kakoune part that takes care of user interaction, can be in another process) switches to another window. It tries first to find and existing free window onto the target buffer, and if it does not find it, it creates a new one. Windows are always linked to a single buffer, that buffer never changes for the lifetime of the window. So, when you switch to a new buffer, what happens is that we take that window (from the free window list of a newly created one), and we associate it with the client (where it will be displayed). Hence the hook we use when that happens is `WinDisplay`.

All that explanation is a bit complex, and I wish we could simplify things around that, because windows are a regular source of confusion in Kakoune. But for now, you should be able to get the behaviour you want by hooking on `WinDisplay`.

**Comment by tawsi-melek** [comment]
Thanks maww.

I just updated my hook with `WinDisplay .*` and now it works perfectly. It automatically updates the tmux window's name. Even when I'm simply jumping to another pane!

But yes, I would've never thought that the hook was `WinDisplay`, when I read "window" I thought about tmux windows, I didn't realize that Kakoune pairs each buffer with a window.
