### ISSUE TITLE
Cygwin build error 

### ISSUE THREAD

**Issue by Vm900** [mawww/kakoune#1981]
Hi
I've been trying to compile the editor using cygwin and I keep getting 
the error as shown:
![ncurseserror](https://user-images.githubusercontent.com/9399631/38168895-287d255a-3552-11e8-9eef-f14b7af9f4ae.PNG)

Please help
Thanks

**Comment by Screwtapello** [comment]
I don't know what the actual problem is, but those "undefined reference" things are supposed to be part of ncurses. If I had to guess, I'd say your ncurses header files are a different version from your ncurses library file, or possibly that built Kakoune once a while ago, then upgraded ncurses somehow, then ran "make" again and now Kakoune is expecting the old version and finding the new version.

My first step would be to `git clean -dxf` to blow away all uncommitted files, and then try building again.

**Comment by Vm900** [comment]
@Screwtapello Yep you're absolutely right.That solved my issue.Thanks a million

**Comment by FlyingWombat** [comment]
I'm getting a similar issue here, except it doesn't seem to be a problem with ncurses.  
Should I make a new issue for this?

My installation:
- Windows 10 17134.472
- MSYS2 with `base base-devel msys2-devel git gcc ncurses-devel` installed;  
  Relevant Packages:
- gcc 7.4.0-1
- ncurses 6.1.20180908-1  [compiled with --enable-widec](https://github.com/msys2/MSYS2-packages/blob/master/ncurses/PKGBUILD)

when running `make` in the `src` directory, I get the following build error.  
```
g++ -rdynamic -O3 -pedantic -std=c++17 -g -Wall -Wextra -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option .alias_registry.opt.o .assert.opt.o .backtrace.opt.o .buffer.opt.o .buffer_manager.opt.o .buffer_utils.opt.o .changes.opt.o .client.opt.o .client_manager.opt.o .color.opt.o .command_manager.opt.o .commands.opt.o .completion.opt.o .context.opt.o .display_buffer.opt.o .env_vars.opt.o .event_manager.opt.o .exception.opt.o .face_registry.opt.o .file.opt.o .hash.opt.o .hash_map.opt.o .highlighter.opt.o .highlighter_group.opt.o .highlighters.opt.o .hook_manager.opt.o .input_handler.opt.o .insert_completer.opt.o .json_ui.opt.o .keymap_manager.opt.o .keys.opt.o .line_modification.opt.o .main.opt.o .memory.opt.o .ncurses_ui.opt.o .normal.opt.o .option_manager.opt.o .option_types.opt.o .parameters_parser.opt.o .ranges.opt.o .ranked_match.opt.o .regex.opt.o .regex_impl.opt.o .register_manager.opt.o .remote.opt.o .scope.opt.o .selection.opt.o .selectors.opt.o .shared_string.opt.o .shell_manager.opt.o .string.opt.o .string_utils.opt.o .unit_tests.opt.o .window.opt.o .word_db.opt.o .version.o -lncursesw -o kak.opt
.backtrace.opt.o: In function `Kakoune::Backtrace::desc() const':
/c/Users/alari/builds/kakoune/src/backtrace.cc:63: undefined reference to `__imp_SymFromAddr'
/c/Users/alari/builds/kakoune/src/backtrace.cc:63:(.text+0xc5): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_SymFromAddr'
/c/Users/alari/builds/kakoune/src/backtrace.cc:51: undefined reference to `__imp_SymInitialize'
/c/Users/alari/builds/kakoune/src/backtrace.cc:51:(.text+0x14d): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_SymInitialize'
collect2: error: ld returned 1 exit status
make: *** [Makefile:96: kak.opt] Error 1
```

**Comment by Screwtapello** [comment]
I don't think msys2 is a supported build platform; that's the "POSIX environment for building Windows programs", right? As opposed to Cygwin, which is a POSIX environment for running POSIX programs on Windows.

In short, `SymFromAddr` and `SymInitialize` come from `dbghelp.dll`, which Kakoune's makefile automatically links with if the output of `uname` includes "CYGWIN". If you just want to see if you can get it working yourself, you should be able to run that same `g++` command and add `-ldbghelp` on the end, and that should get you past this hump.

On the other hand, if you're less interested in experimenting with porting Kakoune, and just want something that works, I recommend sticking with Kakoune inside Cygwin, or Windows 10's WSL.

**Comment by FlyingWombat** [comment]
You are right that MSYS2's main goal is to provide an environment for building POSIX applications to run natively on Windows.  
But, I don't see why it shouldn't be considered a supported build platform, when Cygwin is. After all, MSYS2 is a fork of Cygwin; it shares the same code for the POSIX compatibility layer.  
So, I don't see why they should be any different, as far as Kakoune is concerned. It will always require a POSIX environment to run, as was made clear in #764.

I'll try that flag out, and try building on Cygwin to see if there is any difference.

P.S.
As a side note, I mainly favor MSYS2 over Cygwin because it uses pacman, and the fabulous Arch Build System, rather than Cygwin's installer.

**Comment by Screwtapello** [comment]
The [MSYS2 homepage](https://www.msys2.org/) says "It provides a bash shell, Autotools, revision control systems and the like for building native Windows applications using MinGW-w64 toolchains." i.e. not "building POSIX applications" but "building native Windows applications".

But now that I actually think about it, if MSYS2 provides POSIXy tools like bash and Autotools, I guess there has to be compiler targeting MSYS2 as well as the advertised MinGW-w64 toolchain. As long as you're using the MSYS2 compiler and not MinGW, it should be OK? Maybe? Let us know how you go.

**Comment by FlyingWombat** [comment]
Adding `-ldbghelp` did not solve the build issue in MSYS2; got the same error as before.
Will update again when I try it on Cygwin.

**Comment by FlyingWombat** [comment]
Built on Cygwin without problems.  

IDK what is wrong with MSYS2. My guess is the differences are either with MSYS2's core, or with how GCC was compiled on MSYS2 -- compile flags are different vs Cygwin.  
Do you have any tips for debugging? I'm not trying to port Kakoune to Windows; I'm just trying to build on the MSYS2 POSIX compatability layer, instead of Cygwin's.  
If it's too much trouble I'll just install Cygwin.

**Comment by Screwtapello** [comment]
I don't really know much about MSYS2 or Cygwin, just what I've learned from a few web searches. I do note that `dbghelp.dll` is a Windows API, though, so if MSYS2's POSIX-compatibility is focussed on *pure* POSIX applications, it might not ship with all the bits required to link Windows and POSIX-y libraries in the same executable. Apparently, Cygwin does.

**Comment by FlyingWombat** [comment]
Well I feel kinda dumb now. I just edited the makefile to use the same build flags with MSYS2 as with Cygwin, and it built and ran just fine (`make test` failed though). 

In the make file, I just copied the Cygwin section, replacing `CYGWIN` with `MSYS_NT`:  
```
...
else ifneq (,$(findstring MSYS_NT,$(os)))
    CPPFLAGS += -D_XOPEN_SOURCE=700
    LIBS += -lncursesw -ldbghelp
...
