### ISSUE TITLE
Why is KakEnd triggered before BufClose?

### ISSUE THREAD

**Issue by ul** [mawww/kakoune#2001]
I'm not sure if it's a bug or this behavior is backed by rationale.

### Steps 

Add following lines to kakrc:

```
hook global KakEnd .* %{
    nop %sh{echo "KakEnd" >> /tmp/hook-test.txt}
}
hook global BufClose .* %{
    nop %sh{echo "BufClose" >> /tmp/hook-test.txt}
}
```

Then open any file with kak and then quit editor.

### Outcome 

```
$ cat /tmp/hook-test.txt 
KakEnd
BufClose
```

### Expected 

```
$ cat /tmp/hook-test.txt 
BufClose
KakEnd
```

**Comment by ekie** [comment]
hi,
i think it is not backed by rationale nor is a bug, but just how the implementation turned out. The bufclose hook is run in the buffermanager destructor.
The documentation does not state that kakend will be the last hook that fires, so this can be clarified not to be misleading or fixed to guarantee we have KakEnd to be the last hook that gets executed.

**Comment by mawww** [comment]
@ekie is correct, it just happen to run in that order, that was not a conscious decision. I am not sure however that it would be better to run them in another order, as hooks running during KakEnd might be creating/deleting buffers themselves (not that I would encourage such a practice), so depending on the absence of buffers in KakEnd does not seem like a good idea, if you need a buffer gone in your hook, I guess you can just safely do `delete-buffer my-buffer` in your hook to ensure thats done.

**Comment by ul** [comment]
Thanks for explanation!
