### ISSUE TITLE
<c-r> clears empty idented line, in *.go file.

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#2020]
In insert mode pasting via `<c-r>` clears indentation of empty line. This happens in go file type only. To make sure it's not my `kakrc`, I've removed it completly, before testing.
In the following session, I'm pasting content of the `%` register:
[![asciicast](https://asciinema.org/a/XhqLBV0IhPMUYFLoqDWzL1jLw.png)](https://asciinema.org/a/XhqLBV0IhPMUYFLoqDWzL1jLw)

**Comment by staab** [comment]
This actually happens to me too, in both python and javascript filetypes.

**Comment by mawww** [comment]
This is likely due to the hook that cleanups trailing whitespaces when exiting insert mode. We would need a way to distinguish between transient mode changes (such as <kbd>\<a-;></kbd> or <kbd>\<c-r></kbd> and non transient ones (such as <kbd>\<esc></kbd>). Not sure how to do that yet, we could use the hook filter text to add that information.

**Comment by maximbaz** [comment]
Or stop cleaning trailing whitespaces altogether and instruct users how to do it instead (#2175):

```
%{ try %{ execute-keys -draft \%s\h+$<ret>d }
```

**Comment by vbauerster** [comment]
Looks like fixed by #3620
