### ISSUE TITLE
Tooltip display

### ISSUE THREAD

**Issue by Vm900** [mawww/kakoune#2026]
Hi,
Should the tooltips be displaying like this or i'm missing something on my system?
![kaktooltips](https://user-images.githubusercontent.com/9399631/39599657-50dde7d8-4f14-11e8-9ab9-42ad4413b26e.png)

Thanks

**Comment by mawww** [comment]
it looks like your locale is not utf8, whats the output of the `locale` command in the shell ?

**Comment by Vm900** [comment]
@mawww I'm getting
![kaklocale](https://user-images.githubusercontent.com/9399631/39605224-6054f068-4f27-11e8-93f3-e5dc514ceca7.png)

**Comment by Vm900** [comment]
@mawww Just generated a new one but the issue persists
![kaklocale](https://user-images.githubusercontent.com/9399631/39609111-4283a798-4f3e-11e8-9043-92bdaca84904.png)

**Comment by Screwtapello** [comment]
Wow, I didn't think there were any Linux distros that still defaulted to a non-Unicode locale. You'll want to use `en_GB.UTF-8` rather than `en_GB` so you have proper Unicode support. According to [the SliTaz documentation](http://doc.slitaz.org/en:handbook:systemutils#language-and-keyboard-layout) it looks like you'll need to use the `tazlocale` tool to change the defaults.

**Comment by Vm900** [comment]
@mawww Just generated a new one but the issue persists
![Uploading kakLocale.png…]()

**Comment by Vm900** [comment]
Thanks
