### ISSUE TITLE
Defining custom scopes

### ISSUE THREAD

**Issue by notramo** [mawww/kakoune#2040]
I know that this had been discussed thousands of times. I've read also the relevant paragraph in the FAQ. So this isn't the same idea.
One of the main reasons that only the standard `sh` scope exists is that other scopes would introduce hard dependencies. But `sh` is launched as an external process. Why can't be any other interpreter launched externally? If somebody is developing in a scripting language, that language is most likely installed on his system.
So my idea is that scopes could be defined in Kakoune scripts, similarly to command and option definition. It wouldn't introduce hard dependencies, because if the interpreter isn't available, the scope definition command fails, and only the containing script fails, all other parts will run correctly:
```kakoune
%elv{ echo "quit" } # this don't work

# Define the scope.
# The Elvish shell is a modern scripting language. https://elvish.io
# define-scope <scope_name> <binary_name> <interpreter_arguments...>
define-scope elv elvish -c %c
%elv{echo "quit" } # It works now.
```
What do you think about it?

**Comment by lenormf** [comment]
Scopes are a very UNIX-y and orthogonal component in the editor, there's a scope for options, one for values, another for shell commands… Allowing to define arbitrary scopes that would have a default command for the builtin shell scope sounds redundant.

The other thing is that it's not much more efficient (the overhead of spawning a shell is slight) or convenient, e.g. `%elv{}` versus `%sh{ elvish -c "…" }`.

On the other hand you could actually highlight code in such custom scopes, whereas everything is highlighted as a string in the example above.

**Comment by notramo** [comment]
>The other thing is that it's not much more efficient (the overhead of spawning a shell is slight) or convenient, e.g. %elv{} versus %sh{ elvish -c "…" }.
I know it, but it requires a double quote, so if the e.g. Elvish command has a double quote in it, then it has to be escaped:
```kakoune
%sh{ elvish -c "print \"interpolated\nstring\"" }
# with custom scope
%elv{ print "interpolated\nstring" } # more readable
```

**Comment by mawww** [comment]
So, first, this is not what we call a scope in Kakoune's context. A scope is a set of option values, aliases, hooks, key mappings, faces, and highlighters. In Kakoune there are usually 3 scopes available in a context: window, buffer and global.

What you are referring to are called `typed expansions` (see `:doc expansions typed-expansions`).

I am not really keen on expanding the syntax to support custom expansion types because, as @lenormf explained, its already pretty easy to run a script with a custom interpreter.

One difference is that we introduce a dependencies between commands (we cannot parse `%elv{...}` before we have executed `define-expansion elv ...`), so every script that want to use it has to define that expansion, or has to rely on another script to define it before (which is a not yet solved problem in Kakoune).

Regarding readability, arguably the solution is a HEREDOC:
```
%sh{elvish <<"EOF"
print "interpolated\nstring"
EOF}
```
While I understand your desire to have a nicer syntax to write elvish scripts directly in Kakoune, I think this compromise should be good enough, avoid putting unnecessary complexity into Kakoune core, while still being relatively nice to write.

**Comment by maximbaz** [comment]
Should this issue be closed then?

**Comment by tmccombs** [comment]
Heredocs work, but besides being a little clunky, it is more difficult to get the proper syntax highlighting for the script. Although, hopefully it is possible.
