### ISSUE TITLE
'add-highlighter' No such highlighter factory '/'

### ISSUE THREAD

**Issue by atomrc** [mawww/kakoune#2045]
Just a quick question. I haven't had the time to dig seriously into this issue and produce a reproducible minimal example, sorry for that.
The question is, has something changed lately with highlighter groups?

I wrote a little typescript plugin sometime ago, and it seems it doesn't work anymore and crashed with the error `'add-highlighter' No such highlighter factory '/'`.
https://github.com/atomrc/kakoune-typescript/issues/1

Any idea?

I saw a commit related to `add-highlighter` and the `/` character but I am not sure it is related ..
https://github.com/mawww/kakoune/commit/39e63cf518074564992614c117d9e40a9011c425

**Comment by mawww** [comment]
Hello,

Some time ago, highlighters have been changed to be scoped, you can now have highlighters in global/buffer/window scope, hence the add-higlighter command has been changed to to take an additional argument for the scope.

To fix your problem on recent Kakoune, change `add-highlighter <type> <options>` to `add-highlighter <scope> <type> <option>`. To mimic the previous behaviour, use `window` for `<scope>`.

That change happened in d49555fc7568cff0db385d019a68cfdb0f28f8b0 and was announced on the IRC channel, along with being in Kakoune's startup message for some time (it was removed recently).

There are (unfortunately) some more breaking changes coming up, in order to fix long standing bugs and make Kakoune more consistent. As you maintain an existing script for Kakoune, it could be good to have you idle with us on the IRC channel.

Cheers,

Maxime.

**Comment by atomrc** [comment]
Thanks for your quick reply @mawww 
It's been a long time I haven't used kakoune to be honest.

I'll try to fix this soon then and probably re-jump back to kakoune.

Have a nice day.
