### ISSUE TITLE
Complete word from the current selections with select commands

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2086]
How about completing word from the current selections with the select commands – taking the <kbd>s</kbd> command – instead of the whole buffer?

**Comment by Delapouite** [comment]
Currently the matches are indeed based on the full content of the buffer:

https://github.com/mawww/kakoune/blob/master/src/normal.cc#L756
```cpp
auto matches = get_word_db(context.buffer()).find_matching(word);
```

A `WordDB` loops through all the lines during a rebuild:

https://github.com/mawww/kakoune/blob/master/src/word_db.cc#L101-L114
```cpp
void WordDB::rebuild_db()
{
    auto& buffer = *m_buffer;

    m_words.clear();
    m_lines.clear();
    m_lines.reserve((int)buffer.line_count());
    for (auto line = 0_line, end = buffer.line_count(); line < end; ++line)
    {
        m_lines.push_back(buffer.line_storage(line));
        add_words(m_lines.back()->strview());
    }
    m_timestamp = buffer.timestamp();
}
```

This autocompletion is used for all regex prompts: so it makes sense for `/` but yes it could be better for `s` and similar commands.

**Comment by mawww** [comment]
While I like the feature in principle, the implementation would be pretty complex as we would either have to overhaul the word db to know where the words appear, in order to filter out words that are not present in the selection, or we would have to scan the selection for words on each `s`, which would likely be very slow on big selections.

I dont think this is worth it at the moment.
