### ISSUE TITLE
Relicense Kakoune

### ISSUE THREAD

**Issue by inquisitiv3** [mawww/kakoune#2130]
Kakoune is currently under the *The Unlicense* [0]. The intention of the license is to release the work to the public domain in simple and few statements. While the license is clear to the reader, its legal ramifications is not. Practically the current license create problems and hinders its users from contributing to Kakoune or even using it.

I propose that we work to relicense Kakoune under a license that is on the *Open Source Initiative*’s (also known as “OSI”) list of licenses and standards [1].

Some organizations does only allow its employees to install software that is under a license that is on a preapproved whitelist. The whitelist often consist of the licenses on OSI’s list. This kind of organizations isn’t very common, but they are still out there and sadly prohibits people to use software like Kakoune.

This matters should be settled as soon as possible. Because for every new contributor to Kakoune we need to seek approval to change the license later on. It can create significant problems if we don’t get approval from all the contributors.

The sentiment that all significant jurisdictions should allow people to release their work into the public domain is noteworthy and something that I think should be encouraged. But sadly all legal systems doesn’t allow that today.

Licensing Kakoune under an OSI approved license we enable people in corporate environments to contribute back to Kakoune. This has allowed projects like Neovim to get significant contributions.

By relicensing Kakoune under a license on *Open Source Initiative’s* list we make Kakoune available for a larger audience, without compromising on what the users can do with the source code.

I’m aware that this issue has been discussed earlier in the issue #724, but I and several others want to bring this issue back for discussion.

[0] https://unlicense.org/

[1] https://opensource.org/licenses

**Comment by TeddyDD** [comment]
Personally I don't care but I had lengthy discussion with one person on
ZeroNet and they seem to be really concerned about Kakoune's copyright waiver
and license (simple misunderstanding but that's interesting data point, I
never had to explain how MIT license works...). 

I think "corporate" argument
is convincing...  but on the other hand... maybe that's corporations should
adjust, not the FOSS developers.

If I understand correctly there are two major problems with Unlicense from corpo standpoint: 
- corpo users can't install Kakoune
- corpo	users can't contribute to Kakoune

About first point: Kakoune could be dual licensed, but since it's public
domain, anyone can re-license it anyway, so what is the point doing it
here? Your boss does not allow Unlicense software? Fork and change license
to MIT, problem solved.

Second issue truly cannot be resolved without changing license.

> This matters should be settled as soon as possible. Because for every new contributor to Kakoune we need to seek approval to change the license later on. It can create significant problems if we don’t get approval from all the contributors.

Well, Kakoune is public license so I don't think we need to
approval of contributors, that's a point of Unlicense right?

Anyway, this might be interesting discussion

**Comment by mawww** [comment]
I would like to know about real companies where using Kakoune would be forbidden due to its use of the Unlicense. I understand the theory and the fact that an OSI approved license would be simpler to get approved, but I dont find those reason compelling enough to try to change the license.

One thing regarding changing the license is the following:

* Either the company considers the Unlicense valid, and then anybody can relicense the source code under another license. But in that case there is no reason for us to do it.
* Or the company considers the Unlicense invalid, meaning we cannot relicense the source code without explicit agreement from *all* the existing contributors, meaning we need to contact all of those to ask for permission to license (not relicense, as in this hypothese the licensing was invalid in the first place) their code under whatever license we choose.

So, either nothing needs to be done, or **lots** of work needs to be done.

In all case, I remain far from convinced this is a real problem. Regarding using Kakoune, I doubt many companies would prevent their employees from merely using software under the Unlicense. I would understand if they would prevent people from integrating code from Kakoune into their code, but that seems unlikely, and I dont care enough about that use case for those specific companies to do all the necessary work. Regarding contributing to Kakoune, it might prevent people from contributing in with the copyright of their company, requiring them to ask for a copyright waiver in order to contribute, this again is not a strong enough motivation for me to change the licensing.

The thing is, I dont really believe Kakoune needs to have corporation participating into its development. I dont mind if they do, but I dont think Kakoune needs to be relicensed to make that easier.

I am more sensitive by the fact that some people who would have wanted to use Kakoune might not be able to because their company forbids them to use any software under the Unlicense, but I consider this to be quite unlikely, and I am not sure I'd want to accommodate such a company (although that would mean preventing some good faith employee from using Kakoune, which I am not really happy about).

**Comment by Screwtapello** [comment]
> The sentiment that all significant jurisdictions should allow people to release their work into the public domain is noteworthy and something that I think should be encouraged. But sadly all legal systems doesn’t allow that today.

As a data point, although I haven't actually asked a lawyer, I have heard that my jurisdiction (Australia) doesn't allow works to be placed into the public domain. Or at least, it's not explicitly allowed in our copyright laws, and I've never heard of any court ruling one way or another.
