### ISSUE TITLE
Be able to run tests even in container environment

### ISSUE THREAD

**Issue by jkonecny12** [mawww/kakoune#2165]
### Steps 
1. Create a container to run a build. In my case I use Fedora's mock so I'll describe that. 
2. Download https://jkonecny.fedorapeople.org/packages/kakoune/kakoune-2018.04.13.tar.bz2
3. Download https://raw.githubusercontent.com/mawww/kakoune/master/contrib/kakoune.spec
4. Run "mock -r fedora-rawhide-x86_64 --buildsrpm --spec ./kakoune.spec --sources ./kakoune-2018.04.13.tar.bz2 --resultdir /tmp/srpm-kakoune/"
5. Run "mock -r fedora-rawhide-x86_64 --rebuild /tmp/srpm-kakoune/kakoune-2018.04.13-1.fc29.src.rpm --resultdir /tmp/rpm-kakoune/"

### Outcome 

BUILDSTDERR: ./run: line 64: /dev/tty: No such device or address

Complete logfile:
https://copr-be.cloud.fedoraproject.org/results/jkonecny/kakoune/fedora-28-x86_64/00769904-kakoune/build.log.gz

### Expected 
Build should run.

### Additional notes
https://unix.stackexchange.com/questions/301516/dev-tty-not-available-from-autosys/301532#301532

**Comment by Screwtapello** [comment]
Since ssh does not allocate a TTY by default when you run a command remotely, a simpler test-case is:

    ssh localhost "cd /absolute/path/to/Kakoune-working-copy/test; ./run"

The `cd` is necessary because the `run` script assumes it's being run from Kakoune's test directory; if you don't `cd`, it will scan your entire home directory looking for Kakoune test-cases, and that's probably not what you want.

**Comment by Screwtapello** [comment]
The error about `/dev/tty` occurs because the `run` script supports automating Kakoune by redirecting recorded keyboard input to Kakoune's standard input. Since bash doesn't really support conditional redirection, the script says:

    ui_in="${root}/${dir}/ui-in"
    [ ! -f $ui_in ] && ui_in="/dev/tty"
    # ...later on...
    $root/../src/kak out -n -s "$session" -ui json -e "$kak_commands" > ui-out < "${ui_in}"

If (as is normally the case) Kakoune's tests are being run interactively (in a terminal), the no-scripted-input case is effectively a no-op: input is redirected from the controlling terminal, which is where it was already. However, in a Docker container, or via ssh, there is no controlling terminal, so this explodes.

It's easy enough to change that code to default to, say `/dev/null` rather than `/dev/tty`. However, if you do, you get a bunch of test failures like this:

```
--- /home/st/Code/kakoune/test/./compose/inline-sort/out	2017-07-31 20:55:41.534552550 +1000
+++ out	2018-06-28 22:47:31.247020640 +1000
@@ -1 +1 @@
-(a b c d e)
+()

debug buffer:
*** This is the debug buffer, where debug info will be written ***
shell stderr: <<<
sort: stat failed: -: Bad file descriptor
>>>
```

In every test that tries to make Kakoune pipe something through `sort` or `sed`, `sort` or `sed` dies, claiming that stdin is a bad file descriptor. It's not obvious why that's going on, since Kakoune should be taking control of their stdin so it can pipe to them, and the inherited stdin should be irrelevant.

Note that Kakoune's C++ source *does* mention `/dev/tty` in a few places, but only when dealing with the NCurses UI—that code is not executed for the JSON UI (which is what's used when running tests) and so is not relevant to this issue.

**Comment by jkonecny12** [comment]
Nice, it is working like a charm. The Fedora daily builds and up and running again. Thanks for your help everyone! :)
