### ISSUE TITLE
Work with kitty on a xterm protocol extension to use terminal's *native* multiple cursors (to enable different cursor shapes and blinking)

### ISSUE THREAD

**Issue by maximbaz** [mawww/kakoune#2194]
I want to see a beam cursor in insert mode and an underline cursor in replace mode, and a hollow block cursor when terminal is currently unfocused.

[Kitty](https://github.com/kovidgoyal/kitty/)'s author is open to work on a new [xterm protocol extension](https://sw.kovidgoyal.net/kitty/protocol-extensions.html) to implement native multiple cursors support in terminals. He is looking for collaboration with kakoune developers in order to design the new protocol that can truly fulfill the needs of the editor.

Please join the discussion here: https://github.com/kovidgoyal/kitty/issues/720

----------

<details>

<summary> Old ticket description, no longer relevant </summary>

First of all, I've seen #1385, the argument "there is always a selection, so cursor should always be block" is simply wrong — kakoune _knows_ when I'm in normal, insert and replace mode, it should just render different cursor shapes at corresponding points of time.

I've also seen #1393, and an argument:

> We have experimented with visible ncurses cursor some time ago, and it broke many terminals. Kakoune will keep full control of cursor display for the time being.

Sure, let kakoune control the cursor, but teach it to use different shapes anyway. Do you need Unicode characters to use as cursors? Here you go: `▎` and `▁`. Since current cursor is probably `█`, we can use this one for hollow cursor (when kak is unfocused): `░`.

P.S. If I could get a "hollow block" cursor when the terminal is unfocused, I would be even happier, but I the beam and underline cursors should be the priority.

</details>

**Comment by ekie** [comment]
i am still using a patched kak to support this. if there is a interest i can work on a new pull request.

**Comment by maximbaz** [comment]
Awesome, I'm interested, is there a way for me to try? 

Could you also describe a bit your patch, does it make all cursors change form or only primary, and does it draw cursors as Unicode characters or exposes the ncurses cursor (which seems to be a no-go from the quote I posted in the first message)?

Having all cursors change form would be ideal of course 🙂

**Comment by net** [comment]
Unicode cursors won't help, as they'd overwrite the existing character in their cell.

That there is always a selection of at least one char has little to do with kakoune knowing which mode it's in. Even in insert mode there is a selection, and the cursor is part of the selection. (I apologize if I've misunderstood your disagreement.)

There are in my mind two inconsistencies that occur during insert mode:

  1. When appending to a selection the selection and cursor advance to the character after the selection. This is not only visual: `<a-;>y` will yank the extended selection.

  2. When prepending to a selection whose anchor is to the left and cursor to the right, the cursor jumps to the left side of the selection and remains there after existing. The same occurs when appending to a selection whose cursor is to the left.

I suppose this is kakoune's intended behavior: selections always include cursors, and text is always inserted before cursors. I'm not, however, aware of any pragmatic benefits.

If selections were to be left unmodified when prepending and appending, the problem is then communicating where text will be inserted. One solution is to render `[prepend]` or `[append]` after `insert` in the mode line. Another solution is to render a vertical bar cursor at the insertion point in supported terminals.

**Comment by maximbaz** [comment]
I've started a discussion in kitty terminal emulator about extending xterm protocol for native terminal support for multiple cursors. The author is not opposed to the idea, and actually is looking for collaboration with kakoune developers in order to properly design this feature that can actually meet the needs of the editor.

Everyone who is interested in joining the discussion, please do!

https://github.com/kovidgoyal/kitty/issues/720

**Comment by maximbaz** [comment]
> Unicode cursors won't help, as they'd overwrite the existing character in their cell.

Yeah, someone on IRC explained this to me already... I was under the impression that we can draw one Unicode character on top of another (so that we can draw a cursor char and then a letter on top of it in reversed color), but it's not how this works, we can only put one character in a cell and modify its background and foreground color (so currently the "cursor" is just a white background color).

That's why I created https://github.com/kovidgoyal/kitty/issues/720, I think this should be solved on the terminal level, and not by doing magic with background colors. The native terminal cursor has many capabilities that we can never replicate ourselves, such as cursor shape or blinking. I really hope we get the discussion in https://github.com/kovidgoyal/kitty/issues/720 rolling and implement this. [Kitty's protocol extensions](https://sw.kovidgoyal.net/kitty/protocol-extensions.html) have already proven to be successful, e.g. image protocol is being integrated in ranger so that it can draw pictures without relying on w3m hacks.

> That there is always a selection of at least one char has little to do with kakoune knowing which mode it's in. Even in insert mode there is a selection, and the cursor is part of the selection.

Exactly my point, I think we agree on this. The fact that kakoune always has some selection shouldn't stop us from having different cursor shapes when a user is in insert or replace more, the cursor shape is there to help understand what a next keypress will do to the buffer, just like the indicator in modeline.

> There are in my mind two inconsistencies that occur during insert mode

I think this deserves a ticket of its own, here I have a very specific wish to have kakoune support native multiple cursors with all of it's features, such as shapes and blinking.

**Comment by maximbaz** [comment]
Closing for now as sadly no terminal is currently wishing to implement native multiple cursors.

**Comment by Delapouite** [comment]
For people coming from search engines, some good news around native multiple cursors in Kitty: https://github.com/mawww/kakoune/issues/5377
