### ISSUE TITLE
`prompt`'s command gets executed after subsequent command

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#2216]
### Steps 

Run the following commands
`prompt '' %{ echo -debug first }; echo -debug second`

### Outcome 

In the debug buffer, `second` is printed before `first`.

### Expected 

`first` is printed before `second`.

This matters when running something like this snippet:
```
eval -save-regs ^ %{
    exec Z
    prompt '' "exec z"
}
```
the mark register is reset before the selections are restored

**Comment by lenormf** [comment]
I don't think this is unexpected, the command passed to `:prompt` is a promise that is executed asynchronously whenever the users has validated the prompt, therefore the editor moves on to the commands following the call to `:prompt`.

You need to have the code that you want executed after the callback called by the callback itself.

**Comment by occivink** [comment]
Right I didn't realize that all commands that take user input are executed asynchronously. I think it's rather strange though, for example if you do `prompt foo ''; prompt bar ''` the bar-prompt appears before the foo-prompt. 
The mark usecase I showed is also a lot more difficult to do properly in the callback

**Comment by mawww** [comment]
It is tricky, the only way to "fix" that would be to delay execution of those commands until after the prompt is finished, which leads to lots of unexpected complexity (you cannot assume anything about the state of the buffer, registers, ..., as while we were waiting for the prompt, other clients might have done various things).

I think the current solution (delayed commands should be put in the prompt "callback") is better because its clearer that those will be executed later on, and that anything can happen in the mean time (we might service a `kak -p <session>` while waiting on the prompt).

The snippet you posted is problematic, and there is no nice solution for it, besides using a user register and hoping nothing else will clobber it in the mean time. I am not sure what we could do to improve that.
