### ISSUE TITLE
Dynamic variable names do not seem to work in a %sh environment

### ISSUE THREAD

**Issue by fsub** [mawww/kakoune#2241]
### Steps 
```
decl int mine 5
eval %sh{ name=mine; eval value=\$kak_opt_$name; printf "echo %s\n" "$value" }
```
### Outcome 
Empty output
### Expected 
Output `5`

**Comment by Screwtapello** [comment]
When Kakoune evaluates a `%sh{}` block, it scans it for anything that looks like the words described in `:doc expansions`, and if any such words are found, they are added to the environment before the shell is launched.

For example, if you start Kakoune and type `<a-!>set | grep kak_<ret>` you'll (probably) get no output.

If instead you type `<a-!>set | grep kak_ # kak_opt_debug<ret>` suddenly you'll see `kak_opt_debug` in `set`'s output. It's not that `set` or `grep` did anything differently; that trailing text is a comment that's ignored by the shell. But Kakoune sees the variable name mentioned and adds it to the environment for `set` to find.

So you can use dynamic variable names as long as you only need to dynamically choose one of a handful of possible variables and mention their names somewhere in the `%sh{}` block. You can't use completely arbitrary dynamic variable names.

**Comment by fsub** [comment]
@Screwtapello Thank you for explaining the root cause. I have a bunch of variables whose names consist of a common prefix extended with a unique index. If I need to list all variable names explicitly I cannot practically use dynamic names.

**Comment by alexherbo2** [comment]
You could work-around by doubling the evaluation, but it’s tedious.

**Comment by mawww** [comment]
@fsub isn't it possible to use a list type for those variable (store them in one list instead of separate variables ?)

Making dynamic variables work this way means making every possible expansion available, which would be a huge performance and memory impact. Kakoune needs to see kak_.* somewhere in the %sh{...} contents for that variable to be added to the environment.

The only way this could be solved would be with an alternate system to query Kakoune state externally (something like kak -get <session> <var name>), unfortunately this is not easy to solve either (we need a way to run in a specified context, and we need to prevent side effects)...

**Comment by fsub** [comment]
@mawww I would love to use lists but I need a way to get the length and read/write items by index. Do such facilities exist?
I tried to employ dynamic variables in order to reduce some code duplication. I see why it doesn't work in my use case. At least in the short term, it's not a blocker.

**Comment by mawww** [comment]
From the shell you can, the preferred pattern is `eval set -- "$kak_opt_my_list"` (or you can do `eval my_shell_func "$kak_opt_my_list"`). This will give you the lists elements in `$1..$n`, with `$#` giving you the count. There is one problem still to be solved which is that single quotes inside list-elements will be lost due to how we quote.

**Comment by fsub** [comment]
@mawww Thanks. I might try that.
