### ISSUE TITLE
Kitty integration is broken

### ISSUE THREAD

**Issue by laelath** [mawww/kakoune#2266]
### Steps 
Call `kitty-new`

### Outcome 
A new kitty window is created, but nothing opens, and the original kakoune hangs with 'waiting for shell command to finish'

### Expected 
A new kitty window is created with kakoune open.

**Comment by lenormf** [comment]
Anything in the `*debug*` buffer?

**Comment by mawww** [comment]
Is that on latest Kitty ?

**Comment by laelath** [comment]
I am on the latest kitty, I do have remote kitty control enabled, and I can't access the debug buffer because the kak session is unresponsive, even if trying to connect from a separate terminal.

**Comment by mawww** [comment]
Yeah, not sure whats happening there, seems the kitty call is waiting for the terminal to answer, and is blocked on a read call, seems to be on kitty side though, as it access /dev/tty and correctly manage to open a split, its just reading the response that seems to block.

**Comment by laelath** [comment]
Should the kitty support scripts be removed for now? Seeing as trying to use it hangs kakoune.

**Comment by mawww** [comment]
I dont think it should be removed, it use to work, something might have changed in Kitty itself, we should get kitty fixed.

**Comment by net** [comment]
@mawww what exactly is the issue that should be reported to kitty?

**Comment by mawww** [comment]
@net Kitty starts application on `@ new-window` before the window size is available, resulting to the TIOCGWINSZ ioctl returning a 0,0 size. Additionally, when run from Kakoune, `kitty @ new-window` hangs, seemingly waiting on `read` syscall for an answer from the server, after the new window has been opened.

**Comment by stevenyvr987** [comment]
kitty.kak is not working for me. Here's a test case that tries to reduce the functionality of kitty.kak to a minimum.

1. kitty.kak can be reduced to the following invocation, in which kak is started as session `a`, and then it immediately tries to open a new kitty window executing a kak client on session `a`. The new window flashes and then disappears. Nothing interesting is shown in the debug buffer.
`kak -n -s a -e 'nop %sh{kitty @new-window --no-response kak -n -c a}'`

2. However, if a new kitty window executing kak in a different session `b`, it works.
`kak -n -s a -e 'nop %sh{kitty @new-window --no-response kak -n -s b}'`

```
$ kak -version
Kakoune v2018.10.27-186-g8b6868f
$ kitty --version
kitty 0.13.3 created by Kovid Goyal
```

**Comment by mawww** [comment]
Could you try with a more recent Kakoune release ? Things seems to be working correctly here.

**Comment by stevenyvr987** [comment]
I've upgraded to 699d066, which is the current HEAD of master, and re-compiled.
> src/kak.opt -version
Kakoune v2018.10.27-267-g699d066e

Repeating step 1 in my previous comment shows the same result.
> src/kak.opt -n -s a -e 'nop %sh{kitty @new-window --no-response $HOME/Documents/kakoune/src/kak.opt -n -c a}'

Something flickers and then disappears and only the first client shows up. Maybe a timing problem?

**Comment by ffreling** [comment]
I am new to Kakoune and the broken kitty integration greatly impacts my workflow. I am very used to `fzf` to browse files and buffers and so I naturally installed https://github.com/andreyorst/fzf.kak

The fzf plugin does work if I run Kakoune inside tmux but then I have a small lag in commands. Running directly in Kitty feels much more reponsive.

However if I invoke fzf without tmux inside Kakoune, it spawns a new OS window (not a different Kitty window) with fzf. After choosing a file the window disappear but the original Kakoune window is not updated with the selection.

The original Kakoune window is updated once I kill the second Kitty process that was spawned.

The root issue seems to be that we spawn a new OS window instead of a side-by-side Kitty window.
Running `:kitty-terminal cat` does create a new Kitty window side-by-side.

Environment:
```
macOS Mojave 10.14.3
kitty 0.13.3
kakoune v2019.01.20
```

**Comment by mawww** [comment]
@stevenyvr987 I think the version issue is due to your git repo not containing the tags for later versions, but seems to be pretty recent, as of today there is 290 commits past 2018.10.27, and your version is 267 commits past it, so prettty recent. I tried again here with kitty 0.13.3 and things work correctly.

@ffreling Seems the root of your problem is that for some reason the `terminal` alias is not set to `kitty-terminal`, which might be due to your TERM value not being set to xterm-kitty.

**Comment by ffreling** [comment]
As far as I can see, the TERM is properly set:
``` ➤ env | rg TERM
COLORTERM=truecolor
TERM=xterm-kitty
TERMINFO=/Applications/kitty.app/Contents/Frameworks/kitty/terminfo```

**Comment by laelath** [comment]
Looking in the implementation of fzf.kak, it looks like it hardcodes support for x11 and tmux only, which would be my guess why it's acting weird under kitty. It should be falling back to the `terminal` alias, though I'm not entirely sure why x11.kak isn't launching kitty properly.

**Comment by mawww** [comment]
@ffreling Could you try to add a 'echo -debug kitty was detected' command as part of the commands run in kitty.kak KakBegin hooks (like, add that at line 10). After starting you can take a look at the `*debug*` buffer to see if that hook did run as expected.

If that is the case, then it means something is changing that terminal alias after the fact. By the way, could you just do `:terminal sh` to see what terminal is used ?

**Comment by elasticdog** [comment]
I was also having similar issues with disappearing windows, and getting error messages about a "failure to launch child process [...]" and "no such file or directory". In my case, it wasn't anything Kakoune was doing specifically, but a problem with Kitty's environment; running `kitty @ new-window` worked, but adding any argument on the end did not. Explicitly setting a `PATH` variable in my _kitty.conf_ fixed up most of the behavior within Kakoune:

**~/Library/Preferences/kitty/kitty.conf**
```
env PATH=/Users/elasticdog/bin:/Users/elasticdog/.local/bin:/Users/elasticdog/.cargo/bin:/Users/elasticdog/src/go/bin:/Users/elasticdog/.nix-profile/bin:/Users/elasticdog/.asdf/bin:/Users/elasticdog/.asdf/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/kitty.app/Contents/MacOS
```

Not sure if that would explain anyone else's difficulties, but it sorted things out for me. I was also interested in using fzf.kak and will file a PR upstream to use the `terminal` alias directly rather than hard-coding in the options.

**Comment by ffreling** [comment]
> @ffreling Could you try to add a 'echo -debug kitty was detected' command as part of the commands run in kitty.kak KakBegin hooks (like, add that at line 10). After starting you can take a look at the `*debug*` buffer to see if that hook did run as expected.
> 

I had to wrap 'echo -debug' calls with 'printf %s' statement but it worked fine, I can see that the hook was successful.

> If that is the case, then it means something is changing that terminal alias after the fact. By the way, could you just do `:terminal sh` to see what terminal is used ?

Running `:terminal sh` opens a basic `sh` prompt, even though my main shell is fish with `SHELL=/usr/local/bin/fish`.

**Comment by ffreling** [comment]
@elasticdog Unfortunately specifying the PATH in `kitty.conf` did not solve my issue.

**Comment by laelath** [comment]
@ffreling calling `:terminal sh` will open `sh`, because it's directly launching `sh`, not looking up your shell. Since the kitty hooks were being run, it sounds like you're running into the same problem as @elasticdog, which is due to fzf.kak manually supporting `tmux` and `x11` and not falling back on the `terminal` alias properly.

**Comment by alexherbo2** [comment]
@elasticdog and @ffreling Kitty should work with [Connect].

Simply run

``` kak
connect edit $(fzf)
```

[Connect]: https://github.com/alexherbo2/connect.kak

**Comment by laelath** [comment]
This is unrelated to the original issue which was resolved. The new problem is an issue with fzf.kak not kakoune, which the author of is working on resolving.

**Comment by egolep** [comment]
I also have problems with kitty integration. It' pretty simple: both kitty-repl and kitty-terminal simply does nothing. No actual repl or terminal opens, no "flashing window" nor anything in *debug* buffer.

OS: Manjaro
Kak version: 2020.09.01
Kitty version: 0.19.3

**Comment by m0ar** [comment]
@egolep did you figure this out? Facing the same issue.
