### ISSUE TITLE
TMUX Terminfo override is not working on MacOS

### ISSUE THREAD

**Issue by giodamelio** [mawww/kakoune#2274]
When I try to use the [workaround for TMUX and the colors](https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#im-using-tmux-and-colors-look-weird) `tic` crashes with a SIGSEGV. Has anyone gotten it work on MacOS?

**Comment by net** [comment]
Try xterm-256color:

```tmux
set -g default-terminal "xterm-256color"
```

**Comment by lenormf** [comment]
>Try xterm-256color

That would defeat the point of overriding the default `tmux-256color`.

>`tic` crashes with a SIGSEGV

It looks like this is a recurring issue:

https://github.com/tmux/tmux/issues/194
http://fr.appledv.com/tic-ne-lit-pas-de-stdin-et-segfaults-lors-de-lajout-de-terminfo-pour-supporter-litalique-dans-tmux.html

Since the terminfo file works fine on other systems, I think you should bring it up on `tic`'s tracker.

**Comment by giodamelio** [comment]
@net That was what I had before (and it had the incorrect colors for Kakoune).

@lenormf Thanks for the links, I didn't manage to uncover those. I will talk to the `tic` people.

Just for reference, what version of `tic` are you all on? Latest MacOS is running `ncurses 5.7.20081102`.

**Comment by net** [comment]
@giodamelio you can install ncurses 6.1 with brew—`brew install ncurses`—and find its `tic` in `/usr/local/opt/ncurses/bin`. I was unsuccessful in using the ncurses tmux-256color in `/usr/local/opt/ncurses/share/terminfo/74` which the workaround depends on, and xterm-256color served my purpose.

**Comment by giodamelio** [comment]
@net Thanks so much! I missed the fact that the new version of `tic` was not taking priority in the `$PATH` because of MacOS shenanigans. Using the newer version of `tic` makes the work around in the FAQ work just fine.

For anyone that finds this, having a `tic` version after `6` seems to do the trick.
