### ISSUE TITLE
Linter: stderr is ignored

### ISSUE THREAD

**Issue by MarSoft** [mawww/kakoune#2302]
### Steps 
1. Configure linter but make a typo in the command, or maybe linter doesn't work due to some environment problems (like broken virtualenv).
2. Load a file and run `:lint` command

### Outcome 
"Optimistic" message is snown: `linting results: 0 error(s) 0 warning(s)`.
But in reality the file was not checked at all. If you replicate the same command in the console, you will see an error. But it may be hard to replicate _the same_ command because temp dir is used, and because environment in the console may be slightly different.

### Expected 
1. Linter's return code should probably be checked.
   E.g. it would return `0` on success, nonzero on some errors found, and if it returned nonzero but we found no errors then something is wrong.
2. Linter's `stderr` is probably meant to be captured (temp file is named `stderr`) but in reality it is just dropped. `2>&1` should probably be added.
3. `awk` script should somehow pass through all lines it could not process, so that these errors (having wrong format) would be displayed in the output buffer anyway. Or in some different buffer.
4. Is there any reason why the file is checked in a temporary directory instead of the original file?
   It may be useful when you don't want to save your changes yet, but for some languages and linters which depend on neighbour files
   (like `mypy` checker) it will break everything.
   Probably it should be made configurable? E.g. I use git everywhere and save my changes every now and then, so I don't need this functionality.

5. Possibly unrelated, but... Current linting configuration requires the linter to output the correct format. If it doesn't then you have to use a not-obvious "hack" like this:
```
hook global WinSetOption filetype=python %{
    # this "magic" is to append the last required colon between error code and message
    # (as pylama doesn't support the required format)
    set buffer lintcmd %{
        lint() {
            pylama "$@" | sed 's/: \([A-Z0-9]*\) /: \1: /'
        }
        # important: no newline after the next line, so that the argument will be passed properly
        lint }
}
```
But instead we could use some marker like `__FILEPATH__` or so which would be replaced with the file path, then file path can be placed anywhere in the command, not necessarily at the end:
`set buffer lintercmd "pylama __FILEPATH__ | sed 'my-sed-commands'"`
Or maybe instruct through a docstring to reference some variable, like `$filepath`, and declare that var before calling lintcmd.

**Comment by lenormf** [comment]
>Linter's return code should probably be checked.

Probably, but the question is: how to do it properly? The pipe is making it hard, and we don't want a two-step snippet that sorts `stderr` to a duplicated file.

>Linter's stderr is probably meant to be captured (temp file is named stderr) but in reality it is just dropped. 2>&1 should probably be added.

Since we expect runtime errors to be printed on `stderr`, we better leave that stream alone so that we can see the errors in the debug buffer.

Also this file is mis-named because the original code was copied over from `clang.kak`, but we actually expect `stdout` here.

>awk script should somehow pass through all lines it could not process, so that these errors (having wrong format) would be displayed in the output buffer anyway. Or in some different buffer.

As far as I can tell, `awk` already ignores lines that don't start with coordinates. Not sure it would be worth it to have the script check for the format of each line, considering how slow it already is.

>Is there any reason why the file is checked in a temporary directory instead of the original file?

If you want to lint a buffer not backed by the filesystem.

>Possibly unrelated, but... Current linting configuration requires the linter to output the correct format. If it doesn't then you have to use a not-obvious "hack" like this:
>[…]
>But instead we could use some marker like __FILEPATH__ or so which would be replaced with the file path

The idiomatic way to handle that problem is to create a shell wrapper, and place it in your `$PATH`. It's more UNIX-y, and prevent the script from spawning more processes to replace an arbitrary expansion (`__FILEPATH__` ? `{filepath}` ? `${kak_opt_lint_filepath}` ? etc) and generate the final command.
