### ISSUE TITLE
Indentation guides

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2323]
Hello, I'm continuing exploring Kakoune, and I'd like to ask about it's ncurses TUI capabilities.

Is it possible to have indentation guides, like in modern GUI editors like Sublime, VSCode, Atom, Notepad++, and others? 

In short, Indentation guides is a GUI editors feature, which is highly ignored by most of TUI editor developers, since it is hard to have thin vertical lines, because each will occupy cell, and terminals are not support drawing vertical lines as a cell parameter.

I use Kakoune with `add-highlighter global show_whitespaces -tab "▏" -lf " " -nbsp "⋅" -spc " "`, and used Vim (can't avoid comparison here, since Vim has similar problem since created) for many years with similar setings, and never actually had problems with cell occupation, since these cells are always contain whitespaces:
![image](https://user-images.githubusercontent.com/19470159/44395661-3a0b2180-a543-11e8-9cd8-b88750354b76.png)
(Kakoune | Neovim | VSCode)

You can see that VSCode has one line colored more bright, it shows what area my cursor currently in. That's one more useful feature despite being able to see indentation guides. With this tight code placement it isn't clear how Indentation guides actually can help, let's look at another example, which also contains empty lines between lines of code:
![image](https://user-images.githubusercontent.com/19470159/44396090-8efb6780-a544-11e8-88de-1f4a2d6c52cc.png)
(Kakoune | Neovim | VSCode)

While it's not a problem to see what area cursor is, it is little more ambiguous where does `while` scope starts and end. VSCode shows it with highlighted indentation guide, since cursor is inside of it. (And thankfully this file is formatted *properly* which isn't a common practice AFAICS, since I've seen too much unformatted code for like past 6 years. And when it comes to unformatted code, Indentation guides sometimes are time-savers.)
Deep indented code (which isn't a great practice, I know, but not all code we work with is great) will also benefit from indentation guides, since it is easy to find where scope of current block ends. Yes, I know about `m` motion, however moving to the scope start and then to the end, is slower than just fast look with your eyes over the indentation guide.

The problem with last screenshot (and the main problem with this method), is that not only indentations guides are not drawn at empty lines (since it is just whitespaces with custom highlighting), but that if file is indented with spaces, or mixed spaces, and tabs (like there) you will not see any guides at all, because spaces are not tabs and therefore no vertical bars with `show_whitespaces`. Emulating indentation guides with Kakoune's `show_whitespaces` or Vim's `listchars` isn't great by itself, since I'd like to set tabs to `→` for example, so I could see when indentation is done with spaces, while still being able to see guides. Using code formatters isn't an option, since I often fix other people's code, and wouldn't like to mess with them after committing their code to the repo fully reformatted, which will not please them, since they have [their own strong view of proper formatting](https://user-images.githubusercontent.com/19470159/44397616-a2f59800-a549-11e8-9198-46ce15f5bb18.png) (we don't have style guides, and tons of legacy code, that was written in spaghetti style, but that's another story).

Since ncurses can draw pretty everything we want, can't we have indentation guides either as vertical bars of changed background color, so it won't occupy cell, or as `▏` (or any other pipechar) since indentation guides never actually drawed on non-whitespace area, even in GUI editors.

I've already opened similar issue in neovim: https://github.com/neovim/neovim/issues/7544 and proposed using a folds api, for providing information about indentation guides, since this is really the same thing. AFAICS there's no folds in Kakoune yet https://github.com/mawww/kakoune/issues/453, and knowing that most GUI editors I've mentioned draw indentation guides based on indentwith setting, I think that continious, scope aware guides are possible without fold api.

**Comment by Screwtapello** [comment]
I think it would be possible to write a tool that would read a file on standard input, and write to standard output a `range-specs` description of all the characters that should be highlighted as indentation guides. Then you could use a `ranges` highlighter to display the highlighting, and an `InsertIdle` hook to keep it up-to-date as the buffer contents are changed.

However, I suspect `range-specs` options use coordinates in *characters*, not *cells*, which makes things awkward when one character covers multiple cells (like a tab character) — you might wind up with the entire tab character being highlighted instead of just the left-most cell.

You could concievably also use a `range-specs` option with a `replace-ranges` highlighter that deliberately replaces tabs with multiple single-cell characters so things would still line up properly, but I think it would not be possible to change their colour.

**Comment by andreyorst** [comment]
I don't think that hook based update mechanism should be used, in this case info about ranges should be updated in the same way as code highlighting gets updated.

**Comment by Screwtapello** [comment]
Highlighting is built into Kakoune's core, and every time the buffer is edited, Kakoune knows how to re-apply the rules and dynamically update the highlighting state.

Kakoune does not currently know about identation guides, and so can't automatically keep them up-to-date.

Kakoune could be taught about indentation guides, but that would take time and effort and C++ code. Alternatively, a hook-based system like I described would be less polished, but should be doable with Kakoune as it stands today, no additional core development required.

If I were keen on indentation guides myself, I'd probably start with an external hook-based system, try it for a little bit, take note of the shortcomings, and come back with specific ways that Kakoune would need to change to make indentation guides work properly.

**Comment by alexherbo2** [comment]
I do not agree about the feasibility with `replace-ranges`.

- The highlighter needs actual characters to replace with, so it won’t work on discontinued lines.
  - We can argue that, for empty lines, new line characters being replaced with multiple characters – to draw indent-guides – but:
    - It feels like an abuse.
    - Breaking the _1:1_ character to replace would be very messy on UI interactions.
- Replaced characters can’t be normally selected – they are skipped – so it feels odd to have the whole line starts non selectable; visually, it looks like the lines start beyond the actual line start.

**Comment by mawww** [comment]
It seems to me that indentation guides would be a good candidate for a built-in highlighter, it would likely require to be integrated with the show-whitespace highlighter (by adding a `-indent-guides` switch to it) because they both need to manually expand tabulations in order to display their content, which means they would not work well together as two separate highlighter (actually that would be true for non-tabs characters as well, as we cannot both have a `▏` and a `·` on the same character).

**Comment by alexherbo2** [comment]
@mawww How will you represent indent guides for empty, discontinued lines and distinguish from blank lines

**Comment by andreyorst** [comment]
> It seems to me that indentation guides would be a good candidate for a built-in highlighter, it would likely require to be integrated with the show-whitespace highlighter (by adding a -indent-guides switch to it)

Since `show-whitespace` relies on actual chars in cells, drawing guides on empty lines will require adding/modifining the eol symbol, which is not great, since it is (future) limitation rather than extensibility. I think that guides should be drawn with pure UI (by ncurses in kakoune case), despite contents of the buffer or cell, as it is done within other editors.

>because they both need to manually expand tabulations in order to display their content, which means they would not work well together as two separate highlighter (actually that would be true for non-tabs characters as well, as we cannot both have a ▏ and a · on the same character).

Well, again, if indentation guides are drawn with ncurses, and by coloring cells, this will able to use both guides, and whitespaces like `→` and `·`. 
![image](https://user-images.githubusercontent.com/19470159/44651034-e8eea800-a9f0-11e8-866f-149b4361d8b4.png)
(colored cells)
Though I don't know which way is better, since cells are thick, and such guides may become distractions. However this may make able to use something like this:
![image](https://user-images.githubusercontent.com/19470159/44650872-767dc800-a9f0-11e8-99cb-8f1a6244fc14.png)
or maybe even this (but this requires mechanics which will allow modifications of how guides work on per language basis):
![image](https://user-images.githubusercontent.com/19470159/44650906-944b2d00-a9f0-11e8-8026-003f936fed87.png)

I think that there's needed some an ability to define custom rules, much like with custom regex highlighting. For example In other editors indentation guides are drawn for empty lines if next not empty line has bigger indentation compared to previous guide (but this is kinda poor usage, since this can be syntax aware feature):
![image](https://user-images.githubusercontent.com/19470159/44650275-d4a9ab80-a9ee-11e8-892d-c838c2745bf0.png)
![image](https://user-images.githubusercontent.com/19470159/44650291-e2f7c780-a9ee-11e8-8d6d-decd8d0a0f54.png)
But if no custom rules for language are defined, fallback to standard method of drawing indentations based on tabstop settings can be used.

**Comment by mawww** [comment]
@sittim Regarding the coumn guides, you can combine the `column` highlighter along with the `FocusIn` and `FocusOut` hooks to achieve the same thing in Kakoune.

For indent guides, it needs to be added to the whitespace highlighter.

**Comment by andreyorst** [comment]
good Emacs plugin that does the thing with different methods, and highlighting of current  guide: https://github.com/DarthFennec/highlight-indent-guides
I'm not sure that the lisp implementation will be useful at any rate here, so this is just to provide an example of fine implementation

**Comment by andreyorst** [comment]
AFAICS this is not possible yet, because of empty lines. E.g. we could use `replace-ranges` for leading spaces and tabs to display `|` guide, but IDK if we can replace beyond EOL (`$`):

```
int main() {$
|   if (true) {$
$
|   |   return true;$
|   }$
|   return 0;$
}$

**Comment by wcasanova** [comment]
any progress on this? is something like this possible?
![imagen](https://user-images.githubusercontent.com/12401985/102727760-7d8a1c00-4306-11eb-89bf-fcd49ca67512.png)

**Comment by clarfonthey** [comment]
Right now I use this to get the guide effect when using tabs:

```
add-highlighter global/ show-whitespaces -tab '│' -tabpad '╌'
```

Would be nice if there were some way to do this for spaces, e.g. `faketab` and `faketabpad` options. Here's some sample code for what it looks like:

![Screenshot from 2021-07-27 23-33-04](https://user-images.githubusercontent.com/15850505/127259389-26caf8d5-5a78-4dc8-8d6d-61cddc322080.png)

**Comment by phaazon** [comment]
Just so you know, I think it should be pretty doable with [kak-tree-sitter](https://github.com/phaazon/kak-tree-sitter) now that I think about it.

**Comment by waldyrious** [comment]
@andreyorst just to make sure, why did you close this as "not planned"? None of @mawww's comments in this thread seem to indicate they don't think this is a worthy feature to include.

**Comment by andreyorst** [comment]
I no longer need this feature and not interested in further tracking of it. The "not planned" was shosen because It's not completed, and there was no other status to choose from. 

If there's someone else who needs this feature and wants to keep track of the request for it, they can open a new ticket.

**Comment by waldyrious** [comment]
I think you can unsubscribe from an issue, even if you were the one to create it. Would that work for you?

**Comment by waldyrious** [comment]
> I can't speak for everyone who's been a part of the discussion here, but there's a high possibility that they've also lost interest

Without any signal of such loss of interest, I would hesitate to assume that, let alone assign it a high probablility. On the contrary, at least two people have been active in this thread after its closure; if anything, that signals the opposite of lost interest. In any case, an issue in a public tracker (especially one where multiple people, including the project maintainer, have participated) is a collective artifact, not something that's owned by the original poster. I would have at least announced the intention to close the issue, or requested confirmation from the other participants, before taking that action.

> it will be recreated anew by someone who really needs it

Right, but that splits the discussion making it necessary to jump between two places to have the full context. I find it preferable to simply leave the discussion in place, as a dormant discussion doesn't bother anyone, and if the maintainer considers taking the feature on and is unsure whether the community support is still there, they can simply ask in the thread.

Mind you, I share the despise for bots automatically closing old issues, because they do so without proper context of whether an issue is still relevant or not. However, what you did was not that dissimilar: although you have indeed lost interest in this feature, none of the other people have indicated this, and what's more, the maintainer himself showed openness to considering this feature.

All that said, I realize we are now five comments into an off-topic sub-thread of this issue's discussion, so I won't insist any further. I'd ask you to consider reopening the issue and unsubscribing, but if you insist on keeping it closed, I guess we'll just have to agree to disagree.
