### ISSUE TITLE
Cannot omit passing an empty string to `set` to reset an option

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2350]
Was this behavior only intended for lists?

### Steps 

`set global modelinefmt`

### Outcome 

An error occurs:

```
1:1: 'set' expected a single value for option
```

### Expected 

The string option is reset (an empty string is assigned to it).

**Comment by mawww** [comment]
I am not sure this would be a good feature. For lists its just the natural way to write an empty list, so it makes sense, but for `int`, `str`, or other values, it would need to default to certain value, I am not sure that the convenience of writing `set global my_opt` instead of `set global my_opt 0` or `set global my_opt ''` is strong enough to justify the additional confusion this will add to script readers.

**Comment by lenormf** [comment]
I just wondered if it was a discrepancy, or if the notation only applied to lists. I'm fine with it either way, closing.
