### ISSUE TITLE
Syntax Highlighting Overlapping

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2388]
I feel like syntax highlighting is not working as it should.

Consider neovim and kakoune in comparison:
This is how I tend to configure my kakoune - I'm iterating over string with filenames and sourcing them one by one. This allows me to separate configurations to different meaningful files, and avoid using autoload directory that breaks the whole loading process for some reason:
![image](https://user-images.githubusercontent.com/19470159/45503092-85a19b80-b78e-11e8-9462-d8b18b3f671e.png)

As you can see on this screenshot, i'm using highlighter `show-whitespaces` set to `-tab "▏" -lf " " -nbsp "⋅" -spc " "` Whitespaces has it's own highlighting color which is gray in my case, and those should stay gray, because those are whitespaces, and are not belong to the actual file contents. So for example, if I add this `▏` symbol to my string, I'll won't be able to tell if it is a whitespace highlighted by kakoune, or a part of a string:
![image](https://user-images.githubusercontent.com/19470159/45503391-648d7a80-b78f-11e8-8ada-961506f48539.png)
So in this example a whitespace is being highlighted as a part of a string.

Another example:

A c filetype file:
![image](https://user-images.githubusercontent.com/19470159/45503889-e3cf7e00-b790-11e8-9550-eed41e6f5272.png)
I use this user added highlighters:
```kakoune
hook global WinSetOption filetype=(c|cpp) %{                                                                               
    add-highlighter buffer/ regex \w+(\h+)?(?=\() 0:function                                                               
    add-highlighter buffer/ regex (?<=\.)\w+(?!\()(?!>)(?!") 0:Child                                                       
    add-highlighter buffer/ regex (?<=->)\w+(?!\()(?!>)(?!") 0:Child                                                       
    add-highlighter buffer/ regex \b(v|u|vu)\w+(8|16|32|64)(_t)?\b 0:type                                                  
    add-highlighter buffer/ regex \b(v|u|vu)?(_|__)?(s|u)(8|16|32|64)(_t)?\b 0:type                                        
    add-highlighter buffer/ regex \b(v|u|vu)?(_|__)?(int|short|char|long)(_t)?\b 0:type                                    
    add-highlighter buffer/ regex \b\w+_t\b 0:type                                                                         
}                                                                                                                          
add-highlighter global/ regex (\+|-|\*|=|\\|\?|%|\|-|!|\||->|\.|,|<|>) 0:operator                                          
add-highlighter global/ regex (\(|\)|\[|\]|\{|\}|\;|') 0:Delimiters 
```
and because they are loaded after the main configuration of kakoune (supposing /usr/share/autoload is loaded first, my config is loaded after it), I expect that my highlighters should override highlighters that are coming within kakoune. So if I define a highlighter for function, it should override built in highlighter, like in case of `#define`.

The main issue here is that whitespaces are being highlighted as part of the item in which they're used, and that some highlighters are working too greedy though.

**Comment by laelath** [comment]
Further adding to this mystery, I've found that running `add-highlighter window/ regex '\s+' 0:Whitespace` from the prompt works as expected, but when adding it to your kakrc it doesn't appear to work.

**Comment by Screwtapello** [comment]
This doesn't address your actual issue, but...

> ...avoid using autoload directory that breaks the whole loading process for some reason

If Kakoune finds an autoload directory in `~/.config/kak`, it doesn't bother looking for the system-wide one. That way, if there's some default script that you *don't* want, you can symlink all the other scripts into your per-user autoload directory.

If you want to put custom scripts in your autoload directory *and* load all the defaults, you can symlink the entire system autoload directory into it:

    $ ls -ald ~/.config/kak/autoload/upstream
    lrwxrwxrwx 1 st st 24 Feb 13  2018 /home/st/.config/kak/autoload/upstream -> /home/st/Code/kakoune/rc

> The main issue here is that whitespaces are being highlighted as part of the item in which they're used, and that some highlighters are working too greedy though.

Yeah, that's pretty frustrating. I'm not sure how easy it would be to fix the "whitespace being hilighted as part of the content" issue, but if you can come up with a way to smarten up greedy highlighting, I encourage you to tweak the default C syntax highlighter and make a PR. You don't have to make highlighting perfect, @mawww is pretty good about merging even minor improvements.

> ...that running `add-highlighter window/ regex '\s+' 0:Whitespace` from the prompt works as expected, but when adding it to your kakrc it doesn't appear to work.

At the time kakrc is run, no windows exist yet, so you can't add highlighters to them. When you run the command from the prompt, you're running it in a window, so it works. You can try adding the highlighter in the global scope instead of window scope, but then it's likely to be overridden by regular syntax highlighting. Alternatively, you can add a hook that will run that command automatically at a later time. I think most scripts set up highlighting in a `WinSetOption filetype=.*` hook, so if you add your own such hook in kakrc, it should execute after file-type hooks.

**Comment by laelath** [comment]
Sorry, I should have specified that it was in a `WinCreate .*` hook, but it does work from `WinSetOption filetype=.*`
