### ISSUE TITLE
Backward `m`/`M`

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2425]
Hi,

I use <kbd>m</kbd> to move around a lot, but I have to use <kbd>t</kbd> / <kbd>f</kbd> to move backwards. Now that EOL characters are not treated differently than other characters, <kbd>a-m</kbd> could be freed up (it's basically <kbd>H</kbd><kbd>L</kbd>), and assigned to backwards <kbd>m</kbd>.

<kbd>a-M</kbd> is already free, for backwards <kbd>M</kbd>.

HTH.

**Comment by Screwtapello** [comment]
Just to clarify, the idea is that `m` searches forward for the next opening bracket, and then to the matching close bracket, while `<a-m>` would search backward to find a closing bracket, and then to the matching open bracket, right?

**Comment by Delapouite** [comment]
I'm glad you're proposing this change, I've been experimenting with this same idea on a private branch for quite a while and really enjoy it. Thanks!

`m` (and `M`) is a pretty misunderstood key. At first, and by reading its description, it seems that it only works when when you're on the exact opening (or closing) char to select to the matching char.

But it's actually more powerful than that since the effect of `m` is more "select the next sequence of enclosed in balanced chars." So yeah, it makes perfect sense to have a backward commands to do this operation the other way around.

Also I must confess that I have hardly ever used the current `<a-m>`, "merge consecutive selections". So I don't mind if it's relocated somewhere else. (`<a-_>` could be a good candidate)
