### ISSUE TITLE
'doc topic keyword' broken

### ISSUE THREAD

**Issue by robertmeta** [mawww/kakoune#2442]
Build latest Kakoune (93f913705abafbd7341e4fdd897bef5f6ef4c0dd was the commit hash I used, debug or release mode same behavior).  Open it, run `doc keys m`, get `No such anchor '992'`.  Even happens with autocompleted topics like `doc keys movement`. 

`doc mapping mappable-key` gives `No such anchor '229'` -- I presume this runs through all the docs.

**Comment by lenormf** [comment]
The number you see is the timestamp, I made a PR to make the error message display the actual anchor requested.

The anchor you're looking to reach in the `mapping` page is `mappable-keys` (mind the final 's').

There's no `m` anchor in the `keys` page, it used to work before because the second argument to the `doc` command was simply searched for in the entire page, but not anymore (anchors are basically section titles).

**Comment by robertmeta** [comment]
> The anchor you're looking to reach in the mapping page is mappable-keys (mind the final 's').

Same error with the s -- which was lost in cut/paste to github.

**Comment by lenormf** [comment]
`:doc mapping mappable-keys` works as expected here, what error do you get?

**Comment by robertmeta** [comment]
`No such anchor '229'` on 93f913705abafbd7341e4fdd897bef5f6ef4c0dd

**Comment by robertmeta** [comment]
Checked on second machine, same error.

**Comment by Screwtapello** [comment]
I get the same error as @robertmeta, from the same commit, even if I remove `~/.config/kak` (`kak -n` doesn't load the `:doc` command)

**Comment by Screwtapello** [comment]
I also get warnings in `*debug*`:

    /bin/sh: 5: [: 229: unexpected operator
    /bin/sh: 5: [: description: unexpected operator
    /bin/sh: 5: [: mappable-keys: unexpected operator

Ah, I think I see it:

    if [ "${range#*|}" == "$anchor" ]; then

The ol' `==`-is-a-bashism problem. Replacing it with `=` fixes the problem for me.
