### ISSUE TITLE
Feature request: `doc` command extensibility

### ISSUE THREAD

**Issue by andswitch** [mawww/kakoune#2466]
https://github.com/mawww/kakoune/blob/551021d6e5360c48c0d08da6464a2ee4081bb3d8/rc/core/doc.kak#L133-L160

`doc` only finds documentation that is bundled with kakoune. I think it would be cool if `doc` would also look inside user-specific directories somehow.. That could enable plugins to deploy their own documentation inside kakoune. For example, if a plugin could literally just symlink to its own README.asciidoc, users could have the plugin's documentation available from inside kakoune and don't have to go to the repository's github/gitlab page to read it.

**Comment by Delapouite** [comment]
Yes. Related to https://github.com/mawww/kakoune/issues/2402

**Comment by alexherbo2** [comment]
Yep, though I’m a bit concerned by the implementation.

The most obvious way would be to go with files, but it will not provide the flexibility that Kakoune provides naturally.

The entire Kakoune system works file-less – except color-schemes, but I would like it changes too; so it makes sense to provide a way to document without the need of a file.

It could be done through an option – implemented by [doc.kak] – where extensions could tap into.

This way, we would not be bound to files necessarily, or a certain file structure specifically – which I was disagreeing in #2402.

[doc.kak]: https://github.com/mawww/kakoune/blob/master/rc/core/doc.kak

**Comment by negativedensity** [comment]
I like the idea of having an option. It could be an option that is similar to completion lists. Then plugins can simply add their docs there. Personally I would prefer not to put the actual documentation text in the list, because it's a waste of memory. Something like a str-to-str map would be already fine I guess. Where the key is the topic and the value is the path to the doc file.

**Comment by alexherbo2** [comment]
@negativedensity Like https://github.com/mawww/kakoune/issues/2402#issuecomment-425231865?

**Comment by negativedensity** [comment]
@alexherbo2 Something like this:

```bash
decl -docstring %{
    Str-to-str map of docs (keywords to commands).
} str-to-str-map docs

decl -hidden str currentdoc

define-command -params 1..2 -docstring %{
    Render documentation of %arg{1} and jump to %arg{2}
} my-doc %{
    evaluate-commands %sh{
        # Instead of hardcoding the path, get the value at key $1 from $kak_opt_docs
        # I don't know how to do this, that's why it's hardcoded in this example :)
        echo "my-plugin-doc"
    }

    # taken from rc/core/doc.kak
    evaluate-commands %sh{
        if [ $# -eq 2 ]; then
          jump_cmd="doc-jump-to-anchor '$2'"
        fi
    	echo "evaluate-commands -try-client %opt{docsclient} %{ doc-render ${kak_opt_currentdoc}; ${jump_cmd} }"
    }
}

define-command enable-my-plugin %{
    set-option -add global docs my-plugin=my-plugin-doc
}

define-command -docstring %{
    Plugin decides the location of the documentation
} my-plugin-doc %{ evaluate-commands %sh{
    echo "set-option window currentdoc '$kak_config/doc/my-plugin-doc.asciidoc'"
} }
```

**Comment by mawww** [comment]
I'd be more tempted to keep it simple and just add say `%val{config}/doc/` to the paths on which `doc.kak` looks for documentation. Whats concerning me most is that now we have to symlink two files (the plugin.kak and the doc.asciidoc) instead of one, but I was thinking plugins could just provide a Makefile (or a shell script) that would do that by default (or a plugin manager would do the same: symlink all .kak files inside `$kak_config/autoload`, symlink *.asciidoc or doc/*.asciidoc into `$kak_config/doc/`)

**Comment by Screwtapello** [comment]
How about keeping it *really* simple and treating all `.asciidoc` files in the autoload directory as documentation, just like all `.kak` files in the autoload directory are treated as scripts. Then nobody needs a Makefile or a plugin manager at all.

Going even further, we could come up with a separate file-extension for colorschemes (`.kak-color`? `.kolor`? `.kcs` for Kakoune Color Scheme?) and then we wouldn't need a dedicated "colors" folder either. Then again, there probably aren't that many colorschemes that also include a plugin, or also include documentation, so maybe that isn't necessary.

**Comment by andreyorst** [comment]
> How about keeping it really simple and treating all .asciidoc files in the autoload directory as documentation, just like all .kak files in the autoload directory are treated as scripts. Then nobody needs a Makefile or a plugin manager at all.

I'd rather avoid that. As a creator of some plugins for Vim, and currently for Kakoune, I feel that we need a strong view of what should be treated as loaded part of plugin files, such as scripts, and docs, and what should be ignored, because it is meaningless to have it inside editor, like readme, or license files for example. Therefore plugin maintainer should follow simple concept of plugin layout, that we're discussing at #2402, so plugin manager creators, could opimize such a complex task - maintainance of plugins within the editor. It is sound simple, but acctually there are many routes that can lead to errors in some ways, I've mentioned some of them in [this comment](https://github.com/mawww/kakoune/issues/2402#issuecomment-426613403).

> Going even further, we could come up with a separate file-extension for colorschemes (.kak-color? .kolor? .kcs for Kakoune Color Scheme?) and then we wouldn't need a dedicated "colors" folder either. Then again, there probably aren't that many colorschemes that also include a plugin, or also include documentation, so maybe that isn't necessary.

But I like the idea for separate extension for colorschemes, just to simplify the deducing process of the type of script - is it a script or a colorscheme. So yeah, not having a separate folder for colorschemes, is generally a great idea from my point of view. And the same applies for the documentation. I'd rather would like to inject path to particular documentation in some str list option in Kakoune, to have an ability to load documentation only for those plugins that were actually loaded.

**Comment by TeddyDD** [comment]
> I'd rather would like to inject path to particular documentation in some
str list option in Kakoune

This. As a user I don't want to deal with symlinking anything to magic
directories like docs/autoloads/colors. Kakoune can still use those, just
give me an option so I can point Kakoune to my custom directory or command
that loads resources at runtime (like source).

**Comment by andreyorst** [comment]
This also makes use of the same mechanism that is used for `path` and `clang_options` options so can be considered common practice in Kakoune
