### ISSUE TITLE
[Bug] colorscheme renders differently when opened via built-in tmux cmds

### ISSUE THREAD

**Issue by vinnyA3** [mawww/kakoune#2528]
### Steps: 
  * Start Tmux
  * Start Kakoune
  * Open Tmux pane / window with buffer via:
    ```
    tmux-new-horizontal
    tmux-new-vertical
    tmux-new-window
    ```

### Outcome: 
Kakoune doesn't render the correct colorscheme for windows created via tmux commands ... 

![kakoune-issue](https://user-images.githubusercontent.com/11083531/47600048-f68cc380-d988-11e8-9cfe-05bb8b1a7416.gif)
*screenshot: color disparity between original (top pane) and new (bottom)*

### Expected: 
A consistent theme across all Kakoune + Tmux created pane / windows.

----

I am currently using the base16-color-themes, but using the built-in schemes (ie. tomorrow-night, gruvbox) yield similar results.

**Comment by lenormf** [comment]
Have you tried following the instructions from the FAQ?

https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#im-using-tmux-and-colors-look-weird

**Comment by vinnyA3** [comment]
I have not.  I am currently using the version supplied in the Void repos--which doesn't come with the contrib dir.  I will try building from source to see if that works.  The colors render just fine in the original window, which is odd :/

**Comment by Screwtapello** [comment]
It's an unfortunate interaction with the way tmux works. Kakoune use a standard method to set custom colours, but that method affects the entire terminal. Because tmux can display multiple panes side-by-side, it can't use that same method to set custom colours, or else the programs running in each pane would reset each others' colours all the time. Instead, tmux uses a not-standard-but-widely-available method to set custom colours, which works beautifully but requires a little end-user customisation for most users.

**Comment by lenormf** [comment]
You just need to tweak the `tmux` terminfo, as documented in the FAQ, it's not a bug.

Contact @mawww directly if you want to make a donation.

**Comment by vinnyA3** [comment]
Will do!  I think I got it working now (the colorscheme is now working across splits).  Thanks for your help !
