### ISSUE TITLE
Column highlighter bleeds into status line

### ISSUE THREAD

**Issue by Muffindrake** [mawww/kakoune#2562]
### Steps
- `addhl window/ column 81 red+r` (set to `$COLUMN + 1`)
- attempt to perform an upwards/downwards screen scrolling motion
### Outcome
- observe red first cell in status line
### Expected
- no blood on my status line
### Screenshots
![1541747244](https://user-images.githubusercontent.com/19580030/48248169-8ce3cf00-e3f6-11e8-86b6-a1667240dd4a.png)
(cursor on bottom of screen, about to scroll the screen by moving downwards)
![1541747247](https://user-images.githubusercontent.com/19580030/48248192-a08f3580-e3f6-11e8-9823-89d595198e9a.png)
(scrolling was performed, red cell appears in status line)
![1541747248](https://user-images.githubusercontent.com/19580030/48248205-ad138e00-e3f6-11e8-8abd-56df99944cbb.png)
(cursor was moved back one line upwards, red cell disappears)

### Additional info
rxvt-unicode, kak v2018.10.27-29-g8c2c3d27

**Comment by Screwtapello** [comment]
I can reproduce in gnome-terminal with `$TERM` set to `xterm-256color` and `vte-2017`, and in xterm with `$TERM` set to `xterm-256color`.

**Comment by mawww** [comment]
Good find !

This is actually the interaction of two separate bugs:

* we display column highlighters even if they go past the window end, which does not usually appear because they end up wrapping on next line, which gets then overwritten with that line content.
* on scrolling we trigger display twice, the second redisplay is spurious, however as the status line is known to be the same, we do not repainting, not overdrawing the column that bled into that line.

I'll get those fixed, cheers.
