### ISSUE TITLE
kak opens unwanted scratch buffer

### ISSUE THREAD

**Issue by vivien** [mawww/kakoune#2575]
There are 2 situations where kak opens a scratch buffer where it shouldn't:

1. `kak -e 'grep foo'`

Only the `*grep*` buffer is expected, but `:bn` will iterate over a `*scratch*` scratch buffer.

2. `ls | xargs kak`

Kak shows a `*stdin*` scratch buffer but there's already open file buffers.

_(Note that it'd be neat if kak could exit right away if xargs gives no files to open or grep shows no results, but this is orthogonal to the issue.)_

Shouldn't we have a general rule saying open a scratch buffer if and only if there are no buffers already created?

(If we don't want kak to be smart here, a `--[no-]scratch` option might be intuitive as well.)

**Comment by occivink** [comment]
Regarding 1. you can use `-E` instead of `-e`. This will execute grep before the client is created, and so it doesn't need to create a scratch buffer.

**Comment by vivien** [comment]
Great thank you, 1. fixed! For 2., maybe `isatty()` returns 1, but there must be nothing to read on stdin.

**Comment by mawww** [comment]
As @occivink said, `-E` will work as this can run in a context with no buffer present. `-e` is generally used to do initial work on the buffer that was just opened, and hence runs in a context where a buffer is expected, in the case no filename has been provided, Kakoune creates a scratch buffer. I think this behaviour is reasonable, and as you said, that 1. is fixed.

Regarding 2., *stdin* is a fifo buffer, which means we do not read the full content immediately, to handle the case where data is comming progressively (`make | kak` for example). This means there might be an arbitrary amount of time between starting Kakoune, and when the other side of the pipe closes it, at which point we can check if some data was received or not. If we do remove the `*stdin*` buffer then (because no data read from it), I think it would be more surprising to the user than keeping it. That said, seems xargs connects the command stdin to /dev/null, so maybe we can detect that.

**Comment by vivien** [comment]
If the implementation is simple enough and easy to maintain, it might be an interesting behavior. It depends if you expect `true | xargs kak` to quit right away or keep an unfed *stdin* buffer open.

In the meantime, I workaround 2. with `command | xargs kak -e 'delete-buffer *stdin*'`, which isn't that bad ;-)

**Comment by mawww** [comment]
@vivien If you want to run Kakoune as a non-interactive filter, using the `-f <keys>` switch will do.

**Comment by vivien** [comment]
Usually xargs is used to pass a list of files filtered from another command, e.g. `git diff --check | cut -d: -f1 | sort -u | xargs kak` which is much nicer to write inline than subshell invokations like `kak $(git diff --check | cut -d: -f1 | sort -u)`.

But the `-f` option is really nice though, thank you! Out-of-scope: would it make sense to support multiple commands as in #2576 for this option as well? I intuitively tried `cat file | kak -f 'sfoo<ret>cbar' -f 'stoto<ret>ctata'` (where I guess each _keys_ would be wrapped by `%` and `<esc>`.)

**Comment by mawww** [comment]
The problem with xargs is that I cannot see any way for Kakoune to guess if the fact that stdin is not a tty is an artifact of running with xargs, or a real buffer we want to read from (except if we were looking at the parent process name, but that would be really ugly to have a list of parent process to ignore stdin from...).

Regarding -f, could make sense to support multiple ones, but that requires a refactoring of the option parsing system, for something that is not expected to be very commonly used, so I am not sure if its worth it.

**Comment by Screwtapello** [comment]
> I cannot see any way for Kakoune to guess if the fact that stdin is not a tty is an artifact of running with xargs, or a real buffer we want to read from...

It's not really practical to have a whitelist of "commands that can pipe to stdin", but I think it's practical to have a blacklist of "files we won't bother reading from". If stdin is not a TTY:

- open `/dev/null` ourselves
- Call `fstat(2)` on stdin and on our `/dev/null` descriptor, obtaining two `stat` structs.
- If the `st_rdev` fields of both structs contain the same value, they both represent `/dev/null` and there's no point opening a scratch buffer to read from stdin.

`/dev/null` is probably the only source that *needs* to be on the blacklist. We could potentially add `/dev/zero` and `/dev/full` since they produce infinite streams of NUL bytes, but maybe somebody really wants a lot of NULs in a buffer.

**Comment by vivien** [comment]
I'm scared this can be hacky or non-KISS which seems out-of-scope for Kakoune. There's no obvious way to differ `/dev/null` from a valid EOF from stdin, thus I think sticking with `xargs kak -e 'db *stdin*'` is preferable and simple enough to understand what's going on. (one more reason to support multiple `-e` args though ;-))

**Comment by mawww** [comment]
Ok, so I guess this issue can be closed ?

**Comment by vivien** [comment]
Sure, thank you.
