### ISSUE TITLE
buffers shared between clients?

### ISSUE THREAD

**Issue by anderspapitto** [mawww/kakoune#2647]
In emacs, all clients connected to a server share buffers, and the same buffer can be edited from multiple clients at once, with changes made from any client being reflected live in all other clients.

This is largely a convenience. Without this feature, if I accidentally open the same file in two different terminals, edit it in two different places, and then try to save both edits, I'll have conflicts. With this feature, the shared buffer contains all the (unsaved) edits at all times, so there is no conflict.

Is this possible with kakoune? I can't find any mention of it in the docs, and when I try it out, it seems that buffers aren't visible to other clients.

**Comment by Screwtapello** [comment]
Kakoune works the same way: all clients connected to a session share the same set of buffers. However one possible difference with Emacs is that by default `kak` starts a new session, instead of reconnecting to an existing one, which would explain the behaviour you see.

You can start a new daemonised session with `kak -d -s mysessionname`, and then make clients connect to it with `kak -c mysessionname`, which should provide the behaviour you're looking for.

**Comment by Delapouite** [comment]
Or you can run the `:new` command from inside Kakoune to spawn a new client connected on the same server. But you're right about the doc, we definitely need to introduce something like a `:doc clients` page explaining that.

**Comment by anderspapitto** [comment]
awesome, that's exactly what I was looking for
