### ISSUE TITLE
[Discussion] balanced strings, escaping

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2664]
Hi everyone. Right to the point.  When I was implementing "better" version of `ctags-search` I've realized that there's no way to have an opening `{` in `%{...}` expansion. That leads to all kinds of tricks to workaround the problem:
- using non-standard separators, like `%§...§`
- using escaping quotes hell machine, like in my #2625 pull request
  - where I still need to define this construction: `open='{'; close='}'` variables just to escape the only one of them (which is `$open`) with `sed`. Which is another trick to have a `{` available inside `%{}` while remaining balanced.
- possible other workarounds that I didn't seen yet, but others may know and use.

Generally when I see a suggestion to use different separator for base string to have a certain separator inside a string, makes me think that this is really the weak point in string parser.

When I was trying to build a parser for my Vim snippet manager, I've wrote a script that could understand all kinds of strings, like `${{}}` but that' didn't worked for me, because of the same unbalanced problems as in kakoune, So I've decided that inner `{` and `}` must be escaped with `\`. So this `${1:\}abc\{def}` still was a valid string.
(Screenshot of [early prototype](https://user-images.githubusercontent.com/19470159/50507823-2727d100-0a90-11e9-922d-f50b5a8c3628.png) but escaping isn't implemented yet.)

There was a pull request for this feature I think #2046, which makes me wonder, why `\` escaping wasn't adopted in the first place? It feels so much usable, and reliable, compared to using non-standard punctuation separators, and worry every time when user wants to use this separator in some string for some reason.

**Comment by Screwtapello** [comment]
The reason `\` escaping wasn't adopted in the first place is [here](https://github.com/mawww/kakoune/issues/2046#issuecomment-388960984): Regexes use `\` for escaping, and since Kakoune uses regexes a *lot*, a deeply-nested regex (imagine an `execute-keys` inside a `try` inside a `define-command` inside a `hook`...) would have ridiculous quoting. The fact that `%{}` strings don't allow any escaping is a significant ergonomic boost for humans writing Kakoune script.

It's a bit of a drag for computers writing Kakoune script, of course (like the old `evaluate-commands %sh{}` trick), but the `nonstandard separators` syntax is a nice compromise:

```sh
kakoune_quote () {
    printf "%%@%s@" "$(printf %s "$*" | sed -e "s/@/@@/")"
}
```

**Comment by mawww** [comment]
The reason there is no escaping in balanced strings is that they are pretty often nested (that is their primary use case), if they were escapable, then we would have to double up the escape character for each nesting level.

```
define-command name %{ evaluate-commands -draft %{ echo %{ here we need 3 levels of escaping, and any literal \ is written with six \ } } }
```

Non balanced strings support escaping by doubling up the separator, this was chosen because it does not conflict with the common backslash escaping, and as we can choose various non-balanced separator, we can avoid having to double-double-double-up characters if we have 3 nested strings by using different separators for each level (and doubling up each at the relevant level).

Its not fully satisfying, and there are some cases where it gets ugly, but thats the best we could come up with after long discussions and reflections on how to fix the previous ad-hoc escaping.

**Comment by andreyorst** [comment]
Understood. Thanks for the explanations
