### ISSUE TITLE
problem using options in shell tests

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2682]
I've written a simple test:

```sh
declare-option int cnt 0

define-command test %{
    set-option -add global cnt 1
    nop %sh{ (
        while true; do
            if [ $kak_opt_cnt -eq 0 ]; then
                printf "%s\n" "evaluate-commands -client $kak_client set-option -add global cnt 1" | kak -p $kak_session
            else
                printf "%s\n" "evaluate-commands -client $kak_client set-option -add global cnt -1"  | kak -p $kak_session
            fi
            printf "%s\n" "evaluate-commands -client $kak_client echo -debug 'cnt = %opt{cnt}'"  | kak -p $kak_session
        done
    ) > /dev/null 2>&1 < /dev/null & }
}
```

I suppose it should work like so:
```
cnt = 0
cnt = 1
cnt = 0
cnt = 1
cnt = 0
cnt = 1
cnt = 0
cnt = 1
...
```

instead we grow to infinity:
```
cnt = 0
cnt = -1
cnt = -2
cnt = -3
cnt = -4
cnt = -5
cnt = -6
cnt = -7
cnt = -8
cnt = -9
cnt = -10
cnt = -11
...
```

Is it supposed to work like so? I was trying to measure amount of parallel functions that my plugin calls from another function, and this is the only way how it could be done I suppose, but it isn't working

**Comment by andreyorst** [comment]
I've also tried to do this:
```sh
declare-option int cnt 0

define-command test %{
    set-option -add global cnt 1
    nop %sh{ (
        while true; do
            sleep 1
            [ $kak_opt_cnt -eq 0 ] && exit
            printf "%s\n" "evaluate-commands -client $kak_client echo -debug 'cnt = %opt{cnt}'" | kak -p $kak_session
        done
    ) > /dev/null 2>&1 < /dev/null & }
}

```

This will loop forever until `cnt` will become `0`, which will never happen.
Log would look like so:
```
cnt = 1
cnt = 1
cnt = 1
cnt = 1
cnt = 1
cnt = 1
...
```
But after `:set-option global cnt 0` loop still works, but log shows:
```
cnt = 1
cnt = 1
cnt = 1
cnt = 1
cnt = 1
cnt = 1
cnt = 0
cnt = 0
cnt = 0
...
```

**Comment by Screwtapello** [comment]
> instead we grow to infinity

When the shell block begins, `$kak_opt_cnt` is set according to the current value of the option inside Kakoune. Once the shell block has started, Kakoune can no longer update `$kak_opt_cnt`, so you'll never see the results of your `printf | kak -p` unless you exit the shell block and enter it again.

> ... loop still works, but log shows:

Same deal. The loop keeps running, because it's checking *the script's* copy of `$kak_opt_cnt`. The log shows the correct answer, because you send a message to Kakoune telling it to log *its own* copy of the current value, not the script's copy.

**Comment by Screwtapello** [comment]
How about:

- `task-operator` creates an empty, temporary file with `mktemp`, and passes the path to `some-task`.
- `some-task` increments a counter when it starts, and decrements the counter when it finishes.
- if the counter == 0 after decrementing, `some-task` removes the temporary file.
- `task-operator` does `while [ -e "$FLAG_FILE" ]; do sleep 1; done`

**Comment by andreyorst** [comment]
yeah, creating a file was an option, but there are many instances runnibg simultaneously, which results into `task-operator` watching variable amount of files, or `some-task` functions block each other unable to create files.

**Comment by Screwtapello** [comment]
Creating a file-per-task is very expensive to check (you have to count the number of files in a directory every time). It's also unnecessary, because you already *have* a way for the various tasks to communicate with each other: they can all write to the counter variable inside Kakoune. The only thing that can't read from the counter variable inside Kakoune is the `%sh{}` block inside `task-operator`.

So `some-task` does all the interaction with the counter inside Kakoune, because it can, and when it's done it makes a single filesystem change to notify `task-operator` that everything's done. 

Checking for the existence of a single file is... not *extremely* cheap, but since the same file is being checked repeatedly it should be cached.

**Comment by andreyorst** [comment]
Ain't working. This way if I create file at the beginning, and run a function one by one, the first one which will exit will destroy the file.

**Comment by andreyorst** [comment]
I guess the easiest way is to write amount of running functions to temporary file and check it's contents.

**Comment by andreyorst** [comment]
Or if there were a way to make kakoune output option value to the shell directly

**Comment by Screwtapello** [comment]
> Ain't working. This way if I create file at the beginning, and run a function one by one, the first one which will exit will destroy the file.

That's why I said to use a counter and only remove the file when the counter reaches 0, instead of always removing the file.

**Comment by andreyorst** [comment]
and the problem is 
1. create file
2. start task  
     - increment cnt
    - do nothing
    - decrement cnt
      - cnt is 0. rm file
3. start task
    - increment cnt
    - do long thing
    - decrement cnt
      - cnt is 0 but there's no file
4. wait for file
    - there's no file. exit

Node 2 and node 3 are working in parallel, but launched one after another. And if node finishes before node 3 starts, which may actually happen, cnt will become zero and file will be removed. This will happen a lot because in task sequence there are lots of tasks which are really fast

**Comment by andreyorst** [comment]
This could work, but I think that I'll give up on this method and rework the whole thing. Since it is too hacky it indicates that there should be a better way of doing it, but I need to go back and rethink. But thanks for the input anyways, I think it will come in handy some day
