### ISSUE TITLE
paste commands and tmux buffer

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#2747]
In my experience none of the paste/pipe commands (`!`, `<a-!>`, `|`) work correctly when pasting from tmux buffer. For example copy any path (text with `/` character) into tmux buffer like so:
```
<a-|>tmux setb -b kak "/some/path"<ret>
```
then trying to paste
```
!tmux pasteb -b kak<ret>
```
end up with search prompt filled with `some/path`

**Comment by Screwtapello** [comment]
`tmux paste-buffer` causes the contents of the named buffer to be sent to Kakoune as though it were typed at the keyboard, which is why it ends up in the search prompt. In contrast, commands like `|`, `!` and `<a-!>` expect the given command to print information to stdout.

I think you want `tmux show-buffer` rather than `tmux paste-buffer`.
