### ISSUE TITLE
Kakoune changes terminal transparency

### ISSUE THREAD

**Issue by shumvgolove** [mawww/kakoune#2779]
After quiting Kakoune my terminal background becomes opaque.

![1](https://user-images.githubusercontent.com/37271604/54157267-e4935500-443f-11e9-9c97-9406957a7a6f.gif)

### Configuration
- WM: **Sway**
- Terminal: **st**

**Comment by Screwtapello** [comment]
How do you make `st` transparent in the first place? I don't see any transparency option in the manual page.

**Comment by shumvgolove** [comment]
[This.](https://st.suckless.org/patches/alpha/)

**Comment by Screwtapello** [comment]
Does running `/usr/bin/reset` also disable transparency?

**Comment by shumvgolove** [comment]
Running `reset` doesn't remove transparency.

**Comment by Screwtapello** [comment]
As far as I know, resetting the terminal is the only unusual thing Kakoune does when it exits, and it certainly doesn't know anything about transparency.

If you can reproduce the problem inside a tool like `script`, and `cat`ing the resulting recording also reproduces the problem, you should be able to figure out what causes that behaviour by deleting chunks of the recording until it stops happening.

**Comment by shumvgolove** [comment]
Oops, sorry. Missclicked.

**Comment by shumvgolove** [comment]
So I was able to reproduce the issue using `cat`ing to recorded script. Deleting `;^G` character solves issue.

[typescript.txt](https://github.com/mawww/kakoune/files/2956219/typescript.txt)

**Comment by Screwtapello** [comment]
There's three control sequences in that file. Converted to printf syntax, they are:

- `\e[?1004l` - xterm's "Don't send FocusIn/FocusOut events" sequence
- `\e[?1002l` - xterm`s "Don't use Cell Motion Mouse Tracking" sequence
- `\e]104;\007` - the "reset palette" sequence

The first two are very common and straight-forward sequences, and unlikely to be the problem. The last one is a bit stranger. If I'm reading [ctlseqs.html](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands) correctly, it's normally used as:

    $ printf '\e]104;5\007'

...to reset palette entry 5 (the number between the `;` and the `\007`), or:

    $ printf '\e]104\007'

..to reset the entire palette (with no `;` and no number). Meanwhile, [the sequence Kakoune prints](https://github.com/mawww/kakoune/blob/master/src/ncurses_ui.cc#L289) (also [here](https://github.com/mawww/kakoune/blob/master/src/ncurses_ui.cc#L1255)) does have the ';' but does not have a number.

I'm pretty sure that terminals should ignore redundant `;` characters, but since `st` is so minimalist maybe its escape-sequence parsing is not very robust. Please try each of the following and let me know whether they break your terminal transparency:

    $ printf '\e]104\007'
    $ printf '\e]104;\007'
    $ printf '\e]104;;\007'

**Comment by shumvgolove** [comment]
`$ printf '\e]104;\007'` and `$ printf '\e]104;;\007'` breaks terminal transparency. And thank you for your help, much appreciate it.

**Comment by alexherbo2** [comment]
@mawww It is also at https://github.com/mawww/kakoune/blob/master/src/ncurses_ui.cc#L1255
