### ISSUE TITLE
Change cursor color in insert mode

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2798]
How about changing the cursor color in insert mode?

I just tested [λiquid] a few minutes and noticed they change the cursor color from blue in navigation mode to green in insert mode.  The feeling is quite great.

[λiquid]: https://github.com/mogenslund/liquid

**Comment by occivink** [comment]
This is something you can already achieve easily with hooks like
```
hook global ModeChange ".*:normal" %{ face ... }
hook global ModeChange ".*:insert" %{ face ... }
```
I don't think it should be on by default

**Comment by andreyorst** [comment]
NeoVim introduced an i-beam cursor for insert mode, and it was great way to distinguish insert mode from normal mode without looking to statusbar. I've tried to use colors for that in Kakoune, but found it to be kind of distraction.

**Comment by mawww** [comment]
This is already possible with hooks, as shown by @occivink, I dont plan to make that core. Regarding i-beam, once/if we move away from ncurses, then we might have enough control to do that, but I suspect it will be available through hooks as well.

**Comment by Luflosi** [comment]
How can I change the cursor shape using hooks? I couldn't find anything related to the cursor shape in the commands documentation. Or is this currently not possible?

**Comment by Screwtapello** [comment]
Kakoune is based on the ncurses library, and ncurses only allows the cursor shape to be set to "hidden", "normal" (usually an underline) and "very visible" (usually a block). Since Kakoune supports multiple simultaneous selections and therefore multiple cursors, Kakoune generally keeps the ncurses cursor "hidden" and draws its own "cursor" by changing the foreground and background colour of a cell.

**Comment by Luflosi** [comment]
Thanks for the explanation.
