### ISSUE TITLE
Wayland: Global hook to yank operations with wl-copy waits command to finish forever

### ISSUE THREAD

**Issue by hacktivista** [mawww/kakoune#2818]
### Steps
Copy the following to your `kakrc`:
```
# Use system's clipboard
hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_main_reg_dquote" | wl-copy
}}
```
reload the kakoune config and yank something

### Outcome
kakoune says `waiting for shell command to finish` until you press Ctrl+C

### Expected
Should not expect command to finish, because it contains the copied contents.

Related to #2325

**Comment by moopling** [comment]
I think this is related to wl-copy actually continuing to run in the background. On yanking kakoune freezes, and the buffer is copied to the system clipboard, but if you C-c (ending the process and unfeezing kakoune) the system clipboard clears.

**Comment by hacktivista** [comment]
Yes, it is because of that. As I said my expected result is "Should not expect command to finish, because it contains the copied contents."

**Comment by laelath** [comment]
I don't have a wayland compositor installed to test, but I think this would work?
```
# Use system's clipboard
hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_main_reg_dquote" | wl-copy > /dev/null 2>&1 &
}}
```

**Comment by hacktivista** [comment]
Yes it does :D!! Posted it in the wiki, thanks!

Would be great if you explain why this works... I've tried running the process in background, but not with redirecting outputs, I don't grok it really.

**Comment by Screwtapello** [comment]
The `%sh{}` expansion runs a shell-script and collects its output, then waits for the script to exit. To prevent Kakoune from waiting for a long-running process, you need to:

- redirect stdout with `> /dev/null` so that the long-running process does not inherit the shell's stdout, and therefore the stdout Kakoune reads will be closed immediately when the shell exits
- redirect stderr with `2> /dev/null` (or if stdout is already redirected, `2>&1`) for the same reason
- run the process in the background with `&` so the shell exits 0 immediately instead of waiting for the long-running process to exit
