### ISSUE TITLE
Incorrect instructions re: eslint and kakoune in docs

### ISSUE THREAD

**Issue by jssee** [mawww/kakoune#2828]
As it stands right now, theres no way to get eslint + kakoune working in a sane manner (i.e. working on multiple projects with different eslint settings without configuring kakoune per project). The instructions should be clarified so that future potential users know this going in. It is a critical part of a modern web developers workflow, after all. 

#2314 goes into detail, but basically globally installed eslint wont use locally installed plugins, so if you follow the instructions in the documentation, **you will not have success**. 

Apparently there is a halfway solution that relies on $kak_buffile, but there is no documentation around it.

**Comment by mawww** [comment]
I am not familiar with eslint in general, but a trick might help:

I see eslint support --stdin and --stdin-filename, so setting the lint command with the following hook might help:

```
hook global BufSetOption filetype=javascript %{
    set buffer lintcmd "path/to/eslint --stdin --stdin-filename '%val{buffile}' <"
}
```

The `<` at the end will ensure that the `eval "$kak_opt_lintcmd '$dir'/buf${extension}"` command from lint.kak ends up redirecting the temporary file to stdin instead of passing it as an argument, and the --stdin-filename parameter will point eslint to the correct file path, hopefully helping it get the correct project settings.

Not tested at all, but might be a good direction to fix your problem.

**Comment by jssee** [comment]
@mawww unfortunately your solution did not work, but it did send me on the right path i think. I was able to do more digging, and came upon this solution: 

```
hook global WinSetOption filetype=javascript %{
	set window lintcmd 'run() { cat "$1" | npx eslint -f ~/.config/kak/eslint-kak.js --stdin --stdin-filename "$kak_buffile";} && run '
	lint-enable
	hook buffer BufWritePost .* % {
 	  lint
	}
}
```
I wonder if there a way to clean this up some more, open to suggestions.

**Comment by lenormf** [comment]
Related #2336.

**Comment by losnappas** [comment]
Regarding this... The `lintcmd` is confusing to me.

This works: `set window lintcmd 'run() { cat "$1" | phpcs --standard=WordPress-Core --report="emacs" --stdin-path="$kak_buffile" - | sed "s/ - /: /" ; } && run'`

I would have assumed that `phpcs --standard=WordPress-Core --report="emacs" | sed "s/ - /: /"`, or some slight alteration, would have done the job. Declaring a function on the fly like this seems bizarre. Why doesn't it work without it? How is the file inputted into the thing. And the x:x:x formatting... Well, I would've thought using CSV format could've been a more popular thing. Or copying emacs.

And, uh.. kinda on the thought: `lintcmd` is for linting, `formatcmd` is for fixing, right? A `:doc lintcmd` would've been nice.

**Comment by Screwtapello** [comment]
> Declaring a function on the fly like this seems bizarre. Why doesn't it work without it?

Most lint programs check the filenames specified on the command-line, so `lint.kak` writes the buffer to a temporary file, then adds the filename to the end of `lintcmd` to run it. If you add a filename to the end of a pipeline, you wind up with something like:

    my-lint-program --some-option | sed "s/foo/bar/" /path/to/file

...which doesn't work — the file-to-check should be passed to `my-lint-program` rather than `sed`. Defining a function and then immediately invoking it means the file-to-check is an argument to the function, and so it can be used as `$1` wherever it's needed.

> And the `x:x:x` formatting... Well, I would've thought using CSV format could've been a more popular thing. Or copying emacs.

`file:line[:column]: message` has been the standard output format for compilers probably since the early days of Unix, so it's no wonder that editors expect it, and no wonder that other tools that emit diagnostics also produce it. If `phpcs` has an "emacs" format that doesn't include the final colon before the message, that seems like a bug in 'phpcs', but maybe it's worth teaching Kakoune to not be so strict?

**Comment by losnappas** [comment]
I see, thanks.

>  If phpcs has an "emacs" format that doesn't include the final colon before ...

Seems to use a dash.

```
aaaaa.php:1:1: error - Class file names should be based on the class name with "class-" prepended. Expected class-myclass.php, but found aaaaa.php.
```

phpcs comes with a gorillion report formats but none of them were a match for kakoune format. Didn't know about the compiler things you mentioned.

```
Print either the "full", "xml", "checkstyle", "csv"
                "json", "junit", "emacs", "source", "summary", "diff"
                "svnblame", "gitblame", "hgblame" or "notifysend" report
                (the "full" report is printed by default)
```

**Comment by Screwtapello** [comment]
Ah, I see what's going on - Kakoune expects an extra slightly-non-standard "kind" field at the beginning of the message ("error", "warning", etc.). Possibly Kakoune should be more lenient about that, but it's easy enough to work around.

Some lint programs expect the input on standard input, some expect a command-line argument with the path to the file on disk. Whichever way around Kakoune works by default, it's going to be awkward to make it work with linters of the other type.

**Comment by hacktivista** [comment]
Here is how I'm doing it:

```
# Eslint linter
hook global WinSetOption filetype=javascript %{
  declare-option str eslint_path
  declare-option str eslintrc_path

  evaluate-commands %sh{
    exec 2>/dev/null # silence STDERR
    eslintrc_path=$(ls -1 .eslintrc* || (grep -q 'eslintConfig' package.json && echo 'package.json'))
    echo "set-option buffer eslintrc_path '$eslintrc_path'"
    if [ -n "$eslintrc_path" ]; then
      if [ -x ./node_modules/.bin/eslint ]; then
        echo 'set-option buffer eslint_path "node_modules/.bin/eslint"'
      elif command -v eslint > /dev/null 2>&1; then
        echo 'set-option buffer eslint_path "eslint"'
      else
        echo "fail 'No eslint available'"
      fi
    else
      echo "fail 'No eslintrc config file available'"
    fi
  }

  set buffer lintcmd "%opt{eslint_path} --config '%opt{eslintrc_path}' --format ~/.config/kak/eslint-formatter.js --stdin-filename '%val{buffile}' --stdin <"
  lint-enable
  hook buffer BufWritePost .* lint
}
```

For some reason though the fail errors are not being evaluated (halp plz)... but everything else is working.

`~/.config/kak/eslint-formatter.js` is a copy of `eslint-formatter-kakoune`

**Comment by eraserhd** [comment]
I just ran across this issue, which is that Emacs' flycheck has identical behavior: flycheck/flycheck#1087 .

**Comment by mawww** [comment]
I think the same rationale as flycheck applies here, auto selecting npm installed dependency binaries is out of scope of the base lint script.

And seems the first issue got solved.

Regarding error message parsing, another issue could be opened if requiring a `kind` is too strict.

**Comment by ismay** [comment]
For people encountering this issue whilst trying to set up eslint and prettier for kakoune, this worked well for me:

```
hook global WinSetOption filetype=javascript %{
  set-option window lintcmd "npx eslint --format=~/.config/kak/eslint-formatter-kakoune/index.js --stdin --stdin-filename=%val{buffile} <"
  set-option window formatcmd "npx prettier --stdin-filepath=%val{buffile}"
}
```

[npx](https://www.npmjs.com/package/npx) is an easy way to run eslint from a local node_modules or from a central cache. The formatter I took from [here](https://github.com/Delapouite/eslint-formatter-kakoune/blob/master/index.js) so that it's colocated with my kakoune config and I don't have to install it.
