### ISSUE TITLE
Syntax highlighting for SH (equals sign)

### ISSUE THREAD

**Issue by paualberto** [mawww/kakoune#2832]
Hi! This is a quick and easy one.

I tried to write `ansible-playbook --extra-vars="some stuff"`... and noticed that `vars=` is highlighted as if it was a variable assignment. Probably wouldn't have noticed if all the parameter was highlighted instead of only the last word.

**Comment by Ordoviz** [comment]
How can we distinguish equal signs in variable assignments from other equal signs? Neovim does it by checking what is allowed to go after an equal sign so that it can be a variable assignment (I suppose). The following snippet is from [`sh.vim`](https://github.com/neovim/neovim/blob/master/runtime/syntax/sh.vim#L412):

```vim
syn match  shVariable	"\<\([bwglsav]:\)\=[a-zA-Z0-9.!@_%+,]*\ze="	nextgroup=shVarAssign
syn match  shVarAssign	"="		contained	nextgroup=shCmdParenRegion,shPattern,shDeref,shDerefSimple,shDoubleQuote,shExDoubleQuote,shSingleQuote,shExSingleQuote,shVar
```

This might be too complicated though for such a minor issue.

But at least `\w` should be changed to `\S` to highlight the whole WORD.

https://github.com/mawww/kakoune/blob/b6f4985c10590683b11669b36d8058c7e36f8b1f/rc/filetype/sh.kak#L49
