### ISSUE TITLE
Format not working correctly

### ISSUE THREAD

**Issue by losnappas** [mawww/kakoune#2843]
### Steps 
Run format on a php file with `phpcbf -q --standard=WordPress-Core --stdin-path="$kak_buffile" -`.

Here is the problem in [formatter.kak](https://github.com/mawww/kakoune/blob/master/rc/tools/formatter.kak):
```
if cat \"${path_file_tmp}\" | eval \"${kak_opt_formatcmd}\" > \"\${path_file_out}\"; then
   printf '%s\\n' \"execute-keys \\%|cat<space>'\${path_file_out}'<ret>\"
   printf '%s\\n' \"nop %sh{ rm -f '\${path_file_out}' }\"
else
   printf '%s\\n' \"
   evaluate-commands -client '${kak_client}' echo -markup '{Error}formatter returned an error (\$?)'
...
```

the `if cat....` is false every time. If I remove it, and do this instead, it works.

```
readonly path_file_out=\$(mktemp \"${TMPDIR:-/tmp}\"/kak-formatter-XXXXXX)
cat \"${path_file_tmp}\" | eval \"${kak_opt_formatcmd}\" > \"\${path_file_out}\"
printf '%s\\n' \"execute-keys \\%|cat<space>'\${path_file_out}'<ret>\"
printf '%s\\n' \"nop %sh{ rm -f '\${path_file_out}' }\"
rm -f \"${path_file_tmp}\"
```

So, this line `if cat \"${path_file_tmp}\" | eval \"${kak_opt_formatcmd}\" > \"\${path_file_out}\";` evaluates to false even when everything seems to be fine.

**Comment by Screwtapello** [comment]
The normal command-line convention is that if a tool succeeds, it exits 0, while if it encounters some kind of error it exits non-zero and hopefully the exact exit value is a clue to what went wrong. That's what the `if` statement you quote is testing - did the formatting "succeed" by whatever rules the formatter uses to define success? If it did, we can use its output, but otherwise the output is probably just an error message or a truncated file or something and we don't want to use that.

I'm not familiar with PHP or the `phpcbf` tool, but [looking at the code](https://github.com/squizlabs/PHP_CodeSniffer/blob/c09a4e1a2f3f6fe4a628e72b5e61ad35b309ed02/src/Runner.php#L210), it seems to pick an exit code as follows:

- if the input file was already perfect, exit 0
- if the input file had problems but we fixed them, exit 1
- if the input file had problems but we couldn't fix them, exit 2

I can understand that somebody somewhere might want to distinguish between the first two cases, but since the purpose of a formatter is to format code, it seems weird for the formatter to exit 1 when it successfully formats code. I think other formatting tools have separate "check" and "fix" modes, where "check" exits 0 for "file was perfect" and "fix" exits 0 for "file was perfect or has been fixed".

The long-term solution is probably to file an issue against `phpcbf` asking for a way to exit 0 even problems have been fixed.

The short-term solution is probably just to add `|| true` to your `formatcmd`to eat the exit code. If you really want you could add a more complex shell-script fragment that only eats exit code 1, maybe something like:

    exitval=$?
    if [ "$exitval" -eq 1 ]; then
        exitval=0
    fi
    exit $exitval

**Comment by losnappas** [comment]
Adding `|| true` does the job. They have a few issues about this already, and I don't think anyone is changing it.

In case anyone pops by to this issue, here is a working version:

```
phpcbf -q --standard=WordPress-Core --stdin-path="$kak_buffile" - || true
```
