### ISSUE TITLE
fifo buffers ignore readonly option, even after fifo was closed

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2845]
I'm trying to change buffer mode to `readonly` after `FIFO` was closed. The reason is that after buffer was constructed user should not manually modify it, as it serves for navigation purposes only. I'm using such hook for this task:

```kak
hook global BufCloseFifo .* %{
    evaluate-commands -buffer *tagbar* %{
        set-option buffer readonly true
    }
}
```

For regular buffers the code above works and buffer becomes `readonly`. However this doesn't work for `*tagbar*` buffer, which is created with this command:

    edit! -debug -fifo ${fifo} *tagbar*

If I go to that buffer and echo the option in the prompt, it says `true` but I can write to the buffer.

# 

Also I don't quite understand what parameter does `BufCloseFifo` take. Documentation doesn't mention any in the main line, and the description is a bit ambiguous. Should it take buffer name or fifo, which in my case is `${fifo}`? I don't want to set this option if for example `grep` fifo was closed.

**Comment by mawww** [comment]
Currently an empty string is passed as parameter to BufCloseFifo, so not really helpfull, we could either pass the buffername of fifo filename, whatever is the most convenient, maybe the fifo filename as the buffer name is accessble if %val{bufname}, and this hook was expected to be directly added to the buffer scope after fifo buffer creation (so that it is not necessary to try to filter on buffer name)

**Comment by andreyorst** [comment]
> this hook was expected to be directly added to the buffer scope after fifo buffer creation

reasonable. I guess it is rare situation when you have several fifos in the same buffer, but filtering with fifo filename feels more convenient to me.
