### ISSUE TITLE
Zsh filetype when specifying as `/usr/bin/env`

### ISSUE THREAD

**Issue by dgrisham** [mawww/kakoune#2858]
Setting the shebang of a file to:

```zsh
#!/usr/bin/env zsh
```

doesn't highlight the file as shell code (or at all). This shebang works for other shells (e.g. `bash`).

Tested on the current master branch.

**Comment by alexherbo2** [comment]
It’s because of the file type and because there is no `zsh.kak`.

**Example** – With a file named `hello-script`:

``` zsh
#!/usr/bin/env zsh

echo Hello
```

``` sh
file --brief --mime-type hello-script
# text/plain
```

You can configure and compile `~/.magic` to make it return a `text/x-shellscript` type:

```
0 search/1 #!/usr/bin/env\ zsh Zsh
!:mime text/x-shellscript
```

``` sh
file --compile --magic-file ~/.magic
```

The MIME type mechanism is handled by [file.kak] which detects `text/x-shellscript` types as `sh` scripts.

[file.kak]: https://github.com/mawww/kakoune/blob/master/rc/detection/file.kak

**Comment by dgrisham** [comment]
Right, this is also on files without an extension so I figured it was a filetype issue. But the `~/.magic` approach works great, thanks!
