### ISSUE TITLE
Suppressing "this is a *scratch* buffer" message

### ISSUE THREAD

**Issue by shachaf** [mawww/kakoune#2904]
The "`this is a *scratch* buffer`" message that shows up when running `kak` with no arguments keeps getting in my way. Someone suggested deleting it with a hook, but I like the property that I can press `u` to get to an empty buffer.

Maybe it can be inserted by an rc file or be made optional somehow?

This was discussed a bit in #2759 but that bug is closed.

**Comment by mawww** [comment]
I am not really keen on that message either, but newcomers have been complaining regularly about getting confused when they start Kakoune, type into the default buffer, quit, and nothing prevents them from losing what they typed.

I am not really tempted to add an option to control that because it feels like an ugly solution to an ugly behaviour, on the other hand I do not know how to reduce confusion on the new starters side.

**Comment by alexherbo2** [comment]
Why don’t fill a regular buffer?

https://github.com/mawww/kakoune/issues/1496#issuecomment-473907027

**Comment by mawww** [comment]
I think this would be worse, because we either give it an arbitrary name, and `:wa` will often create that unwanted dummy file, or we need to add some complexity to have buffers that are only saved to a file after an explicit save, possibly with some way to to ask the user for a filename on first save...

**Comment by alexherbo2** [comment]
You mark a good point about the `:wa` command.

**Comment by bugabinga** [comment]
Some options:

- Emit the warning message via `info` instead of filling the buffer.
- Persist/Restore scratch buffers automatically to/from `/tmp` (that could also be useful for the `*debug*` buffer IMO).
- Implement a "prompt text" behavior, like [HTML input fields](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#placeholder) do

**Comment by camsteffen** [comment]
I really like the idea of behaving like `<input placeholder="...">`. The text disappears as soon as the user starts entering their own text. Vim has a welcoming message with this behavior when you start it with no args.

**Comment by Jackojc** [comment]
Could an option be implemented which sets the default scratch buffer contents? For example, I could overwrite it in my kakrc to make it empty.

**Comment by danr** [comment]
Here is an alternative: the scratch buffer is populated instead with a BufCreate hook like this:

```
hook -group write-scratch-message global BufCreate \*scratch\* %
    execute-keys i "*** This is a scratch buffer ***" <esc>
}
```

Then it could be ignored with `set global disabled_hooks write-scratch-message`.

**Comment by Jackojc** [comment]
That seems more idiomatic for Kakoune

**Comment by Chris-F5** [comment]
I believe [51ec633](https://github.com/mawww/kakoune/commit/51ec633718b5d31853110fd08e971eafa6ecb603) should close this issue. Though it would be cool to have a vim-like welcome message as camsteffen suggesed.

**Comment by ewtoombs** [comment]
Looks like this change hasn't made it to archlinux yet for some reason, so I'm posting this workaround.
To get a blank buffer, use this shell script in place of the kak command, in say, /usr/local/bin/kak :
```
#!/bin/sh

if [[ -z "$@" ]]; then
    exec /usr/bin/kak -e 'e -scratch'
fi 
exec /usr/bin/kak "$@"
```
