### ISSUE TITLE
Function key definition case-sensitivity is inconsistent

### ISSUE THREAD

**Issue by dgmulf** [mawww/kakoune#2907]
### Steps 

1. Reference function keys in lower-case in a hook command (e.g. NormalKey \<f10\>).
OR
2. Reference function keys in upper-case in a map command (e.g. map global normal \<F10\>).

### Outcome 

1. Hook doesn't register.
2. Mapping doesn't register.

**Comment by lenormf** [comment]
Here is what's happening:

* you can declare a mapping on function keys using either the `<f10>` or `<F10>` notation, because the editor doesn't care about case when it parses a user-supplied description
* *Key hooks do not take a key for filter, they take a regex on the representation of a key, e.g. `<f10>`, `<F10>` or even `<(?<key>\w+)>` - this is important because it implies the editor cannot do assume the user-supplied data passed to the hook will be a key, it will be an arbitrary string
* when hitting a key in normal mode, the editor will pass an uppercase key representation to the hook engine, `<F10>`
* if the user has declared a *Key hook on `<f10>` (or any regex that doesn't expect the key representation to be uppercase'd), the hook will never trigger

I thought I could make a PR that catches lowercase key descriptions passed to the hook and converts them to uppercase, but that's too difficult to do when the input can be an arbitrary regex; so I made it so you can only bind to uppercase function keys in mappings (`<F10>`), which are used as a way to figure out what key descriptions are being parsed successfully when the user sees the hooks not triggering.
