### ISSUE TITLE
hook modifiers: before, after

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2933]
I wonder if current amount of existing hooks could be reduced in order to make them more generic, and provide a convenient way of hooking some code before or after some event. For example:

    hook global BufWritePre .* %{ format }
    hook global BufWritePost .* %{ git show-diff }

Will become:

    hook global before BufWrite .* %{ format }
    hook global after BufWrite .* %{ git show-diff }

**Comment by Delapouite** [comment]
What would happen to hooks which currently don't have this Pre/Post distinction?

**Comment by andreyorst** [comment]
Those will obtain Pre/Post distinction. Most of those will become even more useful. There are some hooks for which it is currently ambiguous how to use these properties though, for example, all `.*Idle` hooks, but generally these `before` and `after` should work fine since they just call code before other hooked code:

```
hook global after InsertIdle .* %{ clang-parse }
hook global before InsertIdle .* %{ format }
hook global after InsertIdle .* %{ git show-diff }
```

These hook declarations will result into this chain of commands on every `InsertIdle` invocation:

    format -> clang-parse -> git show-diff

So if we wan't to do something before format, we chould just hook it with `before`.

**Comment by Screwtapello** [comment]
For some hooks, having automatic before and after variants is very useful - but these hooks generally already have `*Pre` and `*Post` variants.

For some hooks, having automatic before and after variants isn't very useful, but it doesn't hurt either - thing like `*Idle` hooks.

For some hooks, having automatic before and after variants would be potentially dangerous. For example, any hook that's triggered by Kakoune's internal state changing (`*Close`, `*SetOption`, etc.) needs to run *after* the state change is complete. Since hooks can change Kakoune's internal state, a hook that's trigged by "X is about to happen" might cause X to *not* happen, and then what? Imagine a hook like this:

```
# I really want a standard indentwidth regardless of filetype plugin
hook global before WinSetOption indentwidth=.* %{
    set-option window indentwidth 8
}
```

If I try to run `set window indentwidth 4` I can think of a handful of plausible results:

- `indentwidth=8` because the new `set` overrides the original
- `indentwidth=4` because the original operation continues once the hooks have run
- `RuntimeError` because of stack overflow
- `SIGSEGV` because the hook runs while Kakoune's internal state is partially initialised, and causes a use-after-free

Regardless of which one happens in practice, the fact that there's multiple reasonable outcomes makes this seem like a bit of a foot-gun.

**Comment by andreyorst** [comment]
>```
>hook global before WinSetOption indentwidth=.* %{
>    set-option window indentwidth 8
>}
>```
>
> If I try to run set window indentwidth 4 I can think of a handful of plausible results:

What will happen is:

    WinSetOption: set-option window indentwidth 8 -> set-option window indentwidth 4

If you want 

> a standard indentwidth regardless of filetype plugin

You need `after`:

```
hook global after WinSetOption indentwidth=.* %{
    set-option window indentwidth 8
}

set window indentwidth 4
```

Which produces this chain:

    WinSetOption: set-option window indentwidth 4 -> set-option window indentwidth 8

And which is equal to current behavior of this hook.

# 

But what if you want to save previous value before changing? This isn't possible with `WinSetOption` hook currently but will be if it will accept `before`:

```
hook global before WinSetOption indentwidth=.* %{
    set-option window previous_indentwidth %opt{indentwidth}
}
```
    set window indentwidth 4
    WinSetOption: set-option window previous_indentwidth %opt{indentwidth} -> set-option window indentwidth 4
