### ISSUE TITLE
no such env var: config

### ISSUE THREAD

**Issue by watzon** [mawww/kakoune#2944]
This is a fresh install on MX Linux. I am attempting to get everything configured and install [plug.kak](https://github.com/andreyorst/plug.kak).

First after installing I created the `~/.config/kak` directory and added a `kakrc` file to it.
Then I followed the plug.kak install instructions, adding the line `source "%val{config}/plugins/plug.kak/rc/plug.kak"` to my kakrc.
Upon restarting kak I am treated with the debug buffer saying `'source' no such env var: config`.

**Comment by Delapouite** [comment]
Hi. How old is your kakoune version?

**Comment by watzon** [comment]
@Delapouite I downloaded it from `apt` so I don't know. I tried to build from sources, but I ran into issues there too.

**Comment by watzon** [comment]
So I got it working, but I had to add the debian test repository and download from there

**Comment by Screwtapello** [comment]
The version currently in Debian Stable is very, very old (2016). The version currently in Debian Testing (which will become Debian Stable in a few months) is fairly new (January 2019). There have been some changes to Kakoune since then, but no official release yet, so if you want to use the very latest features you'll need to build from source.

**Comment by watzon** [comment]
Thanks for the info :)
Closing
