### ISSUE TITLE
redundant Could not start kakoune: stdout is not a tty

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#2969]
### Steps 

```
kak | $$
bash: 22022: command not found
Could not start kakoune: stdout is not a tty
```

okay

```
kak -n $$
```

process 22022

```
kak | kak
Could not start kakoune: stdout is not a tty
```

### Outcome 

It starts

### Expected 

Don't start it 

sorry, but... this is the same as saying `Kakoune started: stdin is a tty!`

**Comment by nonumeros** [comment]
but this is the shell 's end.. there's nothing to be done.

**Comment by nonumeros** [comment]
Under vim for example

```
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...
Vim: preserving files...
Vim: Finished.
```
The message ends accordingly. 

there's no `preserving` or for that matter `warnings` or anything like it, on kak's side.

**Comment by nonumeros** [comment]
I have to reopen it because there must be another way to handle this error.

**Comment by nonumeros** [comment]
```
{
        write_stderr(format("Could not start kakoune: {}\n", error.what()));
        return -1;
    }
```

and

```
if (not isatty(1))
        throw startup_error("stdout is not a tty");
```

**Comment by Screwtapello** [comment]
> sorry, but... this is the same as saying Kakoune started: stdin is a tty!

When you say `kak | kak`, you start *two* instances of Kakoune. One of them exits with "out is not a tty", the other one starts successfully.

    $ kak | true
    Could not start kakoune: stdout is not a tty
    $ true | kak
    <Kakoune starts normally, with an empty buffer>
    $ find . | kak
    <Kakoune starts normally, letting you scroll through the output of `find .` as it arrives>

That seems... pretty reasonable to me.

Looking at how Vim handles this situation:

  - `vim | true` causes Vim to start up normally, but the user-interface is entirely hidden (since it's sent to `true` instead of drawn on-screen) so it looks like it's hanging, but `^C` and `^\` don't work, and you have to guess what's happened and try `:q<ret>` to get your prompt back
  - `true | vim` causes Vim to start up normally, with an empty buffer
  - `find . | vim` causes Vim to start up normally, and treat the output of `find .` as normal-mode commands, which is a confusing mess

In all three cases, I think Kakoune's behaviour is better than Vim's, or at least no worse.

If you're suggesting that Kakoune should notice when it's talking to itself and come up with a better message, unfortunately Unix doesn't provide a way for a process to find out who they're talking to at the other end of the pipe, so there's not much Kakoune can do.

**Comment by lenormf** [comment]
I can't see any reason why I would want to run any of the below commands, could you explain what you're trying to do?

``
$ kak | $$
$ kak | kak
```

One case that I can see is not working is the following:

```
$ kak -n -ui json | kak
```

**Comment by nonumeros** [comment]
> One case that I can see is not working is the following:

I think there may be a json file which I used at one time for hugo, but no, no

>  could you explain what you're trying to do?

nothing that important really. Such as a `tex --shell-escape <file>` (not recommended though) 

> If you're suggesting that Kakoune should notice when it's talking to itself and come up with a better message, unfortunately Unix doesn't provide a way for a process to find out who they're talking to at the other end of the pipe, so there's not much Kakoune can do.

I have to agree with you but I would disagree if otherwise, because on a side-by-side comparison kak perfomrs better than vim in this regard, but believe it or not, just yesterday the `**debug**` buffer was showing me precisely what you just said.... as opposed to jlust now that the same `debug` buffer is not returning anything with the error `stderr Could not start kakoune: stdout is not a tty` . 

On the opening message, I copied-paste what the terminal was returning, but I always thought it was neat that the `debug` buffer was still  pretty much returning the same message along the same lines than the terminal.
