### ISSUE TITLE
Option for sorting punctuation/non-punctuation in completion?

### ISSUE THREAD

**Issue by ganwell** [mawww/kakoune#3015]
I use kak-lsp with python. In python there are a lot `__*__()` methods, these are hidden methods. Because kakoune sorts punctuation < non-punctuation, I get all the `__*__()` methods first. I am not interested in these. (Update typo: > should be <)

Changing the sort-order is a breaking change, therefore I propose an option to reverse the order, defaulting in the current behavior. As I just started using kakoune, chances are high that there are better solutions for the problem. Are there any workarounds? I didn't find a way to suppress `__*__()` methods in kak-lsp nor jedi.

One can test the reversed order with this patch:

```cpp
diff --git a/src/ranked_match.cc b/src/ranked_match.cc
index 423fc814..810aa873 100644
--- a/src/ranked_match.cc
+++ b/src/ranked_match.cc
@@ -214,7 +214,7 @@ bool RankedMatch::operator<(const RankedMatch& other) const
             const bool punct1 = iswpunct((wchar_t)cp1);
             const bool punct2 = iswpunct((wchar_t)cp2);
             if (punct1 != punct2)
-                return punct1;
+                return punct2;

             const bool low1 = iswlower((wchar_t)cp1);
             const bool low2 = iswlower((wchar_t)cp2);
```

**Comment by mawww** [comment]
Hello,

There is no way to tweak the ordering besides the C++ sorting code.

From looking at the code, it seems this punctionation ordering was introduced to ensure the following:
```
    kak_assert(RankedMatch{"find(1p)", "find"} < RankedMatch{"findfs(8)", "find"});
```
That is, so that `find(1p)` is considered a better match than `findfs(8)` when the search candidate is `find`. I guess we also want that to be the case if the search candidates was say `fin`. However I agree that in general, punctuation should be ranked after alphanumeric, so what we need is to find a tweak to the sorting that fulfills those requirements.

I suspect what we really want for the `find` case is that shorter words are ranked first, so maybe it would be better to detect word boundaries instead of punctuation.

**Comment by ganwell** [comment]
Closeing because it is merged
