### ISSUE TITLE
There really should be a download and/or github link at thekakoune.org site

### ISSUE THREAD

**Issue by PerMildner** [mawww/kakoune#3016]
Visited the http://kakoune.org/ site. It all looks nice but it completely lacks any information on where to obtain the software.

(Got there via https://langserver.org/ --> https://github.com/ul/kak-lsp --> http://kakoune.org/)

**Comment by Delapouite** [comment]
What about the "Get Started" link in the main navigation bar?

**Comment by PerMildner** [comment]
Ha! I did not even see that gray area. Ok, so this is a user interface issue of the site. All the other things are very bright, I never noticed the navigation bar, it is just too gray.

![Screenshot 2019-07-10 at 14 41 18](https://user-images.githubusercontent.com/1358238/60969824-d5a2ad80-a320-11e9-9b92-243352d374e5.png)

**Comment by danr** [comment]
Agreed, a visible link saying **Download** or **Git repo** or **Github** would help.

**Comment by andreyorst** [comment]
Oh, once in a while when I want to get here and I accidentally get to the web site I always scroll down to press the link at the very bottom to get to the github:

![image](https://user-images.githubusercontent.com/19470159/61070539-a6bb3300-a417-11e9-8323-cba7208dd4be.png)

(because I'm really lazy to add a bookmark or input a proper url, I just hit the first completion my browser gives and suffer)
