### ISSUE TITLE
Specify a kakrc to use.

### ISSUE THREAD

**Issue by Icantjuddle** [mawww/kakoune#3072]
Would it be possible to specify a config file instead of using nothing or the one at `~/.config/kak/kakrc`? I'd like to do this to increase startup speed when using it to edit commit messages etc.

**Comment by Screwtapello** [comment]
You can say something like:

    kak -n -e "source /path/to/some/kakrc"

...but that only loads the kakrc in question, not any of the "standard library" that Kakoune ships with, so it's probably not quite what you wanted.

**Comment by lenormf** [comment]
Wouldn't the following work, then?

```
$ kak -n -e 'source /path/to/some/kakrc' -E 'source "%val{runtime}/kakrc"'
```

I could see an option being implemented to avoid such trickery though.

**Comment by Crote** [comment]
As a possible workaround, you could just set `XDG_CONFIG_HOME`, but that places restrictions on the directory in which your custom `kakrc` is placed. Additionally, it could cause issues when calling other tools from within Kakoune.

**Comment by nrdxp** [comment]
I would like to see a command line switch similar to `vim -u <dir>` but instead of pointing to a file like vim, we use a directory pointing to kakrc and any `autoload` *.kak files. This would make it easier for non-standard setups like NixOS. Seems simple enough, I should be able to work out a pr if it's acceptable for the community.

**Comment by mawww** [comment]
As commented on the pull request, isn't `XDG_CONFIG_HOME=blah kak` good enough to use alternate config directories ?

Hum, thinking about it, I guess the issue is that then all tools launched by kak are going to be impacted as well...

**Comment by eraserhd** [comment]
Maybe this would make the wrapper for the Nix package simpler?  https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/kakoune/wrapper.sh

**Comment by Screwtapello** [comment]
I *think* the Nix wrapper is doing something different. Kakoune normally only loads one set of plugins at startup: `$kak_config/autoload` if it exists, falling back to  `$kak_runtime/autoload` otherwise. However, I guess Nix packages for Kakoune plugins all get installed in separate locations (because that's how Nix works), and so the Nix wrapper has to make Kakoune search in multiple locations for plugins.

The Nix wrapper could probably be simplified if Kakoune supported `$XDG_CONFIG_DIRS` as well as `$XDG_CONFIG_HOME`, but I don't think just specifying a single alternative `kakrc` (as this issue proposes) would help.

**Comment by mawww** [comment]
Ok, revisiting this, I agree we need an alternate way to launch Kakoune with a different configuration directory. I wonder between the proposed `-u` argument and a `KAKOUNE_CONFIG_DIR` env var.

The env-var has a precedent with KAKOUNE_POSIX_SHELL, and would have the benefit of being something that can be set in a shell session. What do you thin ?
