### ISSUE TITLE
Odd font rendering

### ISSUE THREAD

**Issue by h8ed** [mawww/kakoune#3080]
### Steps 
Not exactly sure. Has been this way since installation,
### Outcome 
Odd font rendering near line numbers and popup boxes:
![pic-selected-190908-0613-34](https://user-images.githubusercontent.com/42626564/64488718-d9a75a80-d1ff-11e9-93e0-f81169c415ba.png)

### Expected 
Expected not to have `~T~B` all over my screen, haha

**Comment by Screwtapello** [comment]
You need to make sure Kakoune is built with `libncursesw`, not `libncurses`, so it has Unicode support. You also need to be running in a Unicode locale (`/usr/bin/locale` should mention UTF-8), and you need to have the data-files for that locale available (almost certainly this is already the case, but might be troublesome on NixOS; see #2471).

**Comment by h8ed** [comment]
Yeah, I already have en_US.utf8 running.

I probably should've mentioned in my post, but I'm using kakoune from the Void Linux package, I didn't build it from source. Perhaps I could do that and see if it fixes the issue though.

**Comment by occivink** [comment]
>Yeah, I already have en_US.utf8 running.

It should be `en_US.UTF-8`, maybe that makes a difference?

**Comment by h8ed** [comment]
My bad. It _is_ en_US.UTF-8 in `/etc/locale.conf`, it just shows up differently when running the `locale -a` command.

**Comment by h8ed** [comment]
Just tried building from source. I have all the ncurses libs for void, but still same problem. Even more strangely (maybe im missing something here though) it didn't source my `kakrc` in `~/.config/kak/kakrc`. Went back to the void binary.

**Comment by SolitudeSF** [comment]
have you tried running ` sudo xbps-reconfigure -f glibc-locales`

**Comment by h8ed** [comment]
Had not tried it before. Just did, ran successfully, still same font rendering issues.

**Comment by nonumeros** [comment]
> Had not tried it before. Just did, ran successfully, still same font rendering issues.

according to your distribution you should have fontconfig and xorg-fonts ... Try reinstalling these packages.

**Comment by mawww** [comment]
This does look exactly like what we get with non-unicode locales, so I would investigate further what is going on there. I get those `~T~B` here if I run `LANG=en_US kak` for example, but not when I do `LANG=en_US.utf8 kak` or `LANG=en_US.UTF-8 kak`. Can you try those command ?

 Also, do you get the expected locale if you do `echo %val{client_env_LANG}` ?

**Comment by mbarbar** [comment]
To add more information to the problem. I'm on Void too and run into the same issue.

Setting `LANG` and running shows the same issue. `%val{client_env_LANG}` is `en_US.UTF-8`.

**Comment by nonumeros** [comment]
> To add more information to the problem. I'm on Void too and run into the same issue.
> 
> Setting `LANG` and running shows the same issue. `%val{client_env_LANG}` is `en_US.UTF-8`.

I don't know your distro guys ,,but normally -  locale ,s set through `/etc/locale.cnf` .. What does `localectl list-locales` return ?

**Comment by mbarbar** [comment]
I don't have a localectl binary installed (and it seems like Void doesn't supply it anywhere), but running `locale` gives:
```
LANG=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```

And my `/etc/locale.conf` is:
```
LANG=en_US.UTF-8
LC_COLLATE=C
```

**Comment by Screwtapello** [comment]
My understanding of locale config is that `LANG` is the basic default, then you can set `LC_CTYPE`, `LC_NUMERIC`, etc. to override `LANG` for a specific category of locale stuff, and then `LC_ALL` overrides everything else. *Normally*, if you set `LANG`, it's used for everything because none of the `LC_*` variables are set.

So, you have `LANG` set to a suitable (Unicode-supporting) value, but eery other locale config overrides it with a broken value. I bet if you start Kakoune with:

    LC_ALL=en_US.UTF-8 kak

...everything should work.

The question is, though, why is the locale being set to a non-Unicode locale?

**Comment by nonumeros** [comment]
> The question is, though, why is the locale being set to a non-Unicode locale?

@Screwtapello excellent question but I'm more concerned of 

> LC_ALL=C

What does `env | grep C` returns? 

Is the XDG_CONFIG environment variable there?

**Comment by Screwtapello** [comment]
> ...I'm more concerned of `LC_ALL=C`

That's what I'm saying: something somewhere is setting `LC_ALL` to `C`, so programs will use a non-Unicode locale.

I've heard of some people manually choosing the `C` locale so that tools like `ls` will list files in ASCII-betical order instead of proper case-insensitive order, but normally these days it's the `C.UTF-8` locale so that Unicode stuff still works.

> And with the same token if `LC_ALL=en_US.UTF-8 kak` works, then `LC_ALL= kak` should follow

...maybe. None of the various `LC_*` settings leap out at me as "this controls how the terminal represents non-ASCII characters", but presumably *one* of them does, so you'd have to clear out that one as well as `LC_ALL`.

**Comment by nonumeros** [comment]
> > ...I'm more concerned of `LC_ALL=C`
> 
> That's what I'm saying: something somewhere is setting `LC_ALL` to `C`, so programs will use a non-Unicode locale.

Yes  I can't agree more with you there. 

> I've heard of some people manually choosing the `C` locale so that tools like `ls` will list files in ASCII-betical order instead of proper case-insensitive order, but normally these days it's the `C.UTF-8` locale so that Unicode stuff still works.

Yes... and if he has 

```
LANG=en_US.UTF-8
LC_COLLATE=C
```
then it would coinncide with 

>  it is ineffective if LC_ALL is also set.

because it is indeed set as well

See https://superuser.com/a/448294/256668

> > And with the same token if `LC_ALL=en_US.UTF-8 kak` works, then `LC_ALL= kak` should follow
> 
> ...maybe. None of the various `LC_*` settings leap out at me as "this controls how the terminal represents non-ASCII characters", but presumably _one_ of them does, so you'd have to clear out that one as well as `LC_ALL`.

I agree there too

**Comment by mbarbar** [comment]
Thanks guys for the pointers, they lead me to the solution. It was a problem with my setup. In my case there were two issues,

1. That en_US.UTF-8 was not set up properly (en_AU.UTF-8 was).

2. LC_ALL was being overridden.

Now it's all good.

If anyone else has the same problems as me on Void, I suggest:

1. Check `/etc/default/libc-locales` to check which locales are enabled. You can also run `locale -a`.

2. Make sure `LANG` is set correctly in `/etc/locale.conf`. In my case, that's `LANG=en_AU.UTF-8`. The easy way to see the changes is just log out and log back in.

3. A more temporary solution is `export LC_ALL=en_AU.UTF-8` (Bash will warn if this is wrong, which is how I found the problem) then run `kak`.

To @h8ed, since you mention
> My bad. It is en_US.UTF-8 in /etc/locale.conf, it just shows up differently when running the locale -a command.

I don't think you have the same problem as I did, but maybe you could post all of,
```
locale -a
locale
cat /etc/locale.conf
cat /etc/default/libc-locales
```

**Comment by mawww** [comment]
Glad we got to the bottom of this, closing this assuming @h8ed had the same issue, please re-open if that does not fix it.
