### ISSUE TITLE
update-option on range-specs malfunctioning on first tuple in list

### ISSUE THREAD

**Issue by ZakharEl** [mawww/kakoune#3082]
declare-option range-specs snip_fields
....
set-option -add buffer snip_fields "%val{selection_desc}|1"
...change the contents of the snip_fields in the buffer (like deleting or adding a couple characters)
update-option buffer snip_fields
...now the content of snip_fields will be way off in line number and no column change is displayed
...like before 0 1.25,2.12|1
...like after 15 15.25,16.12|1
if for subsequent tuples added to the list this doesn't happen - it only happens when the list only has a single tuple

**Comment by mawww** [comment]
It seems the issue here is that you do not control the timestamp in the snip_field option when you do  `set-option -add buffer snip_fields "%val{selection_desc}|1"`.

Usually before adding a bunch of elements to a range-specs option, one needs to set the timestamp (with `set-option buffer snip_field %val{timestamp}` (notice no `-add`) if those ranges relate to the current state of the buffer, but could be a previous state in the case of async work being done).

`update-option` updates the option ranges so that it matches the current buffer state. From your example, the option had timestamp 0 while the buffer was already at timestamp 15. So kakoune assumed the given range had to be updated according to all the changes that happend to the buffer in between timestamp 0 and 15.

Hopefully this makes sense, closing this issue as I dont think there is anything to change in Kakoune itself, but feel free to comment if there is an additional issue or if you want more details.

**Comment by ZakharEl** [comment]
Thanks
