### ISSUE TITLE
I/O not working properly in Mac OS in latest builds

### ISSUE THREAD

**Issue by tuffy** [mawww/kakoune#3087]
# Steps

Build latest git version (commit c787128a7c49555c8d1d49bd246dc9df92a5370b) of Kakoune under Mac OS and launch it in an iTerm.

### Outcome

Don't see the news blurb and typing in commands generates a lot of garbage output.

### Expected

Should see the news blurb and be able to type in editor commands.

Using `git bisect`, it appears the brokenness was triggered by commit f2f99580f848949b35311362faf116b1ec0c90a7 .  My same config works under Linux, so it appears to be a Mac-specific issue.

**Comment by Screwtapello** [comment]
Can you paste a screenshot of the brokenness?

**Comment by tuffy** [comment]
I've made a quick video of the bug in action.
[video link](https://imgur.com/a/5d30dNl)
Running directly under the terminal seems mostly okay, but under tmux is particularly bad with a lot of my keystrokes not showing up at all.

**Comment by vbauerster** [comment]
I've noticed that function keys like F2 ceased to work. In insert move pressing `<c-v>F2` outputs `Q`.
Tested with `Kakoune v2019.07.01-127-g271b1d4f`

**Comment by Screwtapello** [comment]
@vbauerster What terminal are you using, and what is `$TERM` set to? Instead of using `<c-v>` in Kakoune, can you try just running `cat`, pressing F2 and reporting what gets printed?

**Comment by mawww** [comment]
Hello,

What version of ncurses are you building against, I can reproduce a pretty bad display issue with the OSX bundled ncurses, but it goes away if I build Kakoune against latest brew installed ncurses.

(Its still a Kakoune bug, just want to see if its the same thing I am reproducing or not).

**Comment by vbauerster** [comment]
@mawww I've `ncurses: stable 6.1` installed via `brew`:
[![Screenshot-2019-09-19-at-09-54-28.png](https://i.postimg.cc/3NGzbXh3/Screenshot-2019-09-19-at-09-54-28.png)](https://postimg.cc/QKX6FWVz)
I can see that [makefile](https://github.com/mawww/kakoune/blob/master/src/Makefile#L64) picks it up.

**Comment by mawww** [comment]
@vbauerster Ok, thats another issue that seems to be tmux related. Seems some terminal send a different escape sequence for F1-4, F2 being `ESC O Q`. I can see some references to that, seems to be called `SS3`. Hopefully there is an easy way to force the terminal to send ANSI style keystrokes, else I'll need to add support for those in the key parser.

**Comment by vbauerster** [comment]
F1-4 not recognized in iTerm2 without tmux.

**Comment by Screwtapello** [comment]
The original VT100 only had four function keys, PF1 through PF4, [which sent `SS3 P` through `SS3 S`](https://vt100.net/docs/vt100-ug/table3-8.html)

The VT220 had 20 function keys, but the first five controlled the terminal itself, and didn't send anything to the remote host. The remainder of the function keys [sent CSI codes ending in `~`](https://vt100.net/docs/vt220-rm/table3-4.html).

[Apparently](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-PC-Style-Function-Keys) early versions of xterm extended the VT220 function key numbering back to cover F1-F5 (being `CSI 11~` to `CSI 15~`), but eventually it was changed to make the F1-F4 codes backwards-compatible with the VT100, rather than being pure guesswork.

On the other hand, it looks like rxvt-like terminals copy the VT220 key-codes and extend them to cover F1-F5 in the same way that old versions of xterm did. Interestingly, that also explains why rxvt function-key codes wrap at 20 instead of 10 or 12 like one might expect.

Luckily, the rxvt and VT100 encodings for F1-F4 are entirely distinct, so there should be no problem automatically supporting both. Supporting keys beyond F10 is awkward (`CSI 23~` might be `<f11>` or `<s-f1>` in rxvt, but can only be `<f11>` in xterm because `<s-f1>` is `CSI 1;2P`) but we had that same problem with ncurses-based input, so that's not a big drawback.
