### ISSUE TITLE
Is there anything like Vim's numberwidth?

### ISSUE THREAD

**Issue by enricozb** [mawww/kakoune#3101]
I'm trying to center the buffer _horizontally_ on a terminal session, and I'm wondering if  there is anything like Vim's `numberwidth` to accomplish this.

**Comment by Delapouite** [comment]
What you can attempt to do is play with the `-separator` switch of the `number-line` highlighter. But the size of this value is limited to 10bytes:

```
addhl global/ number-lines - separator '       '
```

**Comment by danr** [comment]
Another thing to try is the flag-lines highlighter:

```
decl line-specs test %val{timestamp} '1|          '
addhl buffer/ flag-lines default test
```

**Comment by enricozb** [comment]
@danr This is definitely the behavior I wanted. Thank you

**Comment by Delapouite** [comment]
@enricozb Glad it works! Could you close this issue? Thanks

**Comment by Ordoviz** [comment]
@danr When I run these commands I get the desired effect but when I put them in my `kakrc` file and relaunch kakoune “no bufffer in context” gets printed to the `*debug*` buffer. What else can I try?

**Comment by lenormf** [comment]
Replace `buffer` with `global`.

**Comment by Ordoviz** [comment]
@lenormf I still get the same error message. But with
```
declare-option line-specs test 1 '1|     '
add-highlighter global/ flag-lines default test
```
something weird happens: The spaces don’t get added in front of the line numbering but *after* it.

**Comment by Screwtapello** [comment]
Line-numbers and flags stack up from the left-hand side of the window, in the order they're defined. That is, if you say:

    addhl global/ flag-lines default test
    addhl global/ number-lines

...then the spaces will be left-most, but if you say:

    addhl global/ number-lines
    addhl global/ flag-lines default test

...then the numbers will be left-most.

**Comment by Ordoviz** [comment]
Thank you! Sadly `%val{timestamp}` is still breaking my config and using `1` as a workaround means that the highlighter disappears when you input one character.

However, I realized that this is not what Vim’s [numberwidth](https://vimhelp.org/options.txt.html#%27numberwidth%27) does. When you create a new file in Vim and input 10 newlines, the line numbers now take up two digits but the body text doesn’t get pushed over to the right by one column because Vim left some room for the line numbers. When you do the same in Kakoune, the body text gets pushed over the right which distracts me every time.

For this reason I advocate to reopen this issue.

**Comment by Screwtapello** [comment]
This issue was originally about padding the left-hand side of the screen to horizontally centre the buffer, and that problem is solved.

Actually implementing something like Vim's `numberwidth` option is a different thing altogether, but one worth having an open issue about. If you file such an issue, you could point people to https://github.com/mawww/kakoune/blob/b982371843168d104767434dfa1ead2befa7b6e3/src/highlighters.cc#L1156-L1163 which seems to be where the actual width of the line-number highlighter is calculated.
