### ISSUE TITLE
extra_word_chars isn't used to find word completion words

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#3108]
### Steps

```
$ kak -s test-session /tmp/foo.clj
```
Enter:
```
hello-world
hel
hello-w
```

### Outcome 

On the second line, Kakoune offers "hello", but not "hello-world".
On the third line, Kakoune does not offer anything (not even "world")

### Expected 

On the second line, Kakoune should offer "hello-world" and not "hello".
On the third line, Kakoune should offer "hello-world".

**Comment by eraserhd** [comment]
(NOTE: dash is an extra word character in Clojure)

**Comment by mawww** [comment]
The issue here is that clojure.kak sets the extra_word_chars option on the window, but the word database is attached to the buffer itself, and hence can only respect one extra_word_char settings, which is the buffer one (you can see that also when using completion from other buffers, it will not find words that are considered words in the current buffer but not in the originating ones).

It would be tricky to fix that without having to constantly reparse the buffer or significant memory impact, as each window would have to track a word database for each existing buffer (as each window can have it own set of extra_word_chars).

I think the better solution is to change clojure.kak to set extra_word_chars on the buffer itself. It would be slightly less flexible, but would fix the most common issue.

**Comment by eraserhd** [comment]
I came to that conclusion by way of reading the source last night.
