### ISSUE TITLE
-draft misbehaves on end of selection

### ISSUE THREAD

**Issue by xificurC** [mawww/kakoune#314]
Something like

    exec -draft "a<backspace><esc><a-;>;d"

updates the selection at the beginning but fails at the end.

**Comment by mawww** [comment]
So, that is actually the normal behaviour, it seems strange when considering a selection, but is you consider each endpoint separately it makes sense.

it boils down to the behaviour a cursor has when you delete the character it is on. the current behaviour is to not move, which works well for the selection begin, but not well for selection end (If you have a word selected and expect deleting word first char and word last char will keep the remaining word selected).

It could be fixed by handling selection ends differently, when the selection is more than a single char, but I am not sure the added complexity is really worth it, as the single char case is still special.
