### ISSUE TITLE
execute-keys <a-;> wrong behaviour

### ISSUE THREAD

**Issue by JJK96** [mawww/kakoune#3178]
### Steps 

kak -n

1. make a selection e.g. `tes[t]`
2. `execute-keys <a-;>`

### Outcome 

`test-[]`

### Expected 

`[t]est`

**Comment by Screwtapello** [comment]
The Kakoune command-parser uses `;` as a statement delimiter, so `execute-keys` receives the keys `<` (de-indent the current line), `a` (enter append mode), `-` (type a `-`), and then Kakoune attempts to execute the invalid command `>`, producing an error.

To actually execute the `<a-;>` command, you can backslash-escape the semicolon:

    execute-keys <a-\;>

...or put the whole key name in a string:

    execute-keys "<a-;>"

Since commit 21614cb you can also use the special key name `<semicolon>` to avoid quoting hassles:

    execute-keys <a-semicolon>

**Comment by JJK96** [comment]
Thanks, my bad
