### ISSUE TITLE
newline in register " paste

### ISSUE THREAD

**Issue by ZakharEl** [mawww/kakoune#3197]
### Steps
* Normal Mode: **xy**
* go to the **middle** of any other line
* keys: **p, P, <a-p>, <a-P>**

### Outcome
Does not paste before or after selection but rather above or below the line the selection is in

**Comment by Screwtapello** [comment]
This is expected behaviour.

Vim has the concept of "character-wise" or "line-wise" selection, where a "character-wise" selection is always pasted exactly at the cursor, and a "line-wise" selection is always pasted on the line below (or above) the cursor. That way, you can select (say) an expression and paste it into the middle of another expression, but if you select a whole statement then you paste it after the current statement, instead of pasting it in the middle and potentially breaking it.

Kakoune has similar concepts, but instead of storing "character-wise" versus "line-wise" as a flag along-side the selected text, it uses the heuristic of "if the register contents end with a newline, it's line-wise". <kbd>x</kbd> selects the current line, including the trailing newline, and so when you yank and paste it somewhere else, it's treated as line-wise and pasted after the current line, instead of into the middle of it.

**Comment by ZakharEl** [comment]
Thanks for illuminating me
