### ISSUE TITLE
Ncurses doesnot allow mapping <c-j>

### ISSUE THREAD

**Issue by siriKeeton** [mawww/kakoune#3250]
I'm trying to move from vim, but one of my keymaps does not work. I understand that ncurses cannot distinguish `<c-j>` from `<ret>` and `<c-i>` from `<tab>`, but it hurts functionality so much.
Not being able to use <tab> for autocompletion is a drag too.
Any plans to move from nsurses? 
### Steps 
Add to your kakrc:
<pre>map global normal `<c-j>`  10j</pre>
and try to use this keybinding
### Outcome 
Nothing
### Expected 
Jump 10 lines lower

**Comment by Screwtapello** [comment]
This is actually a bit more complex than you describe:

- ncurses is not responsible for mapping `<c-i>` to `<tab>`, or `<c-m>` to `<ret>`; that's a fundamental problem with terminals and it affects Vim just as much as Kakoune.
- Kakoune actually [is responsible](https://github.com/mawww/kakoune/blob/9ace7b584dabf562b29deeda9230064e305fcd30/src/ncurses_ui.cc#L597) for mapping `<c-j>` to `<ret>`, and I'm not sure why. 
- The main difference between Vim and Kakoune is that when Kakoune receives an ambiguous key, it picks one meaning consistently, while when Vim receives an ambiguous key it processes *every* possible meaning.

So, right now, you can get the behaviour you want with:

    map global normal <ret> 10j

If you really want to see `<c-j>` in the mapping, you can say:

    map global normal <c-j> 10j
    hook global RawKey <ret> %{ execute-keys -with-maps <c-j> }

In the future, Kakoune might remove its `<c-j>` → `<ret>` conversion, at which point you will be able to map `<c-j>` directly, although `<c-m>` and `<c-i>` will still require the above workaround.

Kakoune might also consider doing the "trigger all possible meanings" thing. Although it's potentially very confusing, and would make terminal-Kakoune behave differently from a hypothetical GUI-Kakoune, it does seem to be what people expect.

**Comment by Screwtapello** [comment]
I investigated some more, and it seems I was wrong about Vim - it doesn't trigger *every* meaning, but just the most recent mapping. That is, in Vim:

    map <c-m> h
    map <Enter> l

...then `<c-m>` and `<ret>` will both act like `l`. If you do the mappings in the opposite order, they'll both act like `h`. This is true (for me) even in vim-gtk3, which can definitely tell those keys apart. Anyway, I put this info [on the wiki](https://github.com/mawww/kakoune/wiki/Ambiguous-Keys) for future reference.

**Comment by Clyybber** [comment]
In general, differntiating between`<c-j>` and `<c-m>` is possible when `ICRNL` and `INLCR` (and  `IGNCR`) are disabled. This can be achieved by kakoune using the `termios` API or by yourself via `stty`.

**Comment by Screwtapello** [comment]
I applied the following diff to the latest commit:

```diff
--- a/src/ncurses_ui.cc
+++ b/src/ncurses_ui.cc
@@ -594,12 +594,10 @@ Optional<Key> NCursesUI::get_next_key()
         return {};
 
     auto parse_key = [](unsigned char c) -> Key {
-        if (c == control('m') or c == control('j'))
+        if (c == control('m'))
             return {Key::Return};
         if (c == control('i'))
             return {Key::Tab};
-        if (c == control('h'))
-            return {Key::Backspace};
         if (c == control('z'))
         {
             kill(0, SIGTSTP); // We suspend at this line
```

...and I could still type `<ret>` and `<backspace>`, but I could also type `<c-j>` and `<c-h>`. This version of Kakoune uses ncurses, so it automatically sets TTY raw mode, which should prevent the `<c-m>` → `<c-j>` conversion. I'm not sure about the `builtin-terminal-ui` branch, but I assume it would do something similar for the same reasons.

Removing the `<c-h>` → `<backspace>` special case is a bit trickier, since "what the backspace key sends" is often a configuration option (for example, [xterm's `backarrowKey` setting](https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:backarrowKey). Debian at least [guarantees](https://www.debian.org/doc/debian-policy/ch-opersys.html#keyboard-configuration) that backspace sends `^?` instead of `^H`, but I don't know whether that wisdom extends to other Linux distros, let alone macOS, BSDs, etc.

**Comment by siriKeeton** [comment]
Thanks, that is very helpful. Good to hear that you added that to wiki, but I actually used only build in doc command, so I might be worth adding there too.
Great project, by the way. Hope it soon gets the popularity it deserves. :)
