### ISSUE TITLE
Inside tmux <home> and <end> keys behave differently

### ISSUE THREAD

**Issue by Emmk** [mawww/kakoune#3252]
### Steps
1. Try using \<home\> and \<end\> keys outside of tmux
2. Try using them inside tmux
### Outcome
Both \<home\> and \<end\> open the `select to inner surrounding object begin` menu
### Expected
The \<home\> key selects to beginning of line, and the \<end\> key to the end of it

**Comment by Screwtapello** [comment]
I can confirm. I'm using LXTerminal with `TERM=vte-256color`, and tmux 3.0a with `TERM=tmux-256color`. Comparing the `<home>` and `<end>` encodings for both terminals:

    $ infocmp -1x vte-256color tmux-256color | egrep 'home|end'
    kend: '\EOF', '\E[4~'.
    khome: '\EOH', '\E[1~'.

`vte-256color` uses the `SS3 H` and `SS3 F` sequences described under xterm's [PC-style Function Keys](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-PC-Style-Function-Keys) heading, while `tmux-256color` uses the `CSI 1 ~` and `CSI 4 ~` sequences described under xterm's [VT220-style Function Keys](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-VT220-Style-Function-Keys) heading.

Since Kakoune no longer uses the terminfo database, but has its own key sequence decoder, I guess we'll need to teach it about tmux.

**Comment by Jackojc** [comment]
This appears to be happening to me with st (simple terminal) even outside of tmux.

**Comment by Screwtapello** [comment]
Yeah, it looks like st follows the same pattern as tmux:

    $ infocmp -1x vte-256color st-256color | egrep 'home|end'
    kend: '\EOF', '\E[4~'.
    khome: '\EOH', '\E[1~'.

**Comment by Jackojc** [comment]
I wonder if we could get a new release for this since it seems to be a big enough issue in usability.

**Comment by mawww** [comment]
I plan to do a new release soon as 2019-12-10 was a bit too buggy for my taste.
