### ISSUE TITLE
formatcmd with prettier fails

### ISSUE THREAD

**Issue by keutznev3** [mawww/kakoune#3265]
### Steps 
hello, i try to format a markdown file with kakoune. i have this minmal kakrc: https://gist.github.com/keutznev3/d860290c2b1d0fe5da4ba0811947bab3

i want to format text with ":format" now.
### Outcome 
i get an error message in debug buffer na dthe file does not get formatted: 
[error] No parser and no file path given, couldn't infer a parser. 
>>>
error running command 'eval -client client0 %{ fail formatter returned an error 1 }
': formatter returned an error 1 
### Expected 
the text should be formatted. prettier work from console with "prettier README.md".

**Comment by occivink** [comment]
judging by the `prettier` CLI, I don't think you need the `--stdin-filepath=${kak_buffile}`. format.kak expects the formatter to take data from stdin and output the result on stdout, which prettier does.

**Comment by keutznev3** [comment]
that does not work as well. https://github.com/mawww/kakoune/wiki/Lint#javascript-eslint
here it is written to use with --stdin-filepath

**Comment by occivink** [comment]
The problem of using `stdin-filepath` is that it will only take into account the state of the file, and not the changes that are yet unsaved.

If you do `cat READMER.md | prettier` what happens? This is more or less what format.kak does under the hood. Maybe try `prettier --parser markdown`, since the type information is not available when using stdin.

**Comment by keutznev3** [comment]
cat README.md | prettier fails with: [error] No parser and no file path given, couldn't infer a parser.
cat README.md  | prettier --parser markdown works and cat README.md | prettier --stdin-filepath=README.md works as well.

> The problem of using `stdin-filepath` is that it will only take into account the state of the file, and not the changes that are yet unsaved.
that is good for me, i want to use hook at save

> If you do `cat README.md | prettier` what happens? This is more or less what format.kak does under the hood. Maybe try `prettier --parser markdown`, since the type information is not available when using stdin.

cat README.md | prettier fail with: [error] No parser and no file path given, couldn't infer a parser.
cat README.md  | prettier --parser markdown works and cat README.md | prettier --stdin-filepath=README.md works as well.

**Comment by occivink** [comment]
Ok, then the way to go is really to use
```
hook global WinSetOption filetype=markdown %{
    set window formatcmd 'prettier --parser markdown'
}
```

**Comment by keutznev3** [comment]
ok thanks for help

**Comment by keutznev3** [comment]
i found the original problem: i use this `set-option buffer formatcmd "echo ${kak_buffile} > /home/keutz/test.txt"` and it shows me, that `$kak_buffile` is empty.

**Comment by occivink** [comment]
ah yes, actually that's because `kak_buffile` is not exported to the relevant shellscope, since it does not appear in it. Maybe it used to be, but it was refactored some time ago.
If your issue is resolved, you can close it

**Comment by maximbaz** [comment]
Is there a way to bring `kak_buffile` back to the scope? This definitely worked before and it was really nice:

```
hook global WinSetOption filetype=(javascript|typescript|css|scss|json|markdown|yaml|html) %{
    set-option buffer formatcmd "prettier --stdin-filepath=${kak_buffile}"
    hook buffer -group format BufWritePre .* format
}
```

Here I setup a single tool (`prettier`) to format multiple file types, prettier receives code on stdin, detects expected parser based on file extension (coming from `$kak_buffile`, detects local prettier configs based on the file location (again coming from `$kak_buffile`), and performs the formatting.

If I were to set up the above separately for each file type via `--parser`, my config would explore, but even more relevantly I still need to tell `prettier` path to this file so that it can pick up local configs (e.g. if global config has tabstop to 4 spaces, but in this one project tabstop is 2 spaces).

**Comment by maximbaz** [comment]
I looked into this bug, it started to appear since the refactoring of format in https://github.com/mawww/kakoune/pull/3083/

However the fix is surprisingly simple, in order to expose `$kak_buffile` one must... use it? I think this is some lazy loading at play here.

```diff
--- a/rc/tools/format.kak
+++ b/rc/tools/format.kak
@@ -18,6 +18,7 @@ define-command format-selections -docstring "Format the selections individually"
         set-register '|' %{
             format_in="$(mktemp "${TMPDIR:-/tmp}"/kak-formatter-XXXXXX)"
             format_out="$(mktemp "${TMPDIR:-/tmp}"/kak-formatter-XXXXXX)"
+            echo "$kak_buffile" >/dev/null
 
             cat > "$format_in"
             eval "$kak_opt_formatcmd" < "$format_in" > "$format_out"

```

@occivink what do you think, can we fix this? Perhaps in a nicer way than the above?

**Comment by Screwtapello** [comment]
A nicer way might be a comment:

    # Because the formatcmd option might need them,
    # mention envvars to trick Kakoune into putting them into the environment:
    # $kak_buffile $kak_opt_filetype $kak_opt_tabstop $kak_opt_indentwidth

**Comment by Screwtapello** [comment]
Or actually, how about just changing your hook to something like:

    set-option buffer formatcmd "prettier --stdin-filepath=%val{buffile}"

**Comment by maximbaz** [comment]
Oh wow, I didn't know about this! This approach is the best, and it works, just tested 👍

**Comment by occivink** [comment]
Another possibility is to use `prettier --parser "$kak_hook_param_capture_1"` since the kakoune filetypes seem to coincide with the ones used by prettier.

**Comment by schickm** [comment]
Here's some added "why" context to the desire of passing a filepath to a formatter as it relates to Prettier:

If you run `prettier --stdin` without the `--stdin-filename` it will just use it's default configuration options to decide what is "pretty".  If you're working in a codebase that defines some overrides somewhere in a `.prettierrc` file, then you either need to pass the path to that rc file directly...OR...pass the `--stdin-filename` flag.  By passing `--stdin-filename`, Prettier will find the relevant `.prettierrc` file itself.  This is more desireable when working within kakoune, because traversing up the directory hierarchy in search of some file would be a fair amount of work.  So, best to let Prettier do that work for us.
