### ISSUE TITLE
Kakoune breaks iTerm2 color scheme

### ISSUE THREAD

**Issue by camsteffen** [mawww/kakoune#3295]
After using kakoune, some of the colors in my terminal are permanently changed for that terminal instance. The different colors are noticeable to me when I use git with diff-so-fancy. I cannot reproduce the issue using the default macOS Terminal, just iTerm2. The configuration of iTerm2 doesn't seem to matter.

macOS 10.14.6
Kakoune v2019.12.10
iTerm2 3.3.7

#### Minimal kakrc to reproduce
```
colorscheme gruvbox
add-highlighter global/ number-lines
```

### Steps
1. Set kakrc to the above.
1. Open iTerm2
1. Run `printf '\033[1;32;48;5;22mtest\033[m\n'`
1. Run `kak`
1. Close kak

### Outcome
The color of the output from the first command changed!

### Expected
The colors don't change.

#### Before
![image](https://user-images.githubusercontent.com/5565418/72452076-8d0df600-3782-11ea-8d42-d76b36736ea6.png)

#### After
![image](https://user-images.githubusercontent.com/5565418/72452114-a1ea8980-3782-11ea-8231-0056b561115d.png)

**Comment by mawww** [comment]
Kakoune changes the terminal color palette in order to support arbitrary rgb colors, and uses an escape sequence to reset it on quit. It would seem that iterm2 supports changing the palette, but not restoring it.

This will be fixed once we migrate to the builtin-terminal-ui branch, which uses direct rgb escape sequences to set colors (bypassing the palette). In the mean time, getting iterm2 to support OSC 104 would fix this.

**Comment by unrelentingtech** [comment]
104 is just "reset", right? So if you use [escape sequences to set your main terminal color theme from the shell](https://github.com/chriskempson/base16-shell)… and kakoune does the reset on exit… oops, there's no restoring of *that* theme, the terminal can't tell if something's been set by my theme scripts or by the temporary editor instance.

The only reason I wasn't even aware of this behavior for a long long time was because tmux did not let kakoune reset the colors :)

And it looks like the builtin-terminal-ui thing happened already \o/ and I was using a nearly year old version of kakoune (oops, no one was updating FreeBSD ports, let me fix that)

**Comment by mawww** [comment]
Should be fixed now
