### ISSUE TITLE
Has the `clang_options` option been removed?

### ISSUE THREAD

**Issue by arrufat** [mawww/kakoune#3304]
### Steps 
add the following line to my `kakrc`:
`set-option global clang_options -std=c++17`

### Outcome 
The debug buffer contains the following message:

`'set-option' option not found: 'clang_options'. Use declare-option first`

### Expected 
How am I supposed to set the `clang_options`?

**Comment by Screwtapello** [comment]
Inside [clang.kak](https://github.com/mawww/kakoune/blob/master/rc/tools/clang.kak), the "clang_options" option is only declared inside `provide-module clang`, so you won't be able to set it until the module is loaded.

You have a few alternatives available. You could unconditionally load the module before setting the option:

    require-module clang
    set-option global clang_options -std=c++17

...or, you could automatically set the option once the module is loaded for some other reason (like because you opened a C++ source file):

    hook global ModuleLoaded clang %{
        set-option global clang_options -std=c++17
    }

**Comment by arrufat** [comment]
It works! Thank you! :)
