### ISSUE TITLE
ctrl+u and ctrl+w insert mode shortcuts

### ISSUE THREAD

**Issue by tinoucas** [mawww/kakoune#334]
The following (widely used) insert mode shortcuts (and possibly more) don't work in kakoune:
ctrl+u (delete from cursor to start of line)
ctrl+w (delete from cursor to start of previous word)

(installed from brew on OSX:
brew install --HEAD https://raw.githubusercontent.com/mawww/kakoune/master/contrib/kakoune.rb)

**Comment by lenormf** [comment]
Hi @tinoucas,

Those two shortcuts do not exist in kakoune because they don't fit the paradigm that the editor implements: selection-oriented text edition.

The two features you ask for can be done by thinking in terms of what to do with a selection, instead of what to do from the cursor's position:
* selecting the text from the cursor to the start of the line *or* from the cursor to the start of the previous word
* deleting the current selection

With that in mind, these operations translate, in kakoune, to:
* `<a-h>d`: select from cursor to beginning of the line (`alt-h`), then remove the current selection (`d`)
* `<a-i>wd`: select the current word (`alt-i` followed by `w`), then remove the current selection (`d`)

I understand this might seem backward because most editors do not think in terms of *selection* but in term of *movement*, but it's merely a different point of view on editing text.

You could bind `ctrl-w` and `ctrl-u` to the two commands I listed above, if you wanted to, but IMHO it would steer you further away from kakoune's "ideology", instead of help you understand it better.

Note that I'm just a fellow kakoune user, my answer might not necessarily represent the project's author point of view on the matter.

**Comment by mawww** [comment]
Hello,

@lenormf is correct, I would rather recommend using normal mode for these operations, and I would like to avoid adding more insert mode bindings.

If you really want these commands, the most robust way to bind them would be (of the top of my head)

```
map global insert <c-u> '<a-;>:exec -draft <a-h>d<ret>'
map global insert <c-w> '<a-;>:exec -draft <a-l>d<ret>'
```

which translate as 'escape to normal mode for a single command, enter command mode, execute the <a-h>d keys in a copy of the current context'.

**Comment by memeplex** [comment]
Although I agree with @lenormf and @mawww there is still the command prompt where `ctrl-w` is very useful. The way to resolve the tension between insert and normal mode there could be in the lines of vim `q:`. That is, a miniprompt editable in normal mode, without the cruft of an specialized command prompt mode. AFAIK this is not supported by kak. If this happens to be difficult to implement I think adding `ctrl-w` would be a sensible concession from theory to practice, since pressing backspace all the way down feels too clumsy.

**Comment by mawww** [comment]
Hello, `ctrl-w` is actually supported in prompts, although it does not delete next word but moves the cursor to next word. prompt mode is definitely open for a few keybindings to ease edition there, altough for more complex edition of a command, you can just use a scratch buffer, write you command, then `ctrl-r .` in command mode will insert the current selection in it.

**Comment by memeplex** [comment]
What do you think of having a buffer with the prompt history, in "command
mode", and a couple of key bindings to quickly open it and dispatch the
command under cursor?

**Comment by mawww** [comment]
having a prompt history buffer would be a precedent I'd like to avoid, up to now there is no "special buffers" in kakoune, that have special, built-in semantics/content. I'd like to keep in that way. It could be done through a script however, either by making prompt history available to scripts, or with a hook allowing script to remember executed commands.

**Comment by Swoorup** [comment]
What about Ctrl A and Ctrl E that allows me to move to line start and line end respectively? I have evaluating kakoune thinking to switch from vim, only things that bugs me is these and the awkward scripting interface

**Comment by mawww** [comment]
Hello @Swoorup , `<home>` and `<end>` already provide that in insert mode, you should be able to map `<c-a>` and `<c-e>` to these with `map global insert <c-a> <home>` and `map global insert <c-e> <end>`

**Comment by lenormf** [comment]
I think this issue can be closed.
