### ISSUE TITLE
Filetype detection on mac

### ISSUE THREAD

**Issue by matthias-margush** [mawww/kakoune#3373]
File [detection](https://github.com/mawww/kakoune/blob/master/rc/detection/file.kak#L3) doesn't work on the mac:
```
჻ file -b -i -L contrib/describe_sessions.sh
regular file
```

This works:
```
჻ file -b --mime-type -L contrib/describe_sessions.sh
text/x-shellscript
```

It looks like this is because the its version of `file` treats the `-i` flag differently, using `-I` as the short form of `--mime-type`:
```
჻ man file | grep -i -- -i
     -i      If the file is a regular file, do not classify its contents.

     -I, --mime
             Causes the file command to output mime type strings rather than
             the more traditional human readable ones.  Thus it may say
             `text/plain; charset=us-ascii' rather than ``ASCII text''.

     --mime-type, --mime-encoding
             Like -I, but print only the specified element(s).
```

The `BufOpenFile` hook used the `--mime-type` option before, but this was [changed](https://github.com/mawww/kakoune/pull/2859). The long flag does not appear to be available in the mac manual [linked](https://ss64.com/osx/file.html) in the [commit](https://github.com/mawww/kakoune/commit/313c6eadc7ddd79f5057298e9d9751eb284a0857), but it is available on the current Mac OS.

**Comment by Screwtapello** [comment]
The [Linux file command](https://manpages.debian.org/buster/file/file.1.en.html#i) has:

```
-i, --mime
    Causes the file command to output mime type strings rather than the more
    traditional human readable ones. Thus it may say ‘text/plain; charset=us-ascii’
    rather than “ASCII text”.
--mime-type, --mime-encoding
    Like -i, but print only the specified element(s).
```

Normally, a long option (with a `--`) is a GNUism not portable to other operating systems. It looks like somebody saw that the closest short option was `-i`, and hey, [POSIX does specify a `-i` flag](https://www.unix.com/man-page/posix/1P/file/), so that must be the one to use! Unfortunately, POSIX specifies `-i` as:

```
-i	 If a file is a regular file, do not attempt to classify the type of the
         file further, but identify the file as specified in the STDOUT section.
```

...so apparently there's no guaranteed portable way to get a mime-type out of `file(1)`. However, we can still check for *de facto* portability.

- Linux uses `--mime-type`, as described above.
- macOS uses `--mime-type`, courtesy of the screenshot provided above.
- FreeBSD [uses `--mime-type`](https://www.freebsd.org/cgi/man.cgi?query=file&apropos=0&sektion=0&manpath=FreeBSD+12.1-RELEASE+and+Ports&arch=default&format=html)
- NetBSD [uses `--mime-type`](https://netbsd.gw.com/cgi-bin/man-cgi?file++NetBSD-current)
- OpenBSD [uses `--mime-type`](https://man.openbsd.org/file) and does *not* use the same implementation as everybody else
- Solaris [does not support MIME types at all](https://docs.oracle.com/cd/E23824_01/html/821-1461/file-1.html#scrolltoc)

From the wording in the macOS screenshot, it looks like macOS' implementation is based on the regular implementation, but they've patched it to be POSIX-compatible at the expense of being everything-else compatible. I guess that's because they go to the effort of [being Unix certified](https://www.opengroup.org/openbrand/register/brand3653.htm).

I guess `--mime-type` really is the most portable option.

**Comment by matthias-margush** [comment]
From your research @Screwtapello It looks like `--mime-type` will work most places.

Would it be worth adding a `filecmd` option that can be customized if needed?
Does the build system currently offer a way for a default to be baked in by a package manager for a target system?

**Comment by lenormf** [comment]
The flags passed to `file` are an implementation detail, so if `--mime-type` works better than `-i` on most distributions, let's use that.

Package managers that need to change the command to something else can create a patch that edits it directly; there's currently no other way to change hardcoded defaults.

An option could be worth it if users would want to use another tool that performs MIME type detection (I'm not aware of such alternative implementation, are there any?).

**Comment by SolitudeSF** [comment]
> I'm not aware of such alternative implementation, are there any?

https://metacpan.org/release/File-MimeInfo
and `xdg-mime` from `xdg-utils` prefers that to `file`, if that means anything.

**Comment by Screwtapello** [comment]
Peeking at `xdg-mime`, it looks like there's a bunch of tools that do MIME-type detection - `file --mimetype` uses the traditional database, `mimetype` is a different implementation (as pointed out by SolitudeSF) using `find`'s database, KDE has its own `kmimetypefinder` tool using its own database, and GNOME has apparently transitioned through three different tools for consulting *its* database. And then of course there's `xdg-mime` itself as a meta-tool.

**Comment by mawww** [comment]
I believe this is fixed now
