### ISSUE TITLE
Control picture codepoints are annoying for Unicode characters

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#3389]
Introduced in bc8a9d82c3f028681c3f78075110bdd17326d679, Unicode characters, such as french quotes are replaced by control picture codepoints.

**Comment by Screwtapello** [comment]
The code in question says:

    if (c <= 0x21)

...but [StackOverflow suggests](https://stackoverflow.com/questions/2054939/is-char-signed-or-unsigned-by-default) that at least on x86, `char` is typically signed, so that condition will pick up all the bytes of a UTF-8 multi-byte sequence as well as regular control characters.
