### ISSUE TITLE
Installing from source: should we move file from `rc/` to the config folder ?

### ISSUE THREAD

**Issue by joeitu** [mawww/kakoune#3415]
In the source code, the folder `rc/` contain a lot of interesting `kak` file and other. Are we suppose to load them manually in our kakrc or should it be done automatically during install ?

To get `.scala` file highligh, I did had to copy `rc/filetype/scala.kak` to my config folder `.config/kak/autoload/`, is this normal behavior ?

**Comment by caksoylar** [comment]
See this section in the wiki: https://github.com/mawww/kakoune/wiki/Running-commands-at-startup#the-autoload-directory

This is the expected behavior where if a personal autoload directory under `%val{config}/autoload` exists, kak will not source the system default. A workaround is also documented in the wiki page.

**Comment by lenormf** [comment]
Scala file highlighting should work out of the box for all files with the `.scala` extension.

If it doesn't, it a bug and shouldn't require the user to do anything. Please post reproduction steps and the errors in `*debug*` if any, so we can fix it.

**Comment by joeitu** [comment]
I used the wiki solution from @caksoylar 's comment. 

I think the fact that creating and  adding file to the `autoload` break the default load of all the `rc/` file is a bit weird and confusing when you are a newbies and try to custom your kak.
