### ISSUE TITLE
use regex backreference with <a-a>c ( "custorm object desc")

### ISSUE THREAD

**Issue by sucrecacao** [mawww/kakoune#3450]
Hello, 
Today I tried to use a group back-reference for a custom object desc.
Lets assume the following buffer
`ab  X  ba` with X being the position of my cursor.Pretend `a` and `b`  are quotes and double quotes. I used letter to improve readability. 

I wanted to select closest quote. So I tried the following:
`<a-a>c` to enter custom object prompt, followed by:
`(a|b),\1`  
In detail:
`(a|b)` I want to match one of those quotes
`,` comma to separate the open regex to the close regex. And then tried:
`\1` to get  the result of the submatch of the opening regex .  ( See regex groups backreference more info ) . But this doesn't work. 

I can't use `(a|b)` in my closing regex because it won't work with the following case:
`a  X b  a`   
My selection will be `a X b` instead of `a X b a`

Is there a way when using alternative patern on the opening regex to retrieve the matched patern on the closing regex ?

Hope that make sens.

**Comment by Screwtapello** [comment]
When `<a-a>c` asks you to an "object desc", it's really asking for two regexes. The string you type gets split on the comma, and each half is compiled as a separate regex, invoked at different times in different ways to find the surrounding object. That's why you can't use a backreference in the second regex: it doesn't have anything to refer to, since the group is in a different regex entirely.

Generally I think the `<a-a>` menu tries to be specific rather than clever. It lets you match `"` strings and `'` string individually, and doesn't try to guess which one you mean, because sometimes you wind up in a situation like this:

    "Don'tXDo It"

(where X is the cursor again). If you select backward to the previous quotish character, you'd find the apostrophe in "Don't", and then if you select forward to the next apostrophe you might wind up anywhere, or fail to select anything at all.

If you just want to say "select the thing I'm in" and not have to worry about the exact syntax, and your document happens to be in one of the programming languages supported by the Tree Sitter project, you might be interested in the [kak-tree](https://github.com/ul/kak-tree) plugin.

**Comment by sucrecacao** [comment]
It make total sense . Thanks for pointing to the kak-tree project.

**Comment by mawww** [comment]
I might add that for performance reasons, Kakoune regex do not support backreferences, as they are not implementable using an automaton (AFAIR).
