### ISSUE TITLE
Ui breaking when used with tmux + ssh

### ISSUE THREAD

**Issue by in42** [mawww/kakoune#3487]
### Steps 
ssh to a remote machine. Open tmux. Open Kakoune and use prompt to try to open a file. 

### Outcome 
The ui is breaking and not getting refreshed correctly. Screenshot attached below:
![Screenshot from 2020-05-16 20-42-44](https://user-images.githubusercontent.com/12832671/82123298-3d821a00-97b6-11ea-93a8-b0ef1c94dca8.png)
![Screenshot from 2020-05-16 20-42-51](https://user-images.githubusercontent.com/12832671/82123300-4246ce00-97b6-11ea-9671-853fce28ab1b.png)

### Expected 
The ui should refresh correctly like it happens locally.

**Comment by Screwtapello** [comment]
What terminal are you invoking `ssh` in?

What is `$TERM` set to before you launch `tmux`?

What is `$TERM` set to inside tmux?

**Comment by in42** [comment]
1. What terminal are you invoking ssh in?
alacritty. I am ssh'ing this way: `TERM=xterm-256color ssh username@hostname`
2. What is $TERM set to before you launch tmux? xterm-256color
3. What is $TERM set to inside tmux? xterm-256color

**Comment by Screwtapello** [comment]
`xterm-256color` is perhaps not the best `TERM` for alacritty, but it's probably the best one available, so that's fine.

`xterm-256color` is definitely the wrong `TERM` for inside tmux. Try running each of these commands on the remote host:

- `infocmp tmux-256color | grep setaf`
- `infocmp screen-256color | grep setaf`
- `infocmp tmux | grep setaf`
- `infocmp screen | grep setaf`

The first one that *doesn't* say "infocmp: couldn't open terminfo file..." is the best `TERM` to use inside tmux on that server.

**Comment by in42** [comment]
It is working with tmux-256color. Thanks!
