### ISSUE TITLE
[builtin-terminal-ui] Artifact on click

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3506]
### Steps 

I don't have a reliable way of reproducing the bug. I clearly remember clicking on an arbitrary line, then the glitch occurred.

Plain Kitty.

### Outcome 

Notice the relative line number (`24` instead of `1`), and the escape sequence being printed (`[27H`) before the misrendered line.

![](https://files.catbox.moe/3ggqfl.png)

**Comment by lenormf** [comment]
I can reproduce the issue without using the mouse as well, random sequences appear on screen.

**Comment by Screwtapello** [comment]
If you (or anyone else) can screenshot or otherwise record the exact sequences involved (usually beginning with a `[`, optionally some semicolon-separated numbers, then ending with a letter) that should help pin down what Kakoune was doing at the time, and maybe what previous sequence got corrupted or ignored to cause this sequence to be displayed rather than interpreted.

**Comment by Screwtapello** [comment]
It would also help to mention what terminal you're using. I've never seen artifacts on libvte-based terminals, for example.

**Comment by mawww** [comment]
From your screenshot, it looks like that `\033[8H` sequence got somehow misinterpretetd and and did not jump to the start of next line (as we can see that its followed by the next line content, correctly colored).

What is quite interesting is that `|` character preceeding the 8, I wonder where this comes from, and what happened to our CSI introducer.

Kakoune's code is always writing those sequences atomically, so I would not expect an issue with partially written sequences.

**Comment by lenormf** [comment]
>What is quite interesting is that `|` character preceeding the 8

It's not, it's a `[`. I double-checked on the terminal after looking at the screenshot when I posted the command.

The upper notch is cropped from the image (I won't try to make my screenshots pixel-perfect in the future and aim large), and the lower one simply isn't rendered properly, so it looks like a pipe.

I'll have to post more screenshots until we can speculate, I think I recall seeing semicolons in the artefacts at some point, so I'm not convinced the sequence itself is important.

**Comment by Screwtapello** [comment]
I'm pretty sure it's not the escape sequence in `set_cursor_pos()` (line 30) because in the screenshot the glitched sequence is immediately followed by the next line of text, which suggests it occurs during a repaint.

The escape sequence that's immediately followed by an `M` sequence (line 260) does not do any painting; it's not possible for it to glitch two lines together as the screenshots show, so I don't think it's that on either.

The escape sequences on lines 273 and 275 are mutually exclusive on each iteration of the loop, so I guess if the problem is caused by the previous iteration, it could be either of them... but that still narrows it down pretty far.

I note that Kitty has an option to record the bytes sent by the application running in the terminal (`--dump-bytes=/path/to/file`), so if we ever find a way to reproduce the glitch, we can record it and find out exactly what was sent before the glitch occurred.

**Comment by mawww** [comment]
you can also just use `script` to get a dump of the terminal control sequences.

If the previous character is a `[`, then it seems very likely this is `terminal_ui.cc:275` and for some reason the escape character got dropped, as line 273 would have inserted empty lines (with `\033%dL`) which would have erased the data before the cursor.

Is that error transient (does it dissappear on redraw with `<c-l>`) or does it actually stay like that ? I wonder if it could be that some escape sequence generated by kitty ends up adding some data in the Kakoune buffer that would then get interpretted as an escape sequence when written back and would consume that `\033` from line 275.

**Comment by mawww** [comment]
Also, can you try running kitty from another terminal, here I get some errors on kitty's stdout:
```
[167 10:07:57.859097] [PARSE ERROR] Unrecognized DCS = code: 0x32
```

This suggest the synchronized update escape sequences (thats the only DCS sequences we emit) are not compatible with kitty, maybe those are putting kitty in a bad state.

**Comment by mawww** [comment]
I suspect https://github.com/kovidgoyal/kitty/issues/2764 could be the culprit.

**Comment by mawww** [comment]
Got a few things fixed in Kitty recently, could you check if this is still happening on latest kitty git ?

**Comment by lenormf** [comment]
There's still rare flickering, barely perceptible. I'll see how it goes over the next few days.

**Comment by lenormf** [comment]
Didn't help.

**Comment by lenormf** [comment]
Haven't seen this in a while, closing in the meantime.
