### ISSUE TITLE
Entering diacritics on macOS with Alt key produces weird characters

### ISSUE THREAD

**Issue by marekkowalczyk** [mawww/kakoune#3563]
### Steps 

Press e.g. `Alt-a` in an open buffer; macOS keyboard layout "Polish-Pro".

Analogous behavior with other diacritic characters accessed by pressing `Alt-letter`

### Outcome 

Polish diacritic character `ą`.

### Expected 

A weird character.

**Comment by Screwtapello** [comment]
I think you have swapped the "Outcome" and "Expected" sections of the template? You expected `ą` but you got "a weird character" instead? Can you paste this weird character, or a screenshot?

Traditionally on macOS, the Option (Alt) key is used to produce diacritics, and most macOS terminal emulators will (by default) match the behaviour of any other application. However, many terminal apps (including Kakoune) expect the Alt key to be available for their own key-bindings, so macOS terminal emulators typically have an option to send Alt-modified keys through to the app, instead of interpreting them as diacritics. Alt-A in Kakoune (in normal mode) is supposed to bring up the "Select surrounding object" menu, for example, although in insert mode it does nothing.

**Comment by marekkowalczyk** [comment]
1. Yep, I didn't expect a weird character :)

2. I did some DDX and found both positive and negative bug scenarios.

The first image is `kak` on `dvtm` on `alacritty`. 
<img width="477" alt="Screenshot 2020-07-07 at 07 59 15" src="https://user-images.githubusercontent.com/4373765/86723177-f2eb8400-c027-11ea-91e7-5866fc8b433c.png">

The image below is `kak` on `tmux` on `alacritty` or on plain `bash` shell.

<img width="397" alt="Screenshot 2020-07-07 at 08 01 43" src="https://user-images.githubusercontent.com/4373765/86723439-31813e80-c028-11ea-8bc0-c174a03ed56e.png">

In both cases the test string was `Łączność na śniegu.` repeated several times. Interestingly, some accented letters, when entered for the second time, displayed correctly. 

After a bit of poking around I determined the bug only reproduces on `dvtm`, regardless of the terminal emulator.

Can this be solved in `kek`?

**Comment by Screwtapello** [comment]
I'm not familiar with dvtm, but I did find [a comment from the author](https://github.com/martanne/dvtm/issues/13#issuecomment-168430052) saying the code "seems to be severely broken with regard to Unicode handling" (the comment is from 2016-01, but there haven't been any official releases  in 2016-02 or later, so I assume the comment is still true).

Out of curiosity, what does the `locale` shell command produce, when run inside dvtm versus inside tmux (or directly inside alacritty)?

**Comment by marekkowalczyk** [comment]
In all cases the output of `locale` is the same:

```
LANG=
LC_ALL="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
```

Issuing `export LC_ALL=pl_PL.UTF-8` doesn't change the offending behavior in `dvtm` nor impacts  `kak` in other environments.

**Comment by Screwtapello** [comment]
I'm afraid I'm out of ideas, then, sorry. :/

**Comment by marekkowalczyk** [comment]
Seems the only hope is wait for resolution of the UTF-8 problems in DVTM.
