### ISSUE TITLE
"Extend mode" canceled when cursor and anchor are stacked

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3577]
### Steps 

* hit <kbd>a</kbd> on a non-empty line
* optionally, enter any character, for example <kbd>space</kbd>
* hit <kbd>backspace</kbd> until the cursor reaches the anchor (making length-one selection)
* enter any character

### Outcome 

The selection is no longer extended, we're back in "insert" mode.

### Expected 

Characters still extend the selection, as was the case before anchor and cursor were stacked.

**Comment by mawww** [comment]
Why do you consider that a bug ? To me thats the expected behaviour, appending does not guarantee the anchor will stay in place, its usually the case because insertion happens after the anchor because the cursor is after the anchor, but once you force the cursor to be onto the anchor, inserted text now appears before that anchor and it naturally moves.

**Comment by lenormf** [comment]
I don't really know what to think, I guess I wanted to know the official stance on that behaviour rather than want it changed.

From a high-level perspective, I think users will expect <kbd>a</kbd> to *always append characters to a single selection*, and that expectation is broken in one specific case.

At the low-level (when considering the cursor's position in relation with the anchor's after every key press), it also makes sense to me.

**Comment by mawww** [comment]
I dont think this will change, I can see how it could look surprising, but seems like a minor issue and keeping the implementation consistent seems more important.
