### ISSUE TITLE
To highlight the numbers

### ISSUE THREAD

**Issue by rezzovskij** [mawww/kakoune#3584]
why does not work the highlights?

`add-highlighter window/ regex \d+ 0:yellow`

But it works

```
hook global WinSetOption filetype=.* %{
     add-highlighter window/ regex \d+ 0:yellow
}
```

**Comment by occivink** [comment]
It depends where you're executing the first piece of code. If you put it in your kakrc, it won't work since there is no 'window' at the time of execution. However, if you execute it interactively it will work for the current window.
Since you want to globally highlight all numbers, you can try `add-highlighter global/ regex \d+ 0:yellow`

**Comment by rezzovskij** [comment]
> It depends where you're executing the first piece of code. If you put it in your kakrc, it won't work since there is no 'window' at the time of execution. However, if you execute it interactively it will work for the current window.
> Since you want to globally highlight all numbers, you can try `add-highlighter global/ regex \d+ 0:yellow`

This is first what i did. But this has not worked. Is there a way to highlight numbers without conflicts with other highlighters?

**Comment by Screwtapello** [comment]
When you say "this has not worked", does it not even work when editing a `.txt` file? Or does it only not work when editing a file type with its own highlighting for numbers?
