### ISSUE TITLE
`echo %val{config}/kakrc` put a space before /kakrc

### ISSUE THREAD

**Issue by sucrecacao** [mawww/kakoune#3595]
### Steps 
call command: `:echo %val{config}/kakrc<ret>`

### Outcome 
`/home/user/.config/kak /kakrc`

### Expected 
`/home/user/.config/kak/kakrc` ( no space between kak/ and kakrc

**Comment by krobelus** [comment]
I believe this is expected. You need to use `echo "%val{config}/kakrc"` with the double quotes to get a scalar context.

There are some explanations in `:doc command-parsing`. Bare `%val{config}` is expanded to a word, as is `/kakrc`.
The rationale is probably because an expansion can result in multiple words, in that case separating the words  makes more sense:
```sh
set-register a x y z
echo %reg{a}/kakrc
# x y z /kakrc
```
