### ISSUE TITLE
Additional modifiers.

### ISSUE THREAD

**Issue by Josef-Vonasek** [mawww/kakoune#3601]
I am not sure if this goes in the spirit of kakoune design, but just today I have realized how much more pleasant is holding `CTRL` and hitting 3+ times `DEL` than `dwdwdw` in vim ( assuming I don't know how many words I want to delete in advance ).

So I thought, what if there was vim like editor that used this notion of `hold a key => change behavior of commands`.

For example holding `w` would make commands operate over words. This means that 
- `w+ddd` would delete three words
- `w+hhh` would move cursor back three words (which frees `b` for other shortcuts)

Now, I myself am not a vim mage, I use it only to move in text without using mouse in intellij, so perhaps my idea isn't as great as I think. Nevertheless I wanted to share my findings with someone, who aims to improve upon vim design.

**Comment by alexherbo2** [comment]
The idea can be refined, but I like the principle of adding more modifiers.

`w+ddd` will not work in the Kakoune paradigm however, because of the selection—action order.

How to express holding in the scripts?  A `<w-h>` (instead of `w+hhh`) notation could be used, but it will conflict if `c`, `a` and `s` keys can be modifiers.

**Comment by mawww** [comment]
I dont think this would fit well in the existing Kakoune model, but independently of that this cannot be implemented in a widely compatible way due to limitations on how terminal input currently works, there is no key down/key up events in terminals so you just cannot use an arbitrary key as a modifier. Some terminals do have extensions to support that, but we cannot tie Kakoune to the use of a specific terminal emulator.
