### ISSUE TITLE
Start reading terminal input from before UI appears

### ISSUE THREAD

**Issue by SeerLite** [mawww/kakoune#3635]
### Feature 
Currently, I can't run `kak` and immediately type in commands because the UI has to be completely initialized to read input. I'd like kakoune to queue all the keypresses happening during the loading stage (which can take some time depending on the configuration) and reproduce them when ready. I think kakoune used to do this some time ago, but I might be confusing it with another editor. As an example, neovim can do this (and I'm pretty sure vim can too). 
### Usecase 
Sometimes I know exactly what I wanna do when I start editing a file.
For example, I might want to quickly change a specific line starting with `examplecmd`, so I'd run `kak <file>` and immediately start off with `/examplecmd`. However, I have to wait for the configuration to load and the UI to appear, and type my commands only after the fact.

And thanks for this amazing editor!

**Comment by Screwtapello** [comment]
I think I can reproduce this behaviour on the builtin_terminal_ui branch without a complex configuration:

1. Launch Kakoune with a delay, so the user has a chance to write to stdin before Kakoune starts reading it:

        (sleep 5; exec kak -n)

2. Type a command Kakoune will understand, like `:q<ret>`
3. Wait for the timer to expire and Kakoune to launch.

Actual results:

  - Kakoune starts up as normal

Expected results:

  - Kakoune executes `:q` and immediately exits.

Notes:

  - Vim 8.2 behaves as expected, if launched with the equivalent command-line `(sleep 5; exec vim -u NONE -U NONE)`.
  - Just piping to Kakoune does *not* have the same effect, because Kakoune detects when stdin is a pipe and reads that content into a buffer, instead of reading the keys as-is.

As I understand it, this is how things are expected to work: whatever the user types at the terminal gets sent to the stdin of the current foreground process. If keystrokes are being dropped, it must be because Kakoune is actively dropping them, but I can't immediately see anything like that in the source-code.

**Comment by SeerLite** [comment]
> As I understand it, this is how things are expected to work: whatever the user types at the terminal gets sent to the stdin of the current foreground process.

That's what I thought too, considering most CLI programs will do that. Wasn't sure of it though so that's why I labelled it "feature request" instead of "bug". I hope that's not too important

**Comment by SeerLite** [comment]
Thank you so much!
