### ISSUE TITLE
[builtin-terminal-ui] Screen corruption in PuTTY

### ISSUE THREAD

**Issue by greneholt** [mawww/kakoune#3705]
### Steps

Using the latest version of PuTTY (v0.74) and commit 948514e3 of the builtin-terminal-ui branch, open a file and scroll.

This happens regardless of whether TERM is set to xterm-256color or putty-256color.

### Outcome

![image](https://user-images.githubusercontent.com/145090/92016882-31dc4400-ed10-11ea-994d-deb84aa2f4f3.png)

Clicking around with the mouse will produce an even more corrupted screen:

![image](https://user-images.githubusercontent.com/145090/92017899-ab286680-ed11-11ea-8415-580c9ff8f31f.png)

It appears that Kakoune is not succeeding in clearing the screen when redrawing. Everything works fine on the master branch, without true color support however. When running Kakoune within tmux, everything also works fine.

**Comment by Screwtapello** [comment]
I can reproduce this behaviour in Pterm, which is just the terminal-emulation parts of PuTTY ported to Unix. The problem is (I think) ultimately a bug in PuTTY: it does not support [Device Control String sequences](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Device-Control-functions). If I run the shell command:

    printf "\033Pabc\n\033\\"

...in PuTTY, it prints "abc", but if I run that same command in xterm or GNOME Terminal, it correctly prints nothing. The specific DCS sequence Kakoune is trying to use is [the iTerm2 synchronised update sequence](https://gitlab.com/gnachman/iterm2/-/wikis/synchronized-updates-spec), but PuTTY doesn't have to *understand* it, it just has to ignore sequences it doesn't understand.

Unfortunately, it's not immediately clear to me how to report this bug to PuTTY, nor how interested its maintainers would be in fixing it.

**Comment by greneholt** [comment]
Thanks for identifying the problem! I don't know if the developers of PuTTY would have any interest in fixing it, but thankfully since I always run Kakoune inside tmux (which filters out these control characters), it isn't a big issue.

**Comment by greneholt** [comment]
Closing this issue because it is a problem with PuTTY, not Kakoune.
