### ISSUE TITLE
parse error on pattern matching with angle brackets inside a custom map

### ISSUE THREAD

**Issue by eko234** [mawww/kakoune#3722]
i want to map a regex search to find merge conflicts in a file, such regex works well in kakoune
when doing "/^<<<<<<<.*?>>>>>>>" 
### Steps 
anyhow, when i try to map it to a custom key bind i get a error saying 
'evaluate-commands' 116:1: 'source' 1:1: 'map' unable to parse <>
### Expected 
it should be something doing with the fact of how certain keys are written in the from <key>
and the parser interpreting this as an error, there must be a way to express this regex

**Comment by krobelus** [comment]
That's expected; the `map` and `execute-keys` commands interpret strings as sequences of key presses.
According to `:doc mapping`, alternate key names in angle brackets can be used for some characters.
Because of this, the opening angle bracket is the only special character and needs to be escaped.
You just need to replace `<{7}` with `<lt>{7}`.

**Comment by eko234** [comment]
> That's expected; the `map` and `execute-keys` commands interpret strings as sequences of key presses.
> According to `:doc mapping`, alternate key names in angle brackets can be used for some characters.
> Because of this, the opening angle bracket is the only special character and needs to be escaped.
> You just need to replace `<{7}` with `<lt>{7}`.

thank you so much, i did "map global user C %{/([<lt>]{7}(.*)([>>]{7}))}" and now all works as expected, i'm reading the :doc mapping document and all is getting clearer, thanks again!
