### ISSUE TITLE
modelines read one line more than expected

### ISSUE THREAD

**Issue by f380cedric** [mawww/kakoune#3733]
### Steps 
1. write this in scratch:
```python
# kak:tabstop=1:
# kak:tabstop=2:
# kak:tabstop=3:
foo
foo
foo
foo
```
2. exec: set b modelines 1
3. exec: modeline-parse

### Outcome 
tabstop is equal to 2. modeline-parse reads $((modlines+1)) lines

### Expected 
tabstop is equal to 1. modeline-parse reads $modelines lines.

**Comment by lenormf** [comment]
The `modelines` option refers to how many lines will be scanned to try and grab a modeline, and it expects a single one to be present among those lines. The bug you describe was never caught because the implementation doesn't expect to find several of them, I don't know what it should do if that occurred.

Is it common to have files with several modelines? Do you know if other editors parse them all?

**Comment by f380cedric** [comment]
> Is it common to have files with several modelines?

I do not think it is common.
But it is allowed "by standard" (vim), and hence should works.
I am expecting that *some* people splits their modelines for whatever reason.

> Do you know if other editors parse them all?

vim and derivatives parse all `modelines` lines.

It is not necessary an issue w.r.t multiline modelines, but w.r.t documentation.
I am expecting that if I have a modeline-like on line 4 but specified `modelines` as 3,
then it should not read modelines after line 3.

**Comment by lenormf** [comment]
It's an actual bug, the editor does read one more line than it should. I was thinking about the implications of your reproducer being interpreted as expected.

According to the [Vim documentation](http://vimdoc.sourceforge.net/htmldoc/options.html#modeline-version), modelines can be predicated on the version of the editor. But Kakoune ignores those, so I wonder what makes most sense: reading all modelines, the first, the last… ?
