### ISSUE TITLE
Disable modelines

### ISSUE THREAD

**Issue by f380cedric** [mawww/kakoune#3734]
### Feature 
Allow user to disable modelines (eg by setting  `modelines` to 0`).
Disabling modelines may be important in some situations (eg. reading untrusted files, like emails)

**Comment by lenormf** [comment]
Out of curiosity, what kind of trouble do you expect from reading modelines in arbitrary files? The only options that are modified are formatting options:

https://github.com/mawww/kakoune/blob/ec3d7c31040afaee65afde15832d9b0ed6b2224d/rc/detection/modeline.kak#L22-L50

**Comment by f380cedric** [comment]
> Out of curiosity, what kind of trouble do you expect from reading modelines in arbitrary files? The only options that are modified are formatting options:

Normally, security wise, none. But yes, formatting, eg. messing up with wrapping.
For example, it is disabled on `filetype=mail` for eg. avoid `nasty "jokes" (e.g., setting 'textwidth' to 5)`

Note that even if we do not think (or see) that it is a security issue, it could be (and it will be).
You never know what people are able to craft to bypass your parser. Bad people are smart.

For example, I am not a bad person, not even a sec. guy.
However, I can easily bypass your parser by crafting something like this:

```
# kak: tabstop=2;set-option	buffer	autowrap_column	1
```

Using `;` and tabs as space separator allows me to run any (?) arbitrary code.
This is why we should be able to disable that feature, even if we trust the parser.

**Comment by lenormf** [comment]
Interesting find, quoting the value before passing the `set` command to `eval` should fix it.

I'm just not too fond of executing a shell, to check if `modelines` is set to 0, every time `:modeline-parse` is run. It's also a side effect, and I intended that function to be pure — it does what it says, and won't quit prematurely unexpectedly.

Since your configuration is calling that command, why not exclude some filetypes (like `mail`), as you suggested? It's more idiomatic than setting the `modelines` options conditionally.

Regarding the security issues, users who do want to have modelines parsed will run into them anyway, as they won't be touching `modelines` at all. Do you have any more?

**Comment by f380cedric** [comment]
> I'm just not too fond of executing a shell, to check if `modelines` is set to 0, every time `:modeline-parse` is run.

Every time modeline-parse is run, it runs modeline-parse-impl, that executes a `%sh{}`.
I am quite new, but I am guessing that `%sh{}` starts a shell.

Anyway, I do not think that we need to check that variable (see below).

> It's also a side effect, and I intended that function to be pure — it does what it says, and won't quit prematurely unexpectedly.

It should not be an issue if #3733 is solved. The selection should be empty.
If `modelines` is 0, then it reads 0 line. The function will stay "pure" (whatever it means).

> Since your configuration is calling that command, why not exclude some filetypes (like `mail`), as you suggested? It's more idiomatic than setting the `modelines` options conditionally.

Yeah, I totally misread that part. I saw `modeline.kak` in my rc, I wrongly assumed it was executed at file opening (like `file.kak`).
There is no hook in the former.

> Regarding the security issues, users who do want to have modelines parsed will run into them anyway, as they won't be touching `modelines` at all. Do you have any more?

No, I did not dig any further.


Since it is not enabled by default, and I can filter by filetype. I'll close.

Let's keep the discussion around the arbitrary code execution in its specific ticket.

**Comment by lenormf** [comment]
The default count for movement primitives is 0, but `0j` is the same as `1j` so you would need to run an additional shell to check the value of `modelines` explicitly.

I don't know if users expect the `modelines` option to act the same way as in Vim, if they don't care we might as well remove it entirely. If they do, we'll have to check for its value, it's more consistent.

I think this issue is still relevant, you can re-open it if you want Vim cross-compatibility of the option to be implemented, I might make a PR for the entire file that will close it automatically.

**Comment by lenormf** [comment]
Forgot to link to the educational content there.

>The function will stay "pure" (whatever it means).

[Pure function on Wikipedia](https://en.wikipedia.org/wiki/Pure_function).
