### ISSUE TITLE
Unify user experience for de-indentation for different file types

### ISSUE THREAD

**Issue by m-kru** [mawww/kakoune#3764]
In my humble opinion, `kakoune` should provide unified approach for de-indentation for every supported file type.
I propose to **never** de-indent anything automatically. Why?

1. It is source of confusion. Different kak filetypes support de-indendation to some extent or they do not support it at all.
 You never know what to expect. With unified approach, the user experience would be better as there would be only single rule *Nothing is de-indented automatically.*  You can say, that this is one extra keystroke. Well, it is, however now, when you edit multiple different file types and you encounter some stuff that is not auto de-indented, you have to leave insert mode, go line above and `<a-lt>`, it is annoying and slows down much more than pressing `Backspace` few times.

2. Auto de-indenting is counter intuitive. Imagine for now, that there is no support for indentation and  de-indentation. In case of indentation you type some line with some keyword, then you hit the `Enter` and in the newline you hit `Tab`. In case of de-indentation you press `Backspace`, then you type. Now, in case of automatic indentation the flow is exactly the same as by hand, except that the `Tab` after `Enter` is inserted automatically. By hand: `type -> Enter -> indent`, automatic: `type -> Enter -> indent automatically`.  In case of de-indentation the automatic flow does not have the same order as doing it by hand. By hand: `de-indent -> type -> Enter`, automatic: `type -> Enter -> de-indent automatically`.

3. Auto de-indenting is a source of bugs/weird behaviors. Example:
![image](https://user-images.githubusercontent.com/26227737/94331981-450dc700-ffd1-11ea-8721-d45aaca306e4.png)
Now see what happens when I type `o`:
![image](https://user-images.githubusercontent.com/26227737/94331993-65d61c80-ffd1-11ea-8d58-218ee30ec209.png)
There are more such relishes defined within *filetype*.kak files.

**Comment by sjjf** [comment]
The issue you noted with the `sh` filetype handler is a flat out bug, which has been annoying me for ages (particularly since I wrote the shell auto-indentation code in the first place) - I've just submitted a pull request that fixes it.

I don't have much to say on the broader point, except that it seems like the trend is towards standardised formatting with tooling to support it - we already have pretty good mechanisms for integrating those tools, and they'll always do a better job than a filetype handler, so the whole question is probably pretty moot . . .

**Comment by m-kru** [comment]
>  standardised formatting with tooling to support it 

Can you provide an example?

**Comment by sjjf** [comment]
rustfmt would be the thing that comes to mind first - it's probably one of the most formal, too, since the language devs have basically said "this is the way Rust code should be formatted, and here is a tool that will format your code according to these rules" . Go provides gofmt, V provides vfmt, and this seems to be something that new languages are increasingly including in their tooling, particularly with the explosion of things like language servers - formatting is one of the things that language server implementations are designed to support.

I'm in the process of moving all my Python code over to being formatted using Black (via kak-lsp and pyls), and once that's done I'll probably enable auto-formatting. If I could find a working Puppet language server I'd do the same, and I could toss the silly little wrapper script I have around puppet-lint that I'm using at the moment to format things. It really is the way of the future, given the direction that the tooling and language server implementations are going. And Kakoune already has pretty good support for this stuff - kak-lsp is great, and I find it all integrates nicely (modulo the limitations of the actual language server you're using).

**Comment by m-kru** [comment]
@sjjf I was expecting you to mention tools like `gofmt`, `rustfmt` and technologies like *LSP*. Here are at least 6 arguments why I think providing unified behavior by default is still valuable.

1. I have recently installed Linux on some machine where I had to encrypt partitions with [dm-crypt](https://wiki.archlinux.org/index.php/Dm-crypt). It requires writing some configuration files and short scripts. Installing LSP or similar tools to get nice formatting in such scenario is pure overhead.
2. I often I have to log to remote machines and do some stuff. If I am not in charge of the machine, I usually can ask the system administrator to install my favorite text editor. However, I am not going to ask him to install all formatting, LSP tools because *maybe*  it will be valuable to have them. I do not have privileges to install anything and any interaction with the administrator can take days. I just want to have sane, unified default behavior.
3. When you are a beginner in some domain, you usually do not start with installing such tools. For example, when you start learning some new programming language you probably try it without this extra stuff.
4. Not all languages have such tools.
5. You usually call formatting tools on file save (I have never met anyone who calls it on each keystroke, although this is possible). This means, you probably write some block of code, for example `if` block and then you save and get auto format. I do not know what others do, but while typing the if block I already try to keep consistent formatting.
6. If you use the tools and technologies you have mentioned, then does it make a difference to you what is the default behavior? In my humble opinion no, as *filetype.kak* files are not coupled with these tools.

Please note, that what I am asking for is sane, unified, intuitive default approach for handling de-indentation.

**Comment by sjjf** [comment]
That's all well and good, but first you have to actually come up with a sane, unified and intuitive default, which is going to be a challenge across the range of languages supported in the default distribution . . . Also, a default that people will actually accept - personally, I'm not a fan of having to manually manage indentation after many years of having tools to handle it for me, and I suspect there are a lot of other people who'd feel the same way. And a default that won't get in the way of the tooling I've mentioned - it may not be available in all cases, but it's definitely an extremely important use case and one that's only getting more important.

Fortunately for all of us this kind of decision is ultimately up to our friendly local maintainer . . .

**Comment by m-kru** [comment]
> That's all well and good, but first you have to actually come up with a sane, unified and intuitive default, which is going to be a challenge across the range of languages supported in the default distribution . . . 

No it is not a challenge. I get an impression, that you think that I want to do some revolutionary change. It is all super easy. By default nothing would be automatically de-indented.

It is perfectly fine to auto insert de-indented code. This is actually what is expected and what makes the difference. Take an example from `go`.
![image](https://user-images.githubusercontent.com/26227737/94365605-981b7300-00d2-11eb-87f5-ed8e7da9aecf.png)
After hitting Enter we get:
![image](https://user-images.githubusercontent.com/26227737/94365628-b5e8d800-00d2-11eb-9edb-da91a8e01c5b.png)

Also if any external tools *overwrote* the default behavior it would be perfectly fine.

> Also, a default that people will actually accept

What is in your opinion more clear and easier to remember?
1.  Nothing is de-indented by default.
2. In language X, automatic de-indentaiton happens after keywords a,b,c. In language Y there is no automatic de-indentation. In language Z automatic de-indentation happens after keywords d,e,f but after stroking Enter. ...

Number 2 is what we have right now.

Alternative approach is auto alignment instead of auto de-indenting. In case of auto alignment you can de-indent by hand or not, as the line is going to be automatically align anyway. However, auto-aligning is not always possible. For example, in case of nested if bocks, only user knows to which `if` the `else` line should be aligned.

**Comment by sjjf** [comment]
I think most of the formatting code uses auto-alignment logic rather than de-indentation logic - my patch for the sh formatting code moves it over to alignment matching rather than de-indentation. The only reason I can see not to do so (at least, since the addition of things like the custom object match commands) is if indentation is semantically significant, and in that case you obviously don't /want/ to fully automate de-indentation (outside of limited things like aligning try: ... except: blocks in Python). If there's a language that's using simple de-indentation logic rather than matching and aligning the block start/end it's probably in need of fixing (or there's something about the language that makes that impossible).

I'm sure there's lots of scope to improve the various bits of formatting code, and probably also to make them more consistent (though I'm not sure how much that can be standardised given language differences), but throwing our arms up and not even trying to automate this particular aspect of coding doesn't seem like a good idea.

**Comment by m-kru** [comment]
Replacing automatic de-indentation with auto-alignment wherever possible is the best approach. However, as I have already stated auto-alignment can not be put everywhere, as sometimes it is not obvious what should be the alignment anchor. When it can't, I propose to not auto de-indent.

**Comment by sjjf** [comment]
I'm struggling to think of a case where there's no syntax defining the start and end of blocks (which are where you indent/deindent) where the indentation /isn't/ syntactically significant - you either have well defined start/end markers (`{}`, `if/fi`, etc), or you have whitespace being the marker. If the start and end markers are there you can automatically align them; if they're not, then you shouldn't even try. Maybe HTML5, with optional closing markers for things? But in that case they're optional because there's an unambiguous rule to determine when they're optional, not because the standard is ambiguous.  Can you give an example of what you're talking about?

I guess what I'm saying is that if there's formatting code in kakoune that's trying to de-indent when it can't unambiguously figure out the right time to do so, that's probably a bug. And conversely, if there's formatting code making /any/ attempt to deal with syntax that's unambiguous and which doesn't use the built-in support for alignment matching then that's /also/ probably a bug. Maybe you should file bugs against the specific cases you're hitting? As I said in my first comment, the shell formatting was flat out buggy and I've submitted a pull request to fix it (#3765) - if you have other examples I'm sure the people responsible for the buggy code would be happy to fix them.

**Comment by m-kru** [comment]
@sjjf I have analyzed your patch. I did not know about `[c`. It changes a lot. In such case I agree with you. Any issues should be fixed within specific *filetype.kak* files.
