### ISSUE TITLE
`%arg{n/@}` values not preserved in `new`

### ISSUE THREAD

**Issue by SeerLite** [mawww/kakoune#3779]
### Steps 
Source the following:
```kak
define-command example -params .. %{
    new %{
        echo "args: %arg{@}"
    }
}

example a b c d
```
Alternatively, run this oneliner:
```kak
define-command example -params .. %{ new %{ echo "args: %arg{@}" } }; example a b c d
```
### Outcome 
A new client is created, with output `args: ` in the command line/bottom bar.

### Expected 
The new client should have output `args: a b c d`.

I couldn't find anything in the docs saying `new` would drop these values, so I assume it's a bug.

**Comment by mawww** [comment]
I dont think this is really a bug, arguments are local to a function, `new` takes a command to execute in the new client, which will happen later on (creating a new client is not a synchronous operation, the terminal emulator will startup, then run a client, which will connect to the current server and then run its initial command).

To achieve the behaviour you want here, you just need to expand `%arg{@}` in the example command instead of in the newly created client, you can do that by using a double quoted string:

```
define-command example -params .. %{
    new "echo 'args: %arg{@}'"
}
```

That string will get expanded **before** being passed to `new`, it does however introduce potential issues with escaping (here if any argument contains a `'` it might get parsed incorrectly).

**Comment by SeerLite** [comment]
> (creating a new client is not a synchronous operation, the terminal emulator will startup, then run a client, which will connect to the current server and then run its initial command)

Ohh, that explains it! I was viewing the process slightly differently and thought the command passed to `new` would be running like an `eval -client <new_client>` from the old client once the new one was connected.

Thank you! The double quotes do the trick!
