### ISSUE TITLE
Allow closing client with :q instead of :q!

### ISSUE THREAD

**Issue by GavinSmith0123** [mawww/kakoune#3801]
If I start a session with `kak -s foo -d`, and then a client with `kak -c foo tmp`, then make changes to the `tmp` buffer, and then try to quit with `:q`, I get an error: ` 'q' 1 modified buffers remaining`

However, if I quit anyway with `:q!`, and then go into the `tmp` buffer in another Kakoune client, then the changes are still there, even though I hadn't saved them. Hence, it would be harmless if you could close a client with `:q` even if there were unsaved changes.

This would be useful when editing with lots of clients at once and you decide you don't need some of them.

**Comment by mawww** [comment]
We already have this behaviour in general, all but the last clients can quit with modfiied buffers. It seems here what happens is that you quit the last client, but because your server is in daemon mode you'd like to be able to do that regardless of modified buffers because you can still connect another client to it later on.

I think this would be reasonable to do.

**Comment by GavinSmith0123** [comment]
Another way around the issue is to not have any unsaved buffers.

In Vim, there is the `set nohidden` setting which blocks you from changing the buffer while you have unsaved changes. This helps you to remember to save buffers (otherwise, "out of sight, out of mind").

Is it possible to have the same feature in Kakoune? I couldn't use the `WindowDisplay` hook to do this; is there some other hook that could be used?
