### ISSUE TITLE
Tabulations are never rendered as `tabstop` space characters

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3810]
### Steps 

Set `tabstop` to `4`.

In a buffer, write tabulation-separated columns of letters, with one more added for every row. C.f. below, you'll understand what it means when you see it.

### Outcome 

One tabulation character separates every column in the following:

```
a	b	c
aa	bb	cc
aaa	bbb	ccc
aaaa	bbbb	cccc
```

It looks like tabulation characters behave as padding, filled with an amount of space modulo `tabstop` — maybe for alignment purposes?

### Expected 

Every tabulation character is rendered as `4` space characters:

```
a    b    c
aa    bb    cc
aaa    bbb    ccc
aaaa    bbbb    cccc
```

**Comment by krobelus** [comment]
I think that's expected. Tab is a control character that means "move the cursor until the next tabstop", where a tabstop is every column that is a multiple of %opt{tabstop}. Vim does the same, it's really handy for alignment.
The docstring `tabstop - size of a tab character` can be confusing, maybe we can clarify.

**Comment by Screwtapello** [comment]
Yes, the "tabulation" character is called that because it's used to put data into tables - where cells of different lengths are arranged into vertically aligned columns. For example, the VT100 "set tab stop" control sequence doesn't take a width like Kakoune's "tabstop" option, it's literally "set a tab-stop at this cursor column". If you send "clear tabs" and then move the cursor to column 23 and send "set tabstop", then when the terminal receives a tab character in any column from 1 to 22, it moves the cursor to column 23.

Setting tabstop to 8 means "set a tabstop every 8 character cells", not "render a tab character as 8 spaces".

**Comment by lenormf** [comment]
That makes it hard to write tables that are properly formatted. Until now, I've inserted tabulation characters as separators, and used the alignment primitive to pretty print it. But once the table has been padded with spaces, it's tedious to modify it and automate the pretty-printing again (if the history even allows going back to the non-formatted table).

Is there any way to simplify this? An external tool that allows going back and forth between formatted/unformatted table would be ideal.

**Comment by Screwtapello** [comment]
The [kakoune-table](https://gitlab.com/listentolist/kakoune-table/) plugin has a `:table-align` command that will automatically realign a table that uses the GitHub Flavored Markdown syntax for tables, but I don't know about a tool for tables without visible column boundaries.

**Comment by lenormf** [comment]
Thanks. I suppose I'm asking how Kakoune can be used as a spreadsheet transparently — it would be interesting but ultimately not that useful, I might as well type in CSV and format that.
