### ISSUE TITLE
Add `execute-keys -with-text`

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#3823]
**Example** – Insert text:

``` kak
execute-keys i -with-text 'Hello, World!'
```

**Example** – Insert the output of a shell command:

``` kak
execute-keys ! -with-text %{
  lua -e '
    io.write("Hello, World!")
  '
} <ret>
```

[Discussion](https://discuss.kakoune.com/t/multi-line-execute-keys/1303)

**Comment by lenormf** [comment]
It's not clear what problem you're trying to fix here.

The first example doesn't require a flag, the following handles multi-lines well:

```kak
execute-keys i %{
	Multi
	Line
EOL}<esc>
```

As for the second example, I tried the following:

```kak
execute-keys ! '
	cat /etc/resolv.conf
'<ret>
```

The problem is that the first linefeed (following the first quote) validates the shell prompt (executing nothing), and the rest of the command is interpreted as-is by the editor. It seems to be a reasonable behaviour, albeit inconvenient and somewhat concealed (the user probably expects only `<ret>` tokens to validate the command).

The alternatives are:

- using an `%sh{…}` scope that handles indentation:

```kak
execute-keys i %sh{
	cat /etc/resolv.conf
}<esc>
```

- or maybe expanding the auto-formatting feature only enabled for docstrings to all strings, [as was suggested](https://github.com/mawww/kakoune/issues/2405#issuecomment-423029399) earlier?

**Comment by alexherbo2** [comment]
A common pattern to avoid key interpretation is to do:

``` kak
evaluate-commands -save-regs '/' %{
  set-register / %val{text}
  execute-keys 's<ret>'
}
```

or to insert text with the paste command instead of <kbd>i</kbd>.

**Comment by alexherbo2** [comment]
Using sh is very ugly and dangerous.  You are inserting the content of a file as keys.

The linked issue about auto-formatting will not help to remove the key interpretation.

``` kak
evaluate-commands -save-regs '"' %{
  set-register dquote %file{/etc/resolve.conf}
  execute-keys P
}
```

**Comment by mawww** [comment]
I think your own `execute-key` command shows what the idiomatic solution for this should be:

`evaluate-commands -save-regs a %{ set-register a '...'; execute-keys "a!<ret> }`

i.e. put the string inside a register and tell the command use that register.

This does not currently work because `!` does not respect the given register. I think we should fix that, all commands that prompt for some text should support that pattern (`"x<command><ret>` should use the text from register `x`). This seems ok as long as we dont have any command where and empty string is a reasonable parameter, which seems to be the case.

I agree this pattern is not obvious if you dont know it, but I'd argue the suggested alternative would not be either, it is still pretty concise and to the point, so I think its a reasonable idiom to develop.

It might also be nice to improve the conciseness of the pattern by avoiding the need to `-save-regs`, this could be done by introducing a register that is saved by default in `evaluate-commands`, a `draft` register if you will, say `*` (I initially tought `-` but it would conflict with switch syntax).

In that case the pattern becomes `evaluate-commands %{ set-register * %{my shell script}; execute-keys '"*!<ret>' }`

(And I dont thing you should `set-register dquote %file{...}` thats going to store a potentially huge file in a register, `!cat ...` is a better command for that).

I am not convinced that register is really warranted, after all I would expect those commands to be used in scripts anyway, or interactively without caring about restoring registers (in which case using any of the alphabetic registers will be fine).

So, my view of this issue is that we should ensure registers work as input for all commands that prompt for text, and make the `set-register ...; execute-keys ...` a known idiom.

**Comment by alexherbo2** [comment]
Very fair.
