### ISSUE TITLE
Reverse search <a-/> orthoganality

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#3925]
While regular searching with `/` directions of `n` and `<a-n>` are natural and orthogonal i.e. former jumps down and latter jumps up. However while reverse searching with `<a-/>` directions of `n` and `<a-n>` are the same as in regular search. I expected that in reverse search `n` and `<a-n>` would reverse their directions respectively, but this is not the case. The `reverse` part of `<a-/>` is only in its initial jump and afterwards I still have to hold alt key to keep reverse direction, which in my opinion is not so orthogonal.

**Comment by lenormf** [comment]
Setting a side effect on primitives predicated on which one was used previously doesn't sound great, it's not predictable.

One problem I can see would occur upon a user using <kbd>a-/</kbd>, then <kbd>\*</kbd>. I think the user would expect that subsequently hitting <kbd>n</kbd> would select the next (downward) match, but since <kbd>\*</kbd> modifies the search register `/` directly (and shouldn't assume that the user's intent is to search downward), hitting <kbd>n</kbd> would select the previous (upward) match.

**Comment by lenormf** [comment]
I think this behaviour could make for a good plugin, or at least a good snippet for the users' configuration. Here's my quick implementation of it:

```kak
define-command -hidden -params 1 search_direction %{ evaluate-commands %sh{
    case "$1" in
        up) echo "
            map global normal n <a-n>
            map global normal <a-n> n
            exec <a-/>
        ";;

        down) echo "
            map global normal n n
            map global normal <a-n> <a-n>
            exec /
        ";;
    esac
} }

map global normal <a-/> ': search_direction up<ret>'
map global normal / ': search_direction down<ret>'
```

If you do decide to adapt the above code and use it in your user configuration, could you please document it in the wiki?

**Comment by vbauerster** [comment]
Nice solution!

> could you please document it in the wiki?

Yes of course, I think placing it under [Editing](https://github.com/mawww/kakoune/wiki#editing) paragraph. Is it ok?

**Comment by lenormf** [comment]
Sounds good, I rarely care about what's on the wiki, so feel free to create pages as you see fit.

**Comment by vbauerster** [comment]
https://github.com/mawww/kakoune/wiki/Reverse-search
