### ISSUE TITLE
The built-in multiplexing commands lack flexibility

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3943]
### Feature 

The built-in windowing commands don't allow users to do much, they should be extended and new ones created.

HTH.

**Comment by arrufat** [comment]
Hi, I agree that the current windowing commands are somewhat limited (I only use the tmux ones) but developed a wrapper around [tilix](https://github.com/gnunn1/tilix) that defines the following commands:

- `:new`: creates a new session (kind of `C-b c` in tmux)
- `:new-right`: creates a new right split (like `C-b %` in tmux)
- `:new-down`: creates a new horizontal split (like `C-b "` in tmux)

These commands are so convenient that I wish they existed in the tmux wrapper by default, right now there's only `:new` which does a vertical split, but there's no straightforward way to do a horizontal split by default.

I don't think it makes sense to create a new instance in a different window, usually we want to see all kakoune buffers in the same tmux window, so I think it makes sense that `:new` defaults to either vertical or horizontal split.

Also, the horizontal/vertical nomenclature can be ambiguous.
For me, it defines how the line that splits the window will look like. But for some people, it means the way in which the resulting windows will end up being (left and right, therefore horizontal. I know, weird...).
That's why I prefer the right/down nomenclature.

**Comment by lenormf** [comment]
The only promise of `:new` is that it would “create a new window”, and spawn a Kakoune client connected to the current session in it. Where and how it would do that is left at the discretion of the command that implements that alias.

If you wanted to have more control over where/how you had to use the commands that were specific to the implementation you were targetting, for example `tmux-new-vertical`. Call the command, a new window/client appears where you'd expect — you only had to know what window manager was to be used, the command couldn't be agnostic.

But then the implementation commands (like `tmux-new-vertical`) had their API changed, and were made more modular by accepting any shell command, not a new Kakoune client specifically, and running it in a new window. Users now couldn't spawn a new Kakoune client in a predictable location any more without having to type a cumbersome `command kak -c …`, and I think this gap has led to them declaring custom commands [like these](https://gist.github.com/arrufat/59d88cc536294c2434105c9dc451faec#file-tilix-kak-L97-L98).

I'm assuming this is what's resulted into users complaining in the survey about the lack of granularity of the `new` command. They could have used the convenient implementation commands in the past, but not any more (at least without having to type `kak -c …`).

So I think we should introduce `:new-{direction}` commands, whose side effect would be to try to spawn a new client at the `direction` location, or fallback to the default `:new` behaviour if the tool doesn't allow it.

**Comment by crocket** [comment]
I'm not seeing `tmux-new-*` commands.

**Comment by lobre** [comment]
I also think a "direction" should be introduced again. Today, we have `tmux-terminal-horizontal`, `tmux-terminal-vertical`, `tmux-repl-horizontal`, `tmux-repl-vertical` but no way to simply open a file in an horizontal split (or "down" the current one) with `:new`.

This seems inconsistent to me, and especially bring incomprehension for newcomers. A "system" that would work across different multiplexers should be re-designed IMHO.
