### ISSUE TITLE
Segmentation Fault on window resize

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#396]
Hi,

How to reproduce the bug:
* make sure the `autoinfo` variable is set to `2`
* open up a new buffer, and do something in it that makes the autoinfo popup show
* slowly resize the window down until kakoune crashes

This is a very anoying bug, as I do use `autoinfo` and my wm resizes windows around a lot when I'm coding.

Trace:
```
Received SIGSEGV, exiting.
Pid: 1269
Callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x500238]
kak(_Z14signal_handleri+0x195) [0x4cf805]
/usr/lib/libc.so.6(+0x33680) [0x7f79aac59680]
/usr/lib/libncursesw.so.5(wnoutrefresh+0x1eb) [0x7f79abb9300b]
kak(_ZN7Kakoune9NCursesUI6redrawEv+0x4d) [0x5563fd]
kak(_ZN7Kakoune9NCursesUI7refreshEv+0x12) [0x556422]
kak(_ZN7Kakoune6Client10redraw_ifnEv+0x30d) [0x508aad]
kak(_ZNK7Kakoune13ClientManager14redraw_clientsEv+0x24) [0x553ff4]
kak(_Z10run_serverN7Kakoune10StringViewES0_bbbNS_9ArrayViewIKS0_EE+0x9dc) [0x4d3f5c]
kak(main+0xf7a) [0x45595a]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f79aac46610]
kak(_start+0x29) [0x459169]
```

**Comment by mawww** [comment]
fede8da14b5f65a301ce3459a93a95aeffce67d7 should have fixed that, tell me if its not the case for you (I was not getting exactly the same callstack, but I am on ncurses 6 now).

The change is that you loose info/menu box on resize (instead of letting ncurses try to repaint what it can), that might get revisited with something smarter afterwards, but fixing the crash seems more urgent.

**Comment by lenormf** [comment]
That commit fixes it, however as you said, the info window isn't redrawn, which is a minor inconvenience compared to the benefits of the fix.

Cheers.
