### ISSUE TITLE
`kak -E 'kill 0'` results in uncaught exception

### ISSUE THREAD

**Issue by cole-h** [mawww/kakoune#3972]
### Steps 

Occurs on both `Kakoune v2020.09.01` and `Kakoune v2020.09.01-246-g74b6c20a`.

1. Run `kak -E 'kill 0'`

### Outcome 

`uncaught exception` is printed to stdout, and nothing else.

### Expected 

Something more descriptive than `uncaught exception` should be printed, explaining the problem (if there is one). I'm not familiar enough with the codebase (yet) to understand why this happens.

**Comment by Screwtapello** [comment]
I built Kakoune with `make debug=yes` to get a debug binary, then loaded it up in gdb and told it to break on the first thrown exception:

    $ gdb src/kak.debug
    (gdb) catch throw
    (gdb) run -E 'kill 0'

It turns out debug builds of Kakoune run a bunch of tests at startup that throw exceptions, so I had to skip those, but eventually I got an exception whose backtrace looked like:

```
#1  0x0000555555a7e534 in Kakoune::(anonymous namespace)::kill<false> (parser=..., context=...) at commands.cc:605
#2  0x0000555555ac4721 in std::__invoke_impl<void, void (*&)(Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&), Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&> (
    __f=@0x555555fec508: 0x555555a7e44c <Kakoune::(anonymous namespace)::kill<false>(Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&)>) at /usr/include/c++/10/bits/invoke.h:60
#3  0x0000555555abe368 in std::__invoke_r<void, void (*&)(Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&), Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&> (
    __fn=@0x555555fec508: 0x555555a7e44c <Kakoune::(anonymous namespace)::kill<false>(Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&)>) at /usr/include/c++/10/bits/invoke.h:110
#4  0x0000555555ab7382 in std::_Function_handler<void (Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&), void (*)(Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&)>::_M_invoke(std::_Any_data const&, Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&) (__functor=..., __args#0=..., __args#1=..., __args#2=...)
    at /usr/include/c++/10/bits/std_function.h:291
#5  0x0000555555a5b962 in std::function<void (Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&)>::operator()(Kakoune::ParametersParser const&, Kakoune::Context&, Kakoune::ShellContext const&) const (this=0x555555fec508, __args#0=..., 
    __args#1=..., __args#2=...) at /usr/include/c++/10/bits/std_function.h:622
#6  0x0000555555a511ff in Kakoune::CommandManager::execute_single_command (this=0x7fffffffc120, 
    params=ArrayView<Kakoune::String> = {...}, context=..., shell_context=..., pos=Kakoune::BufferCoord(0, 0))
    at command_manager.cc:524
#7  0x0000555555a51930 in Kakoune::CommandManager::execute (this=0x7fffffffc120, command_line="kill 0", context=..., shell_context=...)
    at command_manager.cc:567
#8  0x0000555555bd59b7 in Kakoune::run_server (session="", server_init="kill 0", client_init="", init_coord=..., 
    flags=Kakoune::ServerFlags::None, ui_type=Kakoune::UIType::Terminal, debug_flags=Kakoune::DebugFlags::None, 
    files=ArrayView<Kakoune::StringView>) at main.cc:798
```

The exception gets thrown by the `kill<false>()` function, which looks like this:

https://github.com/mawww/kakoune/blob/74b6c20a0d19c9fcf2b30a93de1ff3b715151e65/src/commands.cc#L593-L606

Apparently it's implemented by throwing the `kill_session` exception. That's pretty straight-forward, I wonder where it's caught? Grepping the codebase for `kill_session` finds exactly one site:

https://github.com/mawww/kakoune/blob/74b6c20a0d19c9fcf2b30a93de1ff3b715151e65/src/main.cc#L906-L909

That `catch` block comes after a `try` block that starts on line 837, so any `:kill` command executed within that span should be handled correctly. But if you look at the traceback, this code was actually called from line 798:

https://github.com/mawww/kakoune/blob/74b6c20a0d19c9fcf2b30a93de1ff3b715151e65/src/main.cc#L795-L805

So apparently the "server initialisation string" is executed before Kakoune is properly running, and before the `:kill` handler is in place, and so it causes "uncaught exception" rather than having the intended effect.
