### ISSUE TITLE
Potentially broken regex in markdown.kak

### ISSUE THREAD

**Issue by enricozb** [mawww/kakoune#4025]
In `markdown.kak`, the capture group for the language in a code fence's info string, there seems to be an extra closing parenthesis: https://github.com/mawww/kakoune/blob/dacaad4e9366365462df7cdea546faae1517fe4a/rc/filetype/markdown.kak#L50

Specifically the open regex for the region, `^(\h*)```\h*(%s|\\{=%s\\}))\\b`, has two open parenthesis and three closing parenthesis. Two questions:

- Is this incorrect?
- If it is, why isn't highlighting for code fences broken?

**Comment by lenormf** [comment]
It's incorrect, no errors are raised because the regex parser seems to be lenient with un-matched closing parenthesis (try <kbd>/</kbd> `)` </kbd>ret</kdb>, no errors).

Feel free to submit a PR. Maybe the regex engine should be fixed as well.

**Comment by SeerLite** [comment]
I accidentally left that in, in a06dcf8c10395370b14d7503cbfa3d6112145633. I did live trial and error searches to highlight the language inside the brackets, and it didn't work unless I added that extra `)`.

I realize now that it didn't work because of `\b` (and not a missing closing parenthesis). Since `}` isn't a word character, `\b` would fail the regex, but for some reason adding that extra parenthesis seems to make `\b` count it in again.

In fact it looks like the (incorrect) regex `)\b` matches anything, so that's why it works. I guess making unmatched `)`s raise errors (like @lenormf suggests) would automatically fix this
