### ISSUE TITLE
add-highlighter window/xxx replace-ranges wrongly interpret offsets

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#4052]
Given following text:
```
fn main() {
    let my_str = String::from("abc");
}
```
apply following highlighter, which pins `: String` to the left side of the offset 15 on line 2.
```
declare-option range-specs test_inlay_hints
add-highlighter global/test_inlay_hints replace-ranges test_inlay_hints
set buffer test_inlay_hints 1 '2.15+0|{Information}{\}: String'
```
After I edit line 2, add space after `my_str` word and/or remove space right before `=`, `: String` is on the right side of the offset 15 which I believe is wrong.
![image](https://user-images.githubusercontent.com/2206533/107149958-4be41780-697d-11eb-83d4-ccba4c47ca64.png)

Such highlighter should be pinned and always be on the same side of the offset regardless of edits.

**Comment by mawww** [comment]
It does look surprising due to the position of the cursor, but I think the behaviour is actually correct, or at least, works as intended:

The inserted hint is displayed at offset 15 (the `:` character is where the cursor would be at offset 15 if there was no hint). When you insert a space, you insert it *before* the cursor, which itself is at offset 15 of the line, so that space is conceptually inserted *before* the hint, which gets its position update to offset 16 after the buffer change.

What we could do is attach the hint to offset 14 (the last character of the variable name) but somehow configure it to display *after* it rather than *before* it, as some kind of additional flag in the position description. However this approach would also fail when extending the variable name as appending `ing` to `my_str` would display that `ing` *after* the hint.

Not sure what a good fix/feature to handle that would be. Not sure what other editors do in this case.

**Comment by vbauerster** [comment]
Ok now I see that behavior is actually right, as indeed `my_str` can be extended and hint should follow that extension.

My concern is that there is an extra space gets inserted right before the hint, when this feature is used by `kak-lsp`. The screenshot below illustrates this where on the left side file is displayed as it is without any hints and on the right side hint is populated by `kak-lsp` and there is suddenly extra space right before the `:` char despite request which produced this contains no extra space `2.15+0|{InlayHint}{\}: String`:

![image](https://user-images.githubusercontent.com/2206533/107183858-58aa4f00-6a01-11eb-870d-f491d78721a0.png)

And here is command which produced the hint and it looks correct. The weird thing if I manually execute this command the hint is without extra space.

```
Feb 08 11:21:07.242 DEBG To editor `35631`: eval -client client0 -verbatim -- eval -buffer '/Users/vbauer/projects/tmp/inlay-test/src/main.rs' -verbatim -- set buffer rust_analyzer_inlay_hints 1 '2.15+0|{InlayHint}{\}: String', module: kak_lsp::editor_transport:84
```

**Comment by vbauerster** [comment]
It could be that a hint is placed sometimes at left side of the offset in which case it looks like:
```
let my_str: String = String::from("abc")
```

and sometimes at right side of the offset in which case it looks like:
```
let my_str : String= String::from("abc")
```
Though I'm not sure.

**Comment by mawww** [comment]
The different behaviour you see might be linked to the first element in that list (`1` here), this is the buffer timestamp to which those location relate to, so if the buffer has been modified in the mean time, Kakoune will update those locations according to the modifications.

If you enter that command manually and want to use the current buffer state, write `%val{timestamp}` instead of `1` there.

**Comment by vbauerster** [comment]
> If you enter that command manually and want to use the current buffer state, write `%val{timestamp}` instead of `1` there.

That didn't help, but I managed to reproduce manually.

It looks like that culprit is `window/` path of `add-highlighter` command. If I add `window/` path highlighter like in a snippet below, then end result is wrong like `let my_str : String= String::from("abc")`, but `global/` and `buffer/` path produces correct result like `let my_str: String = String::from("abc")
`

```
declare-option -hidden range-specs test_inlay_hints
add-highlighter window/test_inlay_hints replace-ranges test_inlay_hints
set buffer test_inlay_hints 1 '2.15+0|{Information}{\}: String'
```
To confirm that it is wrong I have added offset 1 hint along with offset 15 like:
```
set buffer test_inlay_hints 2 '2.1+0|{Information}{\}:T' '2.15+0|{Information}{\}: String'
```
And both hint positions are wrong:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/2206533/107340419-92518780-6adf-11eb-8c24-f7c33a5672ae.png">

**Comment by mawww** [comment]
Hum, I dont quite manage to reproduce that, here if I open a scratch buffer, replace its content with

```
fn main() {
    let my_str = String::from("abc");
}
```

Then do

```
declare-option -hidden range-specs test_inlay_hints
add-highlighter window/test_inlay_hints replace-ranges test_inlay_hints
set buffer test_inlay_hints %val{timestamp} '2.15+0|{Information}{\}: String'
```

I see the hint position at the expected location. If I then do `add-highlighter buffer/test_inlay_hints replace-ranges test_inlay_hints` I see the hint displayed twice one after another, so at the same buffer location.

It looks like you have some syntax highlighting enabled, so it could be some weird interaction with some auto-indentation hooks, does it reproduce in `kak -n` ?

**Comment by vbauerster** [comment]
It doesn't reproduce with `kak -n`, you're right. It's following highlighter which I have in my config:

```
add-highlighter window/whitespaces show-whitespaces -tab '›' -tabpad '⋅' -spc ' ' -nbsp '⍽'
```

Thanks for your time and sorry for bothering. At least now I know why is it.

**Comment by mawww** [comment]
Ahh, yeah, I imagine if you change the ordering of the whitespace highlighter and the inlay_hints one you will get the expected behaviour. I think that should still work out-of-the-box, so I would say this is still a valid issue.
