### ISSUE TITLE
Issue with add-highlighter when editing a new file

### ISSUE THREAD

**Issue by ivanddm** [mawww/kakoune#4054]
### Steps 

I have this in my `kakrc` to add some left padding after the line numbers:

```
declare-option line-specs test 1 '1|   '
add-highlighter global/ flag-lines default test
add-highlighter global/ number-lines
```

Then, create a new file `foo` with `:e foo` and start editing...

### Outcome 

The defined `test` highlighter is turned off and the left padding after the line numbers is lost. I have to reload Kakoune. This does not happen when editing existing files.

### Expected 

The left padding should remain even after editing a new file.

**Comment by lenormf** [comment]
You would need to update the timestamp of the highlighter (the first `1`) as that of the buffer changes.

Why not use `-separator` on the `number-lines` highlighter directly?

**Comment by ivanddm** [comment]
I was following the discussion in #3101.

If I use `%val{timestamp}` instead of the first `1`, I get a `'source' no buffer in context` error. Basically this is not working:

```
declare-option line-specs test %val{timestamp} '1|   '
add-highlighter global/ flag-lines default test
add-highlighter global/ number-lines
```
  
Using `-separator` is a nice solution and should be the way to go as I don't get the issue of the highlighter being off when 
creating new files, and it is just one line:

```
add-highlighter global/ number-lines -separator '|   '
```

The only issue is that if I defined `-separator` to be `|   `, the vertical lines after the numbers is not continuos and does not look like the default one:

![image](https://user-images.githubusercontent.com/20104703/107336887-b6569e00-6aca-11eb-9df1-d8226c6b6372.png)

**Comment by Screwtapello** [comment]
Normally a `line-specs` option is displaying information about specific lines in a specific buffer,  so you want the option to start with the current timestamp of that buffer. Since you're defining a `line-specs` option globally, there is no buffer in scope, so you have to pick a timestamp that works with every buffer, like 1, or better yet 0.

The `number-lines` highlighter doesn't actually use `|` (U+007C VERTICAL LINE) as the separator, it uses `│` (U+2502 BOX DRAWINGS LIGHT VERTICAL) which is supposed to connect vertically with other characters. Paste that one in instead, and it should work as you expect.

**Comment by ivanddm** [comment]
Yes, using U+2502 in the separator does the job, and using `-separator` solves my issue. Thanks for this!
