### ISSUE TITLE
Completion inside hook is quoted

### ISSUE THREAD

**Issue by SeerLite** [mawww/kakoune#4061]
### Steps 
1. `kak`
2. Type `:hook global NormalIdle .* %{`
### Outcome 
Every following completion is shown/entered surrounded by single quotes.
### Expected 
No single quotes

**Comment by Screwtapello** [comment]
Can confirm with `kak -n`. In fact, you can reproduce the behaviour with just `:%{`

Specifically, when you type `%{` Kakoune detects this as "the start of a quoted word", and so it suggests quoted words as completions. For example, if you type:

    :%{echo

...then the only suggestion is `'echo'`. If you hit `<tab>` to accept the completion, it completes to:

    :%'echo'

...which is a perfectly legitimate (if utterly redundant) way to quote a command name.

**Comment by Screwtapello** [comment]
The [hook command's completion logic](https://github.com/mawww/kakoune/blob/master/src/commands.cc#L1055-L1059) uses the generic "list of known commands" completer, rather than (as is more likely for a hook command) a string *containing* commands. Meanwhile, the command completer will automatically enable quoting if it's completing a string that starts with `%` or contains a semicolon, a quote, or whitespace:

https://github.com/mawww/kakoune/blob/dea44e4964e97d29b9a9ec493fec02b3d41e5345/src/command_manager.cc#L679-L680

I'm not sure why it does this, since I'm pretty sure you can't *define* a command whose name contains a semicolon, a quote, or whitespace, but maybe it's just being extra-cautious.

**Comment by SeerLite** [comment]
Not sure if it's useful but I wanted to point out that this works as expected (hooks don't get their completions mis-quoted) on the last [release version](https://github.com/mawww/kakoune/releases/tag/v2020.09.01).
