### ISSUE TITLE
Append (a) command extends selection while in insert mode

### ISSUE THREAD

**Issue by yerlaser** [mawww/kakoune#4067]
Hi,
When I press 'a' to append text, it goes into insert mode, but also keeps extending the selection with the typed text. It doesn't happen with 'A'
The problem with it, highlighted text is poorly visible and also when exiting insert mode I end up with unwanted selection.
Is this by design?
If so, what is the purpose of it?
For now, as a workaround I remapped 'a' to 'li', but I am not sure what side effects it may have.
Thanks!

**Comment by mawww** [comment]
Hello, this is by design.

Insertion always takes place *before* the cursor in insert mode, which seems like a sane and simple behaviour. When appending, we hence need to first shift the cursor one character to the right of its previous position, so that we insert text just *after* the previous cursor position.

I dont think there is many alternatives regarding the cursor behaviour, now the question remains: what to do with the anchor ? (remember, in Kakoune a selection is an inclusive, directed range defined by a cursor and an anchor position). 

If the anchor is not currently on the same position as the cursor, it would be weird to shift it, and we would lose information if we just snapped it back onto the cursor so we want to keep it in place.

If the anchor and cursor were on the same position, we could shift the anchor as well, but we would need to justify such a special case. I hence decided to do keep it in place.

I must say it initially felt weird, but I got used to it and cant really see a better approach.

**Comment by yerlaser** [comment]
Hi,
Thanks a lot for the answer!
I think I won't fully understand the reasoning at this moment, I need to use Kakoune more to fully understand its philosophy.
Overall, Kakoune feels very solid and stable and I am glad it's not a bug.
But, I will keep my mapping for the time being.
I'll close the issue as it's by design. Thanks again.

**Comment by lenormf** [comment]
An alternative explanation is provided [in the FAQ](https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#why-does-a-extend-the-current-selection-but-i-leaves-it-untouched).
