### ISSUE TITLE
Add select-to-first-non-whitespace

### ISSUE THREAD

**Issue by memeplex** [mawww/kakoune#407]
There is select-to-line-begin but I can't see any simple way to avoid including the indentation, as in vim `0` vs `^`. True, you can start inserting right after indentation with `I`, but the equivalent selecting action is not so easily achived. It can be implemented with a zero-width look-behind pattern for the initial whitespace, I guess, but maybe it's worthy of being added to the core.

**Comment by lenormf** [comment]
Hi,

You can map the following command to a key:  
```
<a-h>EB
```

This will select everything to the beginning of the line, unselect everything till the end of the word after all the indentation whitespace, and then re-select the word that was just skipped.
```

**Comment by FranzSkuffka** [comment]
@memeplex if i understand you right, you want to _select all the whitespace in the beginnig of a line_.
What about <code>ghw</code>. This 1. goes to start of the line and 2. selects the current word (e.g. the whitespace).
If you want to make a visual selection of the first non-whitespace _word_ word the command is <code>ghe</code>.
If you want to make a visual selection of the first non-whitespace _character_ the command is <code>gheb;</code>

**Comment by ianthehenry** [comment]
Sublime's "go to beginning of line" command works like this:

1. If your cursor has only whitespace to the left of it, navigate to the actual first character on the line.
2. Otherwise, navigate to the first non-whitespace character.

This means, that in code like this:

```
something() {
  foo()
}
```

With your cursor between the parens of `foo()`, pressing "beginning of line" once will position your cursor before the `f`, and pressing it again will position it at the hard beginning of the line.

It's not idempotent, but it's useful. In any case, I would rather have vim's `^` motion than `0` motion any day, because I am usually editing text that uses indentation to reflect structure.

I tried Kakoune a few months ago and was mystified that I couldn't find the command that behaved this way, nor the command to select a line without its leading whitespace (to duplicate the behavior of `cc`, a common way that I enter insert mode using editors with vim keybindings). I decided to wait a while before I tried Kakoune again, but here I am and it still doesn't seem to be there.

In vim I often type `I` followed by escape because it's easier to type those two characters than to hit `^`. In Kakoune it seems like that's the only way to get my cursor where I want it, but it doesn't allow me to select to there.
