### ISSUE TITLE
wrong indentation in Lisps when comments contain unmatched brackets

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#4081]
### Steps 
Create file `bug.lisp` with the following contents:

``` lisp
(defun foo (bar)
  ;; comment with unclosed {
  bar)
```

Open it and press: <kbd>g</kbd><kbd>h</kbd><kbd>o</kbd>

### Outcome 

Note the indentation:

![image](https://user-images.githubusercontent.com/19470159/109683630-97f73600-7b90-11eb-8626-b9d05d8dc0d8.png)

### Expected 

![image](https://user-images.githubusercontent.com/19470159/109683678-a3e2f800-7b90-11eb-958d-cc78155d33ae.png)

This happens in all Lisp related filetypes: `lisp`, `clojure`, `scheme`, `fennel`. This doesn't happen in c-like languages:

![image](https://user-images.githubusercontent.com/19470159/109684282-2cfa2f00-7b91-11eb-9fd3-3c005420471a.png)

**Comment by eraserhd** [comment]
This is the same issue as `m` matching brackets in comments and strings.

In C-like languages, the column of the opening bracket doesn't affect indentation, where in Lisp it does.  The Lisp indent hook needs to search backward for the current opening bracket, brace, or curly, and it's really hard in Kakoune currently to ignore brackets inside strings, comments, and character literals -- especially since we can't really figure out where these things are unless we parse the file from the beginning.

For example, we could search backward for a semicolon, then ignore the bracket if we find one on that line, but that semicolon could be a character literal (the easy case), or it could be a semicolon in a multi-line string.  It could be a semicolon in a multi-line string which closes on that line, after the semicolon but before the bracket!

I've been thinking about how we could solve this... I have an idea that seems really powerful, but maybe terrible to implement?:  Some kind of "mask selection" stored in an option or register.  `m` would ignore masked-out characters.  So then, we could do something like (oversimplified for demonstration purposes):

```
execute-keys '%s(".*?"|;[^\n]*\n)<ret>"mZ'
```

To set the characters that `m` would ignore.  We could add insert hooks to filetypes to reset the mask register when the user types a quote, backslash, or semicolon.

Drawback: Sometimes you want to go to a matching bracket inside a string or comment.

Perhaps `"mm` uses the register as a mask, and normally it doesn't change?

@mawww thoughts?

**Comment by andreyorst** [comment]
In this very case the closing delimiter can easilly be found with <kbd>m</kbd>, so I think you're overthinking it a bit. I guess we only need to find the column of a matching opening delimiter, and to do that we need to find first closing delimeter before the cursor and execute `m`:

    exec <a-/>[\]})]<ret>m

and we have our indentation even. Yes, this will cause problems for the expressions that contain the **same** delimiter in the comment or string, and you're suggesting a solution for this problem, but I think that this is a different issue which is general for `m` not being smart enough about the semantics of the language.

**Comment by eraserhd** [comment]
I'm pretty sure that doesn't work.  You've given an example where the code is correctly balanced, but that isn't necessarily the case unless parinfer is installed.  Assuming the next closing bracket is the proper type of closing bracket means that a user who doesn't have parinfer installed can't type:

```
(sort [34|)
```

and press enter, since it would go to column 2 instead of 8.

(In fact, both parinfer and the indent hook consider only what is before the cursor to determine the proper indentation.)

It would be possible to disable curly brackets entirely for languages that don't honor them, but even where they aren't specified (like Scheme), they are supported (e.g. Gambit).

**Comment by andreyorst** [comment]
ah, yes, I forgot that indentation can happen in unbalanced code, as I use automatic pair insertion all the time, thus my code is mostly always balanced
