### ISSUE TITLE
Can't delete highlighter when separator="  ", possibly other similar issues

### ISSUE THREAD

**Issue by Nagyhal** [mawww/kakoune#4121]
Hi! I don't often post issues on GitHub, but still, I'll try and do this nicely and I hope I get it right.

I really like kakoune — it's basically my new hobby — so thanks for all the creativity & hard work.

### How to reproduce this:
Create a line number highlighter with spaces as the separator (or any separator ending in spaces):
`:addhl buffer/ number-lines -separator="  "`

Then, go to delete this:
`rmhl buffer/<tab>`

The tab-completed command will fail if executed:
`parse error: unterminated string '...'`

### Someone on IRC taught me how to get around this
You have to quote the entire string, like `rmhl 'buffer/......'`

This produces the intended result — but it was unintuitive enough that I couldn't figure it out on my own (my IQ is about 6 when using Kak!) Still, the tab-completed command definitely shouldn't produce an error.

**Comment by mawww** [comment]
Hum, so there is an issue with completion, but it does not seem to fully match your description, the error you have appears as soon as I try `addhl buffer/ number-lines -separator=" "` because that syntax is incorrect (its parsed as `-separator="` then `"` which is an unterminated string). The correct syntax would be `-separator " "` and it does indeed fail to complete properly.

**Comment by Nagyhal** [comment]
Nice work! :grin:
