### ISSUE TITLE
[builtin-terminal-ui] <a-O> not working on kitty

### ISSUE THREAD

**Issue by Parasrah** [mawww/kakoune#4159]
### Steps 

on `builtin-terminal-ui` branch commit `d5eb98f7fc4c0f065f96bec247504e99d67ffb54`

1) open up kak with default autoload, or with no config `kak -n`, in kitty
2) `<a-O>`

### Outcome 

nothing

### Expected 

should insert line above selection. Seems to also be a problem with all other alt+<capital_letter> combinations.

**Comment by Parasrah** [comment]
tried this on my other computer running `kitty 0.19.3` and it seems to work fine, whereas earlier I was using `0.20.1` I believe

**Comment by Screwtapello** [comment]
If you execute (inside Kakoune):

    :set global debug keys
    :b *debug*

...then press `<a-O>`, what does it display?

**Comment by Parasrah** [comment]
output:
```
Client 'client0' got key '<a-s-o>'
```

And yet I tried `map global normal <a-s-o> ':echo testing<ret>'  to no avail.

PS: thanks for that debug trick, I had no idea that was a thing

**Comment by Screwtapello** [comment]
And I bet if you try the previous commit on the builtin-terminal-ui branch (the one before "Opt-in kitty CSI u support"), it works correctly, right?

In the traditional terminal encoding, the terminal always sends the actual character typed; for example, the encoding for `<a-!>` is literally 0x1b 0x21 (or `ESC !`) without any indication of the Shift key, or what that symbol would be without Shift. As a result, Kakoune doesn't support the shift modifier for printable characters; `<a-o>` and `<a-O>` are different keys and we don't care about whether Shift was involved.

Kitty 0.20(.1?) added support for a new key-encoding (also supported by various other terminals) that provides more information about pressed keys. It seems like it includes the Shift key state in a way that Kakoune wasn't expecting. I'm not sure whether that's a bug in Kakoune, a bug in Kitty, or just a miscommunication between what Kakoune expects and what Kitty implemented.

**Comment by Parasrah** [comment]
Sure enough I went back a single commit and rebuilt and the problem is no longer occurring. I appreciate the explanation, is this new key-encoding protocol why I had to manually map keys like `<c-[>` to `<esc>`, and why I can map [ambiguous keys](https://github.com/mawww/kakoune/wiki/Ambiguous-Keys) now?

I was under the impression that the `builtin-terminal-ui` branch removes the abstraction of `ncurses` and directly interfaces with the terminal in order to solve problems like ambiguous keys? Am I on the right track?

**Comment by Screwtapello** [comment]
> I appreciate the explanation, is this new key-encoding protocol why I had to manually map keys like `<c-[>` to `<esc>`, and why I can map ambiguous keys now?

Yes!

The builtin-terminal-ui branch removes ncurses for handling *output*. ncurses has already been removed for handling *input*, including support for [this new key-encoding protocol](http://www.leonerd.org.uk/hacks/fixterms/), but the builtin-terminal-ui branch is the only one with commit d5eb98f7fc4c0f065f96bec247504e99d67ffb54 that asks Kitty to switch from the old protocol to the new.

This new protocol is still pretty new. Off the top of my head, there's the original proposal (linked above), there's implementations in xterm, tmux, iTerm2 and Kitty, and I'm not at all sure how compatible they are. Which is why somebody needs to do more digging to figure out whether this is a Kakoune issue or a Kitty issue. :)
