### ISSUE TITLE
Different Cursors for different modes

### ISSUE THREAD

**Issue by python128** [mawww/kakoune#4241]
### Feature 
I would like to be able to change the cursor style.
When it is in `Normal` mode, I would like to have a block cursor.
When it is in `Insert` mode, I would like a pipe cursor.

### Usecase 
I, for now, don't have anything for the feature, but I would like to be able to change the cursor.

### Why?
It would be very helpful, as I accidentally type, thinking it is in insert mode. So, if there is an option to do so, it would be very helpful.

Thanks in advance.

**Comment by tototest99** [comment]
rethink what you are seeing: https://github.com/mawww/kakoune/blob/master/README.asciidoc#31-selections

**Comment by Screwtapello** [comment]
This isn't possible, for technical and theoretical reasons.

The technical reason is that although terminal emulators support changing the cursor shape to a block, pipe, or underline, they only support *one* cursor. Since Kakoune is a multi-cursor editor, it can't use the terminal provided cursor and has to fake its own by playing with the foreground and background colours of a character cell. Since a character cell is always a block-shape, Kakoune cursors are also always block-shaped.

The theoretical reason is that since Kakoune must *draw* cursors as block-shaped, on top of an existing character, they *behave* as block-shaped. That is, the minimum length of a selection is 1, you can never put the cursor "between" characters, you always have to choose whether to `i`nsert before or `a`ppend after the selection, and those options always behave differently... drawing the cursor as a pipe would be *misleading*.

If your problem is getting confused about whether you're in Insert or Normal mode, you might want to try changing the cursor colour instead of the shape:

https://discuss.kakoune.com/t/changing-the-cursor-colour-in-insert-mode/394/4

**Comment by python128** [comment]
Ohk, thanks a lot. I'll do so. 
I'm now closing the issue. Thanks again
