### ISSUE TITLE
mapping percent w/ kitty

### ISSUE THREAD

**Issue by basbebe** [mawww/kakoune#4242]
I used to use a mapping which used `<a-percent>` (something like `kakoune.cr`'s `map -docstring 'select all occurrences of current selection' global normal <a-percent> ':select-highlights<ret>'`)

It used to work in the past but since one of the last updates of either kakoune (building from HEAD) or kitty it doesn't do anything anymore.

I'm on
kitty 0.21.1
kakoune 8fdda6d
macOS 11.4

`:buffer *debug*; set -add window debug keys<ret>` reports:
```
Client 'client0' got key '<a-s-5>'
```

changing the shortcut to `<a-s-5>` throws this error on startup:
```
Shift modifier only works on special keys and lowercase ASCII, not '5'
```

`kitty @kitten show_key` reports:
```
UNIX        send_text
%        %
^[%        \x1b%
```

**Comment by Screwtapello** [comment]
I'm pretty sure this is fallout from the extended-key-reporting feature.

Kakoune tries hard to avoid knowing anything about keyboard layouts; it doesn't assume that Shift-5 produces %, so when the traditional terminal encoding sends `^[%` it treats that as `<a-%>`. When Kitty sends `^[[53;4u` (where 53 is the decimal ASCII encoding for `5` and 4 represents the Shift modifier), it treats that as `<a-s-5>`, and Kakoune can't tell it's the same key as `<a-%>`.

(For the record, xterm and tmux both send `^[%` for Alt-Percent even in extended-key-reporting mode)

This wouldn't be such a big deal — you could just map both sequences and Kakoune would trigger either one depending on the terminal behaviour — except that in order to guide people toward mappings that work in traditional terminals, Kakoune forbids mapping `<a-s-5>`.

There's a few things we could do here:

- remove Kakoune's prohibition about the Shift modifier, so people can map `<a-s-5>`
- teach Kakoune to assume QWERTY layout, so it can unify `<a-s-5>` with `<a-%>`
- try and automaticallly avoid using the extended key reporting mode in Kitty, if Kitty is going to make it difficult to support both modes in the same program
- add an option to disable extended key reporting mode (like disabling mouse events) in case other terminals follow Kitty's lead
- avoid using the extended key reporting mode entirely
- Try and talk Kitty's maintainer into switching to some more compatible behaviour

I don't think any of those options are Obviously The Best Solution; I'm interested to hear what other people think.

**Comment by SolitudeSF** [comment]
remove prohibition. maybe behind option.

**Comment by kovidgoyal** [comment]
The correct solution is to use the actual full extended keyboard mode protocol, not the silly travesty xterm implements. The full protocol reports both the unshifted and shifted keys so you can detect them unambiguously and robustly. Read https://sw.kovidgoyal.net/kitty/keyboard-protocol.html#key-codes

**Comment by basbebe** [comment]
I do (of course) have the same problem with alt+( and the like

**Comment by basbebe** [comment]
Sorry to pick this up again.
I can't imagine I'm the only one using kitty with kakoune.
Is there any workaround I'm not aware of!
Thanks!

**Comment by lenormf** [comment]
I can reproduce the issue. One workaround is to use Tmux, the issue doesn't occur in that terminal environment.

**Comment by eraserhd** [comment]
Bleeding edge kitty users, please test out PR #4415.
