### ISSUE TITLE
Key combination of alt + <number row symbol> not working on kitty terminal > 0.20.0

### ISSUE THREAD

**Issue by not-chicken** [mawww/kakoune#4259]
### Steps 
Build kakoune from master, use kitty version > 0.20.0, and try to use `<a-(>` or `<a-)>` to rotate selections content.

### Outcome 
Nothing happens.
### Expected 
Selection content is rotated.

Similarly `<a-&>`, `<a-#>`, etc also don't do anything. I guess this is related to new keyboard reporting protocol of kitty, but not sure if this is a bug of kitty or kakoune, like #4159.

**Comment by Screwtapello** [comment]
The `builtin-terminal-ui` branch just got merged to master, so yes, this is the same kind of thing as #4159.

**Comment by raiguard** [comment]
Bump. This isn't _significantly_ impacting my productivity, but not being able to rotate selection contents or go forward in the jumplist is inconvenient.

**Comment by lenormf** [comment]
```
Client 'client0' got key '<a-s-0>'
```

**Comment by Parasrah** [comment]
@raiguard I could be wrong but I thought the change in behaviour for `<c-i>` was intentional, as it is one of the [ambiguous keys](https://github.com/mawww/kakoune/wiki/Ambiguous-Keys) listed in the wiki? I assumed the actual keycode being used was `<tab>`, and as such remapped `<c-i>` to tab manually. That said, it would probably make more sense for `<c-i>` to be the default (imo).

I think in any case that might be it's own thing, and worth creating a different issue (if none already exists)?

**Comment by raiguard** [comment]
@Parasrah Thanks for the tip, I rebound `<c-i>` and it works again.

However, I still can't rotate selections or use some other alt+binds in kitty. I miss rotating selections. :(

**Comment by eraserhd** [comment]
For ASCII characters, @mawww fixed this here: https://github.com/mawww/kakoune/commit/fb9dbfed2a903fbf38f37db904c960d69973fb8b

The full list of remaining keys for kitty, as far as I can tell, is:

```
kitty     expected
-------   --------
<a-s-0>   <a-)>
<a-s-1>   <a-!>
<a-s-2>   <a-@>
<a-s-3>   <a-#>
<a-s-4>   <a-$>
<a-s-5>   <a-%>
<a-s-6>   <a-^>
<a-s-7>   <a-&>
<a-s-8>   <a-*>
<a-s-9>   <a-(>
<a-s-`>   <a-~>
<a-s-\>   <a-|>
<a-s-/>   <a-?>
<a-s-[>   <a-{>
<a-s-]>   <a-}>
```


I can't map _any_ of the keys for a work around, even the symbols:

`1:1: 'map': Shift modifier only works on special keys and lowercase ASCII, not '0'`.

(I'm trying with:
```kak
evaluate-commands %sh{
    keys="
        '<a-s-0>' '<a-)>'
        '<a-s-1>' '<a-!>'
        '<a-s-2>' '<a-@>'
        '<a-s-3>' '<a-#>'
        '<a-s-4>' '<a-\$>'
        '<a-s-5>' '<a-%>'
        '<a-s-6>' '<a-^>'
        '<a-s-7>' '<a-&>'
        '<a-s-8>' '<a-*>'
        '<a-s-9>' '<a-(>'
        '<a-s-\`>' '<a-~>'
        '<a-s-\>' '<a-|>'
        '<a-s-/>' '<a-?>'
        '<a-s-[>' '<a-{>'
        '<a-s-]>' '<a-}>'
    "
    for mode in normal insert prompt; do
        eval set -- $keys
        while [ $# -gt 0 ]; do
            printf 'map global %s %s "execute-keys -with-maps %s"\n' "$mode" "$1" "$2"
            shift
            shift
        done
    done
}
```
)

**Comment by eraserhd** [comment]
Additional info, which might help in choosing a solution.  I have a custom keyboard with QMK firmware, and that means I don't actually type `alt-shift-0` to get `<a-s-0>` -- I type `alt-symbol-d`.  But kitty can't actually know that, of course, since the keyboard needs to simulate something standard.  I'm not familiar with non-US keyboards, but I know that a keyboard built with QMK is supposed to use ANSI or ISO or whatever standard layout, regardless of its actual layout.

I think I'm saying it's probably ok for Kakoune to assume `<a-s-0>` means `<a-(>` and so forth, even though this might not be the case on a non-US keyboard.

**Comment by not-chicken** [comment]
Redundant since #4415
