### ISSUE TITLE
Syntax highlighting slows down multi selection editing.

### ISSUE THREAD

**Issue by crocket** [mawww/kakoune#4275]
I have an hledger journal which spans about 20,000 lines.

If ledger filetype was activated, loading the journal is slow.
Multi selection editing becomes noticeably slower with ledger mode.

With plain filetype, multi selection editing is a lot faster.

**Comment by Calum-J-I** [comment]
Can you post a copy of the file?

**Comment by lenormf** [comment]
I'm going to hijack this issue to point at other problems in `ledger.kak`, which should be fixed by whoever is kind enough to create a PR that modifies this file.

1. this command is never called and is a misnomer:

https://github.com/mawww/kakoune/blob/15aa4fe/rc/filetype/ledger.kak#L34

2. number highlighted as a function (in general the faces used in the file are suspicious):
 
https://github.com/mawww/kakoune/blob/15aa4fe/rc/filetype/ledger.kak#L54

3. many regions apply to single lines when a regex would have been more appropriate:

https://github.com/mawww/kakoune/blob/15aa4fe/rc/filetype/ledger.kak#L59

4. spawning a shell is not necessary:

https://github.com/mawww/kakoune/blob/15aa4fe/rc/filetype/ledger.kak#L68

5. no word boundary escapes (applies to the rest of the file as well):

https://github.com/mawww/kakoune/blob/15aa4fe/rc/filetype/ledger.kak#L72

6. keyword-specific individual regions may not be necessary, this could potentially all be factorised into a generic highlighter:

https://github.com/mawww/kakoune/blob/15aa4fe/rc/filetype/ledger.kak#L76-L122

HTH.

**Comment by crocket** [comment]
> Can you post a copy of the file?

It is full of my personal information. So, I don't want to post a copy here.

**Comment by crocket** [comment]
@lenormf If your issues are fixed, does ledger.kak become faster?

**Comment by lenormf** [comment]
I don't know, but I don't think so. The issue is bound to your user configuration and the test file itself, so if we have neither, it's difficult to know for sure.

**Comment by crocket** [comment]
If your issue isn't related to performance, you should create another issue.

**Comment by crocket** [comment]
Closing this for a new issue.
