### ISSUE TITLE
Are modules a design error?

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#4285]

**Comment by Screwtapello** [comment]
Modules were added to help reduce the amount of work that had to be done at startup, and also to allow plugins to depend on one another without making assumptions about load order.

As far as I can tell, they succeeded at both. So, no, not a design error. Is there any particular reason you think they might be?

**Comment by Delapouite** [comment]
Please Alexherbo2, most of your issues only have a title and no text-content what so ever!

You have to understand that other people can't always read your mind ;) I hope you'll be able to make more substantial messages in the future.

**Comment by Calum-J-I** [comment]
There are a few implementation details that could be improved upon. For example:

* allowing you to re-require modules (which would also mean making it possible to overwrite hooks and options)
* the lack of a  module private flag to avoid name clashes.

but I don't think this means modules are "design errors".

Modules are simply a lazy `eval` and fit well with kakscript's philosophy of simplicity. Quality of life improvements to kakscript as a whole, like being able to re-declare options, can help improve the module system.

**Comment by Screwtapello** [comment]
> ...being able to re-declare options...

Kakoune already lets you redeclare options - the `toolsclient` option (for example) is declared in `lint.kak`, `make.kak` and `grep.kak`. Hooks and commands and user modes, etc. do require restarting Kakoune, though.

**Comment by Calum-J-I** [comment]
> Kakoune already lets you redeclare options 

only if it has the same type or flags though, which is a nuisance if you writing kakscript and decider your `str` should have been a `str-list`

**Comment by mawww** [comment]
> only if it has the same type and flags though, which is a nuisance if you're writing kakscript and decide your `str` should have been a `str-list`

The reason redeclaring options is not an error is to support shared options that have the same meaning across different scripts, an option that's specific to a single script should have a name that avoids conflicts with other scripts (using some `prefix_` for example). When an option is shared, the different scripts relying on it (and the user config) have to agree on its type.

Regarding the general issue, I think modules ended up with a very straightforward design that added minimal complexity while solving multiple issues (as @Screwtapello mentionned). Faster startup time, ability to override modules without having to go through the autoload symlinking dance, avoid cluttering the command list...

And I agree with @Delapouite, I would like the issues you open to be a bit more descriptive, in this specific case I have no idea what makes you think modules might have been a design error.

**Comment by lenormf** [comment]
I'll join in on the guess game as well.

Originally, the `.kak` scripts were not considered individual plugins, but rather additional functionalities that could be loaded at runtime. There was no abstraction at “language” level, only code that declared new options/commands organised in separate files, according to the functionality they implemented. It was pretty loose.

Over time, the number of functionalities (and thus, scripts) grew, the editor couldn't get away with loading all the scripts indiscriminately at startup without impacting boot-up time any more, and users needed a more robust way to “enable” a set of functionalities (inter-dependencies, hooks, options, commands…).

So naturally the concept of module came up, it fixes the issues mentioned above, and that's how other editors do it© anyway, so users are already familiar with the concept (and it turned out, expected it as well).

Now I'm guessing that @alexherbo2 might be meaning to ask whether there was another direction that could have been taken, other than turning loose scripts into self-contained units we call plugins? I was fond of the original approach, and maybe there was another way of dealing with issues that stemmed from it without slapping a layer of abstraction on top of everything?

It's an interesting thought exercise.
