### ISSUE TITLE
Automatically pick the only completion suggestion of a command/argument

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#430]
Hi,

Usecase:
* I have several buffers open, and I want to switch to another one
* I start typing the command `:b <sometext>`, where `sometext` is a part of the name of the buffer I want to switch to that isn't shared with any of the other open buffers
* the completion menu pops up, and there's only one item in it because I typed in a specific substring that is unique to the name of the buffer I want to switch to
* I directly hit the return key, and my target buffer is open

The way things are implemented now, I would have to hit the tab key before the last step to select the only completion that is offered by `kak`, and that's an extra step that could be avoided imo.

Thanks.

**Comment by mawww** [comment]
Thats tricky, because it needs we need to annotate completions to know if they are providing the full range of valid values or not. For example we cannot apply that method to `:edit` as you might be wanting to create a new file, even though there is a single completion match. We get the same problem with options, as there are some hidden options, that wont get shown to completion, but if for some reason you want to set them, and there is a non-hidden option that matches, you wont be setting the expected option.

That feature would work for the most common cases, but would silently create errors in some more tricky ones (or not so tricky, like the `:edit` case if we dont add some special casing). I do not think it is worth it.

**Comment by lenormf** [comment]
What about implementing only for the use case I gave then, when switching buffers with `:b` ? That case shouldn't be ambiguous ?

**Comment by mawww** [comment]
We could do that, yet I am not convinced the benefits outweighs the consistency costs.

**Comment by lenormf** [comment]
I see, I'll declare a new function of my own then! Closing the issue.

**Comment by Delapouite** [comment]
> I'll declare a new function of my own then

I'm also interested in this exact feature.
I skimmed through https://github.com/lenormf/kakoune-extra without success. Did you end up writing this script? Thanks.

**Comment by lenormf** [comment]
I wrote the following function that relies on `fzy` (it's probably easy to adapt to `fzf`):

```
def -file-completion -params 1 instab %{ %sh{
    path_buffer=$(printf %s\\n "${kak_buflist}" | tr : '\n' | fzy -e "$1")
    if [ -n "${path_buffer}" ] && [ "$(printf %s\\n "${path_buffer}" | wc -l)" = "1" ]; then
        printf 'buffer %%{%s}\n' "${path_buffer}"
    fi
} }
```

In the end I don't use it that much, as it's a bit dirty to use an external fuzzy matcher (it could potentially yield results different from what the one used by kakoune would return). Having access to the list of candidates available at the time of the execution of the command would fix it, but I'm not sure it's worth the trouble.
