### ISSUE TITLE
How to Search the keyword under the cursor.

### ISSUE THREAD

**Issue by lougxing** [mawww/kakoune#4371]
### Question

same as "*" with vim,   search the word under cursor.

**Comment by Screwtapello** [comment]
`*` in Kakoune copies the word under the cursor into the search register, so then you can use `n` and `<a-n>` to cycle between occurrences in the file, `s<ret>` to select all the occurrences in the file, `:grep<ret>` to search for all occurrences in the current directory, etc.

**Comment by lougxing** [comment]
@Screwtapello，   
press ### “*”，
only copy the letter under the cursor, only one letter is searched.
How to search the full word ?

**Comment by Screwtapello** [comment]
Sorry, I explained that wrongly. `*` copies the *contents of the main selection* into the search register. It can be more or less than a word, depending on what's selected. If it's less than a word and you want it to be exactly a word, you can use a command like `<a-a>w`.

In practice, I find I don't need to mess with the selection before hitting `*`, since moving by `w` or `b` will naturally select the word I want (sometimes I hit `_` too, to trim whitespace from the selection before I search for it).

**Comment by lougxing** [comment]
@Screwtapello  Thanks for your help.
