### ISSUE TITLE
[REQUEST] Allow Refusal to Open a File That's Already Open in Another Session 

### ISSUE THREAD

**Issue by nick-chandoke** [mawww/kakoune#4402]
### Feature

There should be a command line option to have kakoune show a warning dialog when trying to open a file that's already open in another kakoune session. (If I want to open an already open file in another window/view then I'd use `kak -s`.) Too many times I've accidentally done this, only to find kakoune asking whether I want to keep the document or reload, but I don't even know where the docs differ!

**Comment by nick-chandoke** [comment]
@krobelus by "legitimate" you mean "useful?" anyway, your technique technically works but is extremely inconvenient whenever the edits are on lines far away from each other. here we can see which all lines were changed only by cycling through all selections, possibly spanning thousands of lines for even only a handful of edited lines. furthermore if edits are made on a long line, then we can only see that the line was changed rather than how it was changed—like diff but not wdiff.

@lenormf you are correct. thank you for the flock suggestion. i couldn't identify a way to use kakoune hooks with it, but in interactive terminals i can alias kak to a script: `flock -n "$1" kak "$1" || echo $1 is already open`

**Comment by mawww** [comment]
I dont think this should be part of Kakoune core, first because I think its a reasonable use case to have the same file opened multiple times, and reload functionality can help for that (some kind of merge functionality could be nice as well), also because implementing this would require some kind of communication between sessions and that adds complexity.

One way to achieve that with a script would be to hook on `BufOpenFile` and either create a `${kak_buffile}.lock` file if it does not exist, or delete the buffer with some error message if that file already existed (with an additional hook to delete the lockfile on close).

**Comment by Screwtapello** [comment]
It's easy to acquire a lock on `BufOpenFile`/`BufNewFile` and release it on `BufClose`, but I don't believe it's possible to hook `:rename-buffer -file <filename>` or `:write <filename>`.

Even if you could hook those things, if it turns out some other session has locked the file, how can a plugin prevent the file from being loaded? If you `:delete-buffer` inside `BufNewFile`, Kakoune throws a runtime error "buffer got removed during its creation" making it difficult to display a nice error message.

**Comment by nick-chandoke** [comment]
It's becoming clear that this issue is not easily solved by kakoune itself, and that this is a personal shortcoming rather than kakoune's. I will implement my own methods to help myself open files exclusively or simultaneously, when whichever is appropriate.
