### ISSUE TITLE
[QUESTION] Can't select entire buffer using GE

### ISSUE THREAD

**Issue by asmarcz** [mawww/kakoune#4454]
### Question

Hello, I used to select the entire buffer by doing:
```
gg
GE
```
After I updated Kakoune it stopped working and says "key not mapped". What is going on?

I'm using v2021.11.08,
Thanks

**Comment by mawww** [comment]
This is an anoying bug fix, it is bothering me quite regularly as well so I am tempted to revert to the old behaviour.

Basically we realized that the goto logic that was ignoring case was breaking the ability to map upper case letters in goto mode (you could map `E` in goto mode, but hitting `GE` would use `e` anyway, ignoring your mapping). The fix was to stop ignoring case in goto mode.

In the mean time you will need to map 'E' to 'e' in goto mode.

**Comment by asmarcz** [comment]
I'm sorry, I'm not very proficient in Kak. I thought that holding Shift extends selection, universally. So, can I achieve the original effect by doing Ge instead of GE? Not sure I understand the explanation completely. Would I break anything by configuring what you suggested? How?

**Comment by sidkshatriya** [comment]
- In older versions both GE and Ge would have the same effect. Recently GE stopped working because mawww wanted people to be able to let people make E mean something else (if you want to)
- But if you want the old behavior you can assign E to mean e when you are doing a goto

```kak
map global goto E e
```

Add the above to your kakrc anywhere.

- You also don't need to do `gg` followed by `Ge` BTW. You can simply use `%` to select the whole buffer
