### ISSUE TITLE
Make the object selection feature smarter

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#449]
Hi,

I think it'd be good to make the object selection aware of escape sequences, particularly when using the `<a-i>` or `<a-a>` combinations. The way things work now, those two key bindings are mere shortcuts to `T` or `F` combinations, and that's sometimes not convenient.

Example:

``` c
static char const * const s = "this is a \"substring\" in a string";
```

If the cursor is located anywhere within the `s` string, using `<a-i>` will stop the selection to the first `"` sign it sees, when I want the entire string to be selected.

That's the most evident case, but I suppose the same issue applies to the other object types.

Thanks.

**Comment by mawww** [comment]
String objects are not the primary target or the object selection, they are actually quite tricky because we cannot know when they start/end locally, we would have to parse the file from the start to see if a `"` is a start or an end, additionally, escaping is language specific, so I would not favor hard coded handling of `\"` as non string delimiter, making object definition configurable might do the trick, but I am not really keen on making object selection behaviour change between buffers.

To be more explicit, object selection is mostly targeted towards nestable object, for example if you are in `{ blah{}, foo{ bar {} } _ }` (` _` marks the cursor position), `<a-i>{` will select inside the outer `{ ... }` block, correctly handling nested ones.

**Comment by lenormf** [comment]
I see where you're coming from, but I still think handling escaping is a good choice. I talked about the double quote sign because that's the one I use the most frequently, but the issue remains with simple quotes and back quotes. Those two characters are handled by `<a-i>` and `<a-a>` in a way that is only half convenient, mostly because (apparently) object selection was intended in the first place to interact with objects whose boundes use different characters (`{` vs `}`, `(` vs `)` etc).

What we can do to deal with this is let object selection deal with actual objects, remove support for simple/double/back quotes, but add a way for the users to extend the object selection command, so that they can have their own `<a-i>"`, `<a-i>'` etc (the kak implementations can be added to the community repository).

**Comment by danr** [comment]
I was bitten by this when writing a python dict that looked something like this: 

    opening = {'}': '{', ']': '[', ')': '('}

Object selection and matching did not work very well here. Hence I'm diving into this old conversation.

> we would have to parse the file from the start to see if a " is a start or an end, 

Common languages and usages of quoted strings are not multiline: it would be enough for most uses to just scan the current line.

> additionally, escaping is language specific,

This is of course true, but single-line strings quoted with `"` or `'` and escaped the standard way covers the vast majority of written code.

I vote to reopen this issue and support standard escaping of strings on a line-by-line basis. It is far better than what we have now.
