### ISSUE TITLE
[BUG] Cursor disappears after closing SSH session

### ISSUE THREAD

**Issue by ttttcrngyblflpp** [mawww/kakoune#4514]
### Version of Kakoune

2020.09.01-3

### Reproducer

SSH into a host, run kakoune, close the SSH session using the escape sequence `Enter`, `~`, `.`.

### Outcome

SSH session gets closed and cursor is restored.

### Expectations

Cursor is no longer visible (requires `reset` to reset the terminal).

### Additional information

I can reproduce this reliably with xterm, uxterm, and gnome-terminal. I'm using a debian-like distribution.

**Comment by Screwtapello** [comment]
I don't think this is a bug in Kakoune; if anything it's a flaw in the design of the Unix terminal system.

When you launch Kakoune it sends a bunch of escape sequences to your terminal, to do things like hide the cursor, enable mouse events, enable more sophisticated keyboard event reporting, etc. When you shut down Kakoune cleanly, it sends a different bunch of escape sequences to your terminal to disable all those things and return to "normal".

If the connection between Kakoune and the terminal is severed unexpectedly (because somebody used `~.`, because an excavator dug up a buried cable, whatever) it doesn't get a chance to send the "undo" sequences. There's nothing Kakoune can do to clean up the terminal state if it can't talk to the terminal.

It would be possible for Kakoune to avoid cleaning up terminal state by not setting terminal state in the first place, but that substantially limits what Kakoune can do. The most complex editor that doesn't need to change the terminal state from what the shell uses is an editor that looks and works like the shell: a command-line editor like `ed` or `ex`.

Another alternative would be to make your shell prompt always send terminal reset sequences, so when you return to the shell (by whatever means) the terminal is automatically in a sensible state.

Yet another alternative would be to use a tool like `mosh` where the terminal emulation happens on the remote side, and the local client is responsible for managing the local terminal, so if the connection goes down the local client can clean things up.

**Comment by ttttcrngyblflpp** [comment]
Closing as "working as intended."
