### ISSUE TITLE
[BUG] Pressing space has no effect while holding the shift key

### ISSUE THREAD

**Issue by gbrookshire** [mawww/kakoune#4534]
### Version of Kakoune

v2021.11.08

### Reproducer

Open a document, press `i` to enter insert mode. Hold shift and type `# HELLO THERE`.

### Outcome

The text appears as `#HELLOTHERE`.

### Expectations

The text should appear as `# HELLO THERE`.

### Additional information

Delete also does not work while holding shift. In the terminal or in other programs, holding shift and pressing space inserts a space.

macOS 12.1

**Comment by Screwtapello** [comment]
Are you using the standard macOS Terminal app, or a third-party terminal like iTerm2?

**Comment by gbrookshire** [comment]
I'm using iTerm2. For what it's worth, the text appears correctly as `# HELLO THERE` when I type directly into the command prompt in iTerm2.

I just tried replicating the bug in the standard Terminal app. The spaces appear correctly, but the colors do not, and the cursor isn't visible.

**Comment by Screwtapello** [comment]
Please start Kakoune and run the following commands:

    :buffer *debug*                # switch to the debug buffer
    :set-option global debug keys  # tell Kakoune to log each received key

Then press Space and Shift-Space and see what gets logged. On my Linux machine in GNOME Terminal, when I press Space I get:

    Client 'client0' got key '<space>'

...and when I press Shift-Space I get exactly the same thing. Likewise, when I press Backspace I get:

    Client 'client0' got key '<backspace>'

...and the same thing happens when I press Shift-Backspace

**Comment by krobelus** [comment]
> Open a document, press `i` to enter insert mode. Hold shift and type `# HELLO THERE`.

Same thing happens in the "foot" terminal.
This is probably because we can map `<s-space>` independently of `<space>`.

Use this command to find out the name of a key:

	on-key %{echo %val{key}}

so the workaround is

	map global insert <s-space> <space>
	map global insert <s-backspace> <backspace>
	map global prompt <s-space> <space>
	map global prompt <s-backspace> <backspace>

I think there are no other keys that behave like this? (for example
shift-return sends `\033[27;2;13~` in my terminal).

> In the terminal or in other programs, holding shift and pressing space inserts a space.

OK, we should try to follow that to make it easier to type HELLO THERE
without letting go of shift (it works everywhere else).

It should affect at least insert and prompt mode. Probably not necessary
for others like normal mode?

The fix is probably something like this (need to check some other places that special-case Key::Space)

```diff
diff --git a/src/input_handler.cc b/src/input_handler.cc
index 5a852e1b..3318c819 100644
--- a/src/input_handler.cc
+++ b/src/input_handler.cc
@@ -467,7 +467,7 @@ public:
             m_cursor_pos = 0;
         else if (key == Key::End or key == ctrl('e'))
             m_cursor_pos = m_line.char_length();
-        else if (key == Key::Backspace or key == ctrl('h'))
+        else if (key == Key::Backspace or key == shift(Key::Backspace) or key == ctrl('h'))
         {
             if (m_cursor_pos != 0)
             {
@@ -1276,7 +1276,7 @@ public:
             m_completer.reset();
             pop_mode();
         }
-        else if (key == Key::Backspace)
+        else if (key == Key::Backspace or key == shift(Key::Backspace))
         {
             Vector<Selection> sels;
             for (auto& sel : context().selections())
diff --git a/src/keys.cc b/src/keys.cc
index 8eb3fce0..e1f3e2c9 100644
--- a/src/keys.cc
+++ b/src/keys.cc
@@ -49,7 +49,7 @@ Optional<Codepoint> Key::codepoint() const
         return '\n';
     if (*this == Key::Tab)
         return '\t';
-    if (*this == Key::Space)
+    if (*this == Key::Space or *this == shift(Key::Space))
         return ' ';
     if (*this == Key::Escape)
         return 0x1B;
```

**Comment by gbrookshire** [comment]
Here's what I get in the debug buffer:

```
*** This is the debug buffer, where debug info will be written ***
error running hook WinSetOption(filetype=python)/: 3:5: 'lint-enable': no such command
Client 'client0' got key '<space>'
Client 'client0' got key '<s-space>'
Client 'client0' got key '<backspace>'
Client 'client0' got key '<s-backspace>'
```

When I try `on-key %{echo %val{key}}` and press shift-space, it says `<s-space>`.

Unfortunately, that workaround doesn't work for me. I get an error: `Shift modifier only works on special keys and lowercase ASCII, not ' '`

Thank you for your help with this!

**Comment by krobelus** [comment]
> Unfortunately, that workaround doesn't work for me. I get an error: `Shift modifier only works on special keys and lowercase ASCII, not ' '`

That must be somthing fixed since the v2021.11.08 release: it doesn't work on that version, but it works on latest master; try compiling that, it should be easy, you just need a new-ish compiler.

**Comment by gbrookshire** [comment]
How new is new-ish? I tried compiling with the default "make" command, and get this warning: "ld: warning: directory not found for option '-L/opt/local/lib'". Then I get an error when trying to start kak that I don't get when running the installation through homebrew: 
```
/x/x/x/x/:1:1: 'def': wrong argument count
error while parsing kakrc:
    1:1: 'source': 1:1: 'def': wrong argument count
```

**Comment by krobelus** [comment]
On Wed, Feb 09, 2022 at 09:20:37AM -0800, Geoff Brookshire wrote:
> How new is new-ish?

According to the CI (.cirrus.yml) gcc 10 or clang 11.
Anway, that's not relevant since you already compiled it successfully.

The workaround with mapping `<s-space>` didn't work for you because you didn't have
658b6b0f (Make space a named key to correctly handle shift modifier, 2021-12-11).

> I tried compiling with the default "make" command, and get this warning: "ld: warning: directory not found for option '-L/opt/local/lib'". Then I get an error when trying to start kak that I don't get when running the installation through homebrew: 

That warning is harmless.  -L/opt/local/lib was added in
https://github.com/mawww/kakoune/pull/1262, but since Kakoune no longer has
dependencies beyond the standard library, these can probably be removed.

> ```
> /x/x/x/x/:1:1: 'def': wrong argument count
> error while parsing kakrc:
>     1:1: 'source': 1:1: 'def': wrong argument count
> ```

There were a few breaking changes since the last release (like 6f135c0c (Do not insert any end-of-line when piping data out, 2022-01-24)) but none of them should matter here.

Perhaps you have overridden the autoload directory and are loading old rc files?
If `HOME=$(mktemp -d) src/kak` works, then it must be something in your config.
