### ISSUE TITLE
Autocomplete function parameters?

### ISSUE THREAD

**Issue by procedural** [mawww/kakoune#455]
Warning trigger: I'm absolute noob multiplied by two here.

I can see variable names, but not function parameters when editing C files. Is it possible to see them?

Thanks!

**Comment by lenormf** [comment]
It's not possible at the moment, I don't think the completion engine has any kind of context awareness.

**Comment by mawww** [comment]
Hello, not sure what you mean by "I cant see function parameters", do you mean displaying some info on the parameters that a function takes while you are writing a call to it ?

That can be enabled with ctags support using `:ctags-enable-autoinfo` which will try to get function signature information from the tags file. We could maybe extend clang.kak to try to get that information from clang as well.

**Comment by procedural** [comment]
>do you mean displaying some info on the parameters that a function takes while you are writing a call to it ?

No, just list parameters of the current function, how many of them and what's their type / name.

>That can be enabled with ctags support using :ctags-enable-autoinfo which will try to get function signature information from the tags file.

Should this out of the box, without installing anything? Because I tried it right now and nothing happened...

**Comment by mawww** [comment]
ctags support requires a tags file, and the readtags command. That command is available as part of universal-ctags (installed by default), or as part of exuberant-ctags (but you have to compile it yourself). ctags.kak also provides a `gentags` command that launch tag generation in the background and notifies you when done.

So, in order to get tag based function information, you need to have a tags file generated, the readtags command available, and execute `:ctags-enable-autoinfo` on the buffers you want. if you want to enable that for all C/C++ buffers, you can add these hooks in your kakrc:

```
hook global WinSetOption filetype=(cpp|c) ctags-enable-autoinfo # enable when filetype is set to c or cpp
hook global WinSetOption filetype=(?!(cpp|c)$).* ctags-disable-autoinfo # disable when set to something else
```

**Comment by mawww** [comment]
clang completion now also tries to display current completion docstring while editing the parameter list.
