### ISSUE TITLE
[QUESTION] Is there a way to quickly select big chunk of lines independently from text sytax?

### ISSUE THREAD

**Issue by Adomas-beep-boop-maggots** [mawww/kakoune#4565]
### Question

Right now i see 2 ways how to do it, but it's not efficient as i would like. 
1. Spamming J, K, X
2. Saving selector with Z and scrolling down (with Ctrl-[u or d] for example) to where you what the selection to end and then a-z u to make a selection.
### Suggestion
If there is no built in way to do this, i suggest Ctrl-Shift-[u or d] as a good keybinding, as at least for me it makes sense, cause Ctrl-[u or d] scrolls half page [up or down] and Shift is commonly used to extend selections.

**Comment by Screwtapello** [comment]
If you want to bulk-select text and you really, really don't want to make any assumptions about the structure of the text you're selecting, then yeah, those are probably your only options. If your text has at least a little bit of structure, you might be able to use `<a-i>i` to select text that shares a common indent, or `m` to select text within grouping symbols or `?` to select text up until the next occurrence of a regex (for example, `?^#<ret>` to select up to the next Markdown heading).

Unfortunately, the traditional terminal keyboard protocol does not allow the Shift key to be used with the Control key, so `<c-s-u>` and `<c-s-d>` can't be mapped, nor can `<c-s-b>` or `<c-s-f>` or `<s-pgup>` or `<s-pgdn>` which is probably why there's no extend-selection-by-a-page keybinding already.

Perhaps Kakoune could have additional `gn` and `gp` mappings for next and previous page, so that `Gn` and `Gp` would extend the selection.

**Comment by krobelus** [comment]
> 1. Spamming J, K, X

note that you can pass a count argument like `11J`

Also, `Gb` (or `GB`) selects to the end of the screen

to select a half screen, perhaps tell your shell to export LINES and add a mapping:

	LINES=$LINES kak -e 'map global user J %{: execute-keys %sh{echo "$(( ${kak_client_env_LINES} / 2 ))J"}<ret>}'

**Comment by Screwtapello** [comment]
> ...tell your shell to export LINES...

Kakoune provides `%val{window_height}` (and therefore `$kak_window_height`) for this kind of thing.

**Comment by krobelus** [comment]
On Sat, Mar 12, 2022 at 05:53:32AM -0800, Screwtapello wrote:
> > ...tell your shell to export LINES...
> 
> Kakoune provides `%val{window_height}` (and therefore `$kak_window_height`) for this kind of thing.

sweet, thanks!
