### ISSUE TITLE
[REQUEST] <a-.> to repeat ANY movement key

### ISSUE THREAD

**Issue by Adomas-beep-boop-maggots** [mawww/kakoune#4567]
### Feature

I think it would be great idea to make <a-.> repeat all previous movement keys rather then restrict it to repeating f and t commands. while Its true that number keys are already used to do movement number of times, you can also use this number functionality and repeat number of times movement with <a-.>.
### Example
10j 10j 10j 10j - 12 keys pressed
turns into
10j <a-.> <a-.> <a-.> - 7 keys pressed

**Comment by Screwtapello** [comment]
Some kinds of movement are very simple, like `w` or `l` or  `j` and I can happily repeat them myself just by holding them down.

Some kinds of movement are more intricate, and require a little thought to get the selection into exactly the right place. For example, `/` (search) and `t`. For those kinds of movement it's good to have a simple repeatable "do the same thing I did last time" so I can pay the mental price to figure them out *once* and then keep doing the same thing without having to remember the details or work them out again every time. For `/`, that mechanism is the search history, so I can `/<ret>` to repeat the last search. For `t`, that mechanism is `<a-.>`.

If `<a-.>` would repeat *any* movement, nine times out of ten it would provide an easy way to repeat a movement that's already easy to repeat, and there'd be no way to repeat the last `f` or `t` command that's difficult to repeat (because it would have been overwritten by the next `w` or `l` or whatever).

**Comment by Delapouite** [comment]
> 10j <a-.> <a-.> <a-.> - 7 keys pressed

With the count support available in this PR https://github.com/mawww/kakoune/pull/1602 you could simplify even further:

> 10j 3<a-.>

**Comment by Adomas-beep-boop-maggots** [comment]
> If `<a-.>` would repeat _any_ movement, nine times out of ten it would provide an easy way to repeat a movement that's already easy to repeat, and there'd be no way to repeat the last `f` or `t` command that's difficult to repeat (because it would have been overwritten by the next `w` or `l` or whatever).

I agree, this behavior also has its downside. And I guess its up to personal preference to what <a-.> behavior would be best for users. I'm unsure myself if its worth adding now...
