### ISSUE TITLE
`:new` doesn't work in `tmux` on OS X

### ISSUE THREAD

**Issue by charles-l** [mawww/kakoune#463]
Running `:new` in a tmux session does not work on OS X (and fails silently). The reason is because the 'client' script attempts to call `setsid` which for some dumb reason isn't in OS X standard utils (srsly apple?). The biggest issue is that it failed silently, and just didn't create the window.

I got around this issue by installing a simple `setsid` command (https://github.com/jerrykuch/ersatz-setsid).

**Comment by mawww** [comment]
Hi, thanks for the report.

This is tricky, we use setsid because we want the launched terminal emulator (when not in the tmux case) to be in another process group, so that a <c-c> in kakoune (which sends SIGINT to the process group to close eventual running shell commands like make/grep) would not close the terminal emulator of the new client.

We also want that to run detached, as we want the %sh{...} block to return before the new terminal emulator is closed, hence the '>/dev/null </dev/null 2>&1 &' thing.

**Comment by mawww** [comment]
it should work now in tmux, as tmux does not need setsid anyway (and the new tmux.kak does not use it anymore).
