### ISSUE TITLE
[BUG] Inlay hints (e.g. via kak-lsp) cause text to be unscrollable horizontally

### ISSUE THREAD

**Issue by sidkshatriya** [mawww/kakoune#4659]
### Version of Kakoune

master

### Reproducer

When looking at source code in kak-lsp with a lsp server (e.g. rust analyzer) which emits inlay-hints (essentially text for things like type annotations) kakoune does not adjust the horizontal width of a line.

### Outcome

So you might be in a situation where a long line is chopped off (due to an inlay hint causing the line's length to increase) and you cant use the cursor to horizontally scroll.

This makes it very inconvenient to edit the document.

### Expectations

Kakoune should allow a horizontal scroll when an inlay hint causes the text to overflow the terminal width.

Essentially an inlay hint is considered zero width by kakoune but it _does_ takes up space for the purposes of a horizontal scroll. 

### Additional information

I'm sure this has been reported before but I was not able to find a related issue. In case anybody knows, please let me know the tracking issue and we can mark this as a duplicate.

**Comment by sidkshatriya** [comment]
@krobelus Maybe you would know how we can solve ^^

**Comment by Screwtapello** [comment]
Steps to reproduce:

1. Create the input document:

        $ echo "hello world" > /tmp/input

1. Launch Kakoune with a `replace-ranges` highlighter with a replacement that's wider than the screen:

        $ kak -n -e 'decl range-specs myrange; addhl global/ replace-ranges myrange; set buffer myrange %val{timestamp} 1.6+0|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' /tmp/input

    (where there should be at least as many "x"s as `$COLUMNS`)

1. Go to the beginning of the buffer and press `l` 6 times:

        gg6l

Expected result:

- View should scroll horizontally so that the "w" of "world" is visible on-screen

Actual result:

- View does not scroll, cursor disappears
- You can see the rest of the line if you follow the above movement with `6vl` to scroll past the replaced character, but if you go one step back to the left you'll get a whole line of "x" again

**Comment by sidkshatriya** [comment]
@mawww -- friendly ping. If you can give me some short technical hints I can try to resolve this bug myself. Though I suspect that the fix may potentially be quite involved!

**Comment by mawww** [comment]
I am looking at that, but as you suspected it is a bit involved, I hope to have a fix done in the coming days.

**Comment by sidkshatriya** [comment]
I can confirm that the above comment addresses the issue ! Hurrah !

One thing is that currently the cursor "jumps" in the the inlay hint area from the beginning of the inlay to the end if you try to traverse it. This has always been the behavior and there is no change here. 

What would be even nicer is if the cursor could move in the inlay hint area _but_ the whole area could be non-editable. Why? Because if the inlay hint is long, and the screen width short you are not able to see the whole inlay hint -- you will only see the beginning and then magically "teleport" to the end. (You would need to adjust the window width and so on to get to see the whole inlay-hint).

This probably requires more discussion and there are probably negatives with this kind of interaction too. But just putting out there.

**Comment by krobelus** [comment]
I think for the original use case (code lenses) the ideal fix would be to be able to insert virtual text in separate lines.
Do we have a use case for really long virtual text?

**Comment by Screwtapello** [comment]
> What would be even nicer is if the cursor could move in the inlay hint area but the whole area could be non-editable.

Part of Kakoune's editing model is that the cursor (and anchor) are always at some specific position in the underlying file. Since range-replaced text like an inlay hint doesn't exist in the underlying file, it doesn't have coordinates and so the cursor can't be placed part-way inside it.

I agree it would be nice if the mapping between buffer coordinates and screen coordinates were more robust, though — we could solve things like https://github.com/mawww/kakoune/issues/2654#issuecomment-731553822 too.
