### ISSUE TITLE
Changelog v2022.10.31 does not address "mode only supports lower case mappings" errors

### ISSUE THREAD

**Issue by xnuk** [mawww/kakoune#4769]
Related: f4ff59f8b2e010813b3cb09dc757a882e7a7b73c

How did I know this error? Because my configuration file is like:
```kak
map global goto u tvc          -docstring 'half page up'
map global goto e <esc><c-d>gc -docstring 'half page down'

# Kakoune complains here
map global goto U k -docstring 'buffer top'
map global goto E j -docstring 'buffer bottom'
```

**Comment by clarfonthey** [comment]
I also noticed due to my generic layout mapping config: https://vc.ltdk.xyz/ltdk/laymap

The change makes things slightly complicated since, for example, Colemak moves the semicolon key over the P, and while different cases aren't supported, different punctuation that can result from pressing shift is. Not sure if there's a good way to solve that problem now, although I've decided to just remove goto mapping in the meantime.

**Comment by mawww** [comment]
That error looks like a brain fart on my side, what this was intended to prevent was mapping **to** upper case keys, but it actually prevents from mapping **from** a upper case key.

The given commit restored the case insensibility of goto as `Ge` is hard to type and `GE` was equivalent for a long time, but preventing users from mapping upper case keys is not only unnecessary, it also break the ability to say map `GU` to `GE` (or `Ge` as those are equivalent). Will fix.
