### ISSUE TITLE
range-specs highlighter misaligment if line contains non-ascii character

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#4800]
### Version of Kakoune

2022.10.31

### Reproducer

```
kak -n -e 'eval -client client0 %{
execute-keys \%c∞,<space>word<esc>
declare-option range-specs lsp_references %val{timestamp} 1.4,1.7|Reference
set-face window Reference white,magenta
add-highlighter window/lsp_references ranges lsp_references
}'
```

### Outcome

∞`, wo`rd

### Expectations

∞, `word`

### Additional information

OS: Arch Linux
Terminal: foot with tmux
Related: https://github.com/kak-lsp/kak-lsp/issues/652

**Comment by krobelus** [comment]
from `:doc options` regarding `range-specs`

    b is the number of bytes from the start of the line to the first byte of the first character

since `∞` is encoded as 3 bytes, it looks correct that `1,4` refers to the `,` in `∞,`.

So this seems to be working as intended.
gopls or kak-lsp need to convert to byte coordinates.. but I thin they already do since I can't repro. Maybe it's due to locale..
