### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by xnuk** [mawww/kakoune#4870]
How about make release, like now? It's been 143 commits to master since [v2022.10.31], and personally I'm waiting #4769 to release. I'm using [kakoune-git] btw, but official release would be appreciated. And more frequent releases would be good.

[v2022.10.31]: https://github.com/mawww/kakoune/releases/tag/v2022.10.31
[kakoune-git]: https://aur.archlinux.org/packages/kakoune-git

**Comment by ismay** [comment]
> And more frequent releases would be good

Or just some insight into the planning. Knowing when a release can be expected, what still needs to be done, etc. That would help as well.

**Comment by donaldcallen** [comment]
And the response to the two reasonable requests above? Silence.

**Comment by xnuk** [comment]
> And the response to the two reasonable requests above? Silence.

@donaldcallen Why are you being offensive?

**Comment by ismay** [comment]
Yeah let's not put pressure on people working on this in their spare time.

**Comment by mawww** [comment]
I'll try to get a release done soon.

**Comment by donaldcallen** [comment]
> > And the response to the two reasonable requests above? Silence.
> 
> @donaldcallen Why are you being offensive?

If you think that is offensive, then I suggest either therapy or growing up. I'm sure you will find *that* offensive, but it's good advice.

**Comment by donaldcallen** [comment]
> Yeah let's not put pressure on people working on this in their spare time.

When you publish work such as kakoune, with a full-blown website and a git repository inviting people to use your work, you unsurprisingly acquire users, quite a few in the case of kakoune. That comes with a responsibility to be at the very least somewhat responsive to reasonable inquiries such as both of you made.  Or, if you will not or can not be responsive, let people know that the project has been abandoned.

I disagree with your assertion that I was putting pressure on kakoune's author. I was not asking for a major new feature NOW. I was simply reacting to the lack of a response to both your queries. The author has since responded, which is all I wanted.

**Comment by donaldcallen** [comment]
> > And the response to the two reasonable requests above? Silence.
> 
> @donaldcallen Why are you being offensive?

I'd like to add something from "the pot calling the kettle black" department: read your own first message, especially "How about make release, like now?"

**Comment by TeddyDD** [comment]
> That comes with a responsibility to be at the very least somewhat responsive

Lol, no. Quoting license:

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED

**Comment by mawww** [comment]
I intend to release really soon, however there is one big breaking change I am having doubts about (the history tree being linearized) and I want to decide what to do with that before releasing as last release with breaking changes led to lots of complaints.

**Comment by ismay** [comment]
This might be naieve, or just my personal preference, but I'm wondering if it would be easier on the maintainers of kakoune to have more frequent, smaller releases. In my experience shorter release cycles are often easier to manage and less stressful.

Looking at fzf for example https://github.com/junegunn/fzf/releases, there seem to be more frequent, smaller releases (at least recently). Wouldn't that be appropriate for kakoune as well?

**Comment by mawww** [comment]
@ismay The issue is that whenever we make a breaking change it needs to be tested for a while to be confident it is worthwhile change, and until that point we cannot really make a release with that change in. For users that are not afraid of trying out those the master branch is usually in a good shape, I believe quite a few users (myself included) use that rather than a release.

In any case the history tree change has frustrated me once to many so I intend to revert it and make a release in the coming week. I hope we can find a way to make history linearization possible with a plugin for users that did prefer the new system.

**Comment by ismay** [comment]
Ah ok. Yeah for me master has been perfectly fine as well. The only thing frustrating about running from master is the build times.

> In any case the history tree change has frustrated me yet another time so I intend to revert it and make a release in the coming week. I hope we can find a way to make history linearization possible with a plugin for users that did prefer the new system.

I see, yeah that sounds like a good course of action to me 👍!

**Comment by ismay** [comment]
Thanks for cutting the new release!
