### ISSUE TITLE
Race condition involving multiple hooks

### ISSUE THREAD

**Issue by chlobes** [mawww/kakoune#4896]
### Version of Kakoune

v2022.10.31

### Reproducer

set up the following hook:
```kak
#map {<ret> to create the other brace
hook global InsertChar \{ %[
	map buffer insert <ret> "<ret><esc>o<backspace>}<esc>kI"
  hook -once buffer InsertChar .* %{
		set buffer idle_timeout 500  
		hook -once buffer InsertIdle .* %{
			unmap buffer insert <ret>
		}
  }
	hook -once buffer ModeChange .*:*:normal %{
    unmap buffer insert <ret>
  }
]
```
then type {<ret> while in insert mode

### Outcome

Inconsistent behaviour, the commands can come out jumbled, or skip characters

### Expectations

the same as if the keypresses were done manually instead of via mapping

### Additional information

both of the once hooks are necessary, I tried to write a minimal example but changing anything prevents reproducing.
I can think of 3 possibilities (more than one of which may be true) that trigger the race condition:
1. ModeChange and InsertChar triggering at the same time
2. creating a new hook inside of a once hook
3. ~~InsertIdle and ModeChange triggering at the same time~~ changing idle_timeout arbitrary high still allows reproducing the bug, so this one seems unlikely

**Comment by krobelus** [comment]
It's generally quite hard to produce race conditions in Kakoune. The editor is single-threaded and hook execution order is deterministic.
(Kakoune does not even use dynamic hash maps, which are the usual source of nondeterminism.)

I can reproduce though.

I think what's going on here is that during execution of the `<ret>` mapping, the hooks trigger and remove said mapping.
The mapping continues executing but with unpredictable results since it's probably use-after-free.

A workaround is to suppress hook execution during the mapping, for example

```kak
rmhooks global x
hook -group x global InsertChar \{ %[
	map buffer insert <ret> "<a-semicolon>:execute-keys %[<lt>ret><lt>esc>o<lt>backspace>}<lt>esc>kI]<ret>"
	hook -once buffer InsertChar .* %{
		hook -once buffer InsertIdle .* %{
			unmap buffer insert <ret>
		}
	}
	hook -once buffer ModeChange pop:insert:.* %{
		unmap buffer insert <ret>
	}
]
```

**Comment by krobelus** [comment]
I'll submit a fix to throw an error if we try to unmap a mapping that is currently executing.
We can support that, no problem but I didn't find a use case yet.
