### ISSUE TITLE
[QUESTION] What data structure does kakoune use to represent text?

### ISSUE THREAD

**Issue by ribosomerocker** [mawww/kakoune#4924]
### Question

Looking at https://github.com/mawww/kakoune/blob/master/src/line_modification.cc
it looks like it might use gap buffers but I'm not really sure. Any confirmation?

**Comment by arrufat** [comment]
You can check @mawww 's answer to that on Reddit:

https://www.reddit.com/r/kakoune/comments/uo3hdp/underlying_data_structure

_In kakoune buffers are stored as a vector of strings. This is not fancy at all but proves very efficient for code as code usually has rather short lines and operations are rarely spanning multiple lines.

In effect, the nature of code makes a vector of lines act like a reasonably well balanced rope. It does break however in text files with very long lines. I would expect helix to beat Kakoune for that use case.

Kakoune can however be very fast for many operations because it keeps track of locations as line/column pairs, and the relevant data is basically two array lookups away which is quite hard to beat.

Selections are stored in a vector, sorted by location in the buffer, and many text operation take advantage of this to stay fast (see ForwardChangeTracker)
_

**Comment by ribosomerocker** [comment]
Thank you very much!
