### ISSUE TITLE
Move view with big selection

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#496]
Hi,

If the current selection spans more lines than can be displayed, modifying the view in the direction of where the cursor is (down if it's at the bottom of the screen and opposite) will not work, even though the cursor would still be visible.

Is there any reason why the cursor needs to included in the view?

**Comment by mawww** [comment]
Hello, the reason is that we try to keep as much of the selection visible as possible, giving priority to to cursor over the anchor.

I experimented with just keeping the cursor visible, not caring about the anchor, but it is an even less desirable behaviour, for example with <a-i>{ when the opening { is not visible yet.

**Comment by occivink** [comment]
What about letting the view be independent from the cursor only when manipulated directly (using ```v```)? Are there significant drawbacks to that approach?

**Comment by mawww** [comment]
Mainly that it requires some big changes, currently its at redraw time that the window tries to adjust its position to make sure the selection is visible, at that time, there is no information available on the user intentions.

I agree we could try to only update that view in certain circumstances (after the selection moved and / or the buffer changed), so that we could move around more freely with v, however I am not sure the complexity that would add is worth it.

**Comment by occivink** [comment]
Very well. For what it's worth, I would appreciate such a feature.

**Comment by robertmeta** [comment]
This just bit me yesterday, had to rotate around selection to read something then get it back.  Ignoring for a moment the complexity of implementation, doesn't it seem like view and selection should be separate?

Anyway, consider me a second person hoping for such a feature, I could see lots of uses for it.

**Comment by danr** [comment]
I thought this was fixed in #1172

**Comment by occivink** [comment]
You're right, I never even noticed. If separation of view and cursor is desirable let's make another issue.
