### ISSUE TITLE
[BUG] Using a non-balanced { in a comment in kakrc

### ISSUE THREAD

**Issue by Veraellyunjie** [mawww/kakoune#5072]
### Version of Kakoune

v2022.10.31

### Reproducer

in your `kakrc`:

```
hook global BufCreate /.* %{
    # hook buffer NormalIdle .* %{
}
```
imagine you want to have `# hook buffer NormalIdle .* %{` there as a reminder that you have such an option, but for cleanliness you don't preserve the body of it

### Outcome

```
error during startup, see `:buffer *debug*` for details
```
```
...: parse error: ...: unterminated string '%{...}'
```

### Expectations

what is commented out is ignored altogether

### Additional information

Might be related to https://github.com/mawww/kakoune/issues/2760

Worthy [comment](https://github.com/mawww/kakoune/issues/2760#issuecomment-469031840) by @eraserhd:

The %{ ... } quoting syntax, which you are using here, requires inside braces to be balanced. You could use %( ... ) or %< ... > instead, or you can add a comment at the end of the map line like so:
```
hook global WinSetOption filetype=latex %{ 
    map global user e 'i\{' # } <-- balance braces
}
```
Kakoune's configuration language is much like shell, although a bit saner because of the ability to nest. Kakoune doesn't know the inside brace is quoted at the time it's collecting the hook commands because it doesn't know yet that it is looking at more configuration language.

**Comment by krobelus** [comment]
the content of a quoted string is not necessarily Kakoune-script, so # might have a different meaning

**Comment by mawww** [comment]
This is by design, `%{` is just introducing a string, the fact that this string might be interpretted as some commands is not known to the parser at all. This is a very similar design to the tcl language. If your strong content is not balanced you can switch to another delimiter (say `%[ .. ]` or `%( ... )` or even  a non nestable one such as `%§ ... §`) or introduce a comment to ensure the delimiter is balanced.
