### ISSUE TITLE
A few questions on X removal

### ISSUE THREAD

**Issue by m-kru** [mawww/kakoune#5114]
### Question

I haven't updated Kakoune for some time, and I was really surprised when I discovered that `X` key was removed, it was my favorite action. Can I find anywhere a rationale for `X` removal? It looks like `X` is currently not used in any way, so why couldn't it stay like it was? How can I now, for example, remove 2 lines using 3 keystrokes? Previously I just typed `XXd`.

**Comment by Screwtapello** [comment]
See #4661, and the commit message for ef8a11b3dbefb8a1222974a8c34e15fa006d56e0.

In short, `x` (and therefore `X`) had complex stateful behaviour that was very convenient for humans but difficult to use in scripts. Now `x` *always* extends the beginning of each selection to the beginning of the line, and the end of each selection to the end of the line, rather than *sometimes* doing that and *sometimes* selecting the next line instead.

Since `X` currently has no function, you can map it to `xJ` for something similar to the previous behaviour (but more predictable).

**Comment by m-kru** [comment]
Is there any Changelog for Keys? There were more changes that completely destroyed my workflow. I feel like I do not how to edit documents anymore. For example, `<space>` does not reduce to single selection anymore. My following custom mappings for pasting from `xsel` stopped working and I have no idea why.
```kak
map global user p '<a-!> xsel --output --clipboard <ret>' -docstring 'System Clipboard - Paste After'
map global user P '!xsel --output --clipboard<ret>' -docstring 'System Clipboard - Paste Before'
```

**Comment by arrufat** [comment]
@m-kru Check this out: https://github.com/mawww/kakoune/blob/master/doc/pages/changelog.asciidoc#kakoune-20221031

**Comment by krobelus** [comment]
> Is there any Changelog for Keys?

clippy should show the changelog on startup. Equivalently, use `:doc changelog`

**Comment by m-kru** [comment]
@krobelus clippy presents overall changelog, and I am interested only in the "Keys Changelog".

**Comment by krobelus** [comment]
makes sense. Grepping for `<` filters it down to

```
* <a-u> and <a-u> now undo/redo selection changes; the previous meaning of moving in history tree has been moved to <c-j> and <c-k>
* <c-g> cancels the current operation and goes back to the main event loop, this provides an escape hatch when kakoune seems to hang due to a costly operation
* p, p, ! and <a-!> commands now select the inserted text
* x now just extends the selection to contain full lines (as <a-x> did) <a-x> trims partial lines from the selection (as <a-x> did)
* user mappings is now bound to <space> while keeping/removing main selection moved to , and <a-,>
```

I think if you want the old paste behavior back you could add `<semicolon>`. But the new behavior seems better

**Comment by GavinSmith0123** [comment]
It's easy to work around but I found the old behaviour was better.

A common task for me is to move some lines in a file from one part to another. Before it was `xxxx...d` to cut the lines, move to the new place in the file, then `P` to paste.

Now to select multiple lines it is something like `xJJJ...`. I don't really understand how this works, as the behaviour of `J` depends on the `x` before it. If the next line is longer than the current line, usually `J` only goes as far into the next line as the length of the current line, but if you type `x` first, it goes to the end of the next line. So the `x` command is still stateful (as of Kakoune 2024.05.18).

There's no way that I can find to get the old behaviour of `x` back exactly and the best I can get is to remap `X` so that you can type `xXXX...` to select multiple lines. I use the mappings posted by "arrufat" [here](https://discuss.kakoune.com/t/improved-and-consistent-line-selection-with-x-and-a-x/2243/5):

````
map -docstring 'extend lines downwards' global normal X %{<a-:>F<ret>x}
map -docstring 'extend lines upwards' global normal <a-X> %{<a-:><a-;><a-H>Kx}
````

Then for pasting, the pasted material is now always selected.  This is not a big deal as it is easy to do

````
map global normal P "P;"
map global normal p "p;"
````

in a config file.

Furthermore, I don't like the swapping of `<space>` and `,` either, as it's ingrained for me to slam the space bar after finishing a multiselection operation, so I swap those back:

````
map global normal <space> ,
map global normal , <space>
````

The change to <a-u> to go back in the selection history is excellent, though, and is the reason I upgraded to the newer version of Kakoune.
