### ISSUE TITLE
[BUG] macOS build results in make errors

### ISSUE THREAD

**Issue by paiv** [mawww/kakoune#5117]
### Version of Kakoune

v2023.08.05-302-g2ebaaaa4

### Reproducer

    git clone https://github.com/mawww/kakoune.git
    cd kakoune
    make

### Outcome

```
echo 'namespace Kakoune { const char *version = ""; }' > src/.version.cc
c++     -std=c++2a -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-sign-compare -O3 -g3    -c -o src/.version.o src/.version.cc
c++      -std=c++2a -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-sign-compare -O3 -g3       src/.version.o -o src/kak.opt
Undefined symbols for architecture arm64:
  "_main", referenced from:
      <initial-undefines>
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [src/kak.opt] Error 1
```

### Expectations

No errors

### Additional information

```sh
% uname -mrs
Darwin 23.3.0 arm64
% make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
```

This make does not handle shell assignments `!=` introduced to Makefile in b05295637e7dbe5239a1142a72afe8265e5d77c3

Apple is not going to upgrade GNU tooling, we are stuck with old versions.

The workaround for this GNU make is to use `= $(shell command)`.

Also works if both forms present https://unix.stackexchange.com/a/733310

**Comment by Screwtapello** [comment]
[Apparently](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html#tag_20_76_13_05) neither `!=` nor `$(shell ...)` are POSIX compliant. I guess if we want a *real* POSIX-compliant makefile, we'll need to turn all the little shell-scripts into build targets that run the given commands and redirect the output to a file, and all the places that *use* those commands to depend on those targets and read the contents in the shell command, rather than reading them in the makefile.

**Comment by mawww** [comment]
Turns out != is accepted for next posix standard... https://www.austingroupbugs.net/view.php?id=337 This does not fix the current issue so maybe using the double `$(shell ...), !=` would work for now. Or maybe OSX as another, non GNU make implementation available ?
