### ISSUE TITLE
[BUG] `complete-command ... shell-script` doesn't show completions after each keypress

### ISSUE THREAD

**Issue by hylophile** [mawww/kakoune#5245]
### Version of Kakoune

Kakoune 2024.05.18-138-g5e0f9a2ce (i.e., current master: https://github.com/mawww/kakoune/commit/5e0f9a2ce0377d8b5aba71f2916a30257221bac8)

### Reproducer

1. Run
```sh
kak -n -e "define-command repro -params .. ''
complete-command repro shell-script %{
        ls -l
}"
```
2. Run `:repro a`

### Outcome

No completion appears. Or rather, completions only appear after pressing `<TAB>` (thanks bravekarma for the hint).

### Expectations

From the docs:
```asciidoc
    *shell-script*:::
        following string is a shell command which takes parameters as
        positional params and outputs one completion candidate per line.
        The provided shell command will run after each keypress.
```
Hence, I'd expect to see completions after each keypress, and updates after each keypress.

**Comment by krobelus** [comment]
I was also somewhat surprised by this.
My use case was writing completions for the `git` command.
That can't use `shell-script-candidates` because completions for the first argument are different from the second argument.
Unfortunately, `git` completions can be somewhat expensive but I'm sure we can find a solution for that. I thought that requiring users to press `<tab>` was a workaround for potential slowness (not safety right) but I guess that's no longer a huge deal since we can compute completions in the background.
fish shell has the same issue (but cannot compute completions in the background yet)

**Comment by mawww** [comment]
@krobelus `shell-script-candidates` executes the script each time we change arguments and you get the argument index in `$kak_token_to_complete` so I suspect you can actually solve your issue with `shell-script-candidates`.

**Comment by Lugarun** [comment]
Thank you @mawww!
