### ISSUE TITLE
Relative filename completion

### ISSUE THREAD

**Issue by rennis250** [mawww/kakoune#609]
It seems that file name completion is only activated after typing a leading '/'. This means that I cannot references files relative to the current directory, which slows one down a fair amount.

Best,
Rob

**Comment by mawww** [comment]
Hello,

Do you mean filename completion in insert mode ? if so, the current problem is that we do not merge completions from different sources in insert mode, we try the completers from the `completers` option list in order, and the first one that returns a non empty list of candidates wins.

with that behaviour, having the filename completer propose candidate when no / is found would inhibit the word based completers too often.

Merging completions from different sources could be a solution, but that would not be nice with code based completion, were we want (for example) only the relevent method names displayed, instead of them merged with word completions.

Tricky problem to fix, the current behaviour of requiring a / (use ./ for local files :) seems the best compromise.

**Comment by rennis250** [comment]
Oh, I had tried ./ and ../ once before and it appeared to not work. Apparently it does. Okay, that is sufficient for me, so I'll close this.
