### ISSUE TITLE
Add a way to define text objects on the fly

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#621]

**Comment by lenormf** [comment]
I actually have discussed this in the past, and what came out of the discussion is that the editor's primitive already allow users to easily select "objects". The shortcuts that exist to select `<` `>`, `{` `}` etc objects are here because they are pretty common, more exotic objects can be handled just as easily with a macro.

**Comment by mawww** [comment]
@alexherbo2 can you explain more precisely what you wanted here ? its all very vague.

**Comment by alexherbo2** [comment]
I was thinking about a way to hook into undefined text objects to define them on the fly.

```
hook global UndefinedTextObject .* %{ exec %{ : %val{hook_param} , %val{hook_param} <ret> } }
```

**Comment by alexherbo2** [comment]
Actually I would prefer to have this built-in Kakoune, not with a user hook, nor configuration needed.

**Comment by mawww** [comment]
Thats actually supported now, you can use any punctuation char as a text object name (meaning the object delimited by this char).
