### ISSUE TITLE
Interfacing with node.js

### ISSUE THREAD

**Issue by FranzSkuffka** [mawww/kakoune#676]
I am currently trying to figure out how to send and receive data from a kakoune socket. I can connect to a socket but I do not receive any data. I was looking into the docs https://github.com/mawww/kakoune/blob/master/doc/interfacing.asciidoc but really can not wrap my head around it as I am new to unix socket programming.

With this script I can connect but I won't receive any data. How can I send the entire buffer over?
```
net = require 'net'
client = net.createConnection "/tmp/kakoune/janwirth/17700"

client.on 'connect', ->
  console.log 'hi'

client.on 'data', (data) ->
  console.log 'DAT INCOMING DATA'
  console.log data
```

**Comment by mawww** [comment]
Hello,

Kakoune uses an ad-hoc protocol to comunicate on the socket, so the preferred way (and the one that is expected to keep working) is to pipe into a `kak -p <session>` process, that will manage the socket connection itself.

Due to historical reason, it happens that the protocol was designed to be simple to use without `kak -p`, you can connect to it, write some commands, and close the connection. At that point the commands should get executed. Note that commands cannot contain a null byte, as that is treated as a marker to convert the connection into a client one (UI mode). Note as well that this is considered "undocumented" and the connection protocol details may change.

Another thing is that Kakoune protocol is totally asynchronous, commands dont generate any results on the socket, UI commands dont get any direct result, only the resulting redraws.

Can I ask you what exactly are you trying to put in place for node.js interfacing ?

**Comment by FranzSkuffka** [comment]
So the end-goal would be an integration for the Atom text editor, but I believe I won't get that far. I am inspired by this: https://www.youtube.com/watch?v=yluIxQRjUCk

I just managed to send some commands to a session both from the shell and within my script (kill, edit <filename>). What I am wondering now is how I receive all the buffer data including cursor placement etc. as well as how I send individual keystrokes to the server.

**Comment by mawww** [comment]
Hi, for that use case, you probably can go the user interface way using the recent json-ui system.

Take a look at doc/json_ui.asciidoc, that seems closer to what you need if you want to use atom as an user interface for Kakoune.

**Comment by FranzSkuffka** [comment]
Thank you for the hint! Will let you know how things are going!

Have a great weekend.
