### ISSUE TITLE
[JSON-RPC] Add new methods

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#719]
Hi,

It'd be convenient to have new methods available for requests, such as:

* `getoption`, `setoption`: get or set configuration options
* ~~`movecursor`: teleport the cursor to the given coordinates~~ I can use `select` for that

Thanks.

**Comment by mawww** [comment]
That would be a refactor of the whole UI system, currently there is not "requests" in UI, the UI sends keystrokes (with a few special keystrokes for mouse/resize handling), and receives draw commands, there is no direct link between a command sent from the UI, and any commands it receives from the server.

If there is a strong use case for it, we could extend that, but I dont think its needed yet, setting an option is possible through the `:set` command, and getting it can be done (although not that easily) with a `%sh{ echo $kak_opt_myoption > wherever }`.

Closing that issue as I believe that any solution wont be json ui specific anyway.

**Comment by lenormf** [comment]
Getting an option's value by parsing `draw` objects seems weird. The usecase I had in mind was to get `buflist` at startup, the UI will have to do something like `:echo %val{buflist}`, then parse the several objects in response (menu/info hide, plus the actual object containing the draw of the value), all that takes way to much time/parsing.

A workaround is to use a named pipe, but using the filesystem to get a small string feels dirty too.

**Comment by mawww** [comment]
Yeah, I agree a mechanism to let UIs easily access this kind of informations would be nice.

A proposal could be the following:
* A way for UI to send a command to be executed (instead of a keystroke) (Some kind of 'KeyCommand containing a string')
* An additional call to the UI to send it a text, available through something like ':echo -ui "data sent to the UI"

For the buflist usecase, the UI could send a KeyCommand `echo -ui "buflist: %val{buflist}"`, and will get an answer through a new "uiecho" command. It can then parse it hopefully more easily.

All that said, I'd probably wait until we have an UI that start really needing that feature before implementing it.
