### ISSUE TITLE
Allow getting the value of a face

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#736]
Hi,

I'd like to be able to get the facespec of an arbitrary face, from a kakscript and/or a shell script (through the environment). I would make use of that feature to hide the cursors/selections when the window loses focus, and show them back when the window gets focused on again (I need to cache the faces when I change them to hide the cursor).

Thanks.

**Comment by mawww** [comment]
Hi, that would not be enough for your use case, as faces are global, so we would need to be eable to change faces per clients, which would be a big change as, up to now, we dont have any per client configuration.

Accessing faces themselves should be easy enough, we can add a face_.* value, that would be available through $kak_face_<name> or %val{face_<name>}. We could eventually add a %face{name} alternative, to follow the %opt{name} construct, although I am not sure its worth it (actually, maybe removing %opt{...} in favor of %val{opt_...} could be nice).

**Comment by lenormf** [comment]
That's too bad, I wanted to have something other than a widget in my modeline to know whether the current window is in focus (make the cursor disappear was a good standard option). By the way the focus hooks are not being called when within a `tmux` session, I'll have to find a workaround to make that work as I mostly use the editor within `tmux`.

On a side note, I think allowing per-client faces would be interesting, to e.g. allow highlighting/hiding of certain parts of the current buffer.

As for the `%val{opt_}`, I think it would be too confusing as it blurs out the distinction between default options and {user,script}-defined ones.

**Comment by mawww** [comment]
%val{opt_.*} already exists, %val{...} gives access to the same things $kak_... would in a shell. and regarding options, we never make any distinction between built-in ones and user ones (built-in ones are just guaranteed to exist).

Per client faces could be interesting, but would be a big change as well, so they would require a strong motivating use case.

**Comment by lenormf** [comment]
Since we don't really have an easy way of doing code folding, I thought we could use range highlighters to darken the entire buffer except some bits we're interested in. It could be convenient if you don't use marks and keep scrolling up and down in the file (jumping to tag definitions for example), so that you'd know where to come back to.

Other than that, collaboratively editing a file by two people who use different terminal configurations (colors, specifically), and can't use the same theme.

**Comment by notramo** [comment]
@mawww any progress?

**Comment by mawww** [comment]
Well, faces are now scoped, so we can change faces in a specific window/buffer, for example we can change the cursor face when we enter/leave insert mode.

I am not sure we need to make faces value accessible from Kakoune, however I would like to change faces to be more flexible: Currently a face is either an alias for another face, or a fg/bg/attributes value, I'd like to change that so that a face is a base face *and* a fg/bg/attribute value thats applied on top of it.

That means we could define a face as "whatever that other face is, but with this additional attribute", or "whatever that other face is, but with background replaced with this color". I believe that would take care of most cases where we could like to get the value of a face.

**Comment by notramo** [comment]
@mawww Getting the value of a face could be usable in plugins:
https://gitlab.com/fsub/kakoune-mark/merge_requests/1

**Comment by ervasive** [comment]
+1 Another use case would be to check if a `face` has a value and if not set something default.

**Comment by FlyingWombat** [comment]
One thing I'm trying to do is, set the background of a new face, based on the background of an existing face. This is to define a highlighter that matches the set colorscheme, rather than hardcoding color values.
So, it would be helpful to access a face's value.  
something like: `set-face global current_line_mark default,BufferPadding.bg`
