### ISSUE TITLE
w, b and e selection inconsistencies

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#752]
the cursor will be represented by `[]`

`one tw[o] three`:
- _problem_: w results in only selecting the following white space
- _expected_: select o + space (same behaviour as for `one t[w]o three`)

`one[ ] two three`:
- _problem_: w results in only selecting white spaces
- _expected_: select two + following spaces (same behaviour as for `one [ ]two three`)

`one two[ ] three`:
- _problem_: b results in only selecting two
- _expected_: select space + two (same behaviour as for `one two [ ]three`)

`one [ ]two three`:
- _problem_: e results in only selecting two
- _expected_: select space + two (same behaviour as for `one[ ] two three`)

**Comment by mawww** [comment]
Hello, all that is actually the expected behaviour.

For the first case, we have the cursor on the last char of the word, so `w` selects the next word (use `W` if you really want to extend to it).

For the second case, we consider the consecutive spaces as a word, in `w`, `b`, `e` sense.

The other cases are are behaving like that for the same reasons.

**Comment by kurkale6ka** [comment]
Thanks for explaining.
It's still confusing that white spaces would be considered as words.
It might be worth explaining in the README what a word is in the context of w, b, e.
