### ISSUE TITLE
Enable persisting history

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#785]
Implementing persisting history would avoid to constantly retype things like
`:set buffer filetype sh`
for non recognised files every time one restarts `kak`.
Even with completion it's quite tedious.
`:set<up arrow>` would be very handy.

**Comment by cbuschardt** [comment]
This is something that the fish shell does a very good job with.  This would be great for prediction that yes, in fact, I wish to run grep-next again :)

**Comment by Delapouite** [comment]
related to:
- https://github.com/mawww/kakoune/issues/1130 - expose $kak_command_history and $kak_search_history
- https://github.com/mawww/kakoune/pull/1397 - expose last entered command in register :
- https://github.com/mawww/kakoune/issues/1204 - display last entry from prompt history

**Comment by dmerejkowsky** [comment]
Hum. How about writing all commands to a text file after they are successful, as a shell does in the history file?

I'm willing to try and implement it, I just need a good starting point.

At first, I thought I would patch `CommandManager::execute_single_command` but *all* commands go through there, and I want only those typed in the bottom line.

**Comment by mawww** [comment]
As a general design guideline, Kakoune core does not write/read state files, I'd rather provide mechanisms that allow that to be implemented as a .kak script. All that we need is a way to read and write the history...

The history is currently a map of prompt => list of strings, ideally we would merge it into an existing mechanism, either a register or an option.

Registers seems like a good candidate, they are lists of strings, are global shared state, and are already used to store the latest entry of many prompt related commands, such as `:` for the last command, `/` for the last search pattern. It could probably make sense to drop the prompt as identifier for the history and just group related history together (like, `$`, `|`, `<a-|>`, `!` and `<a-!>` could share their history into a the `|` register, `/`, `<a-/>`, `<a-k>`, etc... into the `/` register...). We would need as well to add a switch to the `:prompt` command to select the history register to use, but that should be trivial.

The problem I can foresee is that say pasting from those register on multiple selections woud seems strange, as for n selections we would get the n latest history entries pasted, instead of n-times the latest entry as we have now.

Any opinions on that ?

**Comment by occivink** [comment]
>drop the prompt as identifier for the history and just group related history together

Yes, please.

In addition, we could use the main selection to store the last one so that `%val{reg_main_X}` would give the current behavior.

**Comment by dmerejkowsky** [comment]
> Kakoune core does not write/read state files
Oh. Thanks for the clarification.

**Comment by absolutejam** [comment]
Would it make sense to make this a hook, eg. `CommandCompleted` or `PromptCommandCompleted` to distinguish if the user explicitly entered it. Then it becomes extensible and conforms to Kakoune's philosophies.

**Comment by mawww** [comment]
This should now be possible to implement with:

```
hook global KakEnd .* %{ echo -to-file .kak_history -quoting kakoune reg : %reg{:} }
hook global KakBegin .* %{ try %{ source .kak_history } }
```

It is a big security hazard though, and I would be interested in how we could approach this feature in a secure way.

**Comment by lenormf** [comment]
Assuming the issue would come from the ability to execute arbitrary shell commands injected into the history file, one way it could be done is to `source` the file into a shell-free context - shell scopes would not be expanded, but inserted as-is. The context would apply to `exec`/`eval` as well, and be passed to subsequent calls to `source`.

But I'm not sure it would be worth implementing, after all the user is responsible for its own files, if we're not worried about an attacker injecting malicious commands into `kakrc`, then there's no need to worry about this history file that has to be manually configured anyway.

NOTE: assuming the security concerns about history stem from commands injection into modelines, we should be fine in that case as modelines can be present in any arbitrary file passed to the editor, whereas both the file and its name are controlled by the user in that case.

**Comment by mawww** [comment]
Yeah, I think you are right, I was thinking about storing a history file at the root of my projects (to have separate history depending on what I am working on), but I guess its just a bad idea to store that in the $CWD.

**Comment by mawww** [comment]
Which means this issue can be closed now, we have a mechanism for persistent history.

**Comment by Screwtapello** [comment]
Blindly sourcing `.kak_history` would be arbitrary code execution, yes. On the other hand, because of the way Kakoune quoting works, you *should* be able to do something like:

    reg : 'foo' 'bar' '%sh{ rm important-file.txt }'

...without causing any damage. Unfortunately, constructing such a command is a problem. You could do something like:

    eval %{
        echo "reg : "
        cat .kak_history
    }

...but then `eval` would execute arbitrary commands from the file, rather than `source`. Alternatively one might write:

    reg : %sh{cat .kak_history}

...but then the entire history would be a single item in the history, instead of being split into separate elements.

I think the safest solution would be a new kind of expansion that just does splitting and unquoting, rather than execution. For example, let's call this new expansion `%split{)`:

    # all these are effectively identical
    reg : 'foo' 'bar'
    reg : foo bar
    reg : %split{foo bar}
    reg : %split{'foo' 'bar'}
    eval %{reg : foo bar}

Let's say the file `.kak_history` contains the following:

    'foo' 'bar'
    nop %sh{ rm important-file.txt }

...then the following commands would be identical:

    reg : 'foo' 'bar' 'nop' '%sh{' 'rm' 'important-file.txt' '}'
    reg : %split{ %sh{ cat .kak_history } }

... but this command would be *different*:

    eval %{ reg : %sh{ cat .kak_history } } # sets %reg{:} to 'foo' 'bar' then deletes an important file!
    
Of course, as @lenormf points out, if an attacker can overwrite custom files in your home directory, clobbering `.bashrc` is probably a juicier target than `.kak_history`.
