### ISSUE TITLE
Incorrect j/k movements

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#793]
In this case all works as expected:
```
Hello world
H[i]
```
we've got the cursor on `i` or even at the EOL and using `k` brings us right above to either `e` or `l`.
Problem is here:
```
Hello worl[d]
Hi
```
with the cursor at `d` or EOL, `j` brings us on `i` (which is ok although EOL should bring us to the respective EOL) and then we have a fail using `k` which brings us back to `d` vs going on `e`

**Comment by lenormf** [comment]
If the cursor is sent back to where it was before it was moved to the current line, then the `j` and `k` keys are doing what they're supposed to.

**Comment by mawww** [comment]
Thats a feature actually, vertical movement follow the target column position of the cursor, which is the column on which we went with the last horizontal movement (can even be `end of line` if we use `<a-l>`, `x` or `gl`).

In the first case, say you start on the H or Hi, and do `gl`, you'll see that k brings to to `d`, because the current target is `end of line`.

Its hard to see how thats usefull on two lines, but whenever you move around code with empty lines, you'll see thats the desired behaviour (if you do `jj` and the next line was empty, you'll probably be happy the cursor commes back to the column you were in, instead of being forced back in the first column).

**Comment by greduan** [comment]
There is one more alternative behaviour, which is that null space (no character there) is considered a valid position for the cursor. So then you can have

```
// [] is cursor
Hello
World  []
```

And then doing `i` there would create whitespace up to `[]` and insert your text. Vim provides this behaviour I believe, but I don't remember the name of the setting.

**Comment by kurkale6ka** [comment]
Thanks @mawww. I get it

> And then doing i there would create whitespace up to [] and insert your text. Vim provides  this behaviour I believe, but I don't remember the name of the setting.

that's virtual edit (`:h've`) and I had it enabled by default and it is nice but dunno if the added benefit is worth the amount of code needed
