### ISSUE TITLE
Wrong cursor movement around CJK characters

### ISSUE THREAD

**Issue by naptime** [mawww/kakoune#811]
Kakoune does not appear to respect wcwidth when determining the current terminal column.  This makes it very difficult to edit East Asian text, as the cursors jump erratically when moving vertically.

I will now try to show an example, but I'm not sure if GitHub displays monospace CJK correctly, so please keep in mind that each CJK character that I use in the example below is supposed to be exactly twice the width of the Latin characters:

```
123456789012
一二三四五六
```

Putting the cursor where the hash mark is:

```
1234#6789012
一二三四五六
```

and then pressing `j` (down) should move the cursor here:

```
123456789012
一二＃四五六
```

but it moves it here instead:

```
123456789012
一二三四＃六
```

If the cursor was C Unicode codepoints from the start of the line and N terminal character-cell-widths from the left, moving vertically should disregard C and use N to calculate the new location.  However, in all cases except for the horizontal tab character, it seems to disregard N and use C directly.

N is calculated by using wcswidth.  A good implementation can be found here:

https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c

I hope I was clear.

P. S. How is "kakoune" pronounced?

**Comment by mawww** [comment]
Hello,

Thanks for raising that issue, double width codepoints (and zero width ones) is definitely something we should support in Kakoune. I have taken a quick look, and it looks doable, I'll try to get that in soon.

Regarding pronunciation, Kakoune is written using french spelling, the same sound would probably be written something like "kakoon" in english, although the 'oo' is a short vowel, not a long one.

Cheers,

Maxime.

**Comment by naptime** [comment]
I just built the latest version and it works perfectly!  Thank you so, so much!!! ^^

**Comment by mawww** [comment]
No problem, thanks for raising that issue :)

**Comment by BatmanAoD** [comment]
@mawww How are codepoint-widths determined? (I'm guessing it's something from unicode data, but I'm not familiar enough with the standard to know.) I would love it if en-dash used two columns and em-dash used two or even three, but some quick testing shows that they currently are restricted to a single column.

**Comment by Screwtapello** [comment]
Unicode doesn't exactly specify how wide (in terminal columns) a particular string should be. Some characters are defined to be zero-width, some are defined to be "half-width" (1 column), and some are "full-width" (2 columns), but many are "ambiguous" (half or full-width, depending on locale), and some don't fall into any of those categories. Worse, there are Unicode characters that change the width of the preceding character.

Apps like Kakoune generally use the `wcswidth()` function provided by the standard library, which is generally based on information defined by Unicode, but also on guesswork and tradition. Kakoune could potentially include its own, customised version of that function, but in order to display text correctly, Kakoune needs to calculate widths in the same way as the terminal that displays the output does, and the font that the terminal is using. Using the system-provided `wcswidth()` doesn't guarantee that (for example, the terminal and Kakoune might be running on different systems, connected by SSH), but it's more likely to work than something custom would.

**Comment by BatmanAoD** [comment]
Interesting. So if I had a version of `libc` that returned different values for dashes, I could make kakoune respect those values just by linking that instead of the default `libc`?

Also, it looks like there isa  version of wcwidth/wcswidth that is more up to date with Unicode standards than the `libc` implementation: https://pypi.org/project/wcwidth/

Would it be possible to make kakoune use that or another such implementation?

**Comment by Screwtapello** [comment]
Yes, although as I said you'd need to modify Kakoune to use your custom `wcswidth()`, and then modify your terminal to use the same function, and then edit a font to change the visual size of those glyphs.

It wouldn't be easy to use that *particular* implementation of `wcswidth()` in Kakoune, because that's written in Python and Kakoune is written in C++, but other implementations are available.

**Comment by BatmanAoD** [comment]
Hm, you're right that monospace fonts would need to be edited to support proper em-dash width, but for non-monospace fonts, would it be possible for Kakoune to defer to the actual font-width and use the minimum number of columns needed to draw the entire character? (Or, rather, obviously it would be _possible_, but how easy do you think that would be to implement?)

**Comment by Screwtapello** [comment]
Kakoune itself knows nothing of fonts, it just writes Unicode text to stdout. The terminal Kakoune is running inside receives that text, and allocates room for it according to how big it expects the text to be. Then the terminal draws the text in a particular font, which hopefully fills all the room allocated to it without leaving a gap or overflowing.
