### ISSUE TITLE
Apply the `+n` parameter in a smarter way to the positional buffer names

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#836]
Hi,

If I use the following command, `kak` will only open the first buffer at the position passed:
```
$ kak a.c b.c +10
```

It'd be nice for the line specifier to apply to all the buffers that were specified before, that way the previous command could open the buffers at the same locations, and the following command could open the buffers at custom locations:
```
$ kak a.c +5 b.c +10
```

Thanks.

**Comment by mawww** [comment]
That would be a pretty intrusive change, and it would break the use case that led to the introduction of `+<line>`, which is kakoune being invoked like that: `kak +<line> <filename>`.

I dont think its worth it to add the requiered complexity to handle that (we'd need either to store the requested buffer coord in the buffer, waiting for it to actually be shown, or to create a window for each buffer eagerly, so that we can set their selections).
