### ISSUE TITLE
Region highlighters: add -match-captures

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#837]
Here is the need:

``` sh
cat << 'HELP'
Hello
bla bla
...
HELP
```

Currently I use: `heredoc "<<-?\s*[\\']?\w+'?$\K" '(?=^(?:\t*)\w+$)' ''` but it would be far better to have: `heredoc "<<-?\s*[\\']?(\w+)'?$\K" '(?=^(?:\t*)(\w)+$)' ''` and just check that both captures (`(\w+)`) match. This would avoid my regex thinking the region closes at 'Hello' above.

Also, another issue with regions is when using lookahead/lookbehind we still want to highlight them. Examaple: here the region excludes 'HELP' and HELP but I do want to be able to highlight them in a special way which afaik isn't currently possible

**Comment by mawww** [comment]
Finally I revisited that, I was afraid of the additional memory consumption that this adds for every matches (including capture information for every single candidate). I went with a support for only the single match in order to limit that, and if it appears as memory hungry, we can eventually specialize the code.
