### ISSUE TITLE
Smart case matching for '*'

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#84]
I want this feature, but note it is not possible using regular expression.

**Comment by benoit-intrw** [comment]
Sorry to use this old issue to ask but I also like smartcase behavior.

@alexherbo2 ask about `*` command but it's the same for `/` or I miss something ?

**Comment by lenormf** [comment]
I implemented this feature in PR #594, just to try it out.

**Comment by benoit-intrw** [comment]
Thank you for the answer and the PR #594.
Because the PR is closed, I'm answering here.

My particular needs is to know how make easily case insensitive search in kakoune and `A[bB][cC][dD][eE]` is not an answer ;-) 

I did,'t know about `(?i)` (1) 

Which syntax is enabled in kakoune ? looking at the code I see an *ECMAScript* flag ... ?

Looking at [Regular Expression Syntax](http://www.boost.org/doc/libs/1_60_0/libs/regex/doc/html/boost_regex/syntax.html) I don't see `(?i)` explained. 

If you give me the right information I can add information about supported regex syntax in the documentation.


(1) In facts i've seen it in the context of [re2](https://github.com/google/re2/wiki/Syntax)

**Comment by lenormf** [comment]
I closed the PR because @mawww gave an example of a case where smart case is working against the user, namely devs who use camel case. I provided an implementation that you can append to your `kakrc` file.

The regex syntax used is the perl one, [documented here](http://www.boost.org/doc/libs/1_60_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html).

**Comment by benoit-intrw** [comment]
Oh, they call this modifiers.

Is it ok to do this for `/` ?
```
map global normal '/' %{
        :exec /(?i)<ret>
}
```

Thanks for your help.

**Comment by lenormf** [comment]
Your command will only search for `(?i)`, and will not return any match because you put a `<ret>`. Here is an excerpt of my `kakrc` file that defines some case insensitive search methods:

```
map global user '/' %{/(?i)}
map global user '<a-/>' %{<a-/>(?i)}
map global user '?' %{?(?i)}
map global user '<a-?>' %{<a-?>(?i)}
```

**Comment by benoit-intrw** [comment]
In facts its works also, the `<ret>` validate the exec part. 

So `%{}` string execute normal command ? Or it is not necessary ? Your mapping seems to work as good without being surround by `%{}`

What would be the idiomatic way ?

P.S: Again sorry to use this issue as a forum

**Comment by lenormf** [comment]
Those are just strings [documented here](https://github.com/mawww/kakoune#43-string-syntax), I always use them when declaring a mapping to highlight the executed keys versus the bound ones, although they are not necessary in the snippet I pasted.

I don't think there an idiomatic way of declaring bindings, just use whatever works for you as long as it's not too dirty.

**Comment by mawww** [comment]
I dont think that will get implemented, it does not seems like a desirable default behaviour, is a pretty specific feature that seems easy to implement as a script. Closing.

**Comment by lenormf** [comment]
FWIW, here is my implementation:
```
## smart search that ignores case when the pattern is entirely in lowercase
map global user '*' %{
    :try %{
        exec -save-regs '' <lt>a-k>[A-Z]<lt>ret>*
    } catch %{
        exec -save-regs '' */(?i)<lt>c-r>/<lt>ret>
    }<ret>
}
```
