### ISSUE TITLE
Add hook to notify that a register has been modified

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#859]
Hi,

As discussed in #838, it'd be useful to have a hook to know when registers are modified, with filtering based on which register is modified.

**Comment by Screwtapello** [comment]
Huh, I should have know there would already be an issue for this. Here's the text of the issue I was about to create:

## Description

In the style of `hooks.asciidoc`:

**RegisterWrite**: Triggered after text has been written to a register, filtering text is the register name. While this hook is being executed, no further RegisterRead or RegisterWrite hooks for this register will be triggered.

**RegisterRead**: Triggered before text is read from a register, filtering text is the register name. While this hook is being executed, no further RegisterRead or RegisterWrite hooks for this register will be triggered.

## Rationale

There's lots of potential uses for this functionality:

- This would make it easy to integrate with an external clipboard tool, like `xclip` or `tmux set-buffer`.
- It would be possible to implement at least the `"%` and `"_` registers in kakoune's standard configuration files, instead of hard-coding them in C++.
- It would be a convenient way to access generated data. For example:

        hook global RegisterRead d reg d %sh{date --rfc-3339 seconds}

    ...so that pasting from register `d` always pastes the current date and time.
- This would also allow plugins to implement more sophisticated copy/paste semantics, like a LIFO or FIFO buffer instead of just straight replacement
- So far as I can tell, kakoune treats the `"a` and `"A` registers as identical, as opposed to the way Vim uses uppercase to mean "append to the existing value". This feature would allow people who miss that functionality to add it themselves, instead of adding it to the C++ core.
- It would make it very convenient to edit code and repeatedly send it to an external REPL to be executed. For certain development tasks that require rapid iteration of complex code (such as tweaking a SQL query), the fewer keystrokes between making a change and seeing if it works, the better.

## Alternatives

The [Registers & Clipboard](https://github.com/mawww/kakoune/wiki/Registers-&-Clipboard) wiki page already has some suggestions for integrating kakoune with the system clipboard, but honestly I would much rather hit `y` than `<a-|>xsel --input --clipboard <ret>`. There are also example hooks to make copy and paste work with `y`, `d` and `c`, but of course they don't help with `<c-r>` on the command-line, the `%reg{}` expansion or the `:reg` command, making them very leaky abstractions.

The vis editor does not support register hooks, but it has special `"*` and `"+` registers that call vis to invoke the `vis-clipboard` command. People who want to customize copy/paste behaviour are expected to write their own implementation of `vis-clipboard` and put it on `$PATH` ahead of the standard version.

Vim also does not support register hooks, and completely hard-codes the behaviour of its `"*` and `"+` registers.

**Comment by doppioandante** [comment]
@lenormf brought this up again today on IRC, so I wrote a small patch (untested).
There is one problem though: registers are basically arrays, not just values. AFAICT, this means that we should pass its content to the hook by joining all the values with a delimiter, but what delimiter should be used?

```patch
diff --git a/src/commands.cc b/src/commands.cc
index 466a84dd..b8a2ce06 100644
--- a/src/commands.cc
+++ b/src/commands.cc
@@ -772,7 +772,7 @@ static constexpr auto hooks = {
     "BufWritePre", "BufOpenFifo", "BufCloseFifo", "BufReadFifo", "BufSetOption",
     "InsertBegin", "InsertChar", "InsertDelete", "InsertEnd", "InsertIdle", "InsertKey",
     "InsertMove", "InsertCompletionHide", "InsertCompletionShow",
-    "KakBegin", "KakEnd", "FocusIn", "FocusOut", "RuntimeError", "PromptIdle",
+    "KakBegin", "KakEnd", "FocusIn", "FocusOut", "RegisterChanged", "RuntimeError", "PromptIdle",
     "NormalBegin", "NormalEnd", "NormalIdle", "NormalKey", "RawKey",
     "WinClose", "WinCreate", "WinDisplay", "WinResize", "WinSetOption",
 };
diff --git a/src/register_manager.cc b/src/register_manager.cc
index 3abbd61b..134ecd9c 100644
--- a/src/register_manager.cc
+++ b/src/register_manager.cc
@@ -7,6 +7,28 @@
 namespace Kakoune
 {
 
+class WatchedRegister: public Register
+{
+public:
+    WatchedRegister(Codepoint name, std::unique_ptr<Register> reg):
+        m_name(name),
+        m_register(std::move(reg))
+        {}
+    void set(Context& ctx, ConstArrayView<String> values) override
+    {
+        m_register->set(ctx, values);
+        ctx.hooks().run_hook("RegisterChanged", format("{}={}", m_name, values[0]), ctx);
+    }
+
+    ConstArrayView<String> get(const Context& ctx) override
+    {
+        return m_register->get(ctx);
+    }
+private:
+    const String m_name;
+    std::unique_ptr<Register> m_register;
+};
+
 Register& RegisterManager::operator[](StringView reg) const
 {
     if (reg.length() == 1)
@@ -44,7 +66,7 @@ void RegisterManager::add_register(Codepoint c, std::unique_ptr<Register> reg)
 {
     auto& reg_ptr = m_registers[c];
     kak_assert(not reg_ptr);
-    reg_ptr = std::move(reg);
+    reg_ptr = std::make_unique<WatchedRegister>(c, std::move(reg));
 }
 
 }
diff --git a/src/register_manager.hh b/src/register_manager.hh
index a2a1e253..d4bf2a5c 100644
--- a/src/register_manager.hh
+++ b/src/register_manager.hh
@@ -7,11 +7,12 @@
 #include "hash_map.hh"
 #include "string.hh"
 #include "vector.hh"
+#include "context.hh"
 
 namespace Kakoune
 {
 
-class Context;
+//class Context;
 
 class Register
 {
@@ -27,7 +28,7 @@ public:
 class StaticRegister : public Register
 {
 public:
-    void set(Context&, ConstArrayView<String> values) override
+    void set(Context& ctx, ConstArrayView<String> values) override
     {
         m_content = Vector<String, MemoryDomain::Registers>(values.begin(), values.end());
     }
```

**Comment by alexherbo2** [comment]
I would like this functionality as well to generalize the [Yank Ring] to all kind of register, for example refreshing an old search with `yank-ring /`.

[Yank Ring]: https://github.com/alexherbo2/yank-ring.kak

**Comment by absolutejam** [comment]
Would make integrating with OS clipboard a lot easier as it can be automatically injected to all yank operations.

**Comment by eraserhd** [comment]
This also seems useful to me, but my only actual use case is also clipboard.  I currently copy `%reg{"'}` to the system on NormalIdle when it changes, and copy from system to `%reg{"}` on FocusIn if it changed.

**Comment by eraserhd** [comment]
Nice!
