### ISSUE TITLE
Incoherence with the `range-faces` descriptor end column index

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#864]
Hi,

As pointed out by @occivink, it doesn't make sense that the end column index isn't inclusive in the descriptor for a `range-faces` options:
```
*range-faces*::
	a `:` separated list of a pairs of a buffer range
	(`<begin line>.<begin column>,<end line>.<end column>`) and  a face
	(separated by `|`), except for the first element which is just the
	timestamp of the buffer.
```

Since the end line parameter is inclusive, it'd be better to make the end column one inclusive as well. Validating test that should highlight the first character of the first line:
```
0:1.1,1.1|Error
```

Thanks.

**Comment by mawww** [comment]
Well, its not that the line is inclusive and the column is not, `1.1,2.1` will highlight the whole first line, regardless of its length. Its more that in general we specify ranges as `[first, one past last)`, we could decide to be specifying ranges as just `[first,last]`, which would have the advantage of matching the selections (which by nature have to be inclusive, as they are the position of the anchor and the cursor).

I am open to that change, any other opinions ?

**Comment by alexherbo2** [comment]
I don’t have a strong opinion on that but we could express both with `first,,last` syntax?

In Ruby (and maybe other programming language) there is `(begin..end)` range syntax to be inclusive and `(begin...last)` to be exclusive.

**Comment by mawww** [comment]
Nope, I dont want to have two syntaxes.

**Comment by lenormf** [comment]
The fact that selection descriptions and face ranges have different syntaxes makes it hard to use one with the other. I've been making a unit test to check that the `spell` command highlights mistyped words properly, and I basically grab the content of a `face-ranges` variable and convert it into a selection, but the off-by-one thing gives me a hard time in some cases.

But like I said in my PR, I understand why this was implemented that way.

**Comment by occivink** [comment]
Does anybody use `range-faces` for anything besides the spell command?

**Comment by lenormf** [comment]
I have a PoC script that uses it to highlight overstrike sequences in man pages.

**Comment by lenormf** [comment]
After further consideration I think the format should be changed, and use only inclusive indexes, it will make selecting highlighted things easier.

**Comment by mawww** [comment]
I did a quick change locally to check that, the problem is that it makes non-selection based highlighting a bit strange, as in `spell.kak` for example, we now need to use `length - 1` instead of `length` to compute the range end.

I am still wondering whats best here, do we really expect to often generate ranges from selections ?

That could be a nice feature, but it makes the other use case (generating ranges from external tools/data) more cumbersome than necessary, so we really have to choose which use case we want to favor.

**Comment by lenormf** [comment]
From a testing point of view, switching -almost- seamlessly from face range to selection description is pretty convenient. And do all the tools that we have builtin (`spell`, `clang` off the top of my head) use the `offset:length` convention? Would it add a lot of overhead to handle the `offset:offset` convention (I'm guessing yes on that one)? Tough call.

**Comment by mawww** [comment]
Hum, I realized we have another problem, which is that range-faces are not supposed to be directed, we expect `<begin>,<end>`, that will fail with backwards selections.

Here is what I think would be the best solution:
Support for 2 syntaxes
* `<line>.<col>,<line>.<col>`, inclusive, and we reorder them if needed
* `<line>.<col>+<len>`, which means `<len>` bytes from `<line>.<col>` which will be the common use case when we dont want inclusive coords.

That would make both generating ranges from external commands (where we usually have a pos+len) and from selections easy, and syntaxes are explicit and sufficiently different so that we dont confuse them (which was my main objection against `<begin>,<end>` vs `<first>,,<last>`).

**Comment by lenormf** [comment]
How would getting a selection from a face range work? Would the data always be returned in a single format, or in the same format that the face range variable was initialized with?

**Comment by alexherbo2** [comment]
@mawww I like better your solution which is more generic and adapted to the use case.

**Comment by occivink** [comment]
I like the idea of the two syntaxes. Why bytes for `<len>` instead of codepoints ?

Some other generic comments that I have regarding the `range-faces` 
* One face for the entire `range-faces` vs one face for each range. I think the typical usage for a `range-faces` is to color multiple ranges in the same manner, so only defining one face might be preferable. Different faces could still be handled by declaring multiple options.
* I would like to see the timestamp restriction on the `range-faces` liefted if possible, even if it means that some ranges might become invalid (much like marks currently). Clearing the option would still be possible given the appropriate hooks so there wouldn't be any loss of functionality,

**Comment by lenormf** [comment]
>One face for the entire range-faces vs one face for each range. I think the typical usage for a range-faces is to color multiple ranges in the same manner, so only defining one face might be preferable. Different faces could still be handled by declaring multiple options.

In practice that's the way it's being used, but it would be a step back in functionality to only allow one face per face range.

>I would like to see the timestamp restriction on the range-faces liefted if possible, even if it means that some ranges might become invalid (much like marks currently). Clearing the option would still be possible given the appropriate hooks so there wouldn't be any loss of functionality,

This feature is pretty important, and I don't understand what your proposed alternative is, to compensate for its removal.

**Comment by occivink** [comment]
>This feature is pretty important, and I don't understand what your proposed alternative is, to compensate for its removal.

I think it's just easier to clear the content of an option when then buffer is changed, than it is to redefine the option with a slightly different value (i.e. increased timestamp).

Regarding my first point I don't have a strong opinion either way.

**Comment by lenormf** [comment]
The point of the timestamp is to not have to update a variable manually whenever the buffer is changed though.

**Comment by mawww** [comment]
> Why bytes for <len> instead of codepoints ?
Selections are exprimed in bytes, not codepoints, and we actually wont be supporting multiline ranges with the `+len` syntax because we have no reference buffer when parsing the range face (it could be in global scope for example, even if that would not make much sense), so we cannot use the buffer to convert `<line>.<col>+<len>` to actual coordinates.

Regarding single face per range-face or multiple faces (one per range), that could be discussed, multiple seems more flexible, but I dont have a real use case for them right now.

Regarding timestamp, what we could do is the same we do for line-flags: try to update ranges according to buffer modifications. We have most of the needed code for that in place (as we do update selections based on timestamps).

**Comment by occivink** [comment]
>Regarding timestamp, what we could do is the same we do for line-flags: try to update ranges according to buffer modifications.

That sounds useful for `spell` but also the 'mark highlighter' that I would like to achieve.
