### ISSUE TITLE
Question: possibility of implementing GDB plugin.

### ISSUE THREAD

**Issue by aytim** [mawww/kakoune#880]
Sorry, didn't find another place to ask question. Want to try this editor for daily work. 
Ideally, I want something like SublimeGDB or vim-lldb.
Do kakoune's design or philosophy have something against plugins like those mentioned?

**Comment by lenormf** [comment]
What features would you expect from such a plugin? This topic was already discussed a bit in the past, and we came to the conclusion that it would take non negligible effort to implement such a compatibility script, and it wouldn't really make things easier to debug an application compared to having the editor set to Kakoune.

**Comment by aytim** [comment]
Thanks for reply! I didn't find any discussions about this topic (I tried). Still interested to read it.

Answering your question about features. Currently I debugging remotely by gdb via ssh terminal window. My main problem (as many others, I suppose) is lack of code navigation functionality in gdb.
Basically, I want some convenience :). For example:
- navigate to function, I want set breakpoint with few keystrokes. Not remembering line and filename and writing to gdb `b foo.cpp:123`
- same as before, when i see variable, for example, `veryLongName`, I don't wan't to remember name and write to gdb `p veryLongName`.
- when inspecting stack, I want to see caller function in editor, so I can use 'Go to definition' and such convenient tools.

At least implementing these cases would make me happier.

I don't mind to implement plugin by myself, for fun. But my main concern is that kakoune isn't designed to work that way.

So the main question is: is kakoune extension capabilities allow implementing debugger plugin?
Or maybe there exists other way to integrate debugging?

**Comment by mawww** [comment]
Hello,

I have been wanting this for some time, and I think it can be achieved. Here is a potential design:

With gdb 7.12, that was just released, there is the `new-ui` command that allows to make gdb add a new ui (of the wanted type, gdb/mi would be what we want here). We could have a program running, connected to that gdb/mi ui, transforming gdb events into kakoune commands (when the gdb frame changes for example), and listiening for commands comming from kakoune (add breakpoint, display value of that variable...).

That program can just be a shell script implemented in an eventual `gdb.kak`, it does not have to be very complicated: parsing gdb/mi outputs and generating kakoune commands, and parsing commands comming from kakoune (on a fifo for example) and generating the gdb/mi command associated, and potentially the kakoune command to run afterwards (getting a variable value for example would run a gdb/mi command, then parse the result and run a kakoune command to display that result in say an info box).

I hope it makes some kind of sense. Note that what I am thinking about is integration of Kakoune and gdb, I imagine gdb running in its own terminal, along with its own UI, and then kakoune connected to it so that we can control gdb from kakoune for simple things (add breakpoint, get variable value, continue, step until...).

**Comment by aytim** [comment]
Thank you! What you say is probably is what I want (for now :).
Going to try kakoune.

**Comment by lenormf** [comment]
[Interesting](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html#GDB_002fMI).

Note however that it might take a while to implement, as not all features might not be available:
```
Note that gdb/mi is still under construction, so some of the features described below are incomplete and subject to change (see gdb/mi Development and Front Ends).
```

**Comment by mawww** [comment]
gdb/mi has been around for long already (I'd guess more than 10 years), its definitely good enough for what we want. Whats new is the ability to add UI's on the fly with `new-ui` the means we can have a normal gdb, with working readline, and attach another control program later on.
