### ISSUE TITLE
[Questions] Terminal and bindings limitations

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#909]
While trying to remap some keys I experienced some limitations as to what can and cannot be bound.
I don't know much about the inner workings of terminal emulation, but some cursory experimentation led me to the following:
* `alt` modifier bindings are pretty much okay with any key
* `shift` doesn't really exist as a modifier only the alternate key representation is sent, so something like `<s-space>` or `<s-ret>` is not possible
* `ctrl` modifier bindings are only okay with `a-z`

So now the questions:
Do these limitations come from the terminal emulation and cannot be overcome?
If so, do they extend to non-terminal UIs?

**Comment by mawww** [comment]
Hello,

We dont currently treat `shift` as a modifier, because doing that means we would have to handle equivalence of `A` and `<s-a>` or `<` and `<s-,>` in Kakoune code, meaning we would either have to assume a qwerty keyboard, or have a way to know the actual layout of the user keyboard to map correctly `<s-whatever>`.

Regarding `ctrl`, we are hitting limitations of the terminal, Kakoune itself can support any keys with the `ctrl` modifier, but terminals do not, we receive the exact same thing for `<c-m>` or `<ret>`, regardless of the actual key that was pressed, same thing for `<c-i>` and `<tab>`. For that, non terminal UIs will have no problem to send these keystrokes to Kakoune, and Kakoune should handle them just fine.

Cheers,

Maxime.
