### ISSUE TITLE
Improve insert completion

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#931]
Hi,

Not sure how to phrase this because I don't know the implementation details. I will just give a list of things that are possible in Vim and that we could adopt/implement:

- `hello world [cursor]`: `^x^p^p` at this point inserts hello where the cursor is (`^x` forces the search to be done in the local file only). The problem in kak is that we first need to type h and then visually find hello to insert it. Because words are sorted there is no guaranty hello will be the first of the list. (`:h i^x^p` in Vim to get help about this. You can type it literally: caret, then x...)

- `he^x^n` -> `hello^x^n` -> `hello world^x^n` -> `hello world [cursor]`. By re-using `^x^n` you ask for context completion so your proposed words are the ones immediately following hello and so on. This way it is very easy to insert a part from a sentence elsewhere.

Example of the second point: https://asciinema.org/a/0owv9u3q2y8hfo4wvlpmj5tp0

**Comment by mawww** [comment]
Hello,

I understand the interest of these changes, but I dont think they would work well with Kakoune:

We already have the fuzzy completion system that ranks matches, I think it works very well for most use cases, so I dont plan on removing it from insert completion. That means we would need to have distance based completion interact with the current ranking system, the only way I see that working would be by sorting by distance matches that are equivalent ranking wise, which makes distance sorting kick in pretty rarely.

That would be a bit of complexity but could still make sense, the main problem is that we dont have any distance information available, the WordDB implementation manages to be fast because it only knows the words that are in the buffers, and the number of occurences (so, a ref count), whenever it needs updating it just goes through touched lines since last update and udpates the ref count of words added/removed in these lines.

That means word completion is generally very fast because it only depends on modifications made to the buffer, and store just few informations. Supporting distance informations means we have either to store every positions of each words, or drop the WordDB and parse buffers directly for completion, both of which do not seem worth it.
