### ISSUE TITLE
Colors under Tmux session

### ISSUE THREAD

**Issue by kascote** [mawww/kakoune#984]
Hi, I'm having issues with colors under a tmux session.
this are the colors with default kak session from the console (no tmux).. colors are ok.
![kak_term](https://cloud.githubusercontent.com/assets/9757/21193071/a8d365d8-c209-11e6-9782-6927c8867803.png)

this are whe open kak under tmux
![kak_tmux1](https://cloud.githubusercontent.com/assets/9757/21193084/b862cdae-c209-11e6-98f6-c3e586f6993c.png)

now if open another pane, the colors change again
![kak_tmux2](https://cloud.githubusercontent.com/assets/9757/21193103/d198759e-c209-11e6-9e94-b11d343c8510.png)

I'm ussing Terminix (https://github.com/gnunn1/terminix) and tried with gnome-terminal too.. but on both cases the same result.

I have this on my tmux config

    set -ga terminal-overrides ",xterm-256color:Tc"

I disabled it, and used `default-terminal` but the same case. Loaded Tmux without any configuration, same case. I tried with different colors schemes too.

I'm using:
Ubuntu 16.10
kak compiled from sources yesterday using the make_deb script
tmux 2.3
$TERM=xterm-256color (out and inside tmux)

**Comment by mawww** [comment]
Hello,

`TERM=xterm-256color` is wrong in tmux, it advertises that tmux support changing the palette, which it does not. So Kakoune will try to change the color palette, and will have a wrong idea of how color looks in the terminal.

Having `TERM=screen-256color` in tmux should fix it. Colors wont be exactly the same in certain color schemes, because Kakoune has to project requested colors onto the fixed color palette, but this works well enough for most colorschemes.

Cheers,

Maxime.

**Comment by kascote** [comment]
that made the trick.. thanks!

but if tmux 2.3 supports now 24bits and vim and neovim support it too, could be cool that kakoune supports it too! :) ... yes I know, must be last on the priority :). btw i really like kakoune, has some great ideas!

**Comment by FreeFull** [comment]
By the way, `TERM=tmux-256color` is now available too, although tmux still works with the screen one as well.

**Comment by lenormf** [comment]
As mentioned by @FreeFull, the conventional way of fixing this issue is to add the following to one's `tmux` configuration:

```
set -g default-terminal "tmux-256color"
```
