### ISSUE TITLE
Documentation rendering problem

### ISSUE THREAD

**Issue by nyarly** [mawww/kakoune#995]
:help output looks like:

```
DU+8DEU+8ESU+8SC
```

I can puzzle out what's intended, but it's difficult and offputting.

**Comment by kballard** [comment]
Wow, you're right, that's pretty awful. For every letter in the headings, the buffer contains the letter, U+8 (backspace), then the letter again. This must be some artifact of how it's rendering manpages.

You can replicate this with `|man man` (or any manpage, really).

**Comment by kballard** [comment]
From the `man` manpage, it looks like the recommended way to get plain text output without backspaces is to pipe the output through `col -b`.

**Comment by lenormf** [comment]
These are markup signs for the overstrike syntax, it seems that your implementation of `man` will emit then even when the output isn't a terminal. What implementation of `man` are you using (what package/version)?

In the meantime, you can fix your buffer with the following: `%s.\x8<ret>d`

**Comment by kballard** [comment]
I'm using the built-in `man` on macOS 10.12.2.

**Comment by nyarly** [comment]
Likewise:

```
man, version 1.6c

usage: man [-adfhktwW] [section] [-M path] [-P pager] [-S list]
        [-m system] [-p string] name ...

  a : find all matching entries
  c : do not use cat file
  d : print gobs of debugging information
  D : as for -d, but also display the pages
  f : same as whatis(1)
  h : print this help message
  k : same as apropos(1)
  K : search for a string in all pages
  t : use troff to format pages for printing
  w : print location of man page(s) that would be displayed
      (if no name given: print directories that would be searched)
  W : as for -w, but display filenames only

  C file   : use `file' as configuration file
  M path   : set search path for manual pages to `path'
  P pager  : use program `pager' to display pages
  S list   : colon separated section list
  m system : search for alternate system's man pages
  p string : string tells which preprocessors to run
               e - [n]eqn(1)   p - pic(1)    t - tbl(1)
               g - grap(1)     r - refer(1)  v - vgrind(1)
```

**Comment by mawww** [comment]
@lenormf I think we used to go through `col -b` at least in man.kak, can you remind me why that was changed/not used in doc.kak ?

**Comment by lenormf** [comment]
All the implementation I tested (and that users at that time were using) didn't keep the overstrike formatting when the output wasn't the terminal. Not using `col` simplified the logic substantially, so I removed it.

Also `col` is only expected to be on systems that have `nroff` on them, so we cannot rely on that as it would create errors on systems that don't. I think we have to `sed s/.\x8//` and that will be it.

**Comment by nyarly** [comment]
Is there a way to set up kak so that it'll e.g. "man | col -b" or something? I notice the 'docsclient' setting, but that doesn't seem to have an effect.

**Comment by leira** [comment]
There is already sed s/.\x8// in rc/core/doc.kak:12:
```
            sed -i 's/.\x8//g' "${manout}"
```

But sed s/.\x8// doesn't work on macOS, BSD sed doesn't support \x hex value.

I can work around this issue by change the line to some thing stupid like this though:
```
            sed -i $(echo -e 's/.\x8//g') "${manout}"
```

**Comment by lenormf** [comment]
Please use `printf` to print `\x08`, as `echo -e` is undefined:

```
printf 's/.\x8//g'
```

**Comment by leira** [comment]
Thanks~

Changed the line to:
```
sed -ie $(printf 's/.\x8//g') "${manout}"
```

It worked on Mac. I also verified on an Arch Linux box, it didn't break either. Though not pretty. Pull request #1044 created.

**Comment by leira** [comment]
Another work around is to install brew gnu-sed as -with-default-name, not sure if it will break Apple stuff.

```
brew install gnu-sed --with-default-names
```

**Comment by kballard** [comment]
`brew install gnu-sed --with-default-names` is a terrible idea. That's going to break a lot of software that is written for BSD Sed but doesn't hard-code `/usr/bin/sed` as the path.

**Comment by lenormf** [comment]
If that's the case then you should report bugs on the trackers of those software because relying on a particular version of a tool that has a POSIX set of flags is a bad idea.

**Comment by kballard** [comment]
The problem with replacing BSD sed with GNU sed has nothing to do with POSIX flags, and everything to do with the fact that both BSD sed and GNU sed have separate incompatible extensions on top of the POSIX specification for sed, and code written to expect BSD sed's flags will break if it hits GNU sed. A common example of this is the `-i` flag.

**Comment by lenormf** [comment]
Yea that's exactly what I said: "code written to expect BSD sed's flags" is wrong.

**Comment by kballard** [comment]
What the heck are you talking about? Code written to expect BSD sed's flags is no more wrong than code written to expect GNU sed's flags. And when we're talking about OS X (which is the platform where you use `brew`), since `/usr/bin/sed` is BSD sed, literally all software targeting OS X that uses Sed will expect BSD sed. Hopefully any such software that relies on non-POSIX flags will use `/usr/bin/sed`, but it's unfortunately common for people to just rely on finding the tool in `$PATH` instead of providing an absolute path. Similarly, any cross-platform software that supports OS X as a platform and uses non-POSIX sed flags can be expected to detect that it's running on OS X and use BSD sed's flags instead of GNU sed's flags (and in this case it probably won't hard-code the path to sed because that path isn't the same on all platforms). In fact, just earlier this year, I fixed the install script for some software (I forget what) to work properly on OS X by doing that; detecting that it's running on OS X and using BSD sed's flags instead of GNU sed's flags.

In general, if the system ships with one variant of some particular utility, it's a bad idea to dump an incompatible variant in your `$PATH`. This is precisely why `brew install gnu-sed` includes the `g` prefix by default, and I think it has other GNU software packages that do the same thing.
