### ISSUE TITLE
Shortcut choice

### ISSUE THREAD

**Issue by shashurup** [mawww/kakoune#998]
First of all I would like to note that I really appreciate the effort of creating a "better vim". I've been thinking of the ways vim could be improved for quite a long time.
One of the things which bugs me in vim apart from overall non systematic approach is a prevalence of Control based shortcuts. To be honest this is not only Vim specific problem and I was unhappy with all this for a long time until finally I swapped Ctrl and Alt on all my devices and everything is a lot better since.
However, this becomes a problem in Kakoune. On the one hand it tries to mantain "compatibility" with vim, for instance, c-f and c-b, but on the other hand it introduces new ones which, as I can see, are mostly Alt based - alt-a is an example of one which is supposed to be used frequently. I'm afraid at somepoint this may end up with quite a mess which is almost impossible to fix since the editor may got wide adoption.
Not sure exactly about a solution but, I think, there is still time fix this somehow.

**Comment by lenormf** [comment]
Hi,

A few comments about the terminology:
* Kakoune isn't a "better vim", it's merely inspired from it, and I think we say that just because it uses mode based edition
* there is no effort made to maintain any kind of compatibility with `vim`

Now the modifiers on the keys either (usually) extend the selection with `shift`, or indicate (mostly) an /alternate/ behaviour with `alt`. Some shortcuts are wonkier than others because there's only so many keys/combinations on a keyboard, that's why you have to do some finger gymnastics to do certain actions -and some were just copied over from `vim` because no other obvious alternative presented itself, e.g. completion in insert mode- but originally the modifiers were just logical continuations of regular normal-mode keys.

Note that you can `unmap` and re-`map` bindings if you wish.

**Comment by mawww** [comment]
Well, not sure if it qualifies as an effort, but we try not to break compatiblity with vim for no reason, that said, consistency is a good enough reason in many cases. We try to avoid Ctrl based shortcuts because they are hard to type (IMHO), and tend to fail on certain cases with terminals (`<c-m>`, `<c-i>` are `<ret>` and `<tab>`).

We still do breaking changes from time to time on certain bindings, so I would not mind discussing some changes.

**Comment by shashurup** [comment]
I've taking a closer look and figured that my complains was a bit premature.
Actually, among the important vim ctrl shortcuts I found only ctrl-{fbdu} for which, I think, it would make sense to create new alt based shortcuts.

**Comment by lenormf** [comment]
I think this issue can be closed.

**Comment by mawww** [comment]
Yeah, those shortcuts could get changed, but it would be through a separate issue anyway, closing.
